### ISSUE TITLE
Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit

### ISSUE THREAD

**Issue by stillhere** [libgdx/libgdx#1127]
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:110)
    at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
    at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:46)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:76)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:56)
    at com.badlogicgames.superjumper.SuperJumperDesktop.main(SuperJumperDesktop.java:23)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx64.so
    at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:119)
    at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:231)
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:108)
    ... 6 more

How to solve?

**Comment by Skeen** [comment]
Had some issue, same solution works. Thanks.
