### ISSUE TITLE
Fix SpriteBatch shader for Windows Phone 8.1

### ISSUE THREAD

**Issue by NextDev** [libgdx/libgdx#1138]
import com.badlogic.gdx.ApplicationListener;
    import com.badlogic.gdx.Gdx;
    import com.badlogic.gdx.graphics.GL10;
    import com.badlogic.gdx.graphics.OrthographicCamera;
    import com.badlogic.gdx.graphics.Texture;
    import com.badlogic.gdx.graphics.Texture.TextureFilter;
    import com.badlogic.gdx.graphics.g2d.Sprite;
    import com.badlogic.gdx.graphics.g2d.SpriteBatch;
    import com.badlogic.gdx.graphics.g2d.TextureRegion;

    public class Game implements ApplicationListener {
	
	private OrthographicCamera camera;
	private SpriteBatch batch;
	private Texture texture;
	private Sprite sprite;
	
	@Override
	public void create() {		
		
		float w = Gdx.graphics.getWidth();
		float h = Gdx.graphics.getHeight();
		
		this.camera = new OrthographicCamera(1, h/w);
		this.batch = new SpriteBatch();
		
		this.texture = new Texture(Gdx.files.internal("data/libgdx.png"));
		this.texture.setFilter(TextureFilter.Linear, TextureFilter.Linear);
		
		TextureRegion region = new TextureRegion(texture, 0, 0, 512, 275);
		
		this.sprite = new Sprite(region);
		this.sprite.setSize(0.9f, 0.9f * this.sprite.getHeight() / this.sprite.getWidth());
		this.sprite.setOrigin(this.sprite.getWidth()/2, this.sprite.getHeight()/2);
		this.sprite.setPosition(-this.sprite.getWidth()/2, -this.sprite.getHeight()/2);
	}

	@Override
	public void dispose() {
		//this.stage.dispose();
		this.batch.dispose();
		this.texture.dispose();
	}

	@Override
	public void render() {		
		
		Gdx.gl.glClearColor(1, 1, 1, 1);
		Gdx.gl.glClear(GL10.GL_COLOR_BUFFER_BIT);
		
		this.batch.setProjectionMatrix(camera.combined);
		this.batch.begin();
		this.sprite.draw(batch);
		this.batch.end();
	}

	@Override
	public void resize(int width, int height) {
	}

	@Override
	public void pause() {
	}

	@Override
	public void resume() {
	}
    }

java.lang.IllegalArgumentException: Error compiling shader: Shader compilation errors
(5, 9): Macro already defined
(5, 14): syntax error, unexpected NEWLINE_TOK, expecting IDENT_TOK or MACRO_DEFINITION

	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:195)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:159)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:96)
	at com.lz.run.Game.create(Game.java:35)
	at com.badlogic.gdx.backends.gwt.GwtApplication.setupLoop(GwtApplication.java:177)
	at com.badlogic.gdx.backends.gwt.GwtApplication$1$1.update(GwtApplication.java:139)
	at com.badlogic.gdx.backends.gwt.preloader.Preloader$1$1.onSuccess(Preloader.java:184)
	at com.badlogic.gdx.backends.gwt.preloader.AssetDownloader$4$1.onEvent(AssetDownloader.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
	at java.lang.Thread.run(Thread.java:722)

**Comment by badlogic** [comment]
I guess with Windows 10 and the lackluster adoption of Windows 8 Phone, we can close this out :)
