### ISSUE TITLE
Couldn't load shared library 'gdx-freetype64.dll' in latest nightlies

### ISSUE THREAD

**Issue by labodj** [libgdx/libgdx#1821]
I just updated my build.gradle files to reflect 1.0.2 changes by changing or adding these lines:

```
classpath 'com.android.tools.build:gradle:0.10+'
gdxVersion = '1.0.2-SNAPSHOT'
roboVMVersion = '0.0.12'
maven { url "https://oss.sonatype.org/content/repositories/releases/" }
```

Now when I start the desktop app in windows 8.1 update 1 it returns an error:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-freetype64.dll' for target: Windows 8.1, 64-bit
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
    at com.badlogic.gdx.graphics.g2d.freetype.FreeType.initFreeType(FreeType.java:541)
    at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.<init>(FreeTypeFontGenerator.java:102)
    at com.marclabsoftware.games.myapp.utilities.FontFactory.<init>(FontFactory.java:49)
    at com.marclabsoftware.games.myapp.utilities.Utilities.init(Utilities.java:96)
    at com.marclabsoftware.games.myapp.MyApp.create(MyApp.java:54)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:136)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx-freetype64.dll
    at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:124)
    at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:245)
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:113)
    ... 7 more
```

No problem in android with 1.0.2
In windows 8 If I go back to 1.0.1 it works good

**Comment by xiaolei123** [comment]
You Should Add :   
`compile "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"`

on Your Gradle
