### ISSUE TITLE
GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit

### ISSUE THREAD

**Issue by fechy** [libgdx/libgdx#2198]
Hello,

Since the latest build (`1.2.1-SNAPSHOT`) Im getting this exception on Desktop:

``` java
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:117)
    at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
    at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:76)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
    at com.kingmonkey.badfermin.Main.main(Main.java:60)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx64.dylib
    at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:125)
    at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:255)
    at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:114)
```

My LwjglApplicationConfiguration looks like:

``` java
LwjglApplicationConfiguration cfg = new LwjglApplicationConfiguration();
cfg.title = GameConfig.GAME_TITLE;
cfg.vSyncEnabled = true;
cfg.useGL30 = true;
cfg.width = 480;
cfg.height = 800;
```

Setting useGL30 to `false` doesn't solve it :( 

Any idea what might it be?

**Comment by trommlbomml** [comment]
Have this issue also under MacOSX El Caption with LibGDX 1.7.0. I tried switching to 1.7.2 but does not help. Indeed the package cdx-natives does not contain libgdx64.dylib but the x86 version. Tried clearing, but does not help. Nightly builds seem to contain the library.

**Comment by Tom-Ski** [comment]
I don't know where you are getting your natives from, the mavenized artifacts are fine, as are the nightly builds.  Where did you download that gdx-natives.jar that is in your repository in that project you linked?

**Comment by trommlbomml** [comment]
yes it is. I think I used the offical packages...

**Comment by trommlbomml** [comment]
This is the repository we use: https://repo.maven.apache.org/maven2.

**Comment by MobiDevelop** [comment]
Those jars certainly have all the necessary natives.

**Comment by trommlbomml** [comment]
Oh you deadly right....the native dependency was hard coded, seems to be an old version with no x64 support. now everything works!
