### ISSUE TITLE
FileHandle methods crash some Android devices (ErrnoException)

### ISSUE THREAD

**Issue by rdamiano** [libgdx/libgdx#2385]
I have a project that creates an external folder on the SD card and puts a "credits.txt" file in this directory.

This error only occurs with a few Android devices, they all seem to be "low-end" devices, here's a few:
http://www.gsmarena.com/lenovo_s720-5243.php
http://www.gsmarena.com/sony_xperia_tipo-4718.php
http://www.gsmchoice.com/en/catalogue/kyocera/event/Kyocera-Event.html

**This is the error:**
```
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: directory/credits.txt (External)
at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:351)
at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:337)
at package.App.createCreditsFile(App.java:436)
at ...
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error writing file: directory/credits.txt (External)
at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:328)
at com.badlogic.gdx.files.FileHandle.writeString(FileHandle.java:348)
at ...
Caused by: java.io.FileNotFoundException: /mnt/sdcard/directory/credits.txt: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:416)
at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
at com.badlogic.gdx.files.FileHandle.writer(FileHandle.java:320)
at ...
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
at libcore.io.IoBridge.open(IoBridge.java:400) ... 9 more
```
**Here's the code in question:**
```
private void createCreditsFile()
{
	if (Gdx.files.isExternalStorageAvailable() == false)
		return;
	
	// Create the credits text file if it doesn't exist.
	// -------------------------------------------------
	FileHandle creditsTextFile = Gdx.files.external("directory/credits.txt");
	
	if (creditsTextFile.exists() == false)
		creditsTextFile.writeString("blah blah", false);
}
```
**Upon changing the above code to this following code, I stopped receiving the error, though I'm not sure if I'm simply suppressing the error or if the following code does actually work on these problematic devices (basically just converting the FileHandle to a File and writing with that):**
```
private void createCreditsFile()
{
	if (Gdx.files.isExternalStorageAvailable() == false)
		return;
	
	// Create the credits text file if it doesn't exist.
	// -------------------------------------------------
	FileHandle creditsTextFile = Gdx.files.external("directory/credits.txt");
	File file = creditsTextFile.file();
	
	if (creditsTextFile.exists() == false)
	{
		try
		{
			FileWriter fw = new FileWriter(file);
			fw.write("blah, blah");
			fw.close();
		}
		catch (IOException e)
		{
		}
	}
}
```

Very annoying little error, keeps popping up every day in my Analytics from a very limited amount of users - not sure if its actually a bug or something that I can fix on my end.

**Comment by MobiDevelop** [comment]
Not being able to reproduce is going to make this impossible to fix. As this appears to be tied to specific devices and not a general issue, I'm going to close this.
