### ISSUE TITLE
alcDestroyContext/DSoundOpenPlayback bug

### ISSUE THREAD

**Issue by vaxquis** [libgdx/libgdx#2578]
AL lib: (EE) DSoundOpenPlayback: Device init failed: 0x80070057
    AL lib: (EE) DSoundOpenPlayback: Device init failed: 0x80070057
    Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.openal.ALC10.alcDestroyContext(ALC10.java:362)
	at org.lwjgl.openal.AL.destroy(AL.java:210)
	at org.lwjgl.openal.AL.init(AL.java:175)
	at org.lwjgl.openal.AL.create(AL.java:138)
	at org.lwjgl.openal.AL.create(AL.java:102)
	at org.lwjgl.openal.AL.create(AL.java:201)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:72)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:82)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
	at whatever.desktop.DesktopLauncher.main(DesktopLauncher.java:10)

happens quite randomly, without any apparent reason, usually when debugging, but not always. Doesn't depend on the exact client code, happened with code not using sound/music, with project with almost no code at all (test one-liners) etc.

**Comment by badlogic** [comment]
Thanks for the research! I temporarily "fixed" this as you suggested, by catching the exception, logging it and continuing as if disableAudio was set.

**Comment by vaxquis** [comment]
Many thanks for the patch, badlogic.
