### ISSUE TITLE
Assertion failed on iOS device ( ios 7 ipad, ios 8 iphone 6 ), 1.5.3 snapshot

### ISSUE THREAD

**Issue by tajny** [libgdx/libgdx#2694]
This happens only on ios , android, desktop, are running just fine

Assertion failed: (a.x >= 0.0f && a.y >= 0.0f), function SolveVelocityConstraints, file /Users/badlogic/jenkins/workspace/libgdx-mac/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Dynamics/Contacts/b2ContactSolver.cpp, line 412.
AppLauncher failed with an exception:
java.lang.RuntimeException: Unexpected response from debugserver: $X00;description:5465726d696e617465642064756520746f207369676e616c2036;#00
	at org.robovm.libimobiledevice.util.AppLauncher.pipeStdOut(AppLauncher.java:799)
	at org.robovm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:721)
	at org.robovm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1015)
	at org.robovm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)

**Comment by Tom-Ski** [comment]
Will reopen if provided code that reproduces.
