### ISSUE TITLE
I18NBundle  error

### ISSUE THREAD

**Issue by oahc09** [libgdx/libgdx#2701]
find an error in my game.only in samung i9008L mobile phone.
        
        java.lang.NoSuchFieldError: java.util.Locale.ROOT
	at com.badlogic.gdx.utils.I18NBundle.getCandidateLocales(I18NBundle.java:270)
	at com.badlogic.gdx.utils.I18NBundle.createBundleImpl(I18NBundle.java:165)
	at com.badlogic.gdx.utils.I18NBundle.createBundle(I18NBundle.java:130)
	at com.oahcflystudio.game.XueBaGame.init(XueBaGame.java:37)
	at com.oahcfly.chgame.core.mvc.CHGame.create(CHGame.java:136)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:237)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1325)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1116)

**Comment by davebaol** [comment]
Hmmm... looks like Locale.ROOT has been added in API level 9.

**Comment by davebaol** [comment]
Just checked, API level 8 is still supported. 
I'll look into it asap.

**Comment by oahc09** [comment]
yeah,i find android os is 2.2.2 and only one user reports the error.






在2015年01月03 21时51分, "davebaol"<notifications@github.com>写道:



Just checked, API level 8 is still supported.
I'll look into it asap.

**Comment by davebaol** [comment]
Easy fix :)

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://stonemountainrunners.nl/report.php?ek1>

 

loogie@basicelementdesign.com
