### ISSUE TITLE
sometimes report the error when setScreen(....) in my game

### ISSUE THREAD

**Issue by oahc09** [libgdx/libgdx#2707]
````
java.lang.IllegalArgumentException: buffer not allocated with newUnsafeByteBuffer or already disposed
	at com.badlogic.gdx.utils.BufferUtils.disposeUnsafeByteBuffer(BufferUtils.java:507)
	at com.badlogic.gdx.graphics.glutils.VertexArray.dispose(VertexArray.java:67)
	at com.badlogic.gdx.graphics.Mesh.dispose(Mesh.java:551)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.dispose(SpriteBatch.java:1007)
	at com.badlogic.gdx.scenes.scene2d.Stage.dispose(Stage.java:805)
	at com.oahcfly.chgame.core.mvc.CHScreen.hide(CHScreen.java:69)
	at com.badlogic.gdx.Game.dispose(Game.java:31)
	at com.oahcfly.chgame.core.mvc.CHGame.dispose(CHGame.java:116)
````
my code is ：
````java
 @Override
    public void show() {
        setBackKeyPressed(false);
        StretchViewport viewport = new StretchViewport(stageW, stageH);
        stage = new Stage(viewport);
        Gdx.input.setInputProcessor(stage);
        initScreen();
    }
  ......
  @Override
    public void hide() {
        stage.dispose();
        dispose();
    }
````

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or irc  (and you probably want to use the wizard for that). https://github.com/libgdx/libgdx/wiki/Getting-help
