### ISSUE TITLE
I got an error about Pixmap in my game

### ISSUE THREAD

**Issue by oahc09** [libgdx/libgdx#2751]
android os is 4.2.2 and phone Hm note 1td

com.badlogic.gdx.utils.GdxRuntimeException: Error loading pixmap.
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.&lt;init&gt;(Gdx2DPixmap.java:95)
	at com.badlogic.gdx.graphics.Pixmap.&lt;init&gt;(Pixmap.java:114)
	at com.oahcfly.chgame.org.freyja.libgdx.cocostudio.ui.parser.group.CCPanel.parse(CCPanel.java:38)
	at com.oahcfly.chgame.org.freyja.libgdx.cocostudio.ui.CocoStudioUIEditor.parseWidget(CocoStudioUIEditor.java:473)
	at com.oahcfly.chgame.org.freyja.libgdx.cocostudio.ui.CocoStudioUIEditor.createGroup(CocoStudioUIEditor.java:196)
	at com.oahcfly.chgame.core.ui.CHUI.&lt;init&gt;(CHUI.java:39)
	at com.oahcflystudio.game.ui.QuestionUI.&lt;init&gt;(QuestionUI.java:49)
	at com.oahcflystudio.game.screen.QuestionScreen.initScreen(QuestionScreen.java:28)
	at com.oahcfly.chgame.core.mvc.CHScreen.show(CHScreen.java:66)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.oahcfly.chgame.core.mvc.CHGame.setScreen(CHGame.java:248)
	at com.oahcflystudio.game.ui.SelectUI$1.touchUp(SelectUI.java:50)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:346)
	at com.badlogic.gdx.backends.android.AndroidInput.processEvents(AndroidInput.java:393)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:414)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1550)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1263)

**Comment by Tom-Ski** [comment]
Please use the forums for help. 

If you think you have found a bug in LibGDX that you can reproduce, please submit an issue with a self contained test that reproduces the bug.
