### ISSUE TITLE
AndroidInput.onKey exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2807]
Get new crash in-the-wild. Several devices with Android 4.0.3 and 4.2.2. Reports are from the field (China) so no minimal example. Stacktrace:

<pre><code>java.lang.ArrayIndexOutOfBoundsException: length=256; index=1027
       at com.badlogic.gdx.backends.android.AndroidInput.onKey(AndroidInput.java:496)
       at android.view.View.dispatchKeyEvent(View.java:5495)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1246)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1246)
       at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1246)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1921)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1363)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2324)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1848)
       at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3327)
       at android.view.ViewRootImpl.handleFinishedEvent(ViewRootImpl.java:3300)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2460)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)
</code></pre>

**Comment by Tom-Ski** [comment]
1027 is not defined by Android. We can check for invalid input key codes, but that's rather ugly and just hides the problem.

**Comment by titovmaxim** [comment]
I think it can be some non-standard device. Anyway the check would be much better than a crash.

**Comment by titovmaxim** [comment]
We got a bunch of new crashes with the same issue. Now we get new "wrong" code = 256. Totally it is already ~30 crashes. There is also a SO article about this behavior:
http://stackoverflow.com/questions/27890574/libgdx-android-game-crashes-on-resume-with-odd-keycode-1026

So I suppose it is better to implement a safety check. The crash become popular :(

**Comment by titovmaxim** [comment]
@Tom-Ski, could you please share your plans about possible fix of this issue? I think the simplest and reasonable would be just to ignore any keyCodes >= 256.

I've tried to google a bit and see that some specific android-based boxes could have keyCodes >= 256. And it's correlates with our crashes. For example:
https://android.googlesource.com/platform/frameworks/native/+/master/include/android/keycodes.h
http://www.cnblogs.com/larack/p/4223465.html

**Comment by titovmaxim** [comment]
The bug brings new in-the-wild crashes every day. Are there any plans to fix it? I can do a PR (with a simple ignoring everything with code > 255) but I worry to break the existing key event processing logic.

**Comment by NathanSweet** [comment]
If we receive a key code we don't support, we shouldn't crash. Better to just ignore the event.

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://nou-avtostart.moscow/dinner.php?7v>

 

loogie@basicelementdesign.com
