### ISSUE TITLE
AndroidNet.openURI crash

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/libgdx#2823]
Some users got crashes in AndroidNet.openURI in the field. Android version is mainly 4.2.2, but some other are also present.

The stacktrace:
<pre><code>android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://static.bulkypix.com/legal/Terms_of_Use.pdf }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1423)
       at android.app.Activity.startActivityForResult(Activity.java:3391)
       at android.app.Activity.startActivityForResult(Activity.java:3349)
       at android.app.Activity.startActivity(Activity.java:3601)
       at android.app.Activity.startActivity(Activity.java:3569)
       at com.badlogic.gdx.backends.android.AndroidNet$1.run(AndroidNet.java:78)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
</code></pre>

It seems that the cases are quite weird (not browser or something like this?), but it is better not to crash. Another problem is that the crashing code is executed in another thread, so could not be easily catched.

The proposal is to wrap AndroidNet.openURI lines 74-78 in try/catch and just to log it instead of crash.

**Comment by MobiDevelop** [comment]
In this particular stack trace, it crashed because the user doesn't have
any PDF viewer installed on their device.

Not sure that blindly catching and ignoring this scenario is the right
thing to do.

**Comment by titovmaxim** [comment]
I agree. However a crash is also bad. Taking into account that it happens in another thread only the solution I see is to accept optional callback (listener) and to inform if it is supplied.

**Comment by MobiDevelop** [comment]
I'd agree there should be a way to know if the uri was not able to be
opened.

In this particular case - I'd say you might want to have your terms of use
in a more general format (text or html) as I'd guess you would like people
to actually see them.

**Comment by titovmaxim** [comment]
Got one idea. The openURI method is blocking by user experience. So we can use it to catch the exception from UI thread and rethrow it. Then one can catch outside if needed. This way the API would be preserved unchanged.

Something like this:
<pre><code>public void openURI(final String URI)
{
	final SynchronousQueue<Throwable> result = new SynchronousQueue<>();
	final Uri uri = Uri.parse(URI);
	app.runOnUiThread(new Runnable()
	{
		@Override
		public void run()
		{
			try {
				Intent intent = new Intent(Intent.ACTION_VIEW, uri);
				// LiveWallpaper and Daydream applications need this flag
				if (!(app.getContext() instanceof Activity)) {
					intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
				}
				app.startActivity(intent);
				result.offer(null);
			}
			catch (final Throwable ex) {
				result.offer(ex);
			}
		}
	});

	try {
		final Throwable ex = result.take();
		if (ex != null) {
			throw new RuntimeException(ex);
		}
	}
	catch (final InterruptedException ex) {
	}
}
</code></pre>

**Comment by titovmaxim** [comment]
@MobiDevelop, what do you think? Could we use such approach?

**Comment by MobiDevelop** [comment]
Sorry for the delayed reply... I am trying to remember why we are calling this on the UI thread.

**Comment by MobiDevelop** [comment]
My proposal for how to handle this is to let openURI return a boolean. If we know for a fact that we didn't open the uri, we return false, otherwise we return true. As it is the topic of discussion... On Android, we'll query for the existence of an activity to handle the intent - if none exists, we return false.

Thoughts?

**Comment by titovmaxim** [comment]
Boolean would be great.

**Comment by MobiDevelop** [comment]
Alrighty, I'll commit the change later today.
