### ISSUE TITLE
TmxMapLoader: flipped tiled object & loader crash

### ISSUE THREAD

**Issue by FEDE0D** [libgdx/libgdx#2833]
The TmxMapLoader crashes when loading a map containing a flipped tiled object.

This is the error:
>Exception in thread "LWJGL Application" java.lang.NumberFormatException: For input string: "2147483751"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:495)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.badlogic.gdx.utils.XmlReader$Element.getIntAttribute(XmlReader.java:645)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:202)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObjectGroup(BaseTmxMapLoader.java:114)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadTilemap(TmxMapLoader.java:202)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:89)
	at com.fede0d.gengine.maps.LevelLoader.load(LevelLoader.java:38)
	at com.fede0d.gengine.maps.LevelLoader.load(LevelLoader.java:32)
	at com.fede0d.gengine.screens.LevelScreen.loadMap(LevelScreen.java:35)
	at com.fede0d.gengine.classes.Screens.loadMaps(Screens.java:63)
	at com.fede0d.gengine.classes.Screens.load(Screens.java:32)
	at com.fede0d.gengine.classes.Screens.<init>(Screens.java:26)
	at com.fede0d.gengine.classes.GameClass.create(GameClass.java:32)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

Steps to reproduce the issue:
>In Tiled create an object layer.
Select the "Insert Tile" tool.
Select a tile from the tileset and insert it in the new layer.
Select the created object and flip it the x or y coordinate
Load the map in LibGdx.

According to the [TMX Map Format](https://github.com/bjorn/tiled/wiki/TMX-Map-Format#tile-flipping) the flip information of the tile is being saved withing the gid property for the tile.

In my case the object was saved as `<object id="80" name="ASDASDSD" gid="2147483751" x="66" y="626"/>`, and this number can't be parsed by the Integer class in Java and results in an exception.

Note that when not fliped the gid number is saved as an integer `<object id="80" name="ASDASDSD" gid="103" x="66" y="626"/>` and the exception doesn't happen.

**Comment by Darkyenus** [comment]
2147483751 is slightly above signed integer range, in fact 2147483751 - 2^31 = 103
Could be useful to know for resolving.

**Comment by MobiDevelop** [comment]
Yep, this is a bug, we need to mask out the flip and rotation information before trying to retrieve the tile from the tileset.
