### ISSUE TITLE
Error While Generating IDEA Files

### ISSUE THREAD

**Issue by syedalinaqi** [libgdx/libgdx#2871]
Executing 'D:\Android_Development\Android_Projects\libGDX\CopterIT!/gradlew.bat clean --no-daemon idea'
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
	at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)
	... 1 more

**Comment by Tom-Ski** [comment]
Please use the forums. This is an issue tracker.
