### ISSUE TITLE
iOS 8.2: NPE in IOSApplication while calling getIosVersion()

### ISSUE THREAD

**Issue by andresmanz** [libgdx/libgdx#2946]
To be honest, I don't know if that's a libgdx or a RoboVM issue. My app crashes on iOS as soon as didFinishLaunching is reached since I updated to 8.2.

iPod Touch with iOS 8.2
RoboVM 1.0.0
libgdx 1.5.5

```java.lang.NullPointerException
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication.getIosVersion(IOSApplication.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplicationDelegate$ObjCProxy.$cb$application$didFinishLaunchingWithOptions$(Unknown Source)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at ch.gearsoft.sleepwell.IOSLauncher.main(IOSLauncher.java)

**Comment by andresmanz** [comment]
Ok, that seems to happen as soon as I access IOSApplication.getUIViewController() inside of createApplication(). For whatever reason that should be related to didFinishLaunching()/getIosVersion()...
