### ISSUE TITLE
Joystick support crash with X7 keyboard/mouse

### ISSUE THREAD

**Issue by dusakus** [libgdx/libgdx#2964]
App: Delver EarlyAcces (probably not game specific)

The problem: Instant crash when using A4Tech X7 keyboard or mouse buttons. Game crashes when i try to use arrow keys on external keyboard (G800V), i can play using builtin keyboard, but not the external one.

CrashLog (all I have):
 Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: [keyID here]
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.buttonPressed(OisJoystick.java:51)
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(Native Method)
        at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(OisJoystick.java:82)
        at com.badlogic.gdx.controllers.desktop.ois.Ois.update(Ois.java:45)
        at com.badlogic.gdx.controllers.desktop.OisControllers$1.run(OisControllers.java:60)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:238)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:193)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

My setup:
 OS: Kubuntu 14.10  (kernel: 3.16.0)
 Laptop (CPU: i7-4800MQ, GPU: GTX770M, RAM: 16GB)
 ext Keyboard: A4Tech X7 G800V
 mouse: A4Tech X7 X-755BK

Additional info:
 System's configuration utility detects both input devices (additionally to their primary function) as  Joysticks with 69 buttons and 37 axis. It's known that a4tech devices mess up some games, but this is the first time it causes them to crash and based on the exception it's not a game specific problem

**Comment by ShibaBandit** [comment]
Ran into similar issue. I've found that if you modify the global controllers list in the middle of a button press, it breaks the loop exit condition. The problem is here:

```java
    for (int ii = 0, nn = allListeners.size; ii < nn; ii++)
        allListeners.get(ii).buttonUp(OisController.this, buttonIndex);
```

I believe it stems from:

```java
nn = allListeners.size
```

Exception:

```java
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 2 >= 2
	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.badlogic.gdx.controllers.desktop.OisControllers$OisController$1.buttonPressed(OisControllers.java:111)
	at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.buttonPressed(OisJoystick.java:53)
	at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(Native Method)
	at com.badlogic.gdx.controllers.desktop.ois.OisJoystick.update(OisJoystick.java:83)
	at com.badlogic.gdx.controllers.desktop.ois.Ois.update(Ois.java:42)
	at com.badlogic.gdx.controllers.desktop.OisControllers$1.run(OisControllers.java:86)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:250)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:203)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
```

**Comment by MrStahlfelge** [comment]
Hi, please take a look at [gdx-controllers v2 prerelease snapshot](https://github.com/libgdx/gdx-controllers). It should solve your issue.
