### ISSUE TITLE
updating scene2d Table with threads

### ISSUE THREAD

**Issue by nwodb** [libgdx/libgdx#2978]
I am sometimes getting an ArrayIndexOutOfBoundsException when running my app, it looks like it is running through the Table::layout method while the Table is being updated by a network thread that is updating how many objects are in the table. Is there a way around this? or should the code in Table be be using the min between rows and expandHeight.length so it is not overrunning the array? -Thanks

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:932)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:712)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:106)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:100)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.dawgged.GFL.client.GFLClient.render(GFLClient.java:101)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)

From Table::layout - 
		int columns = this.columns, rows = this.rows;
		float[] expandWidth = this.expandWidth, expandHeight = this.expandHeight;
		float[] columnWidth = this.columnWidth, rowHeight = this.rowHeight;

		float totalExpandWidth = 0, totalExpandHeight = 0;
		for (int i = 0; i < columns; i++)
			totalExpandWidth += expandWidth[i];
		for (int i = 0; i < rows; i++)
			totalExpandHeight += expandHeight[i]; // crashes here

**Comment by NathanSweet** [comment]
scene2d and almost all of libgdx is not thread safe.

**Comment by nooone** [comment]
You can use `Gdx.app.postRunnable()` to get back to the main thread and update your table that way.

**Comment by nooone** [comment]
I suppose this one can be closed, as the only solution would be to make libgdx thread safe? :D
