### ISSUE TITLE
Box2dLights does not work in 1.5.5

### ISSUE THREAD

**Issue by voodoosoft** [libgdx/libgdx#3012]
After updating from 1.5.4 to 1.5.5 without changes any code I get an exception on rendering lights with Box2dLights:

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:855)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glVertexAttribPointer(LwjglGL20.java:829)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setVertexAttribute(ShaderProgram.java:639)
	at com.badlogic.gdx.graphics.glutils.VertexArray.bind(VertexArray.java:115)
	at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:380)
	at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:371)
	at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:479)
	at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:449)
	at box2dLight.PositionalLight.render(PositionalLight.java:150)
	at box2dLight.RayHandler.render(RayHandler.java:268)

**Comment by Tom-Ski** [comment]
Please take this to the Box2d Lights issue tracker.
