### ISSUE TITLE
Keyboard Return Crash

### ISSUE THREAD

**Issue by FurryFaust** [libgdx/libgdx#3066]
I got this when I hit return on the Gdx.input.setOnscreenKeyboardVisible(true); for iPhone 4s Simulator.
```
java.lang.NullPointerException

        at com.badlogic.gdx.backends.iosrobovm.IOSInput$3.shouldReturn(IOSInput.java)
        at org.robovm.apple.uikit.UITextFieldDelegate$ObjCProxy.$cb$textFieldShouldReturn$(Unknown Source)
        at org.robovm.apple.uikit.UIApplication.main(Native Method)
        at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
        at com.furryfaust.patterns.IOSLauncher.main(IOSLauncher.java)

```

**Comment by Darkyenus** [comment]
Looks like you didn't set an input processor ([see here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-robovm/src/com/badlogic/gdx/backends/iosrobovm/IOSInput.java#L413)). Maybe we should put a nullcheck there.

**Comment by FurryFaust** [comment]
Hmm you are right.
