### ISSUE TITLE
"Pixmap already disposed "error during FreeTypeFontGenerator.dispose

### ISSUE THREAD

**Issue by bill-lin** [libgdx/libgdx#3075]
Hi,

I added a generated BitmapFonts (by using the latest FreeTypeFontGenerator) into several different skin styles.
Then I got following error when Skin disposed:

```
com.badlogic.gdx.utils.GdxRuntimeException: Pixmap already disposed!
	at com.badlogic.gdx.graphics.Pixmap.dispose(Pixmap.java:307)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator$1.dispose(FreeTypeFontGenerator.java:457)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.dispose(BitmapFont.java:313)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.dispose(Skin.java:392)
	at com.badlogic.gdx.assets.AssetManager.unload(AssetManager.java:192)
	at com.badlogic.gdx.assets.AssetManager.clear(AssetManager.java:619)
	at com.badlogic.gdx.assets.AssetManager.dispose(AssetManager.java:587)
```

**Comment by Darkyenus** [comment]
Please post your code, ideally as executable example code. https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by MobiDevelop** [comment]
Your line numbers don't match current source. What version of libgdx are you using?

**Comment by bill-lin** [comment]
libgdx 1.5.6
I think the problem is: same font was added into UI using different name

**Comment by MobiDevelop** [comment]
Sounds like you found the problem on your side. Closing this out.
