### ISSUE TITLE
LibGDX 1.6.0 Black screen on iOS devices.

### ISSUE THREAD

**Issue by voidstarfire** [libgdx/libgdx#3100]
Tested with iPad & iOS simulator.
App that is previously working in 1.5.6 is now a black screen in 1.6.0

Running with RoboVM version 1.1.0 unfortunately RoboVM 1.2.0 is bugged and many bindings fail with it (Google analytics, InApp purchases, AdMob, list goes on).

**Comment by badlogic** [comment]
Could you please give more info? We can't work off of the info 'screen is
black'. Please include symbilcated crash logs. Please specify how the
bindings don't work.

**Comment by voidstarfire** [comment]
I'll get back to you with a list of errors and logs. Give me a few hours.

**Comment by voidstarfire** [comment]
When launching the app here are the following errors logs (from the iOS sim, 8.3)

``
May  8 11:50:08 --- last message repeated 1 time ---
May  8 11:50:08 Starfire IOSLauncher[16872]: assertion failed: 14D136 12F69: libxpc.dylib + 69007 [21968CDD-4DA7-390D-9264-D74A6FA6AF2B]: 0x7d
May  8 11:50:08 Starfire assertiond[16109]: assertion failed: 14D136 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
May  8 11:50:08 Starfire.local SpringBoard[16105]: [MPUSystemMediaControls] Updating supported commands for now playing application.
``

I can also link this error to RoboVM with all the static libraries failing. It seems that libxpc.dylib has been striped from the latest LibGDX AND RoboVM builds resulting in problems for iOS.

**Comment by badlogic** [comment]
This is the Sim system log. Please also post the crash log (you can find it
via the Console application).

Please also post the linker errors the robovm compiler spits out.

A plain libGDX iOS app and our samples work as intended. If you have a
project that reproduces the issue please post it.

**Comment by voidstarfire** [comment]
There are no crash logs, it just displays a black screen?

**Comment by badlogic** [comment]
Please read what I wrote. You can find the crash logs for the simulator via
the Console app of Mac OS X. They can be found under
~/Library/Logs/DiagnosticReports/, either via Finder or by using said
Console app. The file will have the name of your executable plus a
timestamp.

Also, your system log showed that an assertion was hit. This has nothing to
do with RoboVM linking or not linking libs.

Please also post the other info I requested. If you don't I can't help.
Again, 'the screen is black' does not carry any information. Think what
you'd do with such a bug report.

**Comment by badlogic** [comment]
Texture atlas and asset manager have nothing to do with your issue. Please don't edit messages.

**Comment by voidstarfire** [comment]
Ok no worries, I'll get back to you with logs. :-)

**Comment by voidstarfire** [comment]
Ok so I looked in ~/Library/Logs/DiagnosticReports/

I can confirm that no diagnostic reports are generated for iOS simulator. (Only logs I have here are Android studio | abd crashes)

RoboVM doesn't show any linker errors.

Looking in ~/Library/Logs/CoreSimulator the iOS Simulator.log is blank.

As I said before, there's no crash. Just a blank screen,

Going future I can log the system log of the simulator, attached.

Before you state, I have cleared cache for RoboVM.

These are newly generated logs after the app is opened. They point towards a static library missing: libxpc.dylib

``
May  8 15:46:51 --- last message repeated 1 time ---
May  8 15:46:51 Starfire IOSLauncher[826]: assertion failed: 14D136 12F69: libxpc.dylib + 69007 [21968CDD-4DA7-390D-9264-D74A6FA6AF2B]: 0x7d
May  8 15:46:51 Starfire assertiond[554]: assertion failed: 14D136 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
May  8 15:46:51 --- last message repeated 1 time ---
May  8 15:46:51 Starfire.local SpringBoard[550]: [MPUSystemMediaControls] Updating supported commands for now playing application.
May  8 15:48:48 Starfire.local CoreSimulatorBridge[558]: LaunchServices: installing app for existing placeholder <LSApplicationProxy: 0x7f854bd1b7b0> com.polygonattraction.Mega
May  8 15:48:48 Starfire.local CoreSimulatorBridge[558]: LaunchServices: Not creating progress for <LSApplicationProxy: 0x7f854bd1b7b0> com.polygonattraction.Mega since it is not a placeholder.
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIClientConnection _doBackgroundInstallationForPath:withOptions:completion:]: Install of "/Users/macuser/Documents/Apps/Mega/ios/build/robovm.tmp/IOSLauncher.app" type Developer requested by CoreSimulatorBridge (pid 558)
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 MDMCreateDeltaDirectory: calling MDMDirectoryDiff with:
	state->old_bundle: /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Containers/Bundle/Application/5CDF849C-7E28-4AE3-8E94-EFF61FEDFF4A/IOSLauncher.app
	state->new_bundle: /Users/macuser/Documents/Apps/Mega/ios/build/robovm.tmp/IOSLauncher.app
	state->dst_bundle: /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Library/Caches/com.apple.mobile.installd.staging/temp.x9PY0H/extracted/Payload//IOSLauncher.app, binaryDiff flag: FALSE
		dst_ipa: /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Library/Caches/com.apple.mobile.installd.staging/temp.x9PY0H/extracted
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 createDictFromFile: open failed for /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Containers/Bundle/Application/5CDF849C-7E28-4AE3-8E94-EFF61FEDFF4A/ManifestCache.plist : No such file or directory
May  8 15:48:48 Starfire.local installd[545]: 0x10c41b000 __MDMDirectoryDiff_block_invoke29: calling writeDictToFile with: /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Library/Caches/com.apple.mobile.installd.staging/temp.x9PY0H/extracted/ManifestCache.plist
May  8 15:48:48 Starfire.local installd[545]: 0x10c41b000 writeDictToFile: ==== Successfully wrote Manifest cache to /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Library/Caches/com.apple.mobile.installd.staging/temp.x9PY0H/extracted/ManifestCache.plist
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIInstaller performInstallationWithError:]: Installing <MIInstallableBundlePatch ID=com.polygonattraction.Mega; Version=1, ShortVersion=1.0>
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIInstallableBundlePatch applyPatchWithError:]: Attempting patch update of com.polygonattraction.Mega from 1 (1.0) to 1 (1.0)
May  8 15:48:48 Starfire.local SpringBoard[550]: Killing com.polygonattraction.Mega for termination assertion
May  8 15:48:48 Starfire.local pkd[566]: releasing plug-in hold 5903E5E4-8B7C-46F6-AC3B-ED6D9145561F for dead client pid 550
May  8 15:48:48 Starfire com.apple.CoreSimulator.SimDevice.C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F.launchd_sim[536] (UIKitApplication:com.polygonattraction.Mega[0x4d7e][826]): Service exited due to signal: Killed: 9
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIInstallableBundle _refreshUUIDForContainer:withError:]: Data container for com.polygonattraction.Mega is now at /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Containers/Data/Application/49D03D69-D19D-4AE2-A672-AFB94682304B
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIContainer makeContainerLiveReplacingContainer:withError:]: Made container live for com.polygonattraction.Mega at /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/Containers/Bundle/Application/E768A3FC-FD91-46E4-AD51-F10C18AC8A13
May  8 15:48:48 Starfire.local installd[545]: 0x10a3c1000 -[MIInstaller performInstallationWithError:]: Staging: 0.30s; Waiting: 0.00s; Installation: 0.09s; Overall: 0.39s
May  8 15:48:48 Starfire.local CoreSimulatorBridge[558]: LaunchServices: NotifiedObservers <LSApplicationProxy: 0x7f854be03620> com.polygonattraction.Mega was installed
May  8 15:48:48 Starfire.local lsd[565]: LaunchServices: Updating identifier store
May  8 15:48:48 Starfire.local SpringBoard[550]: [com.polygonattraction.Mega (826)] Kill failed. Error: No such process (3)
May  8 15:48:48 Starfire.local /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/libexec/lsd[565]: LaunchServices: Failed to set the data protection class for /Users/macuser/Library/Developer/CoreSimulator/Devices/C9DE1AB7-9FC1-4ECE-BE5E-6D65EFE4CE4F/data/tmp/com.apple.IconsCache/com.polygonattraction.Mega_CFBundleIcon[15]
May  8 15:48:48 Starfire.local SpringBoard[550]: Installed apps did change.
	Added: {(
	)}
	Removed: {(
	)}
	Modified: {(
	    "com.polygonattraction.Mega"
	)}
May  8 15:48:48 Starfire.local SpringBoard[550]: Application 'UIKitApplication:com.polygonattraction.Mega[0x4d7e]' exited abnormally via signal.
May  8 15:48:48 Starfire assertiond[554]: assertion failed: 14D136 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
May  8 15:48:48 --- last message repeated 1 time ---
May  8 15:48:48 Starfire.local assertiond[554]: notify_suspend_pid() failed with error 7
May  8 15:48:50 Starfire assertiond[554]: assertion failed: 14D136 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
May  8 15:48:51 Starfire IOSLauncher[860]: assertion failed: 14D136 12F69: libxpc.dylib + 69007 [21968CDD-4DA7-390D-9264-D74A6FA6AF2B]: 0x7d
May  8 15:48:51 Starfire assertiond[554]: assertion failed: 14D136 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
May  8 15:48:51 Starfire.local SpringBoard[550]: [MPUSystemMediaControls] Updating supported commands for now playing application.
``

**Comment by Tom-Ski** [comment]
Make sure you've deleted your RoboVM cache and upgraded your RoboVM plugins.

**Comment by voidstarfire** [comment]
I had to update the classpath as well as the RoboVM var.

```
classpath 'org.robovm:robovm-gradle-plugin:1.2.0'
&
roboVMVersion = '1.2.0'
```

Upon doing this I've found a new error to do with analytics static library (libgoogleanalytics.a) from BlueRiver. Maybe this needs to be recompiled?

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ios:launchIPhoneSimulator'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleException: Failed to launch IOS Simulator
        at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.launch(AbstractIOSSimulatorTask.java:81)
        at org.robovm.gradle.tasks.IPhoneSimulatorTask.invoke(IPhoneSimulatorTask.java:28)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 54 more
Caused by: org.gradle.api.GradleException: Error building RoboVM executable for app
        at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:100)
        at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.launch(AbstractIOSSimulatorTask.java:37)
        ... 63 more
Caused by: org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/macuser/Documents/Apps/mega/ios/build/robovm.tmp/IOSLauncher -arch i386 -Wl,-filelist,/Users/macuser/Documents/Apps/mega/ios/build/robovm.tmp/objects -L /Users/macuser/.m2/repository/org/robovm/robovm-dist/1.2.0/unpacked/robovm-1.2.0/lib/vm/ios/x86 -ObjC -exported_symbols_list /Users/macuser/Documents/Apps/mega/ios/build/robovm.tmp/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/macuser/.robovm/cache/ios/x86/release/Users/macuser/Documents/Apps/mega/ios/libs/facebook-1.0.0.jar.extracted/META-INF/robovm/ios/libs -mios-simulator-version-min=5.0 -Wl,-no_pie -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -lrobovm-bc -force_load /Users/macuser/.m2/repository/org/robovm/robovm-dist/1.2.0/unpacked/robovm-1.2.0/lib/vm/ios/x86/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework AudioToolbox -framework AVFoundation -framework CoreGraphics -framework CoreTelephony -framework MessageUI -framework SystemConfiguration -framework FacebookSDK -framework CoreLocation -framework Foundation -framework UIKit -framework CoreData -framework OpenGLES -framework QuartzCore -framework OpenAL -framework AdSupport -weak_framework AdSupport -weak_framework StoreKit -force_load /Users/macuser/.robovm/cache/ios/x86/release/Users/macuser/Documents/Apps/mega/ios/libs/admob-1.0.0.jar.extracted/META-INF/robovm/ios/libs/libadmob.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libgdx-box2d.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libgdx-bullet.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libgdx-freetype.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libgdx.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libgoogleanalytics.a -force_load /Users/macuser/Documents/Apps/mega/ios/build/libs/ios/libObjectAL.a -framework MobileCoreServices' failed (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
        at org.robovm.compiler.util.Executor.exec(Executor.java:344)
        at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:300)
        at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:206)
        at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:330)
        at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:200)
        at org.robovm.compiler.Linker.link(Linker.java:375)
        at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:388)
        at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:96)
        ... 64 more
```

**Comment by mickmuzac** [comment]
This is no longer a libgdx issue. You may be able to find help in the [Blue River bindings issue tracker](https://github.com/BlueRiverInteractive/robovm-ios-bindings/issues) or [robovm's issue tracker](https://github.com/robovm/robovm/issues).

Alternatively, you may try a [forum post](http://badlogicgames.com/forum/viewtopic.php?t=11145) to see if anyone else is having this problem.
