### ISSUE TITLE
PolygonSpriteBatch should check remaining vertex/index before copying.

### ISSUE THREAD

**Issue by RotaruDan** [libgdx/libgdx#3124]
This method https://github.com/libgdx/libgdx/blob/8850b5ef4dace8929472ae2d5d8d5614ca9295db/gdx/src/com/badlogic/gdx/graphics/g2d/PolygonSpriteBatch.java#L745

``` Java
    @Override
    public void draw (Texture texture, float[] spriteVertices, int offset, int count) {
        if (!drawing) throw new IllegalStateException("PolygonSpriteBatch.begin must be called before draw.");

        final short[] triangles = this.triangles;
        final float[] vertices = this.vertices;

        final int triangleCount = count / SPRITE_SIZE * 6;
        if (texture != lastTexture)
            switchTexture(texture);
        else if (triangleIndex + triangleCount > triangles.length || vertexIndex + count > vertices.length) //
            flush();

        final int vertexIndex = this.vertexIndex;
        int triangleIndex = this.triangleIndex;
        short vertex = (short)(vertexIndex / VERTEX_SIZE);
        for (int n = triangleIndex + triangleCount; triangleIndex < n; triangleIndex += 6, vertex += 4) {
            triangles[triangleIndex] = vertex;
            triangles[triangleIndex + 1] = (short)(vertex + 1);
            triangles[triangleIndex + 2] = (short)(vertex + 2);
            triangles[triangleIndex + 3] = (short)(vertex + 2);
            triangles[triangleIndex + 4] = (short)(vertex + 3);
            triangles[triangleIndex + 5] = vertex;
        }
        this.triangleIndex = triangleIndex;

        System.arraycopy(spriteVertices, offset, vertices, vertexIndex, count);
        this.vertexIndex += count;
    }
```

doesn't check if there are enough remaining triangles in the for-loop. I know it checks it right in the `if` before, but what happends if `triangleCount` (`count / SPRITE_SIZE * 6`) is higher than the length of the triangles array? 
I think that inside the for-loop that condition should be checked so that in case it's satisfied the batch should be flushed (calling `flush()`) and the iterating variables (`n`, `triangleIndex` and `vertex` should be updated acordingly.

This can also happen for the vertexIndex copying process. What happends if 'count' is higher than the length of vertices array? (at the moment an `IndexOutOfBoundsException` is thrown in both cases).
This could be avoided by computing the `remainingVertices` and invoking  `System.arraycopy(spriteVertices, offset, vertices, idx, copyCount);` inside a do-while (or while) statement. Something very similar to the implementation of this method in the SpriteBatch: https://github.com/libgdx/libgdx/blob/8850b5ef4dace8929472ae2d5d8d5614ca9295db/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java#L555 . 
Since the SpriteBatch has this behavior I thought that the PolygonSpriteBatch should have it too.
##### Steps to reproduce this:

Draw a BitmapFontCache with a text large enough and a PolygonSpriteBatch.
###### Use case 1,

``` Java
        BitmapFontCache cache = new BitmapFontCache(new BitmapFont());
        cache.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 0, 0);
        Batch batch = stage.getBatch();
        batch.begin();
        cache.draw(batch);
        batch.end();
```

throws an exception inside the `triangles` for-loop like this one:

``` Java
EditorApplicationListener: Fatal error: LWJGL Application(12)
java.lang.ArrayIndexOutOfBoundsException: 6000
    at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.draw(PolygonSpriteBatch.java:760)
    at com.badlogic.gdx.graphics.g2d.BitmapFontCache.draw(BitmapFontCache.java:236)
    at es.eucm.ead.editor.MokapApplicationListener.initialize(MokapApplicationListener.java:107)
    at es.eucm.ead.editor.EditorApplicationListener.create(EditorApplicationListener.java:87)
    at es.eucm.ead.editor.MokapApplicationListener.create(MokapApplicationListener.java:83)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```
###### Use case 2 (the String text is smaller),

``` Java
        BitmapFontCache cache = new BitmapFontCache(new BitmapFont());
        cache.setText("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 0, 0);
        Batch batch = stage.getBatch();
        batch.begin();
        cache.draw(batch);
        batch.end();
```

successfully iterates through the `triangles` for-loop but throws this exception while trying to copy the `vertices`, as described above.

``` Java
EditorApplicationListener: Fatal error: LWJGL Application(12)
java.lang.ArrayIndexOutOfBoundsException
    at java.lang.System.arraycopy(Native Method)
    at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.draw(PolygonSpriteBatch.java:769)
    at com.badlogic.gdx.graphics.g2d.BitmapFontCache.draw(BitmapFontCache.java:236)
    at es.eucm.ead.editor.MokapApplicationListener.initialize(MokapApplicationListener.java:107)
    at es.eucm.ead.editor.EditorApplicationListener.create(EditorApplicationListener.java:87)
    at es.eucm.ead.editor.MokapApplicationListener.create(MokapApplicationListener.java:83)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

By the way, I think the new BitmapFont doesn't compute correctly its bounds nor it draws itself correctly when there are multiple line breaks in a row.
Thankyou for your help!

**Comment by panli32811** [comment]
I solved it like below:
```java
		polygonSpriteBatch = new PolygonSpriteBatch(2500)
		{
			final int MAX = 2500 * 5;
			@Override
			public void draw (Texture texture, float[] spriteVertices, int offset, int count) //当最大顶点数超过batch上限时会缓冲下，特别当渲染大量字体时
			{
				while(count > MAX)
				{
					super.draw(texture, spriteVertices, offset, MAX);
					offset += MAX;
					count -= MAX;
				}
				super.draw(texture, spriteVertices, offset, count);
			}
		};
```

**Comment by RotaruDan** [comment]
I see, thanx! I'll use this solution for the time being.
But I still think that the PolygonSpriteBatch shouldn't throw `ArrayIndexOutOfBoundsException`, since SpriteBatch doesn't.

**Comment by NathanSweet** [comment]
PolygonSpriteBatch methods should use a loop to handle the case where the number of triangles that need to be drawn is higher than the number of triangles the PolygonSpriteBatch can draw in one batch, as [SpriteBatch](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/SpriteBatch.java#L555) does. What wants to take a (thoroughly tested) crack at this? :)

**Comment by NathanSweet** [comment]
On second thought, unlike SpriteBatch, PolygonSpriteBatch cannot (reasonably) split up the rendering into multiple batches when there are too many vertices because the triangles can reference any vertex. It's up to the caller to submit reasonably sized batches.
