### ISSUE TITLE
"unknown error 36059" when trying to use a FrameBufferCubemap

### ISSUE THREAD

**Issue by haedri** [libgdx/libgdx#3227]
When trying to use a FramBufferCubemap on a OSX system I get the following error (from the FrameBufferCubemap test) :
```
Exception in thread "LWJGL Application" java.lang.IllegalStateException: frame buffer couldn't be constructed: unknown error 36059
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:195)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.<init>(GLFrameBuffer.java:111)
	at com.badlogic.gdx.graphics.glutils.FrameBufferCubemap.<init>(FrameBufferCubemap.java:87)
	at com.badlogic.gdx.graphics.glutils.FrameBufferCubemap.<init>(FrameBufferCubemap.java:74)
	at com.badlogic.gdx.tests.g3d.FrameBufferCubemapTest.create(FrameBufferCubemapTest.java:44)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

I noticed that moving the line that gets the frame buffer status a few line below in GLFrameBuffer solves the issue, and the test runs perfectly fine after that (same as on Windows/Linux)

Problem is I have no idea if it is the correct way to do that, so I'll let someone that knows this subject better do a PR :)

There is no problem with standard FrameBuffer

Here's the patch of the modification I did to make the test work :
```
diff --git a/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java b/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
index c9a3648..792f68b 100644
--- a/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
+++ b/gdx/src/com/badlogic/gdx/graphics/glutils/GLFrameBuffer.java
@@ -169,11 +169,11 @@
 			gl.glFramebufferRenderbuffer(GL20.GL_FRAMEBUFFER, GL20.GL_STENCIL_ATTACHMENT, GL20.GL_RENDERBUFFER, stencilbufferHandle);
 		}
 
-		int result = gl.glCheckFramebufferStatus(GL20.GL_FRAMEBUFFER);
-
 		gl.glBindRenderbuffer(GL20.GL_RENDERBUFFER, 0);
 		gl.glBindTexture(GL20.GL_TEXTURE_2D, 0);
 		gl.glBindFramebuffer(GL20.GL_FRAMEBUFFER, defaultFramebufferHandle);
+		
+		int result = gl.glCheckFramebufferStatus(GL20.GL_FRAMEBUFFER);
 
 		if (result != GL20.GL_FRAMEBUFFER_COMPLETE) {
 			colorTexture.dispose();
```

I have no problem on Windows & Linux, I had issues only on OSX, tested on two systems :
* Mac mini (Intel HD 4000), Yosemite
* Hackintosh (Intel HD 3000), Yosemite

**Comment by realitix** [comment]
Good catch, just wait for Xoppa to valid your fix.
