### ISSUE TITLE
Libgdx 1.6.2 + robovm 1.3.0 makes iOS app crash

### ISSUE THREAD

**Issue by TMSantos** [libgdx/libgdx#3232]
Hello

My iOS launch used to work fine, but since I upgraded libgdx to 1.6.2 and robovm to 1.3.0 I started to have problems.

First i had this error:
ld: file not found: /ios/build/libs/ios/libgdx-box2d.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So I changed robovm.xml libs to only a "z" as mentioned by one user in libgdx forums.
(http://www.badlogicgames.com/forum/viewtopic.php?t=19642&p=82236)

After this I can build, but the app is crashing on launch with this exception:
java.lang.UnsatisfiedLinkError: com/badlogic/gdx/backends/iosrobovm/IOSGLES20.init()V

	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init(Native Method)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.<init>(IOSGLES20.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication.didFinishLaunching(IOSApplication.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didFinishLaunching(IOSApplication.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.$cb$application$didFinishLaunchingWithOptions$(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at ggj2015.game.IOSLauncher.main(IOSLauncher.java)

Note that I followed everything said here http://www.badlogicgames.com/wordpress/?p=3694 to update my project correctly.

Thank you

**Comment by TMSantos** [comment]
I am closing this, looks like its bad configuration on my side, so I will need to dig a bit more.

Thanks anyway.
