### ISSUE TITLE
eglSwapBuffers failed: EGL_BAD_ALLOC

### ISSUE THREAD

**Issue by panli32811** [libgdx/libgdx#3241]
Since my game published to Google Play, many crashing was reported to console.The error stack was:
java.lang.RuntimeException: eglSwapBuffers failed: EGL_BAD_ALLOC
	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1178)
	at android.opengl.GLSurfaceView$EglHelper.swap(GLSurfaceView.java:1136)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1216)
Usually this error occurs in Sony Xperia series devices.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Getting-Help
