### ISSUE TITLE
[v1.6.3] Crash sometimes with textField.setText("")

### ISSUE THREAD

**Issue by omicroh** [libgdx/libgdx#3249]
Hi there!

I use a chat in my online game. When we put a message in the chat, the textfield empties with textField.setText("") but sometimes it crashs.

Here is the error :

java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 0
09:38  INFO: [kryonet] Connection 1 disconnected.	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:63)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.updateDisplayText(TextField.java:377)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.paste(TextField.java:446)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.setText(TextField.java:564)
	at com.mygdx.Game.Chat.Chat.emptyTextField(Chat.java:491)
	at com.mygdx.Game.KeyListener.listen(KeyListener.java:35)
	at com.mygdx.Screens.GameScreen.render(GameScreen.java:255)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by Tom-Ski** [comment]
Need a self contained example that reproduces this.  Considering you are working with online chat you are probably just not being thread safe.

**Comment by omicroh** [comment]
KeyListener (g is the GameScreen) :

if(isKeyPressed(Keys.ENTER))
{
	//Si le chat est focused
	if (g.chat.isFocused())
	{
		//On envoit le packet si le chat n'est pas vide
		if (g.chat.getTextField().getText().equals("") == false)
		{
			//Envoit du packet
			g.chat.SendMessagePacket();
					
			//On vide le chat
			g.chat.emptyTextField();
		} 
		//Sinon, le champ est vide, on défocus
		else{
			g.chat.setFocus(false);
		}
	}
	//Le chat n'est pas focus, on le focus
	else {
		g.chat.setFocus(true);
	}
}

chat.emptyTextField() :

public void emptyTextField(){
	textField.setCursorPosition(0); //Looks useless
	textField.setText("");
}

Sorry the notion of thread-safe is not acquired for me. :/

**Comment by Tom-Ski** [comment]
That is not a self contained example, see https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Comment by fuatcoskun** [comment]
And why is this issue closed? Is there any workaround? There are too many similar issues on stackoverflow and forums.

http://stackoverflow.com/questions/32043154/glyphlayout-sometimes-through-arrayindexoutofboundsexception
https://github.com/libgdx/libgdx/issues/3172
http://www.badlogicgames.com/forum/viewtopic.php?t=19854&p=83027

The issue is not only related to thread-safety. I am facing similar issue as seen in following stack trace:

java.lang.ArrayIndexOutOfBoundsException: src.length=8 srcPos=0 dst.length=14 dstPos=0 length=9
       at java.lang.System.arraycopy(System.java)
       at com.badlogic.gdx.utils.Array.resize(Array.java:339)
       at com.badlogic.gdx.utils.Array.add(Array.java:100)
       at com.badlogic.gdx.utils.Pool.free(Pool.java:58)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:201)
       at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:208)
       at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
       at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)

and sure that modifying my scene2D group in UI thread by using "Gdx.app.postRunnable()"

**Comment by Tom-Ski** [comment]
It is closed as there is no self contained example reproducing the error. If you think you have found one, please supply the self contained example that reproduces. See https://github.com/libgdx/libgdx/wiki/Getting-help#barebones-stage

Otherwise, please use the forum or the irc channel for help with your code.
