### ISSUE TITLE
FreeTypeFontGenerator is broken in >=1.6.3

### ISSUE THREAD

**Issue by StanDem** [libgdx/libgdx#3274]
I think something is broken in FreeTypeFontGenerator and libgdx >=1.6.3 when using 
```param.incremental = true```
On previous version (1.6.2) I didn't get this error on the generateFont(param) line.

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator$FreeTypeBitmapFontData.getGlyph(FreeTypeFontGenerator.java:613)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:410)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:163)
```

My code:
```
    FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal("fonts/liberation.ttf"));
        FreeTypeFontParameter param = new FreeTypeFontParameter();
        param.incremental = true;
        param.size = 36;
        font = generator.generateFont(param);
```

**Comment by NathanSweet** [comment]
Fixed in 152b5a66e0cf7bbf970b3b756c28ce915d977b22
