### ISSUE TITLE
IndexOutofBoundsException in AndroidInput

### ISSUE THREAD

**Issue by s565288909** [libgdx/libgdx#3281]
Hi,I have used libGDX for Android TV games,thank you for libGDX.
Now there having a issue about **Key Value**.
On Android TV telecontroller,some key's **Key Value** is unusually.When you press them,program will crash.
Error log:

    FATAL EXCEPTION: main
    java.lang.ArrayIndexOutOfBoundsException: length=256; index=389
    at com.badlogic.gdx.backends.android.AndroidInput.onKey(AndroidInput.java:496)
    at android.view.View.dispatchKeyEvent(View.java:7208)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1362)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1362)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1362)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1920)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1395)
    at android.app.Activity.dispatchKeyEvent(Activity.java:2392)
    ...

**Comment by saltares** [comment]
Which Libgdx version are you using?

**Comment by s565288909** [comment]
I'm using **gdx-1.5.4**.
And I have tried **gdx-1.6.0**,this issue never appear again.Have you fixed it?

**Comment by davebaol** [comment]
Well, just update to 1.6.0 or newer :)
