### ISSUE TITLE
java.lang.NoClassDefFoundError thrown sometimes when returning to idle desktop game window

### ISSUE THREAD

**Issue by kutoman** [libgdx/libgdx#3318]
hi,
actually I'm not sure if it's a libgdx issue or a kotlin issue (since the game core is implemented in kotlin) but I **occasionally** get the mentioned error when I trigger any ingame ClickListener of a non-focused desktop window.

**Comment by Darkyenus** [comment]
https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#bug-reports

At least a complete stack trace would be nice, this is like reporting "it is broken, sometimes" :)

**Comment by kutoman** [comment]
yeah sorry, I read the guidelines before, but I thought I will rather get a response like "no it's not libgdx related", why I skipped some information.

one stack trace here:

```
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoClassDefFoundError: de/lmgt/quiz/view/screens/DuelStateScreen$refreshLayout$2
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.NoClassDefFoundError: de/lmgt/quiz/view/screens/DuelStateScreen$refreshLayout$2
	at de.lmgt.quiz.view.screens.DuelStateScreen.refreshLayout(DuelStateScreen.kt:100)
	at de.lmgt.quiz.view.screens.DuelStateScreen.show(DuelStateScreen.kt:51)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at de.lmgt.quiz.LmgtQuiz.setScreen(LmgtQuiz.kt:219)
	at de.lmgt.quiz.services.DuelModeManager.showDuelStateOf(DuelModeManager.kt:398)
	at de.lmgt.quiz.view.screens.DuelModeScreen$refreshLayout$2$4.invoke(DuelModeScreen.kt:279)
	at de.lmgt.quiz.view.screens.DuelModeScreen$refreshLayout$2$4.invoke(DuelModeScreen.kt:34)
	at de.lmgt.quiz.misc.MiscPackage$SoundedClick$becdf8c1$addSoundedClickListener$1.invoke(SoundedClick.kt:27)
	at de.lmgt.quiz.misc.MiscPackage$SoundedClick$becdf8c1$addSoundedClickListener$1.invoke(SoundedClick.kt)
	at de.lmgt.quiz.misc.MiscPackage$SoundedClick$becdf8c1$soundedClick$1.clicked(SoundedClick.kt:17)
	at de.lmgt.quiz.misc.SoundedClick.clicked(SoundedClick.kt:41)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: java.lang.ClassNotFoundException: de.lmgt.quiz.view.screens.DuelStateScreen$refreshLayout$2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
```

**Comment by xoppa** [comment]
Please use the forum or irc if you need help debugging your code. If you are actually reporting an issue with libgdx, then at least include the information required to reproduce the issue. https://github.com/libgdx/libgdx/wiki/Getting-Help

**Comment by kutoman** [comment]
well, it's not about debugging. I just reported this error, since I faced it several times. The huge problem is that it's happening occasionally. I have no idea what might be the reason. I will provide more information if I'm able to. I've already checked the forums and issues, nothing similar found. The only thing I haven't tried yet are the nightly builds (currently using 1.6.4).

**Comment by MobiDevelop** [comment]
There is pretty much no possible way this could be due to libgdx.

**Comment by kutoman** [comment]
ok thanks for the response, I think I should report this in the kotlin world.
