### ISSUE TITLE
Android Controller Proguard 

### ISSUE THREAD

**Issue by zepplondon** [libgdx/libgdx#3322]
AndroidController class needs to be added to proguard keeps.

-keep class com.badlogic.gdx.controllers.android.AndroidControllers

Please update the docs or correct me if i"m getting something wrong because app crashes without this exclusion. 

Here's the error

 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.badlogic.gdx.controllers.android.AndroidControllers" on path: DexPathList[[zip file "/data/app/com.example.game-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.game-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:309)
            at java.lang.Class.forName(Class.java:273)
            at com.badlogic.gdx.utils.b.b.a(ClassReflection.java:28)
            at com.badlogic.gdx.c.d.b(Controllers.java:97)
            at com.badlogic.gdx.c.d.a(Controllers.java:51)

**Comment by azakhary** [comment]
Maybe this is related to MultiDex APK?

**Comment by badlogic** [comment]
Ya, we should update the proguard file in the template. The controller
implementation is instantiated via reflection. ProGuard finds no reference
to the AndroidControllers impl and rips it out.

**Comment by Tom-Ski** [comment]
Added with https://github.com/libgdx/libgdx/commit/1f32031423ff0a3efc434ee462e2b3a3eec06b5c
