### ISSUE TITLE
About the layout of the label actor method processing, subscript cross-border problems, on the desktop

### ISSUE THREAD

**Issue by KokoField** [libgdx/libgdx#3369]
Exception:
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.badlogic.gdx.utils.Array.resize(Array.java:339)
	at com.badlogic.gdx.utils.Array.add(Array.java:100)
	at com.badlogic.gdx.utils.Pool.free(Pool.java:58)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:199)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:738)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:106)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:738)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:106)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.layout(ScrollPane.java:521)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:106)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:528)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.abc.ranger.MainScreen.render(MainScreen.java:78)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.abc.ranger.MainGame.render(MainGame.java:27)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by Darkyenus** [comment]
Please report reproducible issue within libGDX properly: https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#bug-reports

That aside, this very much looks like a problem that would happen when using multiple threads - libGDX is by default not thread safe and all sorts of bugs (that are not libGDX's fault) will happen when not VERY careful while working with them.
