### ISSUE TITLE
(v1.6.5) GlyphLayout.setText.197 - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fuatcoskun** [libgdx/libgdx#3388]
Hi guys,

I have upgraded my game from libgdx version 1.5.4 to 1.6.5 and facing GlyphLayout issue as seen on following stack trace :

```
java.lang.ArrayIndexOutOfBoundsException: src.length=8 srcPos=0 dst.length=14 dstPos=0 length=9
       at java.lang.System.arraycopy(System.java)
       at com.badlogic.gdx.utils.Array.resize(Array.java:339)
       at com.badlogic.gdx.utils.Array.add(Array.java:100)
       at com.badlogic.gdx.utils.Pool.free(Pool.java:58)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:201)
       at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:208)
       at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
       at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
       at net.games.mobile.core.ui.widget.AnimatedLoadingWidget.draw(AnimatedLoadingWidget.java:86)
       at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
       at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
       at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
       at net.games.libgdx.stagebuilder.core.AbstractScreen.render(AbstractScreen.java:120)
       at net.games.mobile.hearts.core.view.CardGameScreen.render(CardGameScreen.java:114)
       at net.games.libgdx.stagebuilder.core.AbstractGame.render(AbstractGame.java:84)
       at net.games.mobile.hearts.core.CardGame.render(CardGame.java:273)
       at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:422)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

I saw suggestions about preventing multiple thread access to UI elements but I already accessing my widget via Gdx.app.postRunnable() blocks as seen below :

```
public void displayLoadingWidget(final int timeout) {
        Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run() {
                if (loadingWidget != null) {
                    loadingWidget.remove();
                }
                AnimatedLoadingWidget.AnimatedLoadingWidgetStyle style = new AnimatedLoadingWidget.AnimatedLoadingWidgetStyle();
                style.atlasName = Constants.COMMON_ATLAS;
                style.spriteName = "loading";
                style.fontName = Constants.FONT_26;
                style.frameDuration = 40;
 
                loadingWidget = new AnimatedLoadingWidget(style, cardGame.getAssetsInterface(), game.getResolutionHelper());
                stage.addActor(loadingWidget);
                loadingWidget.setText(cardGame.getLocalizationService().getString("loading"));
                loadingWidget.setTimeout(timeout);
                loadingWidget.setVisible(true);
            }
        });
    }
```
```
public void removeLoadingWidget() {
        Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run() {
                log.d("Dismissing loading widget.");
                if (loadingWidget != null) {
                    loadingWidget.setVisible(false);
                }
            }
        });
    }
```

Problem is that 

```
System.arraycopy(items, 0, newItems, 0, Math.min(size, newItems.length));
```

"size" field of Array.java is somehow bigger than "items.length". They should be the same in normal case. I couldn't find any reason for this difference and can not reproduce the issue always, so this situation is uncertain.

I want to highlight this :

```
src.length=8 
srcPos=0 
dst.length=14 
dstPos=0 
length=9
```

Here, length is the result of "Math.min(size, newItems.length)" and it is "9" so size equals to "9".
But src.length = "8" which means items.length.

How can this possible except of multi-threaded access problem?

This is my AnimatedLoadingWidget class and problem occurs on draw methods first line 
( super.draw(batch, parentAlpha);)
:

```
package net.games.mobile.core.ui.widget;
 
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer.ShapeType;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.Group;
import com.badlogic.gdx.scenes.scene2d.Touchable;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.utils.Align;
import com.badlogic.gdx.scenes.scene2d.utils.Drawable;
import net.games.libgdx.stagebuilder.core.assets.AssetsInterface;
import net.games.libgdx.stagebuilder.core.assets.ResolutionHelper;
 
import java.util.ArrayList;
 
public class AnimatedLoadingWidget extends Group{
    private AssetsInterface assets;
    private SequentialImage loadingImage;
    private ShapeRenderer shapeRenderer;
    private Label text;
    private AnimatedLoadingWidgetStyle style;
    private int timeout = 0;
    private long showTime;
 
    public AnimatedLoadingWidget(){
 
    }
 
    public AnimatedLoadingWidget(AnimatedLoadingWidgetStyle style, AssetsInterface assets, ResolutionHelper resolutionHelper) {
        this.assets = assets;
        this.style = style;
        initialize(resolutionHelper);
    }
    private void buildLoadingImage(ResolutionHelper resolutionHelper) {
        ArrayList<Drawable> images = new ArrayList<Drawable>();
        TextureAtlas textureAtlas = assets.getTextureAtlas(style.atlasName);
        SequentialImage.SequentialImageStyle sequentialImageStyle = new SequentialImage.SequentialImageStyle();
        sequentialImageStyle.images = textureAtlas.findRegions(style.spriteName);
        sequentialImageStyle.frameDuration = style.frameDuration;
 
        loadingImage = new SequentialImage(sequentialImageStyle);
        loadingImage.setWidth(sequentialImageStyle.images.get(0).getRegionWidth() * resolutionHelper.getSizeMultiplier());
        loadingImage.setHeight(sequentialImageStyle.images.get(0).getRegionHeight() * resolutionHelper.getSizeMultiplier());
 
        loadingImage.setX((getWidth()-loadingImage.getWidth())/2);
        loadingImage.setY((getHeight()-loadingImage.getHeight())/2);
 
        addActor(loadingImage);
    }
    public void initialize(ResolutionHelper resolutionHelper) {
        float sizeMultiplier = resolutionHelper.getSizeMultiplier();
 
        shapeRenderer = new ShapeRenderer();
 
        setSize(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
 
        buildLoadingImage(resolutionHelper);
        Label.LabelStyle labelStyle = new Label.LabelStyle(assets.getFont(style.fontName), Color.WHITE);
 
        text = new Label("", labelStyle);
        text.setBounds(0, loadingImage.getY()-40, getWidth(), 40);
        text.setAlignment(Align.center | Align.top);
        addActor(text);
        setTouchable(Touchable.enabled);
    }
    public void setText(String string){
        text.setText(string);
    }
 
    private void resizeActor(Actor actor, float sizeMultiplier) {
        actor.setScale(sizeMultiplier);
    }
 
    public void setTimeout(int timeout){
        this.timeout = timeout;
        showTime = System.currentTimeMillis();
    }
 
    @Override
    public void draw (Batch batch, float parentAlpha) {
        super.draw(batch, parentAlpha);
 
        Gdx.gl.glEnable(GL20.GL_BLEND);
        Gdx.gl.glBlendFunc(GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);
 
        shapeRenderer.setProjectionMatrix(batch.getProjectionMatrix());
        shapeRenderer.begin(ShapeType.Filled);
        shapeRenderer.setColor(0f, 0f, 0f, 0.4f);
        shapeRenderer.rect(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        shapeRenderer.end();
 
        if (timeout > 0) {
            if (this.showTime + this.timeout < System.currentTimeMillis()) {
                setVisible(false);
            }
        }
    }
 
    public static class AnimatedLoadingWidgetStyle{
        public String atlasName;
        public String spriteName;
        public String fontName;
        public int frameDuration;
    }
}
```

**Comment by NathanSweet** [comment]
Without an SSCE what can we do?

**Comment by Tom-Ski** [comment]
No SCCE, no way we can reproduce give the code provided. Please reopen if you can supply the SSCE.
