### ISSUE TITLE
unable to create SDF fonts with Hiero

### ISSUE THREAD

**Issue by nickdesaulniers** [libgdx/libgdx#3421]
Following the instructions [here](https://github.com/libgdx/libgdx/wiki/Hiero#running-hiero), I've downloaded the prebuilt jar from [here](https://code.google.com/p/libgdx/downloads/detail?name=hiero.jar&can=2&q=). Running `java -jar ~/Downloads/hiero.jar`, I was initially getting an error which I resolved based on info from [here](http://stackoverflow.com/questions/21028507/libgdx-project-cant-load-library-liblwjgl-dylib#comment53123508_21028507).

Now, when I run `java -jar ~/Downloads/hiero.jar`, I do not have the option "Distance field" under "Effects" as instructed from [here](https://github.com/libgdx/libgdx/wiki/Distance-field-fonts#rendering-super-smooth-scalable-bitmap-fonts).  Further, I have the following stack trace in my console:

```
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NullPointerException
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.start(LwjglCanvas.java:161)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1$1.run(LwjglCanvas.java:66)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.lwjgl.opengl.GL11.glGetString(GL11.java:1901)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:205)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:161)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.start(LwjglCanvas.java:155)
	... 15 more
```

**Comment by nickdesaulniers** [comment]
osx 10.10.5
```
➜  vr-markup git:(dev) ✗ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by xoppa** [comment]
Thanks. Fixed the wiki.

**Comment by nickdesaulniers** [comment]
cool thanks!
