### ISSUE TITLE
Shared Library 'gdx.dll' not found if '!' is in the foldername

### ISSUE THREAD

**Issue by MilchDev** [libgdx/libgdx#3429]
Shared Library 'gdx.dll' not found if '!' is in the foldername.
Tested it on Windows 8 & Windows 7

Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx.dll' for target: Windows 8.1, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
        at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:76)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64)
        ...
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx.dll
        at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:126)
        at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:261)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
        ... 5 more

**Comment by slebed** [comment]
I think that's a Windows issue, not libgdx.  The ! symbol in a file path is probably a no-no.  It would be like using % or * in the name.

**Comment by xoppa** [comment]
Probably something like this: http://bugs.java.com/view_bug.do?bug_id=4523159
I'm afraid there's not much we can do about it. Relevant code: https://github.com/libgdx/libgdx/blob/1.6.5/gdx/src/com/badlogic/gdx/utils/SharedLibraryLoader.java#L125-L126

**Comment by MobiDevelop** [comment]
Sounds like there is nothing we can do here.
