### ISSUE TITLE
Issues embedding LwjglAWTCanvas in swing on certain system(s)

### ISSUE THREAD

**Issue by CotterPin-Source** [libgdx/libgdx#3528]
**Issue**

Upon embedding a `LwjglAWTCanvas` into swing, I am met with error output as shown at the bottom of this post. The same code can be run on my macbook (El Capitan, LibGDX: 1.7.0) without issue. Additionally, `LwjglApplication` and `LwjglCanvas` seem to work normally.

**System Specifications:**
* OS
  * Microsoft Windows 10 Pro 
  * Version: 10.0.10240 Build 10240

* GPU
  * AMD Radeon (TM) R9 390 Series
  * Driver: Catalyst 15.7 9.14.10.01128
  * API Support: OpenGL 4.5, OpenCl 2.0, DirectX 12, Mantle, Vulkan

* LibGDX
  * Version 1.7.0

**Sample Code:**
```java
public class DesktopLauncher extends JFrame {

	private LwjglAWTCanvas canvas;

	public DesktopLauncher() {
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		
		canvas = new LwjglAWTCanvas(new TestGame());
		canvas.getCanvas().setSize(500, 500);
		add(canvas.getCanvas());
		
		pack();
		setVisible(true);
	}

	public static void main (String[] arg) {
		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				new DesktopLauncher();
			}
		});
	}

	@Override
	public void dispose() {
		canvas.stop();

		super.dispose();
	}
}
```

**Crash Error Output:**
```Java
Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
ATI Technologies Inc.
AMD Radeon (TM) R9 390 Series
4.5.13399 Compatibility Profile Context 15.200.1062.1004
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:222)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.initGL(LwjglAWTCanvas.java:89)
	at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:337)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4957)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
ATI Technologies Inc.
AMD Radeon (TM) R9 390 Series
4.5.13399 Compatibility Profile Context 15.200.1062.1004
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:317)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.create(LwjglAWTCanvas.java:214)
	... 25 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas.render(LwjglAWTCanvas.java:238)
	at com.badlogic.gdx.backends.lwjgl.LwjglAWTCanvas$1.paintGL(LwjglAWTCanvas.java:95)
	at org.lwjgl.opengl.AWTGLCanvas.paint(AWTGLCanvas.java:339)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4957)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Additional Information**

Upon adding the following line to the create void in `LwjglAWTCanvas`, the application will open and display a frame of the canvas shortly before freezing up completely without console output.
![](http://i.imgur.com/Pm1WDUI.png)
![](http://i.imgur.com/aUMUvP5.png)

**Comment by NathanSweet** [comment]
Maybe try running from a libgdx nightly, LwjglAWTCanvas has seen fixes lately. Otherwise please post an SSCCE.

**Comment by CotterPin-Source** [comment]
Fresh jdk/gradle install and libGDX 1.7.1 seemed to fix the issue.
