### ISSUE TITLE
Failing build - Unable to extract LWJGL natives

### ISSUE THREAD

**Issue by 3xp0n3nt** [libgdx/libgdx#3578]
@NathanSweet Please see the comments on commit https://github.com/libgdx/libgdx/commit/e1aa0e56415f76df6de67aaafc4ce3bc2cc4f9c1. Several people have reported the same error, now on Windows, Mac, & Linux, from this change. Here's my stack trace on OS X Yosemite:

```
com.badlogic.gdx.utils.GdxRuntimeException: Unable to extract LWJGL natives.
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:67) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:76) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:64) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	at com.forerunnergames.peril.desktop.DesktopLauncher.main(DesktopLauncher.java:65) ~[main/:na]
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error extracting file: openal.dylib
To: /var/folders/9g/w7dzqgq94lj2q7kd_n7q7rth0000gn/T/libgdxAaron/f7649394
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:265) ~[gdx-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFileTo(SharedLibraryLoader.java:171) ~[gdx-1.7.2-SNAPSHOT.jar:na]
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:60) ~[gdx-backend-lwjgl-1.7.2-SNAPSHOT.jar:na]
	... 3 common frames omitted
Caused by: java.io.FileNotFoundException: /var/folders/9g/w7dzqgq94lj2q7kd_n7q7rth0000gn/T/libgdxAaron/f7649394 (Is a directory)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_65]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171) ~[na:1.7.0_65]
	at com.badlogic.gdx.utils.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:255) ~[gdx-1.7.2-SNAPSHOT.jar:na]
```

**Comment by NathanSweet** [comment]
Oops, sorry about that guys. I tested but in apps that had audio disabled!

**Comment by songproducer** [comment]
I'm still getting this error when trying to use Bfont text.
