### ISSUE TITLE
FreeTypeFont

### ISSUE THREAD

**Issue by TaiVuong** [libgdx/libgdx#3583]
file /gdx-tests-android/assets/data/cjsongeb.ttf.gz  can't load.
It make FreeTypeIncrementalTest can't run.
I think http://unifoundry.com is the best font for test multi languages.

**Comment by NathanSweet** [comment]
FreeTypeIncrementalTest works for me.

**Comment by TaiVuong** [comment]
Mac OSX 10.11.1
```
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load font
	at com.badlogic.gdx.graphics.g2d.freetype.FreeType$Library.newMemoryFace(FreeType.java:83)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.<init>(FreeTypeFontGenerator.java:113)
	at com.badlogic.gdx.tests.extensions.FreeTypeIncrementalTest.create(FreeTypeIncrementalTest.java:67)
```
It is not a issue because it is still running if I replace it with another file
