### ISSUE TITLE
Png file is not created together with fnt file

### ISSUE THREAD

**Issue by vinicri** [libgdx/libgdx#3667]
Going to Menu File>Save BMFont files (text) only creates the fnt file. The png is missing

**Comment by MobiDevelop** [comment]
I get a .png file along with the .fnt; however, on my Mac, the Freetype option is not rendering the glyphs (either on the preview or the output).

**Comment by MobiDevelop** [comment]
The problem with Freetype only presents in the case of using a system font (not sure if that is a known issue, but is definitely unrelated to this report).

I am still unable to reproduce the missing png issue, unfortunately.

**Comment by vinicri** [comment]
I run from the Hiero class, ligdx 1.7.1, works fine. 
The issue is with the jar file distributed here https://libgdx.badlogicgames.com/tools.html

**Comment by MobiDevelop** [comment]
I used that jar for my testing and it worked for me.

**Comment by NathanSweet** [comment]
Please note that FreeType needs the font file. When choosing a system font it uses reflection to find it on Sun JVMs, if this fails you'll have to specify a path to a font file. Not sure how to make this clear in the UI.

**Comment by kjempff** [comment]
Getting this exception whether a system font or .ttf file selected. notes. Same ttf works with old BMFont and old Hiero3.
Downloaded 31/12-2015.
output:

C:\java\graphics\fonts\hiero_test>java -jar runnable-hiero.jar
Error saving BMFont files: C:\java\graphics\fonts\hiero_test\test.fnt
java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
        at com.badlogic.gdx.tools.hiero.BMFontUtil.save(BMFontUtil.java:96)
        at com.badlogic.gdx.tools.hiero.Hiero$Renderer.render(Hiero.java:1503)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:242)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$000(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

C:\java\graphics\fonts\hiero_test>java -version
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b22)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)

C:\java\graphics\fonts\hiero_test>

**Comment by MobiDevelop** [comment]
You have to use Java 8 to run it now (unless we remove that one line that makes it require Java 8).

**Comment by badlogic** [comment]
Let's remove that one line.

**Comment by MobiDevelop** [comment]
Done

**Comment by MobiDevelop** [comment]
@vinicri Can you see if this is still an issue for you, perhaps it was the Java 8 method that was problematic for you.

**Comment by NathanSweet** [comment]
Thanks @MobiDevelop. Let's assume that fixed it and reopen if not.
