### ISSUE TITLE
Hiero can't create png

### ISSUE THREAD

**Issue by kiquetal** [libgdx/libgdx#3684]
Hiero couldn't create the png 

Error saving BMFont files: /home/kiquetal/Documents/codes/2016/games/test/core/assets/otro.jpg
java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
        at com.badlogic.gdx.tools.hiero.BMFontUtil.save(BMFontUtil.java:96)
        at com.badlogic.gdx.tools.hiero.Hiero$Renderer.render(Hiero.java:1503)
        at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:242)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

OS:opensuse 13.1
java -version:java version "1.7.0_85"

**Comment by MobiDevelop** [comment]
This has already been fixed. Either update to the snapshots, or use Java 8 in the meantime before the next release.
