### ISSUE TITLE
lwjgl linux; liblwjgl.so: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by junkdog** [libgdx/libgdx#3704]
Using 1.8.0, old LWJGL works fine, but I can't get new one to start.

The liblwjgl.so under /tmp is 32 bit, though the one under target/natives is 64 bit. (I tried manually replacing it, but it's recreated each time as far as I can tell).

```
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/libgdxjunkdog/1c78875b/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libgdxjunkdog/1c78875b/liblwjgl.so: /tmp/libgdxjunkdog/1c78875b/liblwjgl.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1083)
    at org.lwjgl.system.Library$1.load(Library.java:25)
    at org.lwjgl.system.Library$1.load(Library.java:22)
    at org.lwjgl.system.Library.loadLibrary(Library.java:196)
    at org.lwjgl.system.Library.loadSystem(Library.java:90)
    at org.lwjgl.system.Library.<clinit>(Library.java:48)
    at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56)
    at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:57)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:64)
    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:73)
    at se.feomedia.map.MapApplicationDesktopNoSwing.main(MapApplicationDesktopNoSwing.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by badlogic** [comment]
Thanks for reporting. I'll try to reproduce this.

**Comment by Desmaster** [comment]
@junkdog what's the status on this issue?

**Comment by hasuo** [comment]
@junkdog I have the same issue. Could you check something quick? 
Seems like gdx-tools/ pulls in lwjgl version 2: 
http://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-tools/1.9.2

Does your project work without tools? 
My asset processing tool uses the texture packer, and does not work with lwjgl3, the normal desktop project does. Looking at ./gradlew dependencies spits out that both versions of lwjgl are pulled in. 

I have no Idea how to test if that is the actual reason, though...

**Comment by antag99** [comment]
Had this issue, solved it by removing `gdx-tools` from my desktop project.
I think this is because the natives for LWJGL 2 are loaded instead of the LWJGL 3 ones.

**Comment by badlogic** [comment]
@antag99 is exactly right. You can't currently mix a LWJGL3 project with gdx-tools.
