### ISSUE TITLE
1.8.0: Hiero crashing in batch mode

### ISSUE THREAD

**Issue by ttencate** [libgdx/libgdx#3744]
Running it in batch mode from `desktop/build.gradle` like this:

```
task fonts(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  main = "com.badlogic.gdx.tools.hiero.Hiero"
  args = ["--batch", "--input", "../fonts/azoft-sans.hiero", "--output", "android/assets/azoft-sans.fnt"]
}
```

Stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
	at com.badlogic.gdx.tools.hiero.Hiero.updateFont(Hiero.java:303)
	at com.badlogic.gdx.tools.hiero.Hiero$1FontUpdateListener.stateChanged(Hiero.java:433)
	at javax.swing.JSpinner.fireStateChanged(JSpinner.java:458)
	at javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:386)
	at javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:119)
	at javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:447)
	at javax.swing.JSpinner.setValue(JSpinner.java:354)
	at com.badlogic.gdx.tools.hiero.Hiero.open(Hiero.java:375)
	at com.badlogic.gdx.tools.hiero.Hiero.parseArgs(Hiero.java:241)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:205)
	at com.badlogic.gdx.tools.hiero.Hiero$21.run(Hiero.java:1579)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The fix should be easy enough. I'll send a PR.

**Comment by ttencate** [comment]
FWIW, this was also affecting regular GUI mode when opening a Hiero settings file.
