### ISSUE TITLE
Libgdx 1.9.0 crashes on Note 4

### ISSUE THREAD

**Issue by sarkanyi** [libgdx/libgdx#3775]
USER_COMMENT=null
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=0.6.67
BRAND=samsung
PHONE_MODEL=SM-N910F
CUSTOM_DATA=
STACK_TRACE=com.badlogic.gdx.utils.GdxRuntimeException: Error extracting the OpenGL version: OpenGL ES 3.1V@104.0 (GIT@I4ea93f0e25)
at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:269)
at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:238)
at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:292)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
Caused by: java.lang.NumberFormatException: Invalid int: "1V@104.0"
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:410)
at java.lang.Integer.parseInt(Integer.java:367)
at java.lang.Integer.parseInt(Integer.java:334)
at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:267)
... 4 more
java.lang.NumberFormatException: Invalid int: "1V@104.0"
at java.lang.Integer.invalidInt(Integer.java:138)
at java.lang.Integer.parse(Integer.java:410)
at java.lang.Integer.parseInt(Integer.java:367)
at java.lang.Integer.parseInt(Integer.java:334)
at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:267)
at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:238)
at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:292)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by badlogic** [comment]
Wow, Samsung are really great at breaking things.

**Comment by sarkanyi** [comment]
Yupp, will you fix it or should I? I also wonder what other perversions are made by other manufacturers.

**Comment by badlogic** [comment]
Of course we'll fix it :)
