### ISSUE TITLE
In 1.9.0, android can not work: Error extracting the OpenGL version: OpenGL ES 3.1V@104.0 

### ISSUE THREAD

**Issue by tianqiujie** [libgdx/libgdx#3786]
com.badlogic.gdx.utils.GdxRuntimeException: Error extracting the OpenGL version: OpenGL ES 3.1V@104.0 (GIT@I15bf295f1a)
            at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:269)
            at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:238)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:292)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
     Caused by: java.lang.NumberFormatException: Invalid int: "1V@104.0"
            at java.lang.Integer.invalidInt(Integer.java:138)
            at java.lang.Integer.parse(Integer.java:410)
            at java.lang.Integer.parseInt(Integer.java:367)
            at java.lang.Integer.parseInt(Integer.java:334)
            at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:267)
            at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:238)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:292)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by Tom-Ski** [comment]
Resolved in 1.9.1-SNAPSHOT, please search the issue tracker for open and closed issues before posting.

**Comment by davebaol** [comment]
Since 1.9.0 is broken I think that we should release 1.9.1 soon

**Comment by Tom-Ski** [comment]
It will be, there are some other problems at the moment that need fixing before its worthwhile to release.
