### ISSUE TITLE
Exception using Genymotion

### ISSUE THREAD

**Issue by fechy** [libgdx/libgdx#3833]
Hi, 

I'm getting this exception ONLY when trying to debug using Genymotion.

````java
02-09 16:09:54.682    4444-4489/? W/GL2JNIView﹕ creating OpenGL ES 2.0 context
02-09 16:09:54.683    4444-4489/? E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 172
    Process: com.kingmonkey.arkanoid.android, PID: 4444
    java.lang.IllegalArgumentException
            at com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
            at com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
            at com.badlogic.gdx.backends.android.surfaceview.GLSurfaceView20$ContextFactory.createContext(GLSurfaceView20.java:144)
            at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1029)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
````
This happened since version 1.9.0 and currently on version 1.9.2.

**Comment by sjosegarcia** [comment]
Following the stack, and the recent updates it seems like this is happening
since libgdx started using opengl es 3.

**Comment by intrigus** [comment]
Have you tried other apps that use OpenGL ES 2.0?
Please add a sscce.org .

**Comment by MobiDevelop** [comment]
Unable to replicate, without an SSCCE there is nothing anyone can do. Closing.
