### ISSUE TITLE
Double-click select causes StringIndexOutOfBoundsException in TextField.wordUnderCursor

### ISSUE THREAD

**Issue by dan-fitzgerald-av** [libgdx/libgdx#3887]
#### Issue details
In a left-aligned TextField or TextArea, if I double-click to the right of the current text, I get StringIndexOutOfBoundsException 

#### Reproduction steps/code
Double click to the ~~left~~ edit: right of any left-aligned (or probably also center-aligned) text in a TextField or TextArea. (Happens with the default TextArea)
 
#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.charAt(String.java:646)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:166)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:175)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.clicked(TextField.java:769)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.touchUp(TextField.java:795)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:96)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

#### Please select the affected platforms
All (maybe only mouse based?)

**Comment by xoppa** [comment]
Can't reproduce.
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by dan-fitzgerald-av** [comment]
Double click to the right of "Text"

`public static class BarebonesStage extends ApplicationAdapter {
		Stage stage;

		public void create () {
			stage = new Stage(new ScreenViewport());
			Gdx.input.setInputProcessor(stage);

			Skin skin = new Skin(Gdx.files.internal("data/uiskin.json"));

			TextArea textArea = new TextArea("Text", skin);

			Table table = new Table();
			stage.addActor(table);
			table.setFillParent(true);

			table.debug();
			table.defaults().space(6);
			table.add(textArea);
		}

		public void render () {
			Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
			stage.draw();
		}

		public void resize (int width, int height) {
			// Pass false to not modify the camera position.
			stage.getViewport().update(width, height, true);
		}

		public static void main (String[] args) throws Exception {
			new LwjglApplication(new BarebonesStage());
		}
	}`

**Comment by xoppa** [comment]
Can reproduce in `TextAreaTest

**Comment by xoppa** [comment]
Can reproduce it in `TextAreaTest` by removing some test from the `TextArea` and clicking on the right (the initial steps to reproduce said left). Can't reproduce it on the `TextField` though/

**Comment by dan-fitzgerald-av** [comment]
In the test code I sent, when I double click in the TextArea to the right of the contents of the TextArea, it crashes. You're right, I mistakenly said "left of the left-aligned" in the original issue post. 
I haven't reproduced it with TextField either but the problem code resides in TextField.

**Comment by Metaphore** [comment]
This bug appears with my small pixelart bmfont. Somehow `at` parameter of ```TextField#wordUnderCursor``` exceeds text's length by one and that causes crash.

This is workaround for TextField/TextArea I use:
```
@Override
protected int[] wordUnderCursor (int at) {
    String text = this.text;
    // Here is a fix. We constrain at parameter with text length
    int start = Math.min(text.length(), at), right = text.length(), left = 0, index = start;
    for (; index < right; index++) {
        if (!isWordCharacter(text.charAt(index))) {
            right = index;
            break;
        }
    }
    for (index = start - 1; index > -1; index--) {
        if (!isWordCharacter(text.charAt(index))) {
            left = index + 1;
            break;
        }
    }
    return new int[] {left, right};
}
```

**Comment by douglasjunior** [comment]
I also have the same problem.

Just double-click below the text.

![libgdx textarea error](https://cloud.githubusercontent.com/assets/1512341/15796101/c9fea250-29ce-11e6-94ad-e64e318027ab.PNG)

```java
Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: 22
	at java.lang.String.charAt(String.java:658)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:166)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.wordUnderCursor(TextField.java:175)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.clicked(TextField.java:769)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.touchUp(TextField.java:795)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)

```
