### ISSUE TITLE
ETC1.encodeImagePKM crashes due to the null Gdx.app

### ISSUE THREAD

**Issue by JFixby** [libgdx/libgdx#3914]
#### Issue details
Here is the actual line of code that should be replaced with ```System.out.println()```:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/glutils/ETC1.java#L91
```
Gdx.app.debug("ETC1Data", "warning: non-power-of-two ETC1 textures may crash the driver of PowerVR GPUs");
```

#### Reproduction steps/code
```
public static void main(String[] args) {

	File inputFile = new File("some_image.png");
	File outputFile = new File("some_image.etc1");

	GdxNativesLoader.load();
	System.out.println("Processing " + inputFile);

	Pixmap pixmap = new Pixmap(new FileHandle(inputFile));
	if (pixmap.getFormat() != Format.RGB888 && pixmap.getFormat() != Format.RGB565) {
	    System.out.println("Converting from " + pixmap.getFormat() + " to RGB888!");
	    Pixmap tmp = new Pixmap(pixmap.getWidth(), pixmap.getHeight(), Format.RGB888);
	    tmp.drawPixmap(pixmap, 0, 0, 0, 0, pixmap.getWidth(), pixmap.getHeight());
	    pixmap.dispose();
	    pixmap = tmp;
	}
	ETC1.encodeImagePKM(pixmap).write(new FileHandle(outputFile));
	pixmap.dispose();

    }
```

#### Version of LibGDX and/or relevant dependencies
all

#### Stacktrace
```
Converting from RGBA8888 to RGB888!
Exception in thread "main" java.lang.NullPointerException
	at com.badlogic.gdx.graphics.glutils.ETC1$ETC1Data.checkNPOT(ETC1.java:91)
	at com.badlogic.gdx.graphics.glutils.ETC1$ETC1Data.<init>(ETC1.java:60)
	at com.badlogic.gdx.graphics.glutils.ETC1.encodeImagePKM(ETC1.java:166)
	at com.badlogic.gdx.tools.etc1.ETC1Compressor.compressFile(ETC1Compressor.java:48)
	at com.jfixby.tool.texturepacker.test.ETC1CompressorTest.main(ETC1CompressorTest.java:22)
```

#### Please select the affected platforms
- [x] gdx-tools

**Comment by JFixby** [comment]
Thank you @intrigus.

Yes and the suggested fix is to make the class not use gdx because he no need it anyway.
