### ISSUE TITLE
Lwjgl3 error with gl3 enabled

### ISSUE THREAD

**Issue by realitix** [libgdx/libgdx#3932]
#### Issue details
With Lwjgl3 backend, when using GL2, window opens and all works but when using GL3, error appears and application crashes.

#### Version of LibGDX and/or relevant dependencies
Version 1.9.2

#### Stacktrace
```java
[LWJGL] Version: 3.0.0b SNAPSHOT
[LWJGL] 	 OS: Windows 7 v6.1
[LWJGL] 	JRE: 1.8.0_65 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.65-b01 by Oracle Corporation
[LWJGL] Loaded library from org.lwjgl.librarypath: lwjgl
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loaded native library: D:\Users\T0143947\AppData\Local\Temp\libgdxT0143947\135ea35f\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loaded native library: D:\Users\T0143947\AppData\Local\Temp\libgdxT0143947\135ea35f\glfw.dll
[LWJGL] Loaded native library: D:\Users\T0143947\AppData\Local\Temp\libgdxT0143947\135ea35f\OpenAL.dll
[LWJGL] GLFW_VERSION_UNAVAILABLE error
	Description : WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1168)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1251)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:365)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:329)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:93)
		com.realhome.desktop.DesktopLauncher.main(DesktopLauncher.java:14)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:368)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:329)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:93)
	at com.realhome.desktop.DesktopLauncher.main(DesktopLauncher.java:14) 
```

#### Details
My computer doesn't seem to have the `WGL_ARB_create_context_profile` extension. 
If I remove this [line](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L355) , it works.

**Is the OpenGL core profile mandatory in Lwjgl3 ?**

**Comment by code-disaster** [comment]
This compat/forward context stuff is a cross-platform mess. It's mandatory for anything GL3.2+ on OS X, but blows in your face in other occasions like this one.

see: http://www.glfw.org/docs/latest/compat.html

I see two options: use the CORE_PROFILE hint only on OS X, or add a fallback to try the window creation again, without the CORE_PROFILE hint, in case the first attempt fails.

**Comment by realitix** [comment]
It sounds good to try with core profile and then without if it fails.
