### ISSUE TITLE
Crashes java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ldthai** [libgdx/libgdx#3943]
Hello
i got crashes(in device Galaxy Note II)

java.lang.ArrayIndexOutOfBoundsException in com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion

`java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
	at com.badlogic.gdx.backends.android.AndroidGraphics.extractVersion(AndroidGraphics.java:278)
	at com.badlogic.gdx.backends.android.AndroidGraphics.setupGL(AndroidGraphics.java:242)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:302)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1494)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

#### Version of LibGDX
Libgdx 1.9.2

#### platforms
- [ x] Android

thanks!

**Comment by davebaol** [comment]
Code has changed since 1.9.2, see commit https://github.com/libgdx/libgdx/commit/a0d2b13bbc81ecd291c8c9a3f4dc7830373768c8.
So, please, test the snapshot and reopen this issue if the problem is still there.
