### ISSUE TITLE
Multidex on a libgdx android application breaks the application (this should never happen)

### ISSUE THREAD

**Issue by DanHale123** [libgdx/libgdx#3950]
#### Issue details
Enabling multidex on a libgdx android application and having more than one dex file generated causes android projects to crash on startup, unable to construct androidinput.

#### Reproduction steps/code

- Go over the 65k limit on an android application using libgdx.

- Enable multidex in the android modules build.gradle and add the correct android support as a dependency.

- Sync gradle then run.

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
```java
03-20 14:53:47.574  23116-23116/net.dhale.shapeescape.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.dhale.shapeescape.android/net.dhale.shapeescape.android.AndroidLauncher}: java.lang.RuntimeException: Couldn't construct AndroidInput, this should never happen
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.access$700(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Couldn't construct AndroidInput, this should never happen
            at com.badlogic.gdx.backends.android.AndroidInputFactory.newAndroidInput(AndroidInputFactory.java:45)
            at com.badlogic.gdx.backends.android.AndroidApplication.init(AndroidApplication.java:135)
            at com.badlogic.gdx.backends.android.AndroidApplication.initialize(AndroidApplication.java:99)
            at net.dhale.shapeescape.android.AndroidLauncher.onCreate(AndroidLauncher.java:47)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.access$700(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.badlogic.gdx.backends.android.AndroidInputFactory.newAndroidInput(AndroidInputFactory.java:42)
            at com.badlogic.gdx.backends.android.AndroidApplication.init(AndroidApplication.java:135)
            at com.badlogic.gdx.backends.android.AndroidApplication.initialize(AndroidApplication.java:99)
            at net.dhale.shapeescape.android.AndroidLauncher.onCreate(AndroidLauncher.java:47)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.access$700(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NoClassDefFoundError: com.badlogic.gdx.backends.android.AndroidInput$1
            at com.badlogic.gdx.backends.android.AndroidInput.<init>(AndroidInput.java:86)
            at com.badlogic.gdx.backends.android.AndroidInputThreePlus.<init>(AndroidInputThreePlus.java:35)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at com.badlogic.gdx.backends.android.AndroidInputFactory.newAndroidInput(AndroidInputFactory.java:42)
            at com.badlogic.gdx.backends.android.AndroidApplication.init(AndroidApplication.java:135)
            at com.badlogic.gdx.backends.android.AndroidApplication.initialize(AndroidApplication.java:99)
            at net.dhale.shapeescape.android.AndroidLauncher.onCreate(AndroidLauncher.java:47)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.access$700(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
This looks like a problem with proguard more than anything.  I cant replicate it using your steps, please provide an example setup and code that can reproduce your problem.

**Comment by MobiDevelop** [comment]
Most likely, multidex is not putting this class (com.badlogic.gdx.backends.android.AndroidInputThreePlus) into the main dex file because it is only referenced by name via reflection.

**Comment by DanHale123** [comment]
> Most likely, multidex is not putting this class (com.badlogic.gdx.backends.android.AndroidInputThreePlus) into the main dex file because it is only referenced by name via reflection.

So how exactly is that fixed, I've never looked into the workings of how it sorts dex files out when multidex is used?

> This looks like a problem with proguard more than anything. I cant replicate it using your steps, please provide an example setup and code that can reproduce your problem.

Proguard isn't active I believe so it couldn't be this.

**Comment by yncki** [comment]
I ran into the same problem some time ago, take a look at --main-dex-list parameter to specify a text file with classes which should be placed in main dex , 

more info : 
http://frogermcs.github.io/MultiDex-solution-for-64k-limit-in-Dalvik/
http://blog.osom.info/2014/10/multi-dex-to-rescue-from-infamous-65536.html

**Comment by DanHale123** [comment]
The above links solved the issue, specifically the second one. Using main dex list I added the missing class into the main dex. A wiki article on multidexing and this solution would be cool for others who have this problem, as it's fairly obscure. The problem lies in the fact that some classes (in this case just one) were not put in the main dex file.

**Comment by Tom-Ski** [comment]
The wiki is publicly editable, feel free to contribute an article on it.
