### ISSUE TITLE
crash in onConfigurationChanged.

### ISSUE THREAD

**Issue by rami-diwip** [libgdx/libgdx#3965]
#### Issue details
_Hello, I have the following crash in onConfigurationChanged.
i't seems that input is null_
```java		
@Override
public void onConfigurationChanged (Configuration config) {
    super.onConfigurationChanged(config);
	boolean keyboardAvailable = false;
	if (config.hardKeyboardHidden == Configuration.HARDKEYBOARDHIDDEN_NO) keyboardAvailable = true;
	input.keyboardAvailable = keyboardAvailable;
}
```
#### Reproduction steps/code
_I don't  have a reproduction to this crash. I collect the data from "Crashlytics"_

#### Version of LibGDX and/or relevant dependencies
_libgdx 1.5.3_

#### Stacktrace
```java
 Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'boolean com.badlogic.gdx.backends.android.AndroidInput.keyboardAvailable' on a null object reference
       at com.badlogic.gdx.backends.android.AndroidApplication.onConfigurationChanged(AndroidApplication.java:407)
       at com.diwip.vslots.GameSlots.onConfigurationChanged(GameAcitivy.java:665)
       at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4330)
       at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4407)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5595)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

#### Please select the affected platforms
- [ ] Android

**Comment by MobiDevelop** [comment]
According to the stack trace, it isn't the `newConfig` which is null... rather, the `input` is null. Not sure how that would happen.

**Comment by Darkyenus** [comment]
Seems like it was invoked before the app was created or after it was disposed (IIRC android backend sets Gdx statics to null, by a recent change, but that was probably after 1.5.3 so it does not apply here).

**Comment by MobiDevelop** [comment]
Indeed... on that note, we might want to check whether isChangingConfigurations() before unsetting everything. I agree though that this is unlikely to be related to that change.

**Comment by rami-diwip** [comment]
thank you all for the help.
it is probably because i'm not initializing gdx in case that the device not supports GL2

```
if (isDeviceSupportGL2(this)) {
            glView = initializeForView(gdxGame, cfg);
            if (glView instanceof SurfaceView) {
                SurfaceView glView = (SurfaceView) this.glView;
                glView.getHolder().setFormat(PixelFormat.TRANSPARENT);
                glView.setZOrderOnTop(true);
            }
            mainLayout.addView(glView);
        }
```

Neither way i think that onConfigurationChanged  should handle this scenario. it won't be wise not to call onConfigurationChanged super because of this.

**Comment by Tom-Ski** [comment]
Yes, that would be it.  You shouldn't be trying to invoke or use anything that is not initialized in any method.  This is not a LibGDX issue imo, as you are purposefully not initializing, you should have logic to cope with that correctly.
