### ISSUE TITLE
Clipboard on Android get Exception.

### ISSUE THREAD

**Issue by xirtam-ch** [libgdx/libgdx#3974]
#### Issue details
My code: `Gdx.app.getClipboard().getContents();`
Run in libgdx main Thread,My device is Nexus 5 with android 6.0.

#### Reproduction steps/code
Gdx.app.getClipboard().getContents(); 
On android .

#### Version of LibGDX and/or relevant dependencies
1.9.2

#### Stacktrace
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.os.Handler.<init>(Handler.java:200)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.os.Handler.<init>(Handler.java:114)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:213)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:212)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:768)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:721)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.ContextImpl.getSystemService(ContextImpl.java:1365)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:123)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.Activity.getSystemService(Activity.java:5276)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidClipboard.getContents(AndroidClipboard.java:42)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.xirtam.kk.screens.GameScreen$20.run(GameScreen.java:560)
03-29 17:59:43.012    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:467)
03-29 17:59:43.013    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
03-29 17:59:43.013    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.os.Handler.<init>(Handler.java:200)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.os.Handler.<init>(Handler.java:114)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:213)
03-29 17:59:48.173    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:212)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:768)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:721)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.ContextImpl.getSystemService(ContextImpl.java:1365)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:123)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.app.Activity.getSystemService(Activity.java:5276)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidClipboard.getContents(AndroidClipboard.java:42)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.xirtam.kk.screens.GameScreen$20.run(GameScreen.java:560)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:467)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
03-29 17:59:48.174    5383-5414/com.xirtam.dcar.android W/System.err﹕ at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xirtam-ch** [comment]
I tried `Gdx.app.postRunnable(new Runnable() {
            @Override
            public void run() {
                String contents = Gdx.app.getClipboard().getContents();
            }
        });`

But got nothing help.

**Comment by xirtam-ch** [comment]
@Tom-Ski Thx,I am very like Libgdx.
