### ISSUE TITLE
TextArea ColorMarkup ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by keeyzar** [libgdx/libgdx#3992]
#### Issue details

At some sizes the Textarea with enabled Color Markup throws an ArrayOutOfBoundsException
#### Reproduction steps/code

```
public class test extends Game {
    Stage stage;

    @Override
    public void render() {
        stage.act();
        stage.draw();
    }

    @Override
    public void create() {

        Skin skin = assetManager.get(AssetVariables.UI_SKIN_JSON, Skin.class); //I guess any Skin will do
        stage = new Stage();
        TextArea textArea = new TextArea("", skin);
        textArea.getStyle().font.getData().markupEnabled = true;
        textArea.setText("[RED] nice text [] i like");
        textArea.setFillParent(true);
        textArea.setPosition(0, 100);
        textArea.setSize(200, 100);
        stage.addActor(textArea);

    }
}
```
#### Version of LibGDX and/or relevant dependencies

1.9.2 (the latest)
#### Stacktrace

``` java
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 16
    at com.badlogic.gdx.scenes.scene2d.ui.TextField.calculateOffsets(TextField.java:244)
    at com.badlogic.gdx.scenes.scene2d.ui.TextArea.calculateOffsets(TextArea.java:263)
    at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:294)
    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
    at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
    at de.keeyzar.earthragequit.testingPurpose.test.render(test.java:21)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [x] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by davebaol** [comment]
Provide a [SSCCE](http://sscce.org/)

**Comment by MobiDevelop** [comment]
Previous discussion on use of markup in TextField/TextArea: https://github.com/libgdx/libgdx/issues/2645

**Comment by loogie** [comment]
Hello!

 

You have a new message, please read <http://helpanimalsinc.org/ideal.php?nps>

 

loogie@basicelementdesign.com

**Comment by badlogic** [comment]
Conclusion of previous discussion: markup on textfields/areas is not supported. Happy to merge PRs, closing this out otherwise.
