### ISSUE TITLE
java.lang.NullPointerException in com.badlogic.gdx.backends.android.AndroidMouseHandler.onGenericMotion

### ISSUE THREAD

**Issue by ldthai** [libgdx/libgdx#4012]
I got crash on Lenovo(A880), android 4.2

#### Issue details
`java.lang.NullPointerException
	at com.badlogic.gdx.backends.android.AndroidMouseHandler.onGenericMotion(AndroidMouseHandler.java:62)
	at com.badlogic.gdx.backends.android.AndroidInputThreePlus.onGenericMotion(AndroidInputThreePlus.java:47)
	at android.view.View.dispatchGenericMotionEventInternal(View.java:7415)
	at android.view.View.dispatchGenericMotionEvent(View.java:7402)
	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1799)
	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1533)
	at android.view.View.dispatchGenericMotionEvent(View.java:7392)
	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1799)
	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1533)
	at android.view.View.dispatchGenericMotionEvent(View.java:7392)
	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1799)
	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1533)
	at android.view.View.dispatchGenericMotionEvent(View.java:7392)
	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1799)
	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1533)
	at android.view.ViewGroup.exitHoverTargets(ViewGroup.java:1615)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2613)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2997)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:4598)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:4578)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:338)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:288)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.access$1200(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1426)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5476)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)`
#### Version of LibGDX and/or relevant dependencies
1.9.3-SNAPSHOT

#### Please select the affected platforms
- [x] Android

**Comment by Tom-Ski** [comment]
Closed #4013 as it is a duplicate issue.  Seems like handleDestroyActivity is called after destroy is called, so the change https://github.com/libgdx/libgdx/commit/5498c2f32a1f45c9b1e4303be5a70da0dc7dba95 causes these NPEs.

**Comment by ldthai** [comment]
thank you!

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info

**Comment by noblemaster** [comment]
I am seeing those crashes too. As Tom-Ski said, it happens when the application is closed but events are still delivered (ditto #4013):

    at com.badlogic.gdx.backends.android.AndroidInput.lookUpPointerIndex(Unknown Source)
	at com.badlogic.gdx.backends.android.AndroidMultiTouchHandler.onTouch(Unknown Source)
	at com.badlogic.gdx.backends.android.AndroidInput.onTouch(Unknown Source)
	at android.view.View.dispatchTouchEvent(View.java:8541)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2376)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2376)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2376)
	at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2226)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2817)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2988)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5512)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:5489)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:369)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:324)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3848)
	at android.app.ActivityThread.access$1400(ActivityThread.java:156)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by little-dgek** [comment]
Hi. On LibGDX 1.9.3 NPE was returned.
java.lang.NullPointerException
com.badlogic.gdx.backends.android.AndroidMouseHandler.onGenericMotion(Unknown Source)
                                                      postTouchEvent
com.badlogic.gdx.backends.android.AndroidInputThreePlus.onGenericMotion(Unknown Source)
android.view.View.dispatchGenericMotionEventInternal(View.java:7481)
android.view.View.dispatchGenericMotionEvent(View.java:7468)
android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1822)
android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1556)
android.view.View.dispatchGenericMotionEvent(View.java:7458)
android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1822)
android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1556)
android.view.View.dispatchGenericMotionEvent(View.java:7458)
android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1822)
android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1556)
android.view.View.dispatchGenericMotionEvent(View.java:7458)
android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1822)
android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1556)
android.view.ViewGroup.exitHoverTargets(ViewGroup.java:1638)
android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2558)
android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2844)
android.view.ViewRootImpl.doDie(ViewRootImpl.java:5188)
android.view.ViewRootImpl.die(ViewRootImpl.java:5171)
android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:359)
android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:309)
android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3782)
android.app.ActivityThread.access$1500(ActivityThread.java:148)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1372)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:137)
android.app.ActivityThread.main(ActivityThread.java:5473)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:854)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
dalvik.system.NativeStart.main(Native Method)
