### ISSUE TITLE
Unable to copy internal directory from desktop jar

### ISSUE THREAD

**Issue by SonarBeserk** [libgdx/libgdx#4074]
Please ensure you have given all the following requested information in your report.

#### Issue details
I am working on the desktop version and attempting to copy an internal directory named default to be a local directory named "addons/default". However it fails to copy and throws an exception. This code is being run with the dist jar for desktop.

#### Reproduction steps/code
1. Create directory in assets named default, add some sub dirs
2. Add following code
``` java
        FileHandle addonsLocalDir = Gdx.files.local("addons");
        if(!addonsLocalDir.exists()) {
            addonsLocalDir.mkdirs();
            FileHandle addons = Gdx.files.internal("default");
            System.out.println("exists: " + addons.exists());
            System.out.println("name:  " + addons.name());
            System.out.println("isDir: " + addons.isDirectory());
            addons.copyTo(addonsLocalDir);
        }
```
3. Package code using desktop dist
4. Run Game

#### Version of LibGDX and/or relevant dependencies
libgdx: 1.9.2
Version: Desktop

#### Stacktrace
```java
exists: true
name:  default
isDir: false
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error copying source file: default (Internal)
To destination: addons\default (Local)
        at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:684)
        at com.badlogic.gdx.files.FileHandle.copyTo(FileHandle.java:574)
        at net.mountainblade.hexcard.Addon.reloadAll(Addon.java:53)
        at net.mountainblade.hexcard.HexCardGame.create(HexCardGame.java:36)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error stream writing to file: addons\default (Local)
        at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:296)
        at com.badlogic.gdx.files.FileHandle.copyFile(FileHandle.java:682)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.io.FilterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:49)
        at com.badlogic.gdx.utils.StreamUtils.copyStream(StreamUtils.java:36)
        at com.badlogic.gdx.files.FileHandle.write(FileHandle.java:294)
        ... 6 more

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by laubed** [comment]
This issue is probably related to the fact that classpath filetypes are always interpreted as files (isDirectory() always returning false). Therefore the copy method failes because it can't distinguish between files and folders.
When distributing on desktop via jar every content in the asset folder is now on the classpath instead.

**Comment by SonarBeserk** [comment]
well is there any way to work around this? A unsupported exception seems reasonable if it isnt.

**Comment by laubed** [comment]
You could use a zipfile in the assets folder instead. Files can be copied
as usual.
Because we can't distinguish between files and folders on classpath we
can't throw an unsupported exception.
At least I think thats the reason why its not implemented.

2016-05-09 20:32 GMT+02:00 SonarBeserk <notifications@github.com>:

**Comment by SonarBeserk** [comment]
Do you have an example of using the zip file? Ive only seen some hacky solutions.

**Comment by laubed** [comment]
The accepted answer should be the way to go:
http://stackoverflow.com/questions/1386809/copy-directory-from-a-jar-file
I just tested the behaviour of Javas File Object. It's really the case that
we cant distinguish between Files and Directories even if using native Java
API

2016-05-09 20:35 GMT+02:00 SonarBeserk <notifications@github.com>:

**Comment by SonarBeserk** [comment]
I ended up just settling for manually choosing the files to load. Adding a zip wasn't very feasible for me.
