### ISSUE TITLE
Vertical Group crashes randomly when actors are added and removed

### ISSUE THREAD

**Issue by larsmathuseck** [libgdx/libgdx#4096]
#### Issue details
Hey, im trying to implement a list that is refreshed once the datamodell changes.
Im useing a Vertical Group for this, cause i need to add and remove items.
indexOutOfBoundsException happens randomly, im not sure why.

#### Reproduction steps/code

The propertyChange method is called each time something on the datamodel changes.
The crash happens like randomly, sometimes it works and suddenly it crashes.

```java
public void propertyChange(PropertyChangeEvent evt) {

		offerGroup.clear();
		for (Order o : orders) {
			if (o.getObjectId() != null && o.getObjectId() != "" && o.getPlayer() == null) {
				HorizontalGroup container = new HorizontalGroup();
				String ordername = o.getObjectId();
				Label offerLabel = new Label(ordername, uiSkin);
				container.addActor(offerLabel);
				TextField txtBid = new TextField("", uiSkin);
				container.addActor(txtBid);
				TextButton btn = new TextButton("Bid", uiSkin);
				container.addActor(btn);
				offerGroup.addActor(container);
				btn.addListener(new ClickListener() {
					@Override
					public void clicked(InputEvent event, float x, float y) {
						onClickBid(o, txtBid, container);
					}
				});

			}
		}
	}```

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.2'

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 4 >= 3
	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.badlogic.gdx.scenes.scene2d.ui.VerticalGroup.layout(VerticalGroup.java:82)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:115)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.layout(ScrollPane.java:525)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:115)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:758)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:115)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:101)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at de.uks.tps.screens.MainScreen.render(MainScreen.java:118)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at de.uks.tps.MyGdxGame.render(MyGdxGame.java:28)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x ] Windows
- [ ] Linux
- [ ] MacOS

not sure about the other platforms

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
