### ISSUE TITLE
OpenGL 2.0 or higher with the FBO extension is required

### ISSUE THREAD

**Issue by raderio** [libgdx/libgdx#4099]
Windows 10(64-bit)

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
Type: OpenGL
Version: 1:1:0
Vendor: Microsoft Corporation
Renderer: GDI Generic
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:346)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGL(LwjglGraphics.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:142)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

OpenGL version 4.0

**Comment by Tom-Ski** [comment]
Your OpenGL instance isn't 4.0, as the log shows it is 1.1.0, which is unsupported by LibGDX.  Make sure you have up to date drivers for your video card.

**Comment by raderio** [comment]
OpenGL Viewer shows that it is 4.0

**Comment by intrigus** [comment]
@raderio Do you have an Intel graphics card?
If so, you are probably affected by https://github.com/LWJGL/lwjgl/issues/119 , which can unfortunately not be solved by libgdx.

**Comment by raderio** [comment]
yeap, I have Intel graphics card
Thanks

**Comment by intrigus** [comment]
You can patch your java version. So you can at least develop on your. Instructions on how to patch it, can be found in the other issue.

**Comment by ahuynh359** [comment]
Have you fixed this issue? I've got stuck for 1 week but can't figure out how to solve these stuff
