### ISSUE TITLE
Error making a socket connection when I try with ipv6.

### ISSUE THREAD

**Issue by truonguit2010** [libgdx/libgdx#4136]
Is Libgdx support IPV6 when making a socket connection? I got an error when i do. Please give me a hand.

```
com.badlogic.gdx.utils.GdxRuntimeException: Error making a socket connection to my_version_6_ip:my_port
	at com.badlogic.gdx.net.NetJavaSocketImpl.<init>(NetJavaSocketImpl.java:51)
	at com.badlogic.gdx.backends.iosrobovm.IOSNet.newClientSocket(IOSNet.java:63)
	at vn.me.engine.network.MobileClient.doConnect(MobileClient.java:155)
	at vn.me.engine.network.MobileClient.access$3(MobileClient.java:153)
	at vn.me.engine.network.MobileClient$1.run(MobileClient.java:122)
	at java.lang.Thread.run(Thread.java:837)
Caused by: java.net.UnknownHostException: Host is unresolved: my_version_6_ip
	at java.net.Socket.connect(Socket.java:826)
	at java.net.Socket.connect(Socket.java:786)
	at com.badlogic.gdx.net.NetJavaSocketImpl.<init>(NetJavaSocketImpl.java:48)
```

I got this on:
- [x] iOS (robovm)
- [x] Windows
- [x] MacOS

**Comment by RaimundWege** [comment]
It seems you don't provide a correct IPv6 Address and the port should be an int, too.

**Comment by Tom-Ski** [comment]
Please use the issue template. Feel free to reopen when you have submitted a code example that reproduces your issue.
