### ISSUE TITLE
Crashes on startup in fullscreen on certain devices: Cursor objects could not be created 

### ISSUE THREAD

**Issue by flor-ian** [libgdx/libgdx#4171]
#### Issue details
This does not affect any of the computers I tested it on but I have received multiple error reports from users unable to launch my project on their computer in fullscreen. Looking up the error gives me decade old forum posts that don't really help, one of which suggested disabling fullscreen for the error to disappear and that does indeed make it work. But that's more like an ugly patch workaround, not really a fix.

#### Reproduction steps/code
Unfortunately I have no idea how to reproduce this as it doesn't affect any computer I tested it on but I have received reports from users running on various versions of Windows (XP, 7, 10). Basically I'm just launching the project in fullscreen and it's 

#### Version of LibGDX and/or relevant dependencies
Java: 1.8.0_91
OpenGL: 4.5
LibGDX: 1.9.3

#### Stacktrace
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeExcepti
on: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:130)
Caused by: java.lang.ExceptionInInitializerError
        at com.unlogical.colored.GameLauncher.create(GameLauncher.java:193)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplic
ation.java:146)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplicati
on.java:123)
Caused by: java.lang.RuntimeException: Failed to load cursor (res/gui/cursor/def
ault.png)
        at com.unlogical.colored.util.CursorType.<init>(CursorType.java:36)
        at com.unlogical.colored.util.CursorType.<clinit>(CursorType.java:15)
        ... 3 more
Caused by: java.lang.IllegalStateException: Mouse must be created before creatin
g cursor objects
        at org.lwjgl.input.Cursor.<init>(Cursor.java:93)
        at com.badlogic.gdx.backends.lwjgl.LwjglCursor.<init>(LwjglCursor.java:7
3)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.newCursor(LwjglGraphics
.java:618)
        at com.unlogical.colored.util.CursorType.<init>(CursorType.java:32)
        ... 4 more
```

#### Affected platforms
- [X] Windows
- [?] Linux
- [?] MacOS

? = maybe, but haven't received a report yet

**Comment by intrigus** [comment]
That's not the full stack trace, is it?

**Comment by flor-ian** [comment]
Oh, yeah, I assumed only that part would be relevant. I changed it to include the full stack trace. Thanks.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/More-Info
Please include the required information, like which backend, the launcher and other relevant code, etc.

**Comment by intrigus** [comment]
Without seeing your code, I'd assume that `com.unlogical.colored.util.CursorType` is initialized before libgdx/lwjgl is fully initialized.
