### ISSUE TITLE
Maximum Number of Vertices Used

### ISSUE THREAD

**Issue by Lolums** [libgdx/libgdx#4176]
Please ensure you have given all the following requested information in your report.

#### Issue details
I believe that only 32k vertices can be used? That's a really tiny amount though. Is there a way to increase that?

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
Latest.

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Too many vertices used
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.vertex(MeshBuilder.java:539)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.vertex(MeshBuilder.java:582)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.rect(MeshBuilder.java:708)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.rect(MeshBuilder.java:713)
	at com.badlogic.gdx.graphics.g3d.utils.shapebuilders.BoxShapeBuilder.build(BoxShapeBuilder.java:86)
	at com.badlogic.gdx.graphics.g3d.utils.shapebuilders.BoxShapeBuilder.build(BoxShapeBuilder.java:116)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.box(MeshBuilder.java:848)
etc```

#### Please select the affected platforms (Others not tested)
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by Darkyenus** [comment]
The limit is because of indices, which use `short` for their indexing. This won't be *fixed* and has already been discussed. You should probably break up your mesh into smaller parts though.

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
