### ISSUE TITLE
BitmapFont can't load files with spaces in the name

### ISSUE THREAD

**Issue by CreamyCookie** [libgdx/libgdx#4201]
#### Issue details

Using BitmapFont with spaces in the path raises an exception.
#### Reproduction steps/code

Download [font.zip](https://github.com/libgdx/libgdx/files/378695/font.zip)

``` java
import com.badlogic.gdx.*;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.graphics.GL20;

public class Barebones extends ApplicationAdapter {
    public void create () {
        FileHandle path = files.internal("font/DejaVu Sans (test).fnt");
        System.out.println(path.exists());
        BitmapFont font = BitmapFont(path);
    }

    public void render () {
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    }

    public static void main (String[] args) throws Exception {
        new LwjglApplication(new Barebones());
    }
}
```
#### Version of LibGDX and/or relevant dependencies

1.9.4-SNAPSHOT

Java: 8 (64bit)
#### Stacktrace

``` java
true
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: font/"DejaVu
    at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
    at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
    at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
    at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:96)
    at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:164)
    at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:142)
    at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:114)
    at com.badlogic.gdx.graphics.g2d.BitmapFont.<init>(BitmapFont.java:107)
    at com.something.game.Barebones.create(Barebones.java:32)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: font/"GNU (Internal)
    at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
    at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
    at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
    ... 10 more
```
#### Please select the affected platforms

Ubuntu 16.04 / 64bit, but likely all platforms when `BitmapFont` is used.

**Comment by Darkyenus** [comment]
`BitmapFontData` attempts to handle this problem, by [limiting the amount of line splits](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g2d/BitmapFont.java#L523), but limit `4` is too much - changing it to `3` will fix it.

It is still a hack, but the file format seems stable so it should work. (And the rest of `fnt` loading is similarly hackish anyway.)
