### ISSUE TITLE
LwjglCanvas#stop() releases OpenGL context before ApplicationListener#dispose() called

### ISSUE THREAD

**Issue by metaphore** [libgdx/libgdx#4203]
#### Issue details
I use `LwjglCanvas` in conjunction with `JFrame`. Problem comes when application closes. In `LwjglCanvas#dispose()` of my class I'm trying to release some OpenGL related resources (like `Textures` inside `AssetManager`) and get this pretty self explained exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:198)
	at com.badlogic.gdx.assets.AssetManager.unload(AssetManager.java:211)
	at com.badlogic.gdx.assets.AssetManager.clear(AssetManager.java:653)
	at com.badlogic.gdx.assets.AssetManager.dispose(AssetManager.java:621)
    ...
```

My investigation brought me to `LwjglCanvas#stop()` method. Look at the lines order:
```
	public void stop () {
		EventQueue.invokeLater(new Runnable() {
			public void run () {
				if (!running) return;
				running = false;
				try {
					Display.destroy();
					if (audio != null) audio.dispose();
				} catch (Throwable ignored) {
				}
				Array<LifecycleListener> listeners = lifecycleListeners;
				synchronized (listeners) {
					for (LifecycleListener listener : listeners) {
						listener.pause();
						listener.dispose();
					}
				}
				listener.pause();
				listener.dispose();
			}
		});
	}
```

As you can see `Display.destroy()` called before `listener.pause()` and `listener.dispose()` methods, and that causes the issue. This line order looks strange even because kinda similar class `LwjglApplication#stop()` calls `Display.destroy()` after listener's methods and everything fine back there. So I consider this is just an old problem that requires simple lines swap. If I'm wrong and here is a reason behind that specific order, it would be good to know and discuss solution.

#### Reproduction steps/code
Please check out this commit AurelienRibon/libgdx-texturepacker-gui@b0d2d0d393b888ca7a3f9ce19e41354c75972338. Simply run the application using Gradle `./gradlew app:run` and terminate it by clicking X button of the window. See the log output. Exception will be thrown by `aurelienribon.texturepackergui.canvas.Canvas#dispose()` method.

*UPD: just use code in my comment below*

#### Version of LibGDX and/or relevant dependencies
1.9.3

#### Please select the affected platforms
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
Please supply a self contained executable example that reproduces this issue itself. see https://github.com/libgdx/libgdx/wiki/Getting-help#executable-example-code

**Comment by Metaphore** [comment]
Here it is:
```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglCanvas;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Main {
	public static void main (String[] arg) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				ApplicationListener applicationListener = new MyApplicationListener();
				LwjglCanvas glCanvas = new LwjglCanvas(applicationListener);
				new MainWindow(glCanvas);
			}
		});
	}

	private static class MainWindow extends JFrame {
		public MainWindow(LwjglCanvas glCanvas) throws HeadlessException {
			Canvas canvas = glCanvas.getCanvas();
			add(canvas);
			canvas.setSize(640, 480);
			setSize(640, 480);
			setVisible(true);

			// Will finish up application properly on close
			addWindowListener(new WindowAdapter() {
				@Override
				public void windowClosed(WindowEvent e) {
					System.exit(0);
				}
			});
			setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		}
	}

	private static class MyApplicationListener extends ApplicationAdapter {
		private BitmapFont font;
		private SpriteBatch batch;

		@Override
		public void create() {
			font = new BitmapFont();
			batch = new SpriteBatch();
		}

		@Override
		public void render() {
			Gdx.gl.glClearColor(0f, 0f, 0f, 1f);
			Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

			batch.begin();
			batch.setColor(Color.WHITE);
			font.setColor(Color.WHITE);
			font.draw(batch, "TEST TEST TEST", 100, 100);
			batch.end();
		}

		@Override
		public void dispose() {
			font.dispose();
			batch.dispose();
		}
	}
}
```
