### ISSUE TITLE
Getting started with Scala / libgdx fails horriby at : org.roboscala#sbt-robovm;

### ISSUE THREAD

**Issue by michahell** [libgdx/libgdx#4239]
Please ensure you have given all the following requested information in your report.

#### Issue details
running ```sbt``` inside the directory created by the ```g8``` scaffolded project given here:
https://github.com/libgdx/libgdx/wiki/Using-libgdx-with-Scala
fails.

#### Reproduction steps/code
Since this seems to be about project tooling, I don't have an SSCCE :/

#### Version of LibGDX and/or relevant dependencies
- OSX El Capitan 10.11.6 (15G31)
- 2,2 GHz Intel Core i7
- 16 GB 1600 MHz DDR3
- bash 4
- java: java version "1.8.0_77"
- sbt: Getting org.scala-sbt sbt 0.13.12 ?
- g8: 0.6.8
- scala: Welcome to Scala 2.11.8
- libgdx: ?

#### Stacktrace
```java
[info] Loading project definition from /Users/michahell/Projects/games/SCB/scb/project
[info] Updating {file:/Users/michahell/Projects/games/SCB/scb/project/}scb-build...
[info] Resolving org.roboscala#sbt-robovm;1.0.0-alpha-04-SNAPSHOT ...
[warn] 	module not found: org.roboscala#sbt-robovm;1.0.0-alpha-04-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.roboscala/sbt-robovm/scala_2.10/sbt_0.13/1.0.0-alpha-04-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.roboscala/sbt-robovm/scala_2.10/sbt_0.13/1.0.0-alpha-04-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/michahell/.ivy2/local/org.roboscala/sbt-robovm/scala_2.10/sbt_0.13/1.0.0-alpha-04-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/roboscala/sbt-robovm_2.10_0.13/1.0.0-alpha-04-SNAPSHOT/sbt-robovm-1.0.0-alpha-04-SNAPSHOT.pom
[warn] ==== scalasbt snapshots: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/org.roboscala/sbt-robovm/scala_2.10/sbt_0.13/1.0.0-alpha-04-SNAPSHOT/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.roboscala#sbt-robovm;1.0.0-alpha-04-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.roboscala:sbt-robovm:1.0.0-alpha-04-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn]
sbt.ResolveException: unresolved dependency: org.roboscala#sbt-robovm;1.0.0-alpha-04-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
	at sbt.IvySbt.withIvy(Ivy.scala:98)
	at sbt.IvySbt.withIvy(Ivy.scala:94)
	at sbt.IvySbt$Module.withModule(Ivy.scala:115)
	at sbt.IvyActions$.update(IvyActions.scala:125)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.roboscala#sbt-robovm;1.0.0-alpha-04-SNAPSHOT: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by MobiDevelop** [comment]
That scaffolding project was not created or maintained by the libgdx team. Unfortunately, I don't think any of the libgdx team uses Scala so it is probably going to be up to those who do to update the wiki if it needs to be updated.

**Comment by michahell** [comment]
Aha, I see. Let's see what's happening in Clojure land shall we? Onto the next JVM Kingdom! Bye bye evil King Scala !
