### ISSUE TITLE
Errors while using remove() on utility collections' Iterator

### ISSUE THREAD

**Issue by Xemiru** [libgdx/libgdx#4264]
#### Issue details

The issue addressed by ff6f7ca68a92c286ba22fdcb6f0fe444aff91f66 still occurs with other iterators. This has been tested only with the `OrderedMap$Value` iterator, though it is likely that it occurs with other iterators. It seems to occur due to `remove()` not updating the `hasNext` flag.
#### Reproduction steps/code

Simply iterating over values and attempting to remove them can cause this issue. Note, that it seems to be inconsistent, and may take a few runs in order to produce an error.

``` java
import com.badlogic.gdx.utils.OrderedMap;

import java.util.Iterator;

public class Program {

    public static void main(String[] args) {
        OrderedMap<Integer, Object> map = new OrderedMap<>();
        for (int i = 0; i < 16; i++) {
            map.put(i, new Object());
        }

        Iterator<Object> iter = map.values();
        while (iter.hasNext()) {
            iter.next();
            System.out.println("removed");
            iter.remove();
        }
    }
}
```

The above code sometimes resolves to something like this output.

```
removed
removed
removed
removed
removed
removed
removed
removed
Exception in thread "main" java.lang.IndexOutOfBoundsException: index can't be >= size: 8 >= 8
    at com.badlogic.gdx.utils.Array.get(Array.java:127)
    at com.badlogic.gdx.utils.OrderedMap$OrderedMapValues.next(OrderedMap.java:228)
    at Program.main(Program.java:19)
```
#### Version of LibGDX and/or relevant dependencies

Supposedly on v1.9.3. The relevant class had not been updated until 15 days ago, so this might not even matter.
#### Stacktrace

```
[14:51:49,569] ERROR LWJGL Application    Undertailor: Uncaught exception. Program will close.
java.lang.IndexOutOfBoundsException: index can't be >= size: 5 >= 5
    at com.badlogic.gdx.utils.Array.get(Array.java:127)
    at com.badlogic.gdx.utils.OrderedMap$OrderedMapValues.next(OrderedMap.java:228)
    at me.scarlet.undertailor.engine.ui.UIController.process(UIController.java:129)
    at me.scarlet.undertailor.engine.Environment.process(Environment.java:104)
    at me.scarlet.undertailor.engine.EnvironmentManager.process(EnvironmentManager.java:111)
    at me.scarlet.undertailor.Undertailor.render(Undertailor.java:220)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
#### Please select the affected platforms

Any platform where classes from the `com.badlogic.gdx.utils` package can be accessed and used, presumably all platforms.

**Comment by Xemiru** [comment]
Code relevant to the second stacktrace here.

https://github.com/Xemiru/Undertailor/commit/8c2233cfa95b1ad70688dac411e95b36c4015e96
