### ISSUE TITLE
Race condition on AndroidGraphicsLiveWallpaper

### ISSUE THREAD

**Issue by lucasdupin** [libgdx/libgdx#4267]
Hey all,
We found a deadlock that happens on Android live wallpapers.
#### Issue details

There was a race condition between the GL thread and the main thread, when resuming wallpapers. It happens in [here](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java#L138)

If GL thread is much quicker because of scheduling delays, it might end up drawing its frame before the main thread reaches `resume()`.

This is a problem when you are not drawing on continuous mode, which most people probably do to save some battery.

In that case, `synch.wait()` will just hang because nobody else requested a frame since rendering was set to _on-demand_.
#### Reproduction steps/code

It's kind of tricky to reproduce, since it's a concurrency problem, but can add:

``` java
Thread.sleep(3000);
```

[Before the `synch.wait()` call](https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java#L138)
#### Version of LibGDX and/or relevant dependencies

Latest on `master`.
#### Stacktrace

``` java
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x74b2ff58 self=0x7ee2c95a00
  | sysTid=29955 nice=0 cgrp=default sched=0/0 handle=0x7ee6c21a98
  | state=S schedstat=( 146166665 78867030 518 ) utm=9 stm=4 core=1 HZ=100
  | stack=0x7fcc076000-0x7fcc078000 stackSize=8MB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x07dbeb25> (a java.lang.Object)
  at com.badlogic.gdx.backends.android.AndroidGraphicsLiveWallpaper.resume(AndroidGraphicsLiveWallpaper.java:139)
  - locked <0x07dbeb25> (a java.lang.Object)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaper.onResume(AndroidLiveWallpaper.java:156)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.onResume(AndroidLiveWallpaperService.java:402)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.notifyVisibilityChanged(AndroidLiveWallpaperService.java:369)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.onVisibilityChanged(AndroidLiveWallpaperService.java:361)
  at android.service.wallpaper.WallpaperService$Engine.reportVisibility(WallpaperService.java:925)
  at android.service.wallpaper.WallpaperService$Engine.doVisibilityChanged(WallpaperService.java:906)
  at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1187)
  at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6088)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS
### Proposed fix

``` diff
diff --git a/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java b/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java
index 5fcd0e4..0cb0368 100644
--- a/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java
+++ b/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidGraphicsLiveWallpaper.java
@@ -136,6 +136,7 @@
            // by jw: added synchronization, there was nothing before
            while (resume) {
                try {
+                   requestRendering();
                    synch.wait();
                } catch (InterruptedException ignored) {
                    Gdx.app.log("AndroidGraphics", "waiting for resume synchronization failed!");
```

**Comment by snowzoor** [comment]
I am still getting this error.

**Stacktrace**

Type
"main" prio=5 tid=1 Waiting

  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:442)
  at java.lang.Object.wait (Object.java:568)
  at com.badlogic.gdx.backends.android.AndroidGraphicsLiveWallpaper.resume (AndroidGraphicsLiveWallpaper.java:139)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaper.onResume (AndroidLiveWallpaper.java:159)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.onResume (AndroidLiveWallpaperService.java:402)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.notifyVisibilityChanged (AndroidLiveWallpaperService.java:369)
  at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.onVisibilityChanged (AndroidLiveWallpaperService.java:361)
  at android.service.wallpaper.WallpaperService$Engine.reportVisibility (WallpaperService.java:1514)
  at android.service.wallpaper.WallpaperService$Engine.doVisibilityChanged (WallpaperService.java:1489)
  at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1870)
  at com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:44)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8506)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
