### ISSUE TITLE
Build iOS failed

### ISSUE THREAD

**Issue by dungnart** [libgdx/libgdx#4277]
Please ensure you have given all the following requested information in your report.

#### Issue details
I can not build ios.

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.2
Robovm 1.14.0
#### Stacktrace
```java
:ios:launchIOSDevice
Root pattern com.badlogic.gdx.physics.bullet.** matches no classes
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.graphics.glutils.ETC1.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.math.Matrix4.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.utils.BufferUtils.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(etc1_utils.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(gdx2d.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(jpgd.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(jpgd_c.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(com.badlogic.gdx.backends.iosrobovm.IOSGLES10.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(iosgl20.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(iosgl30.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a(memcpy_wrap.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAction.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALActionManager.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioActions.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALUtilityActions.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioTrack.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioTrackNotifications.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioTracks.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALSimpleAudio.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALBuffer.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALCaptureDevice.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALChannelSource.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALContext.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALDevice.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALListener.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALSoundSourcePool.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALSource.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(ALWrapper.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OpenALManager.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioSession.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALSuspendHandler.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(IOSVersion.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(mach_timing.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(NSMutableArray+WeakReferences.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(NSMutableDictionary+WeakReferences.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALAudioFile.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: warning: object file (/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a(OALTools.o)) was built for newer iOS version (6.0) than being linked (5.0)
ld: mach-o string pool extends beyond end of file file '/Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.m2/repository/org/robovm/robovm-dist/1.0.0-beta-03/unpacked/robovm-1.0.0-beta-03/lib/robovm-rt.jar/javax/crypto/spec/PBEKeySpec.class.o' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
:ios:launchIOSDevice FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:launchIOSDevice'.
> Failed to launch IOS Device

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ios:launchIOSDevice'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleException: Failed to launch IOS Device
	at org.robovm.gradle.tasks.IOSDeviceTask.invoke(IOSDeviceTask.java:45)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 56 more
Caused by: org.gradle.api.GradleException: Error building RoboVM executable for app
	at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:100)
	at org.robovm.gradle.tasks.IOSDeviceTask.invoke(IOSDeviceTask.java:40)
	... 64 more
Caused by: org.apache.commons.exec.ExecuteException: Command '/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/dungtran/Desktop/Workspace/Libgdx/ios/build/robovm.tmp/IOSLauncher -arch armv7 -Wl,-filelist,/Users/dungtran/Desktop/Workspace/Libgdx/ios/build/robovm.tmp/objects -L /Users/dungtran/.m2/repository/org/robovm/robovm-dist/1.0.0-beta-03/unpacked/robovm-1.0.0-beta-03/lib/vm/ios/thumbv7 -ObjC -exported_symbols_list /Users/dungtran/Desktop/Workspace/Libgdx/ios/build/robovm.tmp/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -miphoneos-version-min=5.0 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -lrobovm-bc -force_load /Users/dungtran/.m2/repository/org/robovm/robovm-dist/1.0.0-beta-03/unpacked/robovm-1.0.0-beta-03/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -liconv -lsqlite3 -framework Foundation -framework UIKit -framework OpenGLES -framework QuartzCore -framework CoreGraphics -framework OpenAL -framework AudioToolbox -framework AVFoundation -force_load /Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/dungtran/.robovm/cache/ios/thumbv7/release/Users/dungtran/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.2/77ea547b62ef831b4f15562bc5d0eac38bdad5c7/gdx-platform-1.9.2-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -force_load /Users/dungtran/Desktop/Workspace/Libgdx/ios/build/libs/ios/libgdx.a -force_load /Users/dungtran/Desktop/Workspace/Libgdx/ios/build/libs/ios/libObjectAL.a' failed (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:346)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:191)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:194)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:283)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:188)
	at org.robovm.compiler.Linker.link(Linker.java:299)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:340)
	at org.robovm.gradle.tasks.AbstractRoboVMTask.build(AbstractRoboVMTask.java:96)
	... 65 more


BUILD FAILED

Total time: 28.564 secs
```

#### Please select the affected platforms
- [ ] Android
- [ x] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Try with latest RoboVM, 1.0.0-beta-03 is pretty ancient.

**Comment by dungnart** [comment]
Thanks for your help ;)
