### ISSUE TITLE
ArrayIndexOutOfBounds when using color markup with TextField.

### ISSUE THREAD

**Issue by Charanor** [libgdx/libgdx#4303]
I get an ArrayIndexOutOfBoundsException when using a color markup with a custom font generated by FreeTypeFont. This only seems to happen when the text in my text field is => 17 characters long. 
I've tried 3 other fonts and the problem persists, although it goes away if I use the default font shipped with LibGDX. Perhaps it's a FreeTypeFont issue? Looking at the stack trace, maybe it incorrectly determines offsets?

My version of LibGDX is 1.9.4 with FreeTypeFont extension. Stacktrace & ApplicationListener below.

```
public class ErrorTest implements ApplicationListener {

    @Override
    public void create() {
        TextFieldStyle style = new TextFieldStyle();
        /*
         * Change this font to a font generated by FreeTypeFont
         * and it seems to crash, although normal font works fine.
         */
        BitmapFont font = new BitmapFont();
        font.getData().markupEnabled = true;
        style.font = font;
        TextField textField = new TextField("", style);
        /* Crash here */
        textField.setText("[LIGHT_GREY] total text longer than 17 letters.");
    }

    @Override
    public void resize(int width, int height) {
    }

    @Override
    public void render() {
    }

    @Override
    public void pause() {
    }

    @Override
    public void resume() {
    }

    @Override
    public void dispose() {
    }

}
```

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 49
    at com.badlogic.gdx.scenes.scene2d.ui.TextField.calculateOffsets(TextField.java:247)
    at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:297)
    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
    at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:110)
    at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:243)
    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
    at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)

**Comment by gjroelofs** [comment]
Just to chime in; we've had a similar issue, and it seemed to be tied to linebreaks.

**Comment by klaus7** [comment]
It looks like you can quickfix this if you change the line 
`int length = displayText.length();`
with
`int length = glyphPositions.length - 1;`

**Comment by langurmonkey** [comment]
I can confirm the solution proposed by @klaus7 worked for me.
