### ISSUE TITLE
Tiled Map loading throwing IllegalArgumentException: initialCapacity is too large.

### ISSUE THREAD

**Issue by Snehks** [libgdx/libgdx#4309]
#### Issue details
Basically my game is being played by few people at the moment and one of them sometimes get this exception when he moves from one map to the other - 
Tiled Map loading throwing IllegalArgumentException: initialCapacity is too large.

I am not doing anything outside render thread. Even map is loaded on the render thread.

#### Reproduction steps/code
Sadly there is no way I could reproduce it, it just happens on one of my client's computer when a new map is loaded. Also this doesn't happen very often, the exception occurs rarely.

#### The way I load map is like this : 
`currentMap = new TmxMapLoader().load("maps/" + switchMapMessage.getMapId() + TMX_EXTENSION, mapParams);`

#### Version of LibGDX and/or relevant dependencies
Libgdx Version 1.9.3

#### Stacktrace
```
LWJGL Application ERROR - A fatal error
com.badlogic.gdx.utils.SerializationException: Error parsing file: maps/1.tmx
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:83)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:78)
	at com.pbo.game.client.map.DefaultMapManager.setupNewMap(DefaultMapManager.java:158)
	at com.pbo.game.client.ui.screens.MainGameScreen.handleNetworkQueue(MainGameScreen.java:226)
	at com.pbo.game.client.ui.screens.MainGameScreen.render(MainGameScreen.java:156)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.pbo.game.client.GameClient.render(GameClient.java:73)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: java.lang.IllegalArgumentException: initialCapacity is too large: 16
	at com.badlogic.gdx.utils.ObjectMap.<init>(ObjectMap.java:68)
	at com.badlogic.gdx.utils.ObjectMap.<init>(ObjectMap.java:59)
	at com.badlogic.gdx.utils.XmlReader$Element.setAttribute(XmlReader.java:487)
	at com.badlogic.gdx.utils.XmlReader.attribute(XmlReader.java:428)
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:260)
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:61)
	at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:81)
	... 8 common frames omitted
```

#### Please select the affected platforms
Windows

Also sometimes this `Caused by: java.lang.IllegalArgumentException: initialCapacity is too large: 16` has 64 as initial capacity too.

**Comment by Tom-Ski** [comment]
This is most likely a threading issue, but either way we can't do anything without more info. Please supply a self contained test that reproduces your issue, and re-open this issue.

**Comment by ukrainecmk** [comment]
Same thing for me:
class java.lang.IllegalArgumentException: initialCapacity is too large: 64
com.badlogic.gdx.utils.ObjectIntMap.&lt;init&gt;(ObjectIntMap.java:68)
com.badlogic.gdx.utils.ObjectIntMap.&lt;init&gt;(ObjectIntMap.java:53)
com.badlogic.gdx.graphics.glutils.ShaderProgram.&lt;init&gt;(ShaderProgram.java:106)
com.badlogic.gdx.graphics.glutils.ShaderProgram.&lt;init&gt;(ShaderProgram.java:180)
It happen when I create simple shader, on one of my computers, on other - it's ok, I refered to same line:
if (initialCapacity > 1 << 30) throw new IllegalArgumentException("initialCapacity is too large: " + initialCapacity);
and yes - 1 << 30 == 1073741824 on all of my tests, but still - sometimes this error just happens and crash everything.

**Comment by intrigus** [comment]
Do you have more information e.g. java version and exact windows version

**Comment by ukrainecmk** [comment]
Hello.
Yes, actually I saw another topics with this issue - also without any details or steps to reproduce, but for my case - I found issue. It occurred only in one (from two) test computers. Actually what I tried to do - create Shaders dynamically on game loop. I have a one class - some shader manager, after I try to get from it one of ShaderProgram HashMap array - it check if it was created before, and if not - it create ShaderProgram right now (game loop - stage run - is in progress). Exactly this you can check from my log above - final point was on "com.badlogic.gdx.utils.ObjectIntMap.<init>(ObjectIntMap.java:68)". Once I moved initialization of all required and possible shaders to the stage init - before it's draw circle begin - problem gone. Java and windows version is the same as on first machine (that didn't create such issues), processor with this issue is Intel Dual Core 2.42, processor o machine without issue - Intel Core i3. I think replacing "1 << 30" - for just hardcoded "1073741824" (not so cute, I know) - will solve issue.
