### ISSUE TITLE
 IllegalStateException:RoboVmRunProfileState.startProcess must not return null error

### ISSUE THREAD

**Issue by naimburakbasaran** [libgdx/libgdx#4339]
Please ensure you have given all the following requested information in your report.

#### Issue details
I developed a libgdx game for android and want it to port to iOS too, I am fairly new at RoboVM and getting this exception;

 IllegalStateException: @NotNull method org/robovm/idea/running/RoboVmRunProfileState.startProcess must not return null

#### Version of LibGDX and/or relevant dependencies
obovm-gradle-plugin:2.2.1-SNAPSHOT

#### Stacktrace
ava.lang.NullPointerException
	at org.robovm.compiler.target.ios.IOSTarget.createIOSSimLauncher(IOSTarget.java:163)
	at org.robovm.compiler.target.ios.IOSTarget.createLauncher(IOSTarget.java:148)
	at org.robovm.compiler.target.AbstractTarget.doLaunch(AbstractTarget.java:490)
	at org.robovm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:537)
	at org.robovm.compiler.target.AbstractTarget.launch(AbstractTarget.java:486)
	at org.robovm.compiler.AppCompiler.launchAsync(AppCompiler.java:828)
	at org.robovm.idea.running.RoboVmRunProfileState.executeRun(RoboVmRunProfileState.java:69)
	at org.robovm.idea.running.RoboVmRunProfileState.startProcess(RoboVmRunProfileState.java:114)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at org.robovm.idea.running.RoboVmRunner.doExecute(RoboVmRunner.java:79)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:163)
	at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)

#### Please select the affected platforms
- [ ] Android
- [X] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You need the latest snapshot of the IDEA plugin, which by your trace is how you are running.

**Comment by lozan** [comment]
I got this error after upgrading to macOS 10.13.2 and Xcode 9.2.
I tried with IntelliJ IDEA 2017.3 and with 2017.3.1 and it's the same.
I am using RoboVM IntelliJ IDEA Plugin 2.3.4-SNAPSHOT and the same version of RoboVM.

`Error running 'ios-robovm': @NotNull method org/robovm/idea/running/RoboVmRunProfileState.startProcess must not return null`

**Comment by lozan** [comment]
[ERROR] Couldn't start application
java.lang.NullPointerException
	at org.robovm.idea.running.RoboVmRunProfileState.executeRun(RoboVmRunProfileState.java:57)
	at org.robovm.idea.running.RoboVmRunProfileState.startProcess(RoboVmRunProfileState.java:114)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at org.robovm.idea.running.RoboVmRunner.doExecute(RoboVmRunner.java:79)
	at com.intellij.execution.runners.GenericProgramRunner$execute$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.runners.GenericProgramRunnerKt$startRunProfile$$inlined$runProfileStarter$1.executeAsync(GenericProgramRunner.kt:69)
	at com.intellij.execution.impl.ExecutionManagerKtImpl$startRunProfile$startRunnable$1.run(ExecutionManagerKtImpl.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by MrStahlfelge** [comment]
https://github.com/MobiVM/robovm/issues/242
