### ISSUE TITLE
JNIGen: NPE when having JNI section without any native method

### ISSUE THREAD

**Issue by IonAgorria** [libgdx/libgdx#4351]
#### Issue details

NullPointerException occurs when JNI section is declared without any native method in tihe same class that JNI section is.
Probably as cMethodParser.parse(headerFileContent) can't find any JNIEXPORT returns null and .getMethods() is called with null result causing NPE
#### Reproduction steps/code

Create a java file with and pass the JNIGen:
public class Example {
    /*JNI
    static jint example = 0;
     */
}
#### Version of LibGDX and/or relevant dependencies

JNIGen 1.9.4
#### Stacktrace

``` java
Exception in thread "main" java.lang.NullPointerException
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.generateCppFile(NativeCodeGenerator.java:304)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:267)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.generate(NativeCodeGenerator.java:236)
    at com.badlogic.gdx.jnigen.NativeCodeGenerator.generate(NativeCodeGenerator.java:202)
```
#### Please select the affected platforms
- [X] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [ ] MacOS

**Comment by badlogic** [comment]
Can't reproduce this in latest jnigen from master.
