### ISSUE TITLE
A clean test app won't launch due to LwjglGraphics.createDisplayPixelFormat error

### ISSUE THREAD

**Issue by Betalord** [libgdx/libgdx#4356]
I just installed created a fresh libgdx application via the generator found on the official web site. I left practically all things at default. Once generated, I imported the project in eclipse using Gradle (as explained in the official procedure). Upon trying to launch my application on desktop, I get the following error:

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:322)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:216)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:142)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

Under "Project and External Dependencies" I can see it links to libgdx 1.9.4 and lwjgl 2.9.2 (by the way, why isn't libgdx using lwjgl 2.9.3, which is the latest version?) and some other non-important stuff.

Note that this is a fresh project generated by the "Libgdx Project Generator" - I haven't modified a thing!

I'm running Windows 10 on HP Elitebook 8560p (it's a laptop) and it has Intel HD Graphics 3000 (which is Microsoft DirectX 10.1 (Shader Model 4.1) and OpenGL 3.0 capable).

If you require any more info, please tell.

**Comment by Betalord** [comment]
OK, I solved the problem - I had install JDK 1.8.0_51 and link my Eclipse's run configuration to it. The problem is whit Intel HD 3000 graphic card which doesn't support Windows 10. Hence a need to revert Java because in version 8u51 (and earlier) it didn't support Windows 10 yet.
However, this is a known issue it seems - I've read about it on Minecraft forums, LWJGL forums, and others.
