### ISSUE TITLE
MultipleRenderTargetTest error message when running from LwjglTestStarter

### ISSUE THREAD

**Issue by jlnguy** [libgdx/libgdx#4369]
#### Issue details
Running the test demo "MultipleRenderTestTarget" included in LibGDX test examples runs the application and then crashes with an exception message. 

We tested this issue on three laptops that run Windows and one Mac. 

#### Reproduction steps/code
- Run LwjglTestStarter.java (in Eclipse)
- Select MultipleRenderTestTarget in the window that pops up

#### Version of LibGDX and/or relevant dependencies
I believe I'm using 1.9.4.

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest$MRTFrameBuffer.build(MultipleRenderTargetTest.java:561)
	at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest$MRTFrameBuffer.<init>(MultipleRenderTargetTest.java:483)
	at com.badlogic.gdx.tests.g3d.MultipleRenderTargetTest.create(MultipleRenderTargetTest.java:146)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
You need to enable GL30 to run this test.
