### ISSUE TITLE
Cannot run gdx tests with lwjgl3 on OS X

### ISSUE THREAD

**Issue by magicgoose** [libgdx/libgdx#4471]
#### Reproduction steps/code
Initialize everything needed to [run tests from source](https://github.com/libgdx/libgdx/wiki/Running-demos-%26-tests),  
`gradle tests:gdx-tests-lwjgl:launchTestsLwjgl` should work fine.

Then run `gradle tests:gdx-tests-lwjgl3:launchTestsLwjgl3` on OS X 10.11 (or maybe any OS X), this is going to fail.

> GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.

#### Version of LibGDX and/or relevant dependencies
adb26f3b776fca66db14d94e4a67d2ff6d9382fd and everything as referenced

#### Stacktrace
```java
:tests:gdx-tests-lwjgl3:launchTestsLwjgl3
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1384)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:425)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
        at com.badlogic.gdx.tests.lwjgl3.Lwjgl3TestStarter.main(Lwjgl3TestStarter.java:45)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
        at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:38)
        ... 5 more
AL lib: (EE) alc_cleanup: 1 device not closed
```

#### affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by magicgoose** [comment]
I'm pretty much blocked by this because I need to add test in #4465 but it requires GL3 for running.

**Comment by magicgoose** [comment]
@intrigus thank you, now it launches! 😎

**Comment by magicgoose** [comment]
Hmmm, I misunderstood. LWJGL3 has nothing to do with OpenGL 3.

**Comment by badlogic** [comment]
Thanks for the fix @intrigus. Closing this out.
