### ISSUE TITLE
Custom Properties of Tiled Files. "File" And "Color" not supported

### ISSUE THREAD

**Issue by badnomis** [libgdx/libgdx#4474]
#### Issue details

If I add a File or Color Custom Properties to my tmx file, my application crash with this Error:
`Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Wrong type given for property CustomProperties, given : file, supported : string, bool, int, float`

To reproduce, simply load a TMX files containing a Object Layer that contain Objects with custom Properties of type Color or File

#### Version of LibGDX and/or relevant dependencies
My version of LibGDX is 1.9.4

#### Stacktrace
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Wrong type given for property CustomProperties, given : color, supported : string, bool, int, float
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.castProperty(BaseTmxMapLoader.java:289)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadProperties(BaseTmxMapLoader.java:273)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:257)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObjectGroup(BaseTmxMapLoader.java:120)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadTilemap(TmxMapLoader.java:215)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:90)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:65)
```

**Comment by piotr-j** [comment]
This should be closed probably.
