### ISSUE TITLE
iOS MOE launch failing (Xcode 8.1 compatibility issue)

### ISSUE THREAD

**Issue by kerberjg** [libgdx/libgdx#4501]
I'm unable to launch the default base iOS-MOE project generated by gdx-setup

#### Issue details
I've attempted to compile other MOE samples and they launch without any problem. The only difference that I noticed is that the samples use MOE 1.2.5, while the libGDX project seems to use 1.2.3

I'm not having any trouble with Android and Desktop backends of the same project.

#### Reproduction steps/code
1. Generate a project in gdx-setup with a ios-moe backend
2. Import generated projects into Eclipse
3. Run the "ios-moe" project as "Multi-OS Engine iOS Application"
4. Fails after the ":ios-moe:moeLaunch" task

#### Version of LibGDX and/or relevant dependencies
* Intel MOE 1.2.3
* LibGDX 1.9.5
* Gradle 2.10
* Eclipse Neon 4.6.0
* Xcode 8.1
* macOS 10.11
* Default iOS simulator: iOS 10.1

#### Stacktrace
```java
:ios-moe:moeLaunch (Thread[Daemon worker Thread 5,5,main]) started.
:ios-moe:moeLaunch
Executing task ':i
os-moe:moeLaunch' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command '/Users/kerberjg/.moe/moe-sdk-1.2.3/tools/simlauncher''. Working directory: /Users/kerberjg/.moe/moe-sdk-1.2.3/tools Command: /Users/kerberjg/.moe/moe-sdk-1.2.3/tools/simlauncher --udid=A9F79815-B33C-41E5-A5DE-4AEE1561FA90 --app-path=/Users/kerberjg/git/gdxstudio-backends/ios-moe/build/moe/xcodebuild/Debug-iphonesimulator/ios-moe.app --launch-arg=-args

Successfully started process 'command '/Users/kerberjg/.moe/moe-sdk-1.2.3/tools/simlauncher''

2016-12-22 21:48:14.056 simlauncher[62113:868773] +[SimDeviceSet defaultSet]: unrecognized selector sent to class 0x105e3f118
2016-12-22 21:48:14.057 simlauncher[62113:868773] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[SimDeviceSet defaultSet]: unrecognized selector sent to class 0x105e3f118'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9404348b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa87a5cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff940c4bd4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff93fb5b55 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fff93fb56a8 _CF_forwarding_prep_0 + 120
	5   simlauncher                         0x00000001026d721d getSimDevice + 53
	6   simlauncher                         0x00000001026d6dbb moe_main + 569
	7   simlauncher                         0x
00000001026d6b5c main + 275
	8   libdyld.dylib                       0x00007fffa9084255 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Command failed: [null]


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios-moe:moeLaunch'.
> Process exited with non-zero exit value

* Try:
Run with --debug option to get more log output.

* Exception is:

:ios-moe:moeLaunch FAILED
:ios-moe:moeLaunch (Thread[Daemon worker Thread 5,5,main]) completed. Took 0.264 secs.

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ios-moe:moeLaunch'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.j
ava:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.exe
cution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLaunch
er$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProces
sBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.e
xecute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.
api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.G
radleException: Process exited with non-zero exit value
	at org.moe.gradle.utils.TaskUtils.exec(TaskUtils.java:143)
	at org.moe.gradle.tasks.Launchers.lambda$setupDevicesAndSimulators$17(Launchers.java:880)
	at org.moe.gradle.tasks.Launchers$$Lambda$158/1081535708.execute(Unknown Source)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more



BUILD FAILED

Total time: 1.483 secs

Stopped 0 compiler daemon(s).

Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':ios-moe:moeLaunch'.] from daemon DaemonInfo{pid=61081, address=[5b055eef-0559-41f2-897f-13c9d1553e98 port:59916, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=a51760cd-a8e5-40f4-96c6-c83fdf0999b0,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home,daemonRegistryDir=/Users/kerberjg/.gradle/daemon,pid=61081,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx1500m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by kerberjg** [comment]
The failing element seems to be MOE's iOS Simulator launcher, as apparently it's throwing an exception

**Comment by tianqiujie** [comment]
I have no idea about eclipse. But in android studio, I just change the version of moe gradle plugin .
```'org.multi-os-engine:moe-gradle:1.2.3'``` to classpath ```'org.multi-os-engine:moe-gradle:1.2.5'``` in the build.gradle , and you can refresh dependence or re-import into eclispe
