### ISSUE TITLE
Can't build html - Unexpected element 'resource'

### ISSUE THREAD

**Issue by Yaty14** [libgdx/libgdx#4522]
### Issue details
I'm trying to build for the first time my game for html but I have a problem when I execute gradlew html:dist. 

LibGDX version = 1.9.5

#### Stacktrace
gradlew html:dist --stacktrace (full stacktrace here : http://pastebin.com/Si99F2uc)

```D:\Bureau\Projet 1A2A\explorationminiere>gradlew html:dist --stacktrace

Configuration on demand is an incubating feature.
:html:clean
:html:addSource
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:html:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:html:processResources UP-TO-DATE
:html:compileGwt
janv. 07, 2017 3:48:22 PM java.util.prefs.WindowsPreferences <init>
Loading inherited module 'com.mygdx.minexploration.GdxDefinition'
   Loading inherited module 'com.badlogic.gdx.backends.gdx_backends_gwt'
      Loading inherited module 'com.google.gwt.user.User'
         Loading inherited module 'com.google.gwt.media.Media'
            Loading inherited module 'com.google.gwt.user.UI'
               Loading inherited module 'com.google.gwt.uibinder.UiBinder'
                  [ERROR] Line 20: Unexpected element 'resource'
                  [ERROR] Failure while parsing XML
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
        at com.google.gwt.dev.util.xml.DefaultSchema.onUnexpectedElement(DefaultSchema.java:86)
        at com.google.gwt.dev.util.xml.Schema.onUnexpectedElement(Schema.java:94)
        at com.google.gwt.dev.util.xml.Schema.onUnexpectedElement(Schema.java:94)
        at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:223)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at 
...

BUILD FAILED
Total time: 1.844 secs
```

And with gradlew html:dist --debug (http://pastebin.com/jxgJ0bsH it's around line 1859).

#### Please select the affected platforms
- [X] HTML/GWT
- [X] Windows
- [ ] Linux - not tested
- [ ] MacOS - not tested

**Comment by Tom-Ski** [comment]
LibGDX 1.9.5 requires gwt 2.8.0
