### ISSUE TITLE
Gradle Repo is Broken

### ISSUE THREAD

**Issue by Jonatino** [libgdx/libgdx#4523]
Version 1.9.5 repo is broken. It was working fine yesterday but this morning I get the following error

```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:81)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
	at com.charlatano.overlay.Overlay.open(Overlay.kt:57)
	at com.charlatano.Charlatano.main(Charlatano.kt:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx64.dll
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:127)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:280)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
	... 11 more
```

Here's my build script.

```groovy
buildscript {
    ext.kotlin_version = "1.1-M04"
    ext.gdxVersion = "1.9.5"

    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: "java"
apply plugin: "kotlin"
apply plugin: "application"

sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
}
dependencies {
    compile group: "com.badlogicgames.gdx", name: "gdx", version: gdxVersion
    compile group: "com.badlogicgames.gdx", name: "gdx-box2d", version: gdxVersion
    compile group: "com.badlogicgames.gdx", name: "gdx-backend-lwjgl", version: gdxVersion

    compile group: "com.badlogicgames.gdx", name: "gdx-platform", version: "$gdxVersion:natives-desktop"
    compile group: "com.badlogicgames.gdx", name: "gdx-freetype-platform", version: "$gdxVersion:natives-desktop"
}
```

**Comment by Tom-Ski** [comment]
Artifacts look fine on maven central, this is most likely a configuration issue on your side. Please generate a project with the setup tool and try to run from there first.
