### ISSUE TITLE
MOE 1.2.3 is broken in LibGDX 1.9.5

### ISSUE THREAD

**Issue by doit-ceo** [libgdx/libgdx#4527]
#### Issue details
Trying to generate a project using the LibGDX project generator, this will result in failed build !

#### Reproduction steps/code
Select the "ios-MOE" and click "Generator" , the error related to the ".../.moe/moe-sdk-1.2.3.tmp/sdk/moe-ios.jar" , I tried to unzip the jar manually , but it's corrupted !

I even cleared my .gradle cache and redownloaded the moe SDK again, but same issue !

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Stacktrace
Download https://dl.bintray.com/multi-os-engine/maven/org/multi-os-engine/moe-sdk/1.2.3/moe-sdk-1.2.3.zip
Exception in thread "Thread-10" org.gradle.api.GradleException: Could not expand ZIP '/home/alaa/.moe/moe-sdk-1.2.3.tmp/sdk/moe-ios.jar'.
	at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:99)
	at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:109)
	at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:135)
	at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:58)
	at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:37)
	at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
	at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:498)
	at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:322)
	at org.gradle.api.internal.file.copy.DelegatingCopySpecInternal.walk(DelegatingCopySpecInternal.java:206)
	at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:36)
	at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
	at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:56)
	at org.gradle.api.internal.file.copy.FileCopyAction.execute(FileCopyAction.java:35)
	at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:52)
	at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
	at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:38)
	at org.gradle.api.internal.file.copy.FileCopier.doCopy(FileCopier.java:64)
	at org.gradle.api.internal.file.copy.FileCopier.copy(FileCopier.java:49)
	at org.gradle.api.internal.file.DefaultFileOperations.copy(DefaultFileOperations.java:134)
	at org.gradle.api.internal.project.AbstractProject.copy(AbstractProject.java:776)
	at org.moe.gradle.MoeSDK.lambda$completePartialSDK$6(MoeSDK.java:206)
	at java.lang.Thread.run(Thread.java:745)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ X] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by doit-ceo** [comment]
BTW I'm running the generator in Linux Ubuntu 14.11 !, I tried to download the SDK manually (both 1.2.3 & 1.2.5) and I failed to unzip them both ! do I need a Mac to start the MOE ?

**Comment by doit-ceo** [comment]
Running this in MacOS fix this problem
