### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by zjc121** [libgdx/libgdx#4557]
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:81)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
	at de.swagner.paxbritannica.desktop.DesktopLauncher.main(DesktopLauncher.java:13)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx64.dll
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:127)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:280)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
	... 5 more

**Comment by hardik124** [comment]
Please provide steps for reproduction.

**Comment by zjc121** [comment]
game pax-britannica  
compile with the 1.9.5 gdx source project not gdx.jar and other jar lib          then i run the desktop 
@hardik124
