### ISSUE TITLE
Intel Multi-OS Engine and SimpleXML crash

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4573]
On RoboVm SimpleXML works without any problem.

#### Reproduction steps/code
This code running on separate thread. (rx-java, io-scheduler)
```java
val questFile = gdxContext.files.internal("quest.xml")
xmlSerializer.read(Quest::class.java, questFile.reader())
```

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.5
org.multi-os-engine:moe-gradle:1.3.0-beta-2
org.simpleframework:simple-xml:2.7.1

#### Stacktrace

```java
Caused by: java.lang.NoSuchMethodException: <init> [interface org.simpleframework.xml.core.Contact, interface org.simpleframework.xml.ElementList, class org.simpleframework.xml.stream.Format]
	at java.lang.Class.getConstructor(Class.java:573)
	at java.lang.Class.getConstructor(Class.java:537)
	at org.simpleframework.xml.core.LabelExtractor$LabelBuilder.getConstructor(LabelExtractor.java:426)
	at org.simpleframework.xml.core.LabelExtractor$LabelBuilder.getConstructor(LabelExtractor.java:415)
	at org.simpleframework.xml.core.LabelExtractor.getConstructor(LabelExtractor.java:300)
	at org.simpleframework.xml.core.LabelExtractor.getLabel(LabelExtractor.java:265)
	at org.simpleframework.xml.core.LabelExtractor.getSingle(LabelExtractor.java:190)
	at org.simpleframework.xml.core.LabelExtractor.getLabels(LabelExtractor.java:174)
	at org.simpleframework.xml.core.LabelExtractor.getGroup(LabelExtractor.java:142)
	at org.simpleframework.xml.core.LabelExtractor.getLabel(LabelExtractor.java:95)
	at org.simpleframework.xml.core.Support.getLabel(Support.java:242)
	at org.simpleframework.xml.core.StructureBuilder.process(StructureBuilder.java:245)
	at org.simpleframework.xml.core.StructureBuilder.process(StructureBuilder.java:185)
	at org.simpleframework.xml.core.ObjectScanner.method(ObjectScanner.java:459)
	at org.simpleframework.xml.core.ObjectScanner.scan(ObjectScanner.java:372)
	at org.simpleframework.xml.core.ObjectScanner.<init>(ObjectScanner.java:82)
	at org.simpleframework.xml.core.ScannerFactory.getInstance(ScannerFactory.java:81)
	at org.simpleframework.xml.core.Support.getScanner(Support.java:357)
	at org.simpleframework.xml.core.Source.getScanner(Source.java:271)
	at org.simpleframework.xml.core.Source.getSchema(Source.java:317)
	at org.simpleframework.xml.core.Composite.read(Composite.java:198)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at org.simpleframework.xml.core.Persister.read(Persister.java:462)
	at red.kometa.quest.player.model.managers.story.QuestDataSource$get$1.call(QuestDataSource.kt:20)
	at red.kometa.quest.player.model.managers.story.QuestDataSource$get$1.call(QuestDataSource.kt:10)
	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:41)
	at rx.internal.operators.SingleFromCallable.call(SingleFromCallable.java:29)
	at rx.Single.subscribe(Single.java:1876)
	at rx.internal.operators.SingleDoOnEvent.call(SingleDoOnEvent.java:40)
	at rx.internal.operators.SingleDoOnEvent.call(SingleDoOnEvent.java:25)
	at rx.Single.subscribe(Single.java:1876)
	at rx.Completable$11.call(Completable.java:622)
	at rx.Completable$11.call(Completable.java:605)
	at rx.Completable.unsafeSubscribe(Completable.java:2037)
	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.next(CompletableOnSubscribeConcatArray.java:92)
	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.onCompleted(CompletableOnSubscribeConcatArray.java:68)
	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.next(CompletableOnSubscribeConcatArray.java:88)
	at rx.internal.operators.CompletableOnSubscribeConcatArray$ConcatInnerSubscriber.onCompleted(CompletableOnSubscribeConcatArray.java:68)
	at rx.Completable$24$1$1.call(Completable.java:1628)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

#### Please select the affected platforms
- [ ] iOS (MOE)

**Comment by Try4W** [comment]
fixed via appending file `proguard.append.cfg`

```
-keep public class org.simpleframework.** { *; }
-keep class org.simpleframework.xml.** { *; }
-keep class org.simpleframework.xml.core.** { *; }
-keep class org.simpleframework.xml.util.** { *; }

-keepattributes ElementList, Root

-keepclassmembers class * {
    @org.simpleframework.xml.* *;
}
```
