### ISSUE TITLE
MOE and FreeType fonts: Couldn't load shared library

### ISSUE THREAD

**Issue by Try4W** [libgdx/libgdx#4574]
With RoboVm everything works as expected.

#### Reproduction steps/code
```java
project(":krq-player-ios-moe") {
    apply plugin: "java"
    apply plugin: "kotlin"
    apply plugin: "moe"

    configurations { natives }

    dependencies {
        compile project(":krq-player-core")

        compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

        compile 'org.slf4j:slf4j-simple:1.7.12'
        
        compile "com.badlogicgames.gdx:gdx-backend-moe:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-ios"
    }
}
```

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Stacktrace
```java
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx-freetype' for target: Darwin, 32-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeType.initFreeType(FreeType.java:887)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.<init>(FreeTypeFontGenerator.java:94)
	at red.kometa.quest.player.utils.gdxsmartfont.SmartFontGenerator.generateFontWriteFiles(SmartFontGenerator.java:81)
	at red.kometa.quest.player.utils.gdxsmartfont.SmartFontGenerator.createFont(SmartFontGenerator.java:70)
	at red.kometa.quest.player.presentation.Fonts.generateFont(Fonts.kt:107)
	at red.kometa.quest.player.presentation.Fonts.generateFont(Fonts.kt:88)
	at red.kometa.quest.player.presentation.Fonts.access$generateFont(Fonts.kt:28)
	at red.kometa.quest.player.presentation.Fonts$generateFonts$1.call(Fonts.kt:77)
```

#### Please select the affected platforms
- [ ] iOS (MOE)

**Comment by idanakav** [comment]
Had the same issue with 1.9.5, 
only 1.9.6-SNAPSHOT and MOE 1.3.0-beta-2 worked for me.
