### ISSUE TITLE
TextField crash when writing brackets if color markup is enabled

### ISSUE THREAD

**Issue by MrPlow442** [libgdx/libgdx#4576]
#### Issue details
Opening and closing brackets `[]` when color markup is enabled causes an `IndexOutOfBoundsException` regardless of how many characters are between the brackets

#### Reproduction steps/code
```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.TextField;
import com.badlogic.gdx.utils.viewport.FitViewport;

/** {@link com.badlogic.gdx.ApplicationListener} implementation shared by all platforms. */
public class Test extends ApplicationAdapter {
    private Stage stage;
    private Skin skin;

    @Override
    public void create() {
        stage = new Stage(new FitViewport(640, 480));
        skin = new Skin(Gdx.files.internal("skin.json"));

        BitmapFont font = skin.getFont("default-font");

        font.getData().markupEnabled = true;

        stage.addActor(new TextField("", skin));

        Gdx.input.setInputProcessor(stage);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(0f, 0f, 0f, 1f);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        stage.act(Gdx.graphics.getDeltaTime());
        stage.draw();
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height);
    }

    @Override
    public void dispose() {
        stage.dispose();
        skin.dispose();
    }
}
```

#### Version of LibGDX and/or relevant dependencies
Attempted on LibGDX versions 1.9.5 and 1.9.6-SNAPSHOT

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 2 >= 1
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:104)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.drawCursor(TextField.java:373)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:343)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at test.Test.render(Test.java:82)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by NathanSweet** [comment]
@metaphore Disabling color markup for text field/areas sounds OK.

**Comment by mcol** [comment]
I've encountered this crash too, as it's not documented (outside of github issues) that markup should not be used in TextAreas.
