### ISSUE TITLE
[NVIDIA] Latest 378.49 driver is broken!

### ISSUE THREAD

**Issue by ghost** [libgdx/libgdx#4584]
#### Issue details

libGDX games refuse to run

#### Reproduction steps/code
Try to run your game with the latest Nvidia driver installed

Reverting to an older version of the driver solve the issue

#### Version of LibGDX and/or relevant dependencies
1.9.5

#### Stacktrace
```text
"C:\Program Files\Java\jdk1.8.0_121\bin\java" -XX:+UseG1GC -Didea.launcher.port=7536 -Didea.launcher.bin.path=C:\Users\scellow\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\163.11103.6\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\scellow\Projects\Java\theRoguer\out\production\desktop;C:\Users\scellow\Projects\Java\theRoguer\out\production\core;C:\Users\scellow\Projects\Java\theRoguer\out\production\data;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.0.6\d19acb6ed49b9c48228c0e5dff8071fce23be4b8\kotlin-stdlib-1.0.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.0.6\3d499d3b7768f88c4796e5a1e357933e11a8936d\kotlin-reflect-1.0.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-test-junit\1.0.6\bcf90b8a2115939f76eadc4c292aec3b9e0af82f\kotlin-test-junit-1.0.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx\1.9.5\dc65bb2f51828c58b1b2b3ac585357204d54ee5f\gdx-1.9.5.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.esotericsoftware\kryonet\2.22.0-RC1\2f25f7250a3096a8d1b8182946f6572d90d280d0\kryonet-2.22.0-RC1.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-runtime\1.0.6\3562c66f648480d3bd4f76cff722488ced13445b\kotlin-runtime-1.0.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-test\1.0.6\b44f2fa44562133e8c06c4358c3ae23af9b381c7\kotlin-test-1.0.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.esotericsoftware.kryo\kryo\2.24.0\c6b206e80cfd97e66a1364003724491c757b92f\kryo-2.24.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.esotericsoftware\jsonbeans\0.7\de977f0875708eddd154f2a4c3a3f58a13ef297\jsonbeans-0.7.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.esotericsoftware.minlog\minlog\1.2\59bfcd171d82f9981a5e242b9e840191f650e209\minlog-1.2.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.1\87c0ea803b69252868d09308b4618f766f135a96\objenesis-2.1.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-freetype\1.9.5\71eba1332b3c2436d3b8e24296a0feb1c01d9e67\gdx-freetype-1.9.5.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-ai\1.8.0\ec30677d8ab1a8b8aa4b853c5f4e4b1361f50bf5\gdx-ai-1.8.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.mashape.unirest\unirest-java\1.4.5\674128dedd39ed4f128c8c74a2608c372e2d1a95\unirest-java-1.4.5.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.kotcrab.vis\vis-ui\1.3.0-SNAPSHOT\782e01fac16f47ae5c9af722b1bf6f8f43fe71c9\vis-ui-1.3.0-SNAPSHOT.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.3.6\4c47155e3e6c9a41a28db36680b828ced53b8af4\httpclient-4.3.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpasyncclient\4.0.2\6c0421e057af0fed081f0b8b4c4df829c4732a5c\httpasyncclient-4.0.2.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpmime\4.3.6\cf8bacbf0d476c7f2221f861269365b66447f7ec\httpmime-4.3.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.json\json\20140107\d1ffca6e2482b002702c6a576166fd685e3370e3\json-20140107.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.3.3\f91b7a4aadc5cf486df6e4634748d7dd7a73f06d\httpcore-4.3.3.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.1.3\f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f\commons-logging-1.1.3.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.6\b7f0fc8f61ecadeb3695f0b9464755eee44374d4\commons-codec-1.6.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore-nio\4.3.2\4038f9f6c7ab8e3fc03ad11772e44f751822e648\httpcore-nio-4.3.2.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-backend-lwjgl3\1.9.5\9d1fe3cfc96fd2463be17bd62dc50205ca53442d\gdx-backend-lwjgl3-1.9.5.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-platform\1.9.5\bc0c7ee7fca96eb3c691b5a87cf11fd4d9f1bab6\gdx-platform-1.9.5-natives-desktop.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.gdx\gdx-freetype-platform\1.9.5\8ceda028ccbad322d1c02bb806291d2b6bed0232\gdx-freetype-platform-1.9.5-natives-desktop.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.1.0\fae7a04425666311d5dfe5ef7d89021ca0308d8d\lwjgl-3.1.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.1.0\98d1c7d40b17eda66018b7806f2735c7f715dff2\lwjgl-3.1.0-natives-windows.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.1.0\702ba8be5d76944a4f87c6f58e900bb12d908da\lwjgl-3.1.0-natives-linux.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.1.0\76e769ab8997c54db5b44ed618bf68c85c7cf1b7\lwjgl-3.1.0-natives-macos.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.1.0\5f07fdd867a9785ec124828385fe45cf4d5671ec\lwjgl-glfw-3.1.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.1.0\5b3b88d2fd848de8581347d0d6bb90086e17fd26\lwjgl-glfw-3.1.0-natives-windows.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.1.0\712db96640a35b57cb2f2c52a680b6f517fa3249\lwjgl-glfw-3.1.0-natives-linux.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.1.0\d94cf701f26bc3da0089ba05650e99ec5cb3157b\lwjgl-glfw-3.1.0-natives-macos.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.1.0\ddd34894c24d8755eebd11707ffec246e8921609\lwjgl-jemalloc-3.1.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.1.0\1390bc6f4282cf33f4f31608ce89ac64fd581edc\lwjgl-jemalloc-3.1.0-natives-windows.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.1.0\94c97797b41ebe7fa20ba5dc68fff8276f79620\lwjgl-jemalloc-3.1.0-natives-linux.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.1.0\4506f881cc9b0dec1d7c0c381808b9faabaaf631\lwjgl-jemalloc-3.1.0-natives-macos.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-opengl\3.1.0\e4f2fc62238fc512245d01d45ddf794ceb084943\lwjgl-opengl-3.1.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.1.0\4434dbe160557e692eff747c73b273a420a7a40f\lwjgl-openal-3.1.0.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.1.0\fc8cc5b70fc446620f9bb03e7612ca564e27425e\lwjgl-openal-3.1.0-natives-windows.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.1.0\d745360ab8c939c620c4c3c2c7ec4400dac58a7e\lwjgl-openal-3.1.0-natives-linux.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.1.0\9e3ee369a141a4dbd3054a5aefa00a3871c651cd\lwjgl-openal-3.1.0-natives-macos.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\com.badlogicgames.jlayer\jlayer\1.0.1-gdx\7cca83cec5c1b2f011362f4d85aabd71a73b049d\jlayer-1.0.1-gdx.jar;C:\Users\scellow\.gradle\caches\modules-2\files-2.1\org.jcraft\jorbis\0.0.17\8872d22b293e8f5d7d56ff92be966e6dc28ebdc6\jorbis-0.0.17.jar;C:\Users\scellow\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\163.11103.6\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.scellow.game.desktop.DesktopLauncherKt
[LWJGL] GLFW_API_UNAVAILABLE error
	Description : WGL: The driver does not appear to support OpenGL
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1235)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1388)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:425)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
		com.scellow.game.desktop.DesktopLauncherKt.main(DesktopLauncher.kt:16)
		sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		java.lang.reflect.Method.invoke(Method.java:498)
		com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:428)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:372)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
	at com.scellow.game.desktop.DesktopLauncherKt.main(DesktopLauncher.kt:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 1
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

More info here: 

http://forum.lwjgl.org/index.php?topic=6439.msg34284#msg34284

" They really screwed up with this one. Even Direct3D 9 and 11 applications do not work anymore if being renamed to "java.exe" and started as "java". "

It's not an libGDX issue, but i think everyone should be aware of this

**Comment by badlogic** [comment]
NVIDIA is working on a hotfix, see
https://twitter.com/ManuelGuzman/status/826117015924387840

**Comment by Scellow** [comment]
They released the hotfix there: http://nvidia.custhelp.com/app/answers/detail/a_id/4378/

**Comment by hugorosario** [comment]
I just spent 2 hours trying to figure out why the DesktopLauncher was not working.
Should have come here sooner. 
Never thought that an NVIDIA driver could break this so easy.
Working fine after installing hotfix 378.57.

**Comment by EtK2000** [comment]
Although this was an issue for me at the time, I just reinstalled the old driver and couldn't get it to crash with Java 1.8.0_181.

**Comment by Tom-Ski** [comment]
Resolved
