### ISSUE TITLE
Couldn't load shared library 'gdx' for target: Linux, 32-bit

### ISSUE THREAD

**Issue by little-dgek** [libgdx/libgdx#4586]
#### Issue details
On some devices (for ex Nexus 7) crash with this error.
Only for Android 6.0

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.6-SNAPSHOT
#### Stacktrace
```java
02-01 02:28:50.394   610  1096 I ActivityManager: Force stopping net.playwithworld.yahtzee.dice appid=12127 user=0: from pid 12042
02-01 02:28:50.647   610   790 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=net.playwithworld.yahtzee.dice/net.playwithworld.yatzy.dice.AndroidLauncher} from uid 2000 on display 0
02-01 02:28:50.665 12042 12042 D AndroidRuntime: Shutting down VM
02-01 02:28:50.683   610   620 I ActivityManager: Start proc 12050:net.playwithworld.yahtzee.dice/u0a2127 for activity net.playwithworld.yahtzee.dice/net.playwithworld.yatzy.dice.AndroidLauncher
02-01 02:28:50.786 12050 12050 D AndroidRuntime: Shutting down VM
02-01 02:28:50.789 12050 12050 E AndroidRuntime: FATAL EXCEPTION: main
02-01 02:28:50.789 12050 12050 E AndroidRuntime: Process: net.playwithworld.yahtzee.dice, PID: 12050
02-01 02:28:50.789 12050 12050 E AndroidRuntime: java.lang.ExceptionInInitializerError
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: Caused by: com.badlogic.gdx.utils.j: Couldn't load shared library 'gdx' for target: Linux, 32-bit
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.badlogic.gdx.utils.ae.b(SharedLibraryLoader.java:124)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.badlogic.gdx.utils.i.a(GdxNativesLoader.java:33)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.badlogic.gdx.backends.android.a.<clinit>(AndroidApplication.java:63)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	... 12 more
02-01 02:28:50.789 12050 12050 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr" referenced by "/data/app/net.playwithworld.yahtzee.dice-1/lib/arm/libgdx.so"...
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	at com.badlogic.gdx.utils.ae.b(SharedLibraryLoader.java:118)
02-01 02:28:50.789 12050 12050 E AndroidRuntime: 	... 14 more
02-01 02:28:50.791   610  1210 W ActivityManager:   Force finishing activity net.playwithworld.yahtzee.dice/net.playwithworld.yatzy.dice.AndroidLauncher
```

#### Please select the affected platforms
- [*] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
