### ISSUE TITLE
[JSON] Error parsing json that contains brackets in strings

### ISSUE THREAD

**Issue by RUSshy** [libgdx/libgdx#4594]
Please ensure you have given all the following requested information in your report.

#### Issue details
Can't parse a json with brackets in strings like this: 

```kotlin
JsonReader().parse(Gdx.files.internal("data/json/strings.json"))
```

```json
{
  "AbilityBar.levelLabel": "Lvl. {level}",
}
```

#### Reproduction steps/code
Try to parse the json code above

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
Exception in thread "main" com.badlogic.gdx.utils.SerializationException: Error parsing file: data/json/strings.json
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:77)
	at com.rus.game.managers.DataManager.init(DataManager.kt:110)
	at com.rus.game.MyRPG.create(MyRPG.kt:51)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:419)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:367)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:136)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
	at com.rus.game.desktop.DesktopLauncher.main(DesktopLauncher.kt:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line 2 near: ﻿{
  *ERROR*"AbilityBar.levelLabel": "Lvl. {level}",
  "AccountInfo.guest":
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:549)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:55)
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:75)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
That supplied json string parses just fine.

**Comment by RUSshy** [comment]
This is weird 0o, i tried again with that shrinked json, and still crash

**Comment by Tom-Ski** [comment]
Your stack trace includes other parts of the json that you havent supplied. Please provide the whole json that you are using to reproduce your issue.

**Comment by RUSshy** [comment]
i shared only the 1st line since that's where it crash, but here is full one:

```json
{
  "AbilityBar.levelLabel": "Lvl. {level}",
  "AccountInfo.guest": "guest account",
  "AccountInfo.log_in": "log in",
  "AccountInfo.log_out": "log out",
  "AccountInfo.loggedIn": "logged in as {userName}",
  "AccountInfo.register": "register"
}
```

**Comment by Tom-Ski** [comment]
Can't reproduce. Please supply a full self contained executable example as the issue template asks for, and also fill out versions you are using. Please reopen when you have done this.

**Comment by RUSshy** [comment]
ill setup test repo to see if it crash

**Comment by Tom-Ski** [comment]
You don't need a whole repo, just a fully self contained ApplicationListener/Adapater

**Comment by RUSshy** [comment]
ohhh, i know what was wrong, i created a new file and copy paste the content and it works!

i was file encoding issue :)
