### ISSUE TITLE
new Texture(pixmap) crashes if I use pixels.put(someByte) on the pixels ByteBuffer of the pixmap

### ISSUE THREAD

**Issue by PeterStampfli** [libgdx/libgdx#4610]
If I use pixels.put(someByte) on the ByteBuffer of a pixmap, then the new Texture(pixmap) command crashes. 

        gdxVersion = '1.9.4'

Sample code:

public class Test extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;
	
	@Override
	public void create () {
		batch = new SpriteBatch();
		byte b=(byte) 100;
		Pixmap pixmap=new Pixmap(64,64, Pixmap.Format.RGBA8888);
		ByteBuffer pixels=pixmap.getPixels();
		pixels.put(0,b);
		pixels.put(b);                                 // this makes problems, no crash if out-commented

		img=new Texture(pixmap);
		pixmap.dispose();
	}
...

The error message is

Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Number of remaining buffer elements is 16383, must be at least 16384. Because at most 16384 elements can be returned, a buffer with at least 16384 elements is required, regardless of actual returned element count
	at org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162)
	at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189)
	at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:230)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:2855)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glTexImage2D(LwjglGL20.java:600)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:217)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:181)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:137)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:125)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:120)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:104)
	at com.mygdx.game.Test.create(Test.java:25)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

Obviously, it is the desktop app.

The pixmap.get(); command creates the same problem.

It would be nice to be able to use the pixmap.put(data)-command without index for setting the components of a color. Instead, I can use pixmap.put(i++,data) to get around.

Thanks for your great work, yours sincerely

Peter Stampfli

**Comment by xoppa** [comment]
The exception message looks very clear to me. Anyways, please use the forum or irc for personal support requests. https://github.com/libgdx/libgdx/wiki/Issue-Tracker

**Comment by Frosty-J** [comment]
Thanks for your issue. I had a similar problem but was getting a native crash instead of stack trace. `pixels.rewind()` before creating the texture fixed it.
