### ISSUE TITLE
UI SplitPane error

### ISSUE THREAD

**Issue by xpenatan** [libgdx/libgdx#4642]
@NathanSweet 

#### Issue details
New changes to Splitpane#removeActor   throw UnsupportedOperationException

#### Reproduction steps/code
Execute UITest

#### Version of LibGDX and/or relevant dependencies
1.9.7 Snapshot   #8adcb61
#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.UnsupportedOperationException: Use ScrollPane#setWidget(null).
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.removeActor(SplitPane.java:314)
	at com.badlogic.gdx.scenes.scene2d.Group.removeActor(Group.java:321)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.setFirstWidget(SplitPane.java:283)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.<init>(SplitPane.java:74)
	at com.badlogic.gdx.scenes.scene2d.ui.SplitPane.<init>(SplitPane.java:64)
	at com.badlogic.gdx.tests.UITest.create(UITest.java:125)
```

#### Please select the affected platforms
- [X] Android
- [X] iOS (robovm)
- [X] iOS (MOE)
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [X] MacOS

**Comment by cypherdare** [comment]
This was fixed in 005499197a1e5f699e82dbff1b17068f2639797c
