### ISSUE TITLE
Android-crash:ConcurrentModificationException happened when AndroidFragmentApplication.onPause

### ISSUE THREAD

**Issue by qjoy** [libgdx/libgdx#4709]
#### Issue details
Crash about ConcurrentModificationException happened when AndroidFragmentApplication.onPause

#### Version of LibGDX and/or relevant dependencies
    compile "com.badlogicgames.gdx:gdx-backend-android:1.9.3"
    natives "com.badlogicgames.gdx:gdx-platform:1.9.3:natives-armeabi-v7a"
    compile "com.badlogicgames.gdx:gdx-box2d:1.9.3"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:1.9.3:natives-armeabi-v7a"

#### Stacktrace
```
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
	at com.badlogic.gdx.graphics.Texture.getManagedStatus(Texture.java:285)
	at com.badlogic.gdx.backends.android.AndroidGraphics.logManagedCachesStatus(AndroidGraphics.java:541)
	at com.badlogic.gdx.backends.android.AndroidGraphics.clearManagedCaches(AndroidGraphics.java:536)
	at com.badlogic.gdx.backends.android.AndroidFragmentApplication.onPause(AndroidFragmentApplication.java:228)
	at com.youku.laifeng.lfspecialeffect.libgdxwidget.widget.liveroomLibGDXFragment.onPause(liveroomLibGDXFragment.java:328)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1161)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2163)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2255)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1161)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2163)
	at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:446)
	at com.youku.laifeng.module.room.livehouse.activity.ViewerLiveHouseActivity.onPause(ViewerLiveHouseActivity.java:98)
	at android.app.Activity.performPause(Activity.java:6194)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1319)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3356)
```

#### Please select the affected platforms
- [x] Android

**Comment by qjoy** [comment]
The param 'managedTextures' of com.badlogic.gdx.graphics.Texture is not Thread-safe. I create a Texutre in a Work-Thread, Maybe this cause the crash?

**Comment by Tom-Ski** [comment]
LibGDX is not thread safe unless specific api states so.  If you think there is an issue still, please fill in the issue template completely and supply a test case.
