### ISSUE TITLE
Couldn't load shared library 'gdx' for target: Linux, 32-bit

### ISSUE THREAD

**Issue by dherediat97** [libgdx/libgdx#4750]
#### Issue details
When GameFragment is created throw exception. I am using Android Studio with libgdx dependencies in gradle project.
```
super.onCreate(savedInstanceState);
GameFragment fragment = new GameFragment(); //Here Break the App
FragmentTransaction trans = getSupportFragmentManager().beginTransaction();
trans.replace(android.R.id.content, fragment);
trans.commit();
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
```java
java.lang.ExceptionInInitializerError  at breaktherules.dherediat97.musiclegends.vista.AndroidLauncher.onCreate(AndroidLauncher.java:19)
                                                                                            at android.app.Activity.performCreate(Activity.java:5241)      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2194)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:143)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5124)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                                         Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
                                                                                            at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:124)
                                                                                            at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
                                                                                            at com.badlogic.gdx.backends.android.AndroidFragmentApplication.<clinit>(AndroidFragmentApplication.java:54)
                                                                                            at breaktherules.dherediat97.musiclegends.vista.AndroidLauncher.onCreate(AndroidLauncher.java:19) 
                                                                                            at android.app.Activity.performCreate(Activity.java:5241) 
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2194) 
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279) 
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:143) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5124) 
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613) 
                                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                                         Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gdx from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/breaktherules.dherediat97.musiclegends-1.apk", zip file "/data/data/breaktherules.dherediat97.musiclegends/code_cache/secondary-dexes/breaktherules.dherediat97.musiclegends-1.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/breaktherules.dherediat97.musiclegends-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                                            at java.lang.System.loadLibrary(System.java:526)
                                                                                            at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
                                                                                            at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33) 
                                                                                            at com.badlogic.gdx.backends.android.AndroidFragmentApplication.<clinit>(AndroidFragmentApplication.java:54) 
                                                                                            at breaktherules.dherediat97.musiclegends.vista.AndroidLauncher.onCreate(AndroidLauncher.java:19) 
                                                                                            at android.app.Activity.performCreate(Activity.java:5241) 
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2194) 
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279) 
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:143) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5124) 
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] HTML/GWT
- [ ] iOS (MOE)
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by tpnet** [comment]
@dherediat97  How to solve it?

**Comment by rockbass2560** [comment]
I have the same problem
