### ISSUE TITLE
AndroidInput NullPointerException

### ISSUE THREAD

**Issue by jovezhougang** [libgdx/libgdx#4754]
java.lang.NullPointerException: Attempt to write to field 'boolean com.badlogic.gdx.backends.android.AndroidInput.keyboardAvailable' on a null object reference
	at com.badlogic.gdx.backends.android.AndroidApplication.onConfigurationChanged(AndroidApplication.java)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4909)
	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:4814)
	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5045)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
