### ISSUE TITLE
HTTP request fails with https URL in iOS - SSLHandshakeException

### ISSUE THREAD

**Issue by flaviohaueisen** [libgdx/libgdx#4766]
#### Issue details
I'm trying to use Facebook Graph API like https://graph.facebook.com/v2.9/me
but it always fails in iOS

#### Reproduction steps/code
```java
private void requestData(String url) {
    if (url != null) {
        Net.HttpRequest httpRequest;
        String httpMethod = Net.HttpMethods.GET;
        httpRequest = new Net.HttpRequest(httpMethod);
        httpRequest.setUrl(url);
        httpRequest.setContent(null);
        Gdx.net.sendHttpRequest(httpRequest, this);
    }
}
```
#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.6
MOE 1.3.0

#### Stacktrace
```java
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:344)
	at com.android.okhttp.Connection.connectTls(Connection.java:235)
	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
	at com.android.okhttp.Connection.connect(Connection.java:172)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:442)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:118)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
	at com.badlogic.gdx.net.NetJavaImpl$1.call(NetJavaImpl.java:197)
	at com.badlogic.gdx.net.NetJavaImpl$1.call(NetJavaImpl.java:169)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:120)
	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:572)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:340)
	... 18 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 24 more
```

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [x] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by winghim** [comment]
That looks like an Android stacktrace.

**Comment by flaviohaueisen** [comment]
@winghim MOE is based on ART thats why it looks like a Android stacktrace
Found a fix here: https://discuss.multi-os-engine.org/t/cant-download-file-from-https/508/10
