### ISSUE TITLE
GLIBC 2.11 dependency

### ISSUE THREAD

**Issue by dveyarangi** [libgdx/libgdx#4773]
Hello,

#### Issue details

I have been trying to install libgdx-based application distribution at a linux system. It seems that it requires glibc version 2.11 to be already installed at the target os... Question is, isn't this dependency supposed to come with libgdx natives, since if provide installer for my game, I cannot expect the user to already have this version of glibc, or to force him to install it.
In my case (and I suppose, in many other cases), the user might have his own considerations about what linux libraries he has in his system. Shouldn't libGDX natives jar contain the required dependencies? Or am I missing something.

In case that current state of things is forcing the user to install some specific version of glibc, where can I see the entire package dependencies tree for it? Unfortunately, my user does not have internet connection on his machine, so he cannot download it via package manager...

Thanks!

#### Reproduction steps/code
To reproduce, run libgdx application in RedHat/CentOS with glibc version lower than 2.11. I've tried this in CentOS 5.8.

#### Version of LibGDX and/or relevant dependencies
1.7.1

#### Stacktrace
```java
java.lang.UnsatisfiedLinkError: /tmp/libgdxroot/6ef2d459/libgdx64.so: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /tmp/libgdxroot/6ef2d459/libgdx64.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:328)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:297)
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:130)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadNatives(GdxRCPLibraryLoader.java:63)
        at midas.visual.libgdx.GdxRasterEngine.start(GdxRasterEngine.java:70)
        at midas.visual.VisualModule.load(VisualModule.java:85)
        at midas.core.resources.Resources.load(Resources.java:70)
        at midas.core.OrcBootstrap.start(OrcBootstrap.java:162)
        at midas.core.OrcBootstrap.run(OrcBootstrap.java:121)
        at meteo.Main.main(Main.java:9)
java.lang.UnsatisfiedLinkError: /tmp/6ef2d4597754381420438804597.tmp: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /tmp/6ef2d4597754381420438804597.tmp)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:328)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:303)
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:130)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadNatives(GdxRCPLibraryLoader.java:63)
        at midas.visual.libgdx.GdxRasterEngine.start(GdxRasterEngine.java:70)
        at midas.visual.VisualModule.load(VisualModule.java:85)
        at midas.core.resources.Resources.load(Resources.java:70)
        at midas.core.OrcBootstrap.start(OrcBootstrap.java:162)
        at midas.core.OrcBootstrap.run(OrcBootstrap.java:121)
        at meteo.Main.main(Main.java:9)
java.lang.UnsatisfiedLinkError: /root/.libgdx/6ef2d459/libgdx64.so: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /root/.libgdx/6ef2d459/libgdx64.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:328)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:309)
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:130)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadNatives(GdxRCPLibraryLoader.java:63)
        at midas.visual.libgdx.GdxRasterEngine.start(GdxRasterEngine.java:70)
        at midas.visual.VisualModule.load(VisualModule.java:85)
        at midas.core.resources.Resources.load(Resources.java:70)
        at midas.core.OrcBootstrap.start(OrcBootstrap.java:162)
        at midas.core.OrcBootstrap.run(OrcBootstrap.java:121)
        at meteo.Main.main(Main.java:9)
java.lang.UnsatisfiedLinkError: /root/Desktop/MiDAS/meteo.ducts.process-1.0/.temp/6ef2d459/libgdx64.so: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /root/Desktop/MiDAS/meteo.ducts.process-1.0/.temp/6ef2d459/libgdx64.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:328)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:313)
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:130)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadNatives(GdxRCPLibraryLoader.java:63)
        at midas.visual.libgdx.GdxRasterEngine.start(GdxRasterEngine.java:70)
        at midas.visual.VisualModule.load(VisualModule.java:85)
        at midas.core.resources.Resources.load(Resources.java:70)
        at midas.core.OrcBootstrap.start(OrcBootstrap.java:162)
        at midas.core.OrcBootstrap.run(OrcBootstrap.java:121)
        at meteo.Main.main(Main.java:9)
Exception in thread "MiDAS bootstrap" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:132)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadNatives(GdxRCPLibraryLoader.java:63)
        at midas.visual.libgdx.GdxRasterEngine.start(GdxRasterEngine.java:70)
        at midas.visual.VisualModule.load(VisualModule.java:85)
        at midas.core.resources.Resources.load(Resources.java:70)
        at midas.core.OrcBootstrap.start(OrcBootstrap.java:162)
        at midas.core.OrcBootstrap.run(OrcBootstrap.java:121)
        at meteo.Main.main(Main.java:9)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /tmp/libgdxroot/6ef2d459/libgdx64.so: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /tmp/libgdxroot/6ef2d459/libgdx64.so)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:322)
        at midas.visual.libgdx.GdxRCPLibraryLoader.load(GdxRCPLibraryLoader.java:130)
        ... 7 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libgdxroot/6ef2d459/libgdx64.so: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by /tmp/libgdxroot/6ef2d459/libgdx64.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:328)
        at midas.visual.libgdx.GdxRCPLibraryLoader.loadFile(GdxRCPLibraryLoader.java:297)
        ... 8 more

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
I don't know what you are using, but its not LibGDX, nothing we can do for this.

**Comment by dveyarangi** [comment]
I have wrote my own Eclipse RCP backend, this is true, but there are clearly dependencies on glibc from the libgdx.so...

**Comment by dveyarangi** [comment]
I have wrote my own Eclipse RCP backend, this is true, but there are clearly dependencies on glibc from the libgdx.so, the issue is not relevant to how I bootstrap the LibGDX

**Comment by Tom-Ski** [comment]
If you can provide a pure libgdx example that reproduces your issue please feel free to reopen an issue with the relevant details, otherwise we can't access anything, or attempt to reproduce with proprietary software.

**Comment by dveyarangi** [comment]
Sure you can reproduce it, by running gdx application on linux with glibc version lower than 2.11. What you asking for is a formality, does libgdx.so not depend on glibc?

**Comment by intrigus** [comment]
Disassembling the binary gives us this:
libgdx64.so:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000005c70 l    d  .init	0000000000000000              .init
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memset
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 ftell
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memcpy
**0000000000000000      DF *UND*	0000000000000000  GLIBC_2.11  __longjmp_chk**

So we have a dependency on glibc 2.11 which seems to be caused by FORTIFY_SOURCE as seen in this answer: https://stackoverflow.com/questions/27227271/elf-weak-import-fallback-stubs-for-glibc-functions
