### ISSUE TITLE
Mesh.java .copy() function tries to pass 'null' value to IndexBufferObject .setIndices() function when Mesh has zero indices.

### ISSUE THREAD

**Issue by libbyJix** [libgdx/libgdx#4775]
#### Issue details
Create a non-indexed Mesh (pass '0' for numIndices) and try to copy that Mesh using Mesh.java's .copy() function a NullPointerException is thrown.

#### Reproduction steps/code
```
public class MyMeshTest extends ApplicationAdapter{
   ModelInstance modelInstance;
   private ModelBatch modelBatch;
   private Camera camera;
   
   @Override
   public void create () {
      //pass in '0' for numIndices because I don't want to index the Mesh
      Mesh m = new Mesh(false, 3, 0, new VertexAttribute( VertexAttributes.Usage.Position, 3, "3_vec" ));
      m.setVertices(new float[]{1,2,3, 2,3,4, 3,3,9});
      m.copy(false);
   }

   @Override
   public void render () {
      Gdx.gl.glClearColor(1, 0, 0, 1);
      Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
   }
   
   @Override
   public void dispose () {
      modelBatch.dispose();
   }
}

```
#### Version of LibGDX and/or relevant dependencies
LibGDX version: 1.9.6
Backend: LWJGL Desktop Configuration

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
at com.badlogic.gdx.graphics.Mesh.setIndices(Mesh.java:271)
at com.badlogic.gdx.graphics.Mesh.copy(Mesh.java:1084)
at com.badlogic.gdx.graphics.Mesh.copy(Mesh.java:1092)
at com.mygdx.meshtest.MyMeshTest.create(MyMeshTest.java:40)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Thanks for the report.
