### ISSUE TITLE
AssetManager fails to load different dependencies with same file name

### ISSUE THREAD

**Issue by winniehell** [libgdx/libgdx#4795]
#### Issue details

When resolving dependencies, `AssetManager` only distinguishes by file name and not by type. This leads to dependencies with same file name but different type not being loaded.

#### Reproduction steps/code

- create custom `AsynchronousAssetLoader`
- add two dependencies with same file name but different type

I have created an example that demonstrates the bug [here](https://github.com/winniehell/libgdx-duplicate-dependency-filename/blob/master/core/src/de/winniehell/libgdx/duplicatedependencyfilename/DuplicateDependencyFileName.java).

#### Version of LibGDX
1.9.6

#### Stacktrace
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: ingredient
	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:148)
	at de.winniehell.libgdx.duplicatedependencyfilename.DuplicateDependencyFileName.create(DuplicateDependencyFileName.java:111)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

This happens when accessing the [Pear dependency](https://github.com/winniehell/libgdx-duplicate-dependency-filename/blob/master/core/src/de/winniehell/libgdx/duplicatedependencyfilename/DuplicateDependencyFileName.java#L111) which should have been loaded [here](https://github.com/winniehell/libgdx-duplicate-dependency-filename/blob/master/core/src/de/winniehell/libgdx/duplicatedependencyfilename/DuplicateDependencyFileName.java#L93).

#### Please select the affected platforms
All, but tested only on

- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

#### Probable cause

I think the bug was introduced by 14ac0c9639880a10c50c85e83236351cd996c986. [This line](https://github.com/libgdx/libgdx/commit/14ac0c9639880a10c50c85e83236351cd996c986#diff-f4157411d9517868c26e594fec9cf3f4R385) only checks the file name and not the type.

**Comment by winniehell** [comment]
@NathanSweet Could you have a look please? I would be happy to create a bug fix if my guess is right about the cause.

**Comment by NathanSweet** [comment]
AssetManager is a beast. It [appears](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/assets/AssetManager.java#L132) that it expects every asset to have a unique file name. Assets are identified by their file name in many places, eg `unload`, `getReferenceCount` and other methods. I do see some methods that take both a file name and a type, but the lack of consistency is confusing.
