### ISSUE TITLE
 Json: /*ERROR*home/

### ISSUE THREAD

**Issue by egordorichev** [libgdx/libgdx#4796]
Hey! I've moved my games save folder from game location to ~/.LastTry:
And now this code, that worked OK, fails:

```
JsonValue root = jsonReader.parse(System.getProperty("user.home") + "/.LastTry/data/items.json");
```

```

com.badlogic.gdx.utils.SerializationException: Error parsing JSON on line 1 near: /*ERROR*home/egor/.LastTry/data/items.json
	at com.badlogic.gdx.utils.JsonReader.parse(JsonReader.java:549)
	at org.egordorichev.lasttry.item.Items.load(Items.java:30)
	at org.egordorichev.lasttry.core.Bootstrap.load(Bootstrap.java:29)
	at org.egordorichev.lasttry.state.LoadState$1$1.run(LoadState.java:27)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:259)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:210)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

Json file is fully valid and accessible. I'm on linux.

**Comment by intrigus** [comment]
Please don't defeat the issue template and provide at least an http://sscce.org/.

**Comment by egordorichev** [comment]
```
import com.badlogic.gdx.utils.JsonReader;
import com.badlogic.gdx.utils.JsonValue;

public class Main {
	public static final void main(String[] args) {
		JsonReader jsonReader = new JsonReader();
		JsonValue root = jsonReader.parse(System.getProperty("user.home") + "/.LastTry/data/items.json");
	}
}
```

```
{
	"lt:dirt" : {
		"type" : "org.egordorichev.lasttry.item.block.BlockGround"
	},

	"lt:grass" : {
		"type" : "org.egordorichev.lasttry.item.block.plant.Grass",
		"spreads" : [ "lt:dirt" ]
	},

	"lt:copper_coin" : {
		"type" : "org.egordorichev.lasttry.item.items.Coin",
		"cost" : 1
	},

	"lt:silver_coin" : {
		"type" : "org.egordorichev.lasttry.item.items.Coin",
		"cost" : 100
	},

	"lt:gold_coin" : {
		"type" : "org.egordorichev.lasttry.item.items.Coin",
		"cost" : 10000
	},

	"lt:platinum_coin" : {
		"type" : "org.egordorichev.lasttry.item.items.Coin",
		"cost" : 1000000
	},

	"lt:copper_pickaxe" : {
		"type" : "org.egordorichev.lasttry.item.items.Pickaxe",
		"speed" : 22,
		"damage" : 4,
		"power" : [ 35, 0, 0 ]
	},

	"lt:superpick" : {
		"type" : "org.egordorichev.lasttry.item.items.Pickaxe",
		"speed" : 4,
		"damage" : 100,
		"unobtainable" : true,
		"power" : [ 255, 255, 255 ]
	},

	"lt:copper_axe" : {
		"type" : "org.egordorichev.lasttry.item.items.Axe",
		"speed" : 22,
		"damage" : 3,
		"power" : [ 0, 35, 0 ]
	},

	"lt:copper_shortsword" : {
		"type" : "org.egordorichev.lasttry.item.items.ShortSword",
		"speed" : 22,
		"damage" : 5
	},

	"lt:magic_mirrow" : {
		"type" : "org.egordorichev.lasttry.item.items.MagicMirrow",
		"speed" : 20
	},

	"lt:stone" : {
		"type" : "org.egordorichev.lasttry.item.block.Block"
	},

	"lt:workbench" : {
		"type" : "org.egordorichev.lasttry.item.block.station.Workbench",
		"size" : [ 2, 1 ]
	},

	"lt:furnace" : {
		"type" : "org.egordorichev.lasttry.item.block.station.Furnace",
		"size" : [ 3, 2 ],
		"level" : 0
	},

	"lt:anvil" : {
		"type" : "org.egordorichev.lasttry.item.block.station.Anvil",
		"size" : [ 2, 1 ],
		"level" : 0
	},

	"lt:copper_ore" : {
		"type" : "org.egordorichev.lasttry.item.items.Ore"
	},

	"lt:iron_ore" : {
		"type" : "org.egordorichev.lasttry.item.items.Ore"
	},

	"lt:silver_ore" : {
		"type" : "org.egordorichev.lasttry.item.items.Ore"
	},

	"lt:gold_ore" : {
		"type" : "org.egordorichev.lasttry.item.items.Ore"
	},

	"lt:copper_bar" : {
		"type" : "org.egordorichev.lasttry.item.items.Bar"
	},

	"lt:iron_bar" : {
		"type" : "org.egordorichev.lasttry.item.items.Bar"
	},

	"lt:silver_bar" : {
		"type" : "org.egordorichev.lasttry.item.items.Bar"
	},

	"lt:gold_bar" : {
		"type" : "org.egordorichev.lasttry.item.items.Bar"
	},

	"lt:chest" : {
		"type" : "org.egordorichev.lasttry.item.block.Chest",
		"size" : [ 2, 2 ]
	},

	"lt:sand" : {
		"type" : "org.egordorichev.lasttry.item.block.TileableBlock"
	},

	"lt:ebonstone" : {
		"type" : "org.egordorichev.lasttry.item.block.EvilBlock"
	},

	"lt:ebonsand" : {
		"type" : "org.egordorichev.lasttry.item.block.EvilBlock"
	},

	"lt:crimstone" : {
		"type" : "org.egordorichev.lasttry.item.block.EvilBlock"
	},

	"lt:crimsand" : {
		"type" : "org.egordorichev.lasttry.item.block.EvilBlock"
	},

	"lt:ash" : {
		"type" : "org.egordorichev.lasttry.item.block.TileableBlock"
	},

	"lt:mud" : {
		"type" : "org.egordorichev.lasttry.item.block.TileableBlock"
	},

	"lt:snow" : {
		"type" : "org.egordorichev.lasttry.item.block.TileableBlock"
	},

	"lt:ice" : {
		"type" : "org.egordorichev.lasttry.item.block.TileableBlock"
	},

	"lt:gel" : {
		"type" : "org.egordorichev.lasttry.item.Item"
	},

	"lt:dirt_wall" : {
		"type" : "org.egordorichev.lasttry.item.wall.Wall"
	},

	"lt:chunk_loader" : {
		"type" : "org.egordorichev.lasttry.item.block.ChunkLoader"
	}
}
```

**Comment by intrigus** [comment]
You're passing `home/egor/.LastTry/data/items.json`as a String to `JsonReader.parse(String json)`
which will obviously fail, since it's no valid json.

You issue seems to be no libgdx issue, so please use the forums or irc.

**Comment by egordorichev** [comment]
Oh, im so sorry.
