### ISSUE TITLE
UBJsonWriter can output short[] but UBJsonReader 'oldFormat' default causes unhelpful error message

### ISSUE THREAD

**Issue by libbyJix** [libgdx/libgdx#4799]
#### Issue details
Use UBJsonWriter to write a short[] and then any other kind of data after. Reading back this data with UBJsonReader will result in a "Unrecognized data type, string expected" error though that is not the actual problem and leaves the user without any hint of what has gone wrong. The underlying problem is that the default state ('oldFormat' field set to 'true') of UBJsonReader treats short values as integers and thus over-reads data which leads to the parse() function breaking. This can be seen if only a short[] is written using UBJsonWriter; trying to read it back leads to an EOFException unless 'oldFormat' is set to false. To solve this mismatch between UBJsonWriter and UBJsonReader perhaps there can be a 'useOldFormat' boolean in the UBJsonWriter constructor that, if set to true (defaults to true?), internally converts and writes Shorts as Ints? This would prevent the error and it would alert a user of the two classes of this inter-dependency. This is, of course, only a suggestion without knowing all the background of what went into the code being this way; whatever lets users know what's going on here is the idea. Just trying to save someone else hours of debugging ;) Thanks for your time.

#### Reproduction steps/code
```
public class UBJsonReadWriteTest implements ApplicationListener {

	@Override
	public void create () {
		try{
			UBJsonWriter writer = new UBJsonWriter( new FileOutputStream("test.bin") );
			writer.object();
			writer.set("shortArray", new short[]{1,2,3});
                        //comment out following line to see EOFException
			writer.set("stringArray", new String[]{"dog", "hat", "run"});
			writer.pop();
			writer.close();

		}catch(FileNotFoundException fnf){}catch(IOException ioe){}
		UBJsonReader reader = new UBJsonReader();
		//reader.oldFormat = false;
		reader.parse(Gdx.files.getFileHandle("test.bin", Files.FileType.Internal));
	}
	@Override
	public void render () {}
	@Override
	public void dispose () {}
	@Override
	public void resume(){}
	@Override
	public void pause(){}
	@Override
	public void resize(int x, int y){}
}
```

#### Version of LibGDX and/or relevant dependencies
LibGDX version: 1.9.6
Back-end: LWJGL3 Desktop Configuration

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error parsing file: test.bin
	at com.badlogic.gdx.utils.UBJsonReader.parse(UBJsonReader.java:56)
	at com.mygdx.meshtest.UBJsonReadWriteTest.create(UBJsonReadWriteTest.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unrecognized data type, string expected
	at com.badlogic.gdx.utils.UBJsonReader.parseString(UBJsonReader.java:210)
	at com.badlogic.gdx.utils.UBJsonReader.parseObject(UBJsonReader.java:158)
	at com.badlogic.gdx.utils.UBJsonReader.parse(UBJsonReader.java:72)
	at com.badlogic.gdx.utils.UBJsonReader.parse(UBJsonReader.java:62)
	at com.badlogic.gdx.utils.UBJsonReader.parse(UBJsonReader.java:43)
	at com.badlogic.gdx.utils.UBJsonReader.parse(UBJsonReader.java:54)
	... 3 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment]
If `UBJsonWriter` cannot write the old format, then then the default should probably be to not read using the old format. The old format is likely no longer relevant so we probably can remove support for it (that change was made about 4 years ago according to the history).

**Comment by libbyJix** [comment]
Ok, that's helpful to know. Thanks.
