### ISSUE TITLE
HTTPS support not working

### ISSUE THREAD

**Issue by Queatz** [libgdx/libgdx#4816]
#### Issue details
Unable to perform HTTPS request with gdx 1.9.6 and Java 1.8.

#### Reproduction steps/code
```java
        Net.HttpRequest get = new HttpRequestBuilder()
                .newRequest()
                .method(Net.HttpMethods.GET)
                .url("https://*************")
                .followRedirects(true)
                .header("Content-Type", "application/json")
                .includeCredentials(true)
                .build();

        Gdx.net.sendHttpRequest(get, listener);
```

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
```java
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.badlogic.gdx.net.NetJavaImpl$1.call(NetJavaImpl.java:197)
	at com.badlogic.gdx.net.NetJavaImpl$1.call(NetJavaImpl.java:169)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	... 17 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 23 more

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
You are probably going to have to manually add the certificate to the trusted certs. What is the endpoint you are targeting?

**Comment by Queatz** [comment]
@Tom-Ski Yes, I was able to make it work using Apache's

```java
HttpAsyncClients.custom()
                .setSSLContext(SSLContextBuilder.create().loadTrustMaterial(new TrustSelfSignedStrategy()).build())
                .setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE)
                .build();
```

Is there an equivalent with `sendHttpRequest`?

**Comment by Queatz** [comment]
I'm targeting my own game server signed with a valid cert from Letsencrypt

`https://scatteredage.com:8443/purchase/abcdef`

**Comment by Tom-Ski** [comment]
What version of java 8 are you using?

**Comment by Queatz** [comment]
Maybe because I'm using OpenJDK?
```
jacob@debian:~$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by Tom-Ski** [comment]
You are missing a full certificate chain in your backend. You'll need to add the root and intermediate certificate also to your apache server.

**Comment by Lucrecious** [comment]
I don't understand, how do I fix this? Could someone explain?
