### ISSUE TITLE
OGG buffer crash

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#4820]
#### Issue details
Crash when loading some .ogg files as Sounds on Windows 10 using 1.9.7-SNAPSHOT. Seems to be related to commits https://github.com/libgdx/libgdx/commit/a6ccb776f3d5994c4e8711b209e164f621a5bbe4, https://github.com/libgdx/libgdx/commit/578dfe2a2cb54c06e930ca0f3caf1da4eb418be5 since it's a project I work regularly work with and has just started crashing.

**Edit**: It fails for Ogg file sizes larger than around 10KB (5KB loads, 15KB doesn't). The buffer size needs to be much larger (similar to what it was previous to the commits) not to limit the maximum file size.

**Edit 2** **To take advatage of this optimization for OGG Music without breaking larger OGG sound loading, the buffer size could depend on the file size if sounds are loaded.**
@NathanSweet What do you think, I can work on a PR for this 

#### Reproduction steps/code
Try to load this OGG file https://drive.google.com/open?id=0ByyxXkY-N0Vmcm5vWmtKZWlRckk as a Sound.

#### Version of LibGDX and/or relevant dependencies
1.9.7-SNAPSHOT

#### Stacktrace
```java
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: sounds/gamestart.ogg
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:121)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:504)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:378)
	... 5 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Error creating sound com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound for file: sounds/gamestart.ogg
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:119)
	... 8 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Error creating sound com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound for file: sounds/gamestart.ogg
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:119)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:41)
	at com.badlogic.gdx.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:48)
	at com.badlogic.gdx.assets.loaders.SoundLoader.loadAsync(SoundLoader.java:29)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:70)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.newSound(OpenALAudio.java:117)
	... 10 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Ogg block too big to be buffered: 1024, 0
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.readPCM(OggInputStream.java:371)
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.read(OggInputStream.java:435)
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.read(OggInputStream.java:453)
	at com.badlogic.gdx.backends.lwjgl.audio.OggInputStream.read(OggInputStream.java:465)
	at com.badlogic.gdx.backends.lwjgl.audio.Ogg$Sound.<init>(Ogg.java:70)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
Sorry for the delay. It used to allocate a 4096 * 500 = 2MB buffer, which seems crazy. OggInputStream should read the OGG in chunks and not require such a large buffer. Probably we should rewrite the class. Want to give that a try? Otherwise I guess we can increase the buffer size until that can be done.

**Comment by obigu** [comment]
Correct me if I'm wrong but as far as I know Sound must be fully read in memory (unlike Music). To do that we need a buffer that can contain the whole file. OpenALSound creates a ByteBuffer the size of the byte array it receives as an argument in the setup() method which, in the Ogg extension case is the byte array containing the whole decoded file read in Ogg.Sound. The 2MB buffer is probably an overkill for the usual Ogg file sizes but we should probably not limit Ogg Sounds to several KB. I'm not familiar on how ByteBuffer handles allocation but in case it allocates its whole capacity I was suggesting to create a different ByteBuffer (or byte array). I'll have a look and see what I can come up with.

**Comment by obigu** [comment]
Haven't had the time to look at this yet but until somebody does I think we should revert to the previous OggInputStream.

**Comment by NathanSweet** [comment]
I'll revert, but we should really fix OggInputStream. It should actually stream, not buffer the entire decoded audio!
