### ISSUE TITLE
Shaders just crash on Linux

### ISSUE THREAD

**Issue by monkeymanboy** [libgdx/libgdx#4834]
Please ensure you have given all the following requested information in your report.

#### Issue details
_Please provide the details of your issue_
When a shader gets run on linux it doesn't let uniforms be passed to the shader which prevents it from working and pedantic can be set to false but then the shader just does nothing

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_
Just run any shader on linux

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
1.9.7-SNAPSHOT

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: no uniform with name 'u_projTrans' in shader
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:308)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:298)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:528)
    at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:519)
    at com.badlogic.gdx.graphics.g2d.SpriteBatch.setupMatrices(SpriteBatch.java:1045)
    at com.badlogic.gdx.graphics.g2d.SpriteBatch.setShader(SpriteBatch.java:1075)
    at com.monkeymanboy.screens.SplashScreen.render(SplashScreen.java:32)
    at com.badlogic.gdx.Game.render(Game.java:46)
    at com.monkeymanboy.Main.render(Main.java:98)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ x] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
It actually happens when you have shader compilation errors, you can try this : 

```
ShaderProgram shader = new ShaderProgram(vertFile, fragFile);
if(!shader.isCompiled()) throw new GdxRuntimeException(shader.getLog());
```

IMO this kind of check could be done in ShaderProgram to avoid confusion.

**Comment by monkeymanboy** [comment]
Yeah it seems to be I didn't convert an int to a float. I guess just a slight difference in opengl between linux and windows that made windows work fine but linux not. Anyways thanks for the help.

**Comment by mgsx-dev** [comment]
FYI difference in compilation depends on GPU driver, I recommend you to set a version in your GLSL code (first line of your code). For me it enable driver strict compilation. For instance :  `#version 100` for GLES2
