### ISSUE TITLE
Tooltips broken on Android

### ISSUE THREAD

**Issue by Dakror** [libgdx/libgdx#4924]
#### Issue details
Tooltips broken on Android. They do not show but cause an exception instead.
Also referenced in #4921 

#### Reproduction steps/code
Run the UITest on android (i used a Huawei P8, Android 5)

#### Version of LibGDX and/or relevant dependencies
1.9.6

#### Stacktrace
```java
10-12 18:23:17.610 571-761/com.badlogic.gdx.tests.android W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'com.badlogic.gdx.scenes.scene2d.Stage com.badlogic.gdx.scenes.scene2d.Actor.getStage()' on a null object reference
10-12 18:23:17.610 571-761/com.badlogic.gdx.tests.android W/System.err:     at com.badlogic.gdx.scenes.scene2d.ui.TooltipManager$2.run(TooltipManager.java:69)
10-12 18:23:17.610 571-761/com.badlogic.gdx.tests.android W/System.err:     at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:488)
10-12 18:23:17.610 571-761/com.badlogic.gdx.tests.android W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
10-12 18:23:17.610 571-761/com.badlogic.gdx.tests.android W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
I can't reproduce this on my device.  You are running the stock UITest?

**Comment by Dakror** [comment]
I'm running the stock UITest and when tapping on the Button "Multi Line Toggle" there should be a tooltip popping up, but instead an exception gets thrown.

**Comment by Tom-Ski** [comment]
Yeah, I can't reproduce this with your steps.  I'll try find another device to test on to see if i can it there. Otherwise, hopefully someone else can reproduce and test.

**Comment by Zomby2D** [comment]
I tried various phones and tablets with Android versions ranging from 4.1.2 to 7.1, and I can't reproduce the issue either. The tooltip always pops up correctly for me. (I tried with both USB and Bluetooth mices)

**Comment by Dakror** [comment]
No there are no other steps involved. I sadly do not have any other working phone around to pin point the issue to my device specifically. Huawei is involved in all kinds of weird Android bugs though

**Comment by JasonMacKeigan** [comment]
This same issue is occurring for me as well. Unfortunately I haven't been able to pinpoint the issue either. Tooltips are just simply not showing on Android. I'm using an Android Pixel XL with API 26.

**Comment by mobiuscog** [comment]
It's likely a race condition as TooltipManager isn't thread-safe - there are no synchronization / guard blocks.

**Comment by feifei889** [comment]
Never found this issue before.

**Comment by tookjacksuio** [comment]
> #### 发行细节
> 机器人上的工具提示。它们不显示，而是导致异常。也被引用在#4921
> 
> #### 再现步骤/代码
> 在Android上运行UITest(我使用了华为P8，Android 5)
> 
> #### LibGDX和/或相关依赖项的版本
> 1.9.6
> 
> #### 斯塔克迹
> ```java
> 10-12 18:23:17.610 571-761/COM.坏逻辑.GDX.试验.安卓W/系统.错误: Java.lang.NullPointerException: 尝试调用虚拟方法'Com.badlogic.gdx.aspes.scene2d.Stage com.badlogic.gdx.scenes.scene2d.Actor.getStage()'在.上零对象引用10-12 18:23:17.610 571-761/COM.坏逻辑.GDX.试验.安卓W/系统.错误:在…Com.badlogic.gdx.scenes.scene2d.ui.工具管理器$2.跑(工具管理器.爪哇:69)
> 10-12 18:23:17.610 571-761/COM.坏逻辑.GDX.试验.安卓W/系统.错误:在…Com.badlogic.gdx.backends.android.雄激素图形学.OnDrawFrame(雄激素图形学.爪哇:488)
> 10-12 18:23:17.610 571-761/COM.坏逻辑.GDX.试验.安卓W/系统.错误:在…Android.opengl.GLSurfaceView$GLThread.[医]Run(GLSurfaceView.爪哇:1531)
> 10-12 18:23:17.610 571-761/COM.坏逻辑.GDX.试验.安卓W/系统.错误:在…Android.opengl.GLSurfaceView$GLThread.跑(GLSurfaceView.爪哇:1248)
> ```
> 
> #### 请选择受影响的平台
> * [x] 安卓
> * [ ] IOS(机器人)
> * [ ] 监督办(教育部)
> * [ ] HTML/GWT
> * [ ] 窗
> * [ ] Linux
> * [ ] MacOS

love you

**Comment by tookjacksuio** [comment]
love you

**Comment by tookjacksuio** [comment]
mm
