### ISSUE TITLE
Got an error when start gdx-setup.jar

### ISSUE THREAD

**Issue by N01esh** [libgdx/libgdx#4952]
#### Issue details
When I run gdx-setup.jar I get an error (see in Stacktrace section).
I open cmd in Windows 10 and execute the folowing command:
java -jar gdx-setup.jar

#### Version of LibGDX and/or relevant dependencies
The latest version of file that I downloaded at 28.10.2017

#### Stacktrace
java.lang.IllegalArgumentException: InputStream cannot be null
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.initData(Unknown Source)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.uiLayout(Unknown Source)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$Form.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$UI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.main(Unknown Source)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.setup.GdxSetupUI$Form.uiLayout(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$Form.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$UI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: input == null!
        at javax.imageio.ImageIO.read(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$SetupCheckBox.getCheckboxImage(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$SetupCheckBox.<clinit>(Unknown Source)
        ... 5 more

#### Please select the affected platforms
- [ ] Windows

**Comment by Tom-Ski** [comment]
Version of java?

**Comment by MobiDevelop** [comment]
I don't think we're ever going to get the requested info.
