### ISSUE TITLE
File not found using relative path and classpath type

### ISSUE THREAD

**Issue by mgsx-dev** [libgdx/libgdx#4954]
#### Issue details
relative path doesn't work with classpath type. It works well with internal type but not when assets are in the final jar. 

#### Reproduction steps/code
load a skin containing a bitmap font with relative path : 
```
{
com.badlogic.gdx.graphics.g2d.BitmapFont: { 
	default-font: { file: ../fonts/game_font.fnt } 
}
```
Note : it will works for desktop when files are in an external folder but fails when files are inside the dist jar (loaded from classpath)

#### Version of LibGDX and/or relevant dependencies
1.9.6 with Lwjgl2 backend

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.SerializationException: Error reading file: skins/game-skin.json
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:579)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:380)
	at com.badlogic.gdx.assets.AssetManager.finishLoadingAsset(AssetManager.java:411)
	at net.mgsx.game.core.storage.EntityGroupStorage.loadNow(EntityGroupStorage.java:187)
	at net.mgsx.game.core.storage.EntityGroupStorage.loadForEditing(EntityGroupStorage.java:86)
	at net.mgsx.game.core.EditorApplication.loadWork(EditorApplication.java:113)
	at net.mgsx.game.core.EditorApplication.restoreWork(EditorApplication.java:98)
	at net.mgsx.game.core.EditorApplication.create(EditorApplication.java:59)
	at net.mgsx.examples.platformer.OpenWorldEditorLauncher$1.create(OpenWorldEditorLauncher.java:59)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: skins/game-skin.json
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:98)
	at com.badlogic.gdx.assets.loaders.SkinLoader.loadSync(SkinLoader.java:75)
	at com.badlogic.gdx.assets.loaders.SkinLoader.loadSync(SkinLoader.java:38)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:141)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:504)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:378)
	... 9 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: skins/game-skin.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:702)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:96)
	... 15 more
Caused by: com.badlogic.gdx.utils.SerializationException: Font file not found: ../fonts/game_font.fnt
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$3.read(Skin.java:472)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$3.read(Skin.java:463)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:892)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:428)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:860)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:449)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:438)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:434)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:892)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:428)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:700)
	... 16 more

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Your folder structure is what exactly?

**Comment by mgsx-dev** [comment]
```
assets
|- skins
    |- game-skin.json
|- fonts
    |- game_font.fnt
```

**Comment by mgsx-dev** [comment]
I think the problem is here : https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/files/FileHandle.java#L135

path need to be resolved in some way when containing some `../../`

**Comment by ShipshapeDetour** [comment]
Windows is also affected.

**Comment by MrStahlfelge** [comment]
@mgsx-dev do you think you can make a PR for this?

**Comment by mgsx-dev** [comment]
@MrStahlfelge i tried and get satisfying result except for GWT, i used Path.normalize or URI.normalize but both are not available on GWT. I didn't found anything similar with GWT. We already talk about it and it would require to import some Java code into emu. Might be a lot of code and i'm not sure it worth it.
If you think we should do it, could you please tell me from where i can copy java code (with right licence, etc). Then i could make the PR.

**Comment by mgsx-dev** [comment]
i think all platforms are affected. Currently, it only works when running from IDE (or with assets as external folder)

**Comment by MrStahlfelge** [comment]
If I understand correctly, the FileHandle is instanitated with `FileHandle("skins/../fonts/game_font.fnt")` here.
If this is the case, I think this should be fixed - or better: resolved) right in the constructor.

For GWT, there's already a fixSlashes method called with a similar intention, but not dealing dealing with double dots.

[Path normalization with Apache 2 license can be found here](https://github.com/apache/commons-io/blob/cdf779422d47637ead33e094ae8f971de1c395f6/src/main/java/org/apache/commons/io/FilenameUtils.java#L358). Some of this is not needed, but there's a loop dealing with doubler dots.

**Comment by mgsx-dev** [comment]
After few discussions on Discord, i will close this issue. There is no simple way to fix this, actually more than FileHandle would be impacted : AssetManager rely on String path names and some loaders (TMX Map Loader) resolve relative path internally. A quick fix could be to do the same thing when loading a skin but it may have other impacts. So in the end i don't think it worth it.
