### ISSUE TITLE
Freetype-Font generation with own PixmapPacker and incremental throws exception

### ISSUE THREAD

**Issue by Trurl101** [libgdx/libgdx#4959]
#### Issue details
When I use the FreetypeFontloader with my own PixmapPacker and incremental parameter a NullPointerException is thrown.

I tried this with different ttf fonts. When I set incremental=false or don't use my own PixmapPacker it works.

#### Reproduction steps/code
```
PixmapPacker fontTexture = new PixmapPacker(1024, 1024, Pixmap.Format.RGBA8888, 1, false, new PixmapPacker.GuillotineStrategy());

FreetypeFontLoader.FreeTypeFontLoaderParameter pf = new FreetypeFontLoader.FreeTypeFontLoaderParameter();
		pf.fontFileName = "font/dum.ttf";
		pf.fontParameters.size = size;
		pf.fontParameters.characters = characters;
		pf.fontParameters.magFilter = Texture.TextureFilter.Linear;
		pf.fontParameters.minFilter = Texture.TextureFilter.Linear;
		pf.fontParameters.packer = fontTexture;
		pf.fontParameters.incremental=true;
		app.assets.manager.load("stdFont.ttf", BitmapFont.class, pf);
```

#### Version of LibGDX and/or relevant dependencies
1.9.8-SNAPSHOT

#### Stacktrace
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NullPointerException
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:582)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:383)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:404)
	at xxx.Assets.loadStartScreen(Assets.java:106)
	at xxx.create(xxx.java:31)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:422)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:370)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at xxx.desktop.DesktopLauncher.main(DesktopLauncher.java:34)
Caused by: java.lang.NullPointerException
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator$FreeTypeBitmapFontData.getGlyph(FreeTypeFontGenerator.java:665)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:475)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:181)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:174)
	at com.badlogic.gdx.graphics.g2d.freetype.FreetypeFontLoader.loadSync(FreetypeFontLoader.java:41)
	at com.badlogic.gdx.graphics.g2d.freetype.FreetypeFontLoader.loadSync(FreetypeFontLoader.java:20)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:141)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:507)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:381)
	... 8 more
```

**Comment by Tom-Ski** [comment]
Please supply code that can be run. See https://libgdx.badlogicgames.com/documentation/help/Issue%20Reporting.html

**Comment by Trurl101** [comment]
I could narrow down the error. I think it is an error, perhaps it is known behaviour:

It crashes when doing the following:
- incremental=true
- own PixmapPacker
- no space " " in character string

The following code crashes. But when I add a space to the pf.fontParameters.characters string it works.

`
public class MyGdxGame extends ApplicationAdapter {
	SpriteBatch batch;
	Texture img;

	@Override
	public void create() {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");

		AssetManager manager = new AssetManager();
		FileHandleResolver resolver = new InternalFileHandleResolver();
		manager.setLoader(FreeTypeFontGenerator.class, new FreeTypeFontGeneratorLoader(resolver));
		manager.setLoader(BitmapFont.class, ".ttf", new FreetypeFontLoader(resolver));

		PixmapPacker fontTexture = new PixmapPacker(1024, 1024, Pixmap.Format.RGBA8888, 2, false, new PixmapPacker.GuillotineStrategy());

		FreetypeFontLoader.FreeTypeFontLoaderParameter pf = new FreetypeFontLoader.FreeTypeFontLoaderParameter();
		pf.fontFileName = "dum.ttf";
		pf.fontParameters.size = 20;
		pf.fontParameters.characters = "0123456789abcdefghijklmnopqrstuvwxyz";
		pf.fontParameters.magFilter = Texture.TextureFilter.Linear;
		pf.fontParameters.minFilter = Texture.TextureFilter.Linear;
		pf.fontParameters.incremental = true;
		pf.fontParameters.packer = fontTexture;
		manager.load("stdFont.ttf", BitmapFont.class, pf);

		manager.finishLoading();
	}

	@Override
	public void render() {
		Gdx.gl.glClearColor(1, 0, 0, 1);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		batch.begin();
		batch.draw(img, 0, 0);
		batch.end();
	}

	@Override
	public void dispose() {
		batch.dispose();
		img.dispose();
	}
}
`

**Comment by Tom-Ski** [comment]
Can you supply the font you are using in this test?

**Comment by Trurl101** [comment]
I tried it with four completely different ttf fonts. For example 
 "Noto Sans UI" (https://www.google.com/get/noto/#sans-lgc) from Google and some standard fonts like "comic" from my Mac.

But the outcome is still the same. With space all okay, without space in character string it crashes.
