### ISSUE TITLE
AtlasTmxMapLoader not working as documented

### ISSUE THREAD

**Issue by heschlie** [libgdx/libgdx#4974]
#### Issue details
The javadocs for `AtlasTmxMapLoader` states the following (trimmed a bit)

> The atlas must have in it indexed regions named after the tilesets used in the map. The indexes shall be local to the tileset (not the global id).

But this is not the case, and when you do you get NPE if you have an object layer with stuff in it, or just a messed up map with the wrong tiles in the wrong places.

I feel, and I might be wrong on this, that you should be able to simply pack all your tilesets using the texturepacker indexed like stated above and point the map at it. It keeps the process simple for the end user and feels like different tools are working together. At a minimum the docs should be updated to reflect reality.

#### Reproduction steps/code
- Create a tmx file with the atlas property at the map level as indicated, include at least two tilesheets (with just one the local ID and Global ID are the same)
- Pack your tilesheets into an atlas using the libgdx texturepacker
- Try to load the map
- See NPE if you have an object layer with objects in it, or tiles in the wrong place

#### Version of LibGDX and/or relevant dependencies
libgdx version: 1.9.7

#### Stacktrace
```java
// NPE with an object layer
java.lang.NullPointerException
	at com.badlogic.gdx.maps.tiled.objects.TiledMapTileMapObject.<init>(TiledMapTileMapObject.java:42)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:278)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:222)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObjectGroup(BaseTmxMapLoader.java:160)
	at com.badlogic.gdx.maps.tiled.AtlasTmxMapLoader.loadMap(AtlasTmxMapLoader.java:276)
	at com.badlogic.gdx.maps.tiled.AtlasTmxMapLoader.load(AtlasTmxMapLoader.java:160)
	at com.badlogic.gdx.maps.tiled.AtlasTmxMapLoader.load(AtlasTmxMapLoader.java:112)
	at com.ifgames.rabbots.levels.Level.loadTileMap(Level.java:291)
	at com.ifgames.rabbots.levels.Level.init(Level.java:136)
	at com.ifgames.rabbots.screens.DebugLevelMenu$1.clicked(DebugLevelMenu.java:48)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

#### Further information

I found a [post](https://gamedev.stackexchange.com/questions/116354/libgdx-atlastmxmaploader-with-multiple-tilsets#) which demonstrates how to get around this issue and what is happening. The tldr is that the regions in the atlas actually do need to be related to the tile gid, sorta, it is `tilegid - 1`.

I took a swing at correcting this, but I had already created a script to work around this and it is unfortunately not as simple as tweaking a few lines in the `AtlasTmxMapLoader`.

**Comment by mgsx-dev** [comment]
I fixed a bug recently, maybe it is related ? https://github.com/libgdx/libgdx/pull/4975

**Comment by heschlie** [comment]
@mgsx-dev Let me give that a shot (I think I have already but honestly don't know for sure)

**Comment by heschlie** [comment]
Yep that fixes it, I would have sworn for some reason you didn't have access to the firstgid when it loaded the atlas regions, thanks!

**Comment by mgsx-dev** [comment]
Cool ! I just realized you had 2 issues : tileset indexing and object layers. For the object layers i think the problem is here : https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/maps/tiled/AtlasTmxMapLoader.java#L261 it calls loadTileLayer instead of loadLayer (which support all layer types), maybe you could try.

**Comment by heschlie** [comment]
The two issues were linked to the same underlying issue of the tileid not matching up. Now that they do it finds all of the objects as well so it doesn't throw an NPE.
