### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Action.act(float)' at com.badlogic.gdx.scenes.scene2d.actions.RepeatAction.delegate(SourceFile:29)

### ISSUE THREAD

**Issue by denis-stepuschik** [libgdx/libgdx#5079]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.badlogic.gdx.scenes.scene2d.Action.act(float)' on a null object reference
       at com.badlogic.gdx.scenes.scene2d.actions.RepeatAction.delegate(SourceFile:29)
       at com.badlogic.gdx.scenes.scene2d.actions.DelegateAction.act(SourceFile:43)
       at com.badlogic.gdx.scenes.scene2d.Actor.act(SourceFile:96)
       at com.badlogic.gdx.scenes.scene2d.Group.act(SourceFile:49)
       at com.badlogic.gdx.scenes.scene2d.Group.act(SourceFile:49)
       at com.badlogic.gdx.scenes.scene2d.Stage.act(SourceFile:221)
       at ....StageScreen.render(SourceFile:98)
       at ....BaseScreen.render(SourceFile:71)
       at ....BaseGame.render(SourceFile:97)
       at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(SourceFile:459)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1583)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

This crash occurs on Android, gdx version is '1.9.6'. 
Seems it happens immediately after the app was launched.

**Comment by Tom-Ski** [comment]
Please fill in the issue template fully. Without reproducible code its very difficult to troubleshoot your issue.
