### ISSUE TITLE
PolygonSprite.java setRegion bug

### ISSUE THREAD

**Issue by JKazma** [libgdx/libgdx#5099]
#### Issue details
I am trying to execute this piece of code in my game.

`public void draw(Batch batch, float parentAlpha){
    PolygonRegion polyReg = new PolygonRegion(connectorTextureRegion, getVertices(), getTriangles());
    polygonSprite.setRegion(polyReg);
    polygonSprite.draw((PolygonSpriteBatch)batch);
}`

In general, it works well but sometimes I'm getting an ArrayIndexOutOfBounds exception caused by the setRegion line. If I dive into the methods code, it fails at the first line in the for loop.

    public void setRegion (PolygonRegion region) {
         this.region = region;

    float[] regionVertices = region.vertices;
    float[] textureCoords = region.textureCoords;

    if (vertices == null || regionVertices.length != vertices.length) vertices = new float[(regionVertices.length / 2) * 5];

    // Set the color and UVs in this sprite's vertices.
    float floatColor = color.toFloatBits();
    float[] vertices = this.vertices;
    for (int i = 0, v = 2, n = regionVertices.length; i < n; i += 2, v += 5) {
        vertices[v] = floatColor;
        vertices[v + 1] = textureCoords[i];
        vertices[v + 2] = textureCoords[i + 1];
    }

    dirty = true;
}`

Now let me know if I'm wrong, but I feel like there might be an issue with the if condition. We should have
`(regionVertices.length /2)*5!= vertices.length`
instead of
`regionVertices.length != vertices.length` 

Whenever I get the exception, it's because the length of the region vertices array and the length of the sprite vertices array are equal.

#### Version of LibGDX and/or relevant dependencies
Libgdx:1.9.6

#### Stacktrace
E/AndroidRuntime: FATAL EXCEPTION: GLThread 3995
                                                                Process: com.kozma.rope, PID: 13199
                                                                java.lang.ArrayIndexOutOfBoundsException: length=20; index=22
                                                                    at com.badlogic.gdx.graphics.g2d.PolygonSprite.setRegion(PolygonSprite.java:342)
                                                                    at com.kozma.rope.components.LineConnector.draw(LineConnector.java:99)
                                                                    at com.kozma.rope.models.LineSegment.draw(LineSegment.java:372)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
                                                                    at com.kozma.rope.models.Line.draw(Line.java:341)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
                                                                    at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
                                                                    at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
                                                                    at com.kozma.rope.screens.GameScreen.render(GameScreen.java:248)
                                                                    at com.badlogic.gdx.Game.render(Game.java:46)
                                                                    at com.kozma.rope.Rope.render(Rope.java:139)
                                                                    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:459)
                                                                    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
                                                                    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by obigu** [comment]
Not sure if it's related but you could check if current 1.9.9-SNAPSHOT fixes the issue with this commit https://github.com/libgdx/libgdx/commit/dcb5da717e3af7453015f326eb092d834a63a611

**Comment by JKazma** [comment]
@obigu I'll take a look when I have time but looking at the changes, it doesn't seem to affect the setRegion method.

**Comment by piotr-j** [comment]
Looks like simple fix, why not make a PR for it? Making multiple issues about same thing wont help.

**Comment by NathanSweet** [comment]
Closed by #5039.
