### ISSUE TITLE
Win. Unable to allocate audio buffers. AL Error: 40963

### ISSUE THREAD

**Issue by artsb** [libgdx/libgdx#5115]
#### Issue details
I have an error:
Unable to allocate audio buffers. AL Error: 40963

#### Reproduction steps/code
```java
public class GameMusic implements Music.OnCompletionListener {
    private static final String MUSIC1_FILENAME = "music/music1.mp3";
    private static final String MUSIC2_FILENAME = "music/music2.mp3";

    private Music music1;
    private Music music2;
    private Music currentMusic;

    @Override
    public void onCompletion(Music music) {
        if(currentMusic == music1) {
            currentMusic = music2;
        }
        else {
            currentMusic = music1;
        }

        music.stop();

        currentMusic.play(); // <-- Exception
    }

    public GameMusic() {
        music1 = Gdx.audio.newMusic(Gdx.files.internal(MUSIC1_FILENAME));
        music2 = Gdx.audio.newMusic(Gdx.files.internal(MUSIC2_FILENAME));
        currentMusic = music1;

        music1.setOnCompletionListener(this);
        music2.setOnCompletionListener(this);
    }

    public void play() {
        currentMusic.play();
    }

    public void pause() {
        if(currentMusic.isPlaying()) {
            currentMusic.pause();
        }
    }

    public void dispose() {
        music1.stop();
        music2.stop();

        music1.dispose();
        music2.dispose();
    }
}
```

#### Version of LibGDX and/or relevant dependencies
Win7 Pro x64 with updates
Android Studio 3.0.1
LibGDX 1.9.8
Gradle 2.3.3
Build Tools 27.0.3

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Unable to allocate audio buffers. AL Error: 40963
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:83)
	at xxxxxxxxxxxxxxxxxxxxxxx.utils.GameMusic.onCompletion(GameMusic.java:33)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.update(OpenALMusic.java:242)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.update(OpenALAudio.java:227)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:218)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [+] Windows
- [ ] Linux
- [ ] MacOS

**Comment by NathanSweet** [comment]
Thanks for the issue, but please post *executable* example code using assets in `tests\gdx-tests-android\assets\data`. I've modified your submission and don't see an errors:
```
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Music;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;

public class GameMusic implements Music.OnCompletionListener {
	private static final String MUSIC1_FILENAME = "data/shotgun.mp3";
	private static final String MUSIC2_FILENAME = "data/8.12.mp3";

	private Music music1;
	private Music music2;
	private Music currentMusic;

	@Override
	public void onCompletion (Music music) {
		if (currentMusic == music1) {
			currentMusic = music2;
		} else {
			currentMusic = music1;
		}

		music.stop();

		currentMusic.play(); // <-- Exception
	}

	public GameMusic () {
		music1 = Gdx.audio.newMusic(Gdx.files.internal(MUSIC1_FILENAME));
		music2 = Gdx.audio.newMusic(Gdx.files.internal(MUSIC2_FILENAME));
		currentMusic = music1;

		music1.setOnCompletionListener(this);
		music2.setOnCompletionListener(this);
	}

	public void play () {
		currentMusic.play();
	}

	public void pause () {
		if (currentMusic.isPlaying()) {
			currentMusic.pause();
		}
	}

	public void dispose () {
		music1.stop();
		music2.stop();

		music1.dispose();
		music2.dispose();
	}

	static public void main (String[] args) throws Exception {
		new LwjglApplication(new ApplicationAdapter() {
			public void create () {
				new GameMusic().play();
			}
		});
	}
}
```
