### ISSUE TITLE
FileHandleResolver cannot get the corresponding png file of a `BitmapFont` file if it use an absolute path of `FileHandle` 

### ISSUE THREAD

**Issue by Fang3s** [libgdx/libgdx#5121]
Please ensure you have given all the following requested information in your report.

#### Issue details

Use an absolute path of `FileHandle` to resolve a `BitmapFont` file (num.png), it cannot get its corresponding png file.

#### Reproduction steps/code
```
package ss.fang.wonders;

public class WondersGdxGame extends Game implements ApplicationListener {
	private static final String assetsPath = System.getProperty("assets.path");
	private static final FileHandleResolver resourceResolver = new FileHandleResolver() {

		@Override
		public FileHandle resolve(String fileName) {
			// Gdx.files.absolute(assetsPath + File.pathSeparatorChar + fileName);
			// resourceResolver>>>>>>>>>>>>D:/dev/wonders/android/assets/num.png
			System.out.println("resourceResolver>>>>>>>>>>>>" + fileName);
			return null == assetsPath ? Gdx.files.internal(fileName) : new FileHandle(new File(assetsPath, fileName));
		}
	};

	@Override
	public void create() {
		AssetManager manager = new AssetManager(new FileHandleResolver() {
			@Override
			public FileHandle resolve(String fileName) {
				// AssertManager>>>>>>>>>>>>D:/dev/wonders/android/assets/num.png
				System.out.println("AssertManager>>>>>>>>>>>>" + fileName);
				return resourceResolver.resolve(fileName);
			}
		});

		// NOTE!! it will check existence of "fileName.gen", e.g. arial.ttf.gen
		// set the loaders for the generator and the fonts themselves
		FileHandleResolver resolver = resourceResolver;
		manager.setLoader(FreeTypeFontGenerator.class, new FreeTypeFontGeneratorLoader(resolver));
		manager.setLoader(BitmapFont.class, ".ttf", new FreetypeFontLoader(resolver));

		// load to fonts via the generator (implicitly done by the FreetypeFontLoader).
		// Note: you MUST specify a FreetypeFontGenerator defining the ttf font file name and the size
		// of the font to be generated. The names of the fonts are arbitrary and are not pointing
		// to a file on disk (but must end with the font's file format '.ttf')!
		FreeTypeFontLoaderParameter ftfLoaderParams = new FreeTypeFontLoaderParameter();
		ftfLoaderParams.fontFileName = TTF_FILE;
		ftfLoaderParams.fontParameters.size = 12;
		manager.load(FONT_FILE_NAME, BitmapFont.class, ftfLoaderParams);

		// // Font generator
		// FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.internal(TTF_FILE));
		// // make the font
		// // font parameters for this size
		// FreeTypeFontParameter params = new FreeTypeFontParameter();
		// params.flip = true; // if your cam is flipped
		// params.characters = FreeTypeFontGenerator.DEFAULT_CHARS; // your String containing all letters you need
		// params.size = 28;
		// params.magFilter = TextureFilter.Linear; // used for resizing quality
		// params.minFilter = TextureFilter.Linear; // also
		// bmpFontDesignationNumber = generator.generateFont(params);
		// generator.dispose(); // dispose to avoid memory leaks

		// we also load a "normal" font generated via Hiero
		manager.load(FONT_FILE_RESOURCE_NUMBER, BitmapFont.class);
	}
}


/** {@link AssetLoader} for {@link BitmapFont} instances. Loads the font description file (.fnt) asynchronously, loads the
 * {@link Texture} containing the glyphs as a dependency. The {@link BitmapFontParameter} allows you to set things like texture
 * filters or whether to flip the glyphs vertically.
 * @author mzechner */
public class BitmapFontLoader extends AsynchronousAssetLoader<BitmapFont, BitmapFontLoader.BitmapFontParameter> {
	public BitmapFontLoader (FileHandleResolver resolver) {
		super(resolver);
	}

	BitmapFontData data;

	@Override
	public Array<AssetDescriptor> getDependencies (String fileName, FileHandle file, BitmapFontParameter parameter) {
		Array<AssetDescriptor> deps = new Array();
		if (parameter != null && parameter.bitmapFontData != null) {
			data = parameter.bitmapFontData;
			return deps;
		}

		data = new BitmapFontData(file, parameter != null ? parameter.flip : false);
		if (parameter != null && parameter.atlasName != null) {
			deps.add(new AssetDescriptor(parameter.atlasName, TextureAtlas.class));
		} else {
			for (int i = 0; i < data.getImagePaths().length; i++) {
				String path = data.getImagePath(i);  ///////// D:/dev/wonders/android/assets/num.png
				FileHandle resolved = resolve(path);

				TextureLoader.TextureParameter textureParams = new TextureLoader.TextureParameter();

				if (parameter != null) {
					textureParams.genMipMaps = parameter.genMipMaps;
					textureParams.minFilter = parameter.minFilter;
					textureParams.magFilter = parameter.magFilter;
				}

				AssetDescriptor descriptor = new AssetDescriptor(resolved, Texture.class, textureParams);
				deps.add(descriptor);
			}
		}

		return deps;
	}
}
```

#### Version of LibGDX and/or relevant dependencies
gdx-1.9.8 at least

#### Stacktrace
```java
// Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: D:/dev/wonders/android/assets/num.png
// 	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:582)
// 	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:383)
// 	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:404)
// 	at ss.fang.wonders.WondersGdxGame.create(WondersGdxGame.java:99)
// 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
// 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
// Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: D:/dev/wonders/android/assets/num.png
// 	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:153)
// 	at com.badlogic.gdx.assets.loaders.BitmapFontLoader.loadSync(BitmapFontLoader.java:96)
// 	at com.badlogic.gdx.assets.loaders.BitmapFontLoader.loadSync(BitmapFontLoader.java:39)
// 	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:141)
// 	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
// 	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:507)
// 	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:381)
// 	... 4 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
Unfortunately, when writing a custom `FileHandleResolver`, you must handle both absolute and relative paths.

(Though it would be nice to refactor `BitmapFont` to leave creating absolute paths to the resolver, but it probably wouldn't be simple and would break people's code.)
