### ISSUE TITLE
java.lang.IllegalArgumentException: Bad position 8/0 on Android LWP

### ISSUE THREAD

**Issue by klaszlo8207** [libgdx/libgdx#5142]
#### Issue details
Sometimes on my android live wallpaper I get this exception: IllegalArgumentException: Bad position 8/0

#### Version of LibGDX and/or relevant dependencies
latest libgdx

#### Stacktrace
```java
java.lang.IllegalArgumentException: Bad position 8/0
                                                                          at java.nio.Buffer.position(Buffer.java:249)
                                                                          at com.badlogic.gdx.graphics.glutils.VertexArray.bind(VertexArray.java:118)
                                                                          at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:391)
                                                                          at com.badlogic.gdx.graphics.Mesh.bind(Mesh.java:382)
                                                                          at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:490)
                                                                          at com.badlogic.gdx.graphics.Mesh.render(Mesh.java:460)
                                                                          at com.badlogic.gdx.graphics.g2d.SpriteBatch.flush(SpriteBatch.java:977)
                                                                          at com.badlogic.gdx.graphics.g2d.SpriteBatch.setProjectionMatrix(SpriteBatch.java:1049)
                                                                          at hu.lacas.newalienlwp.Renderer.resizeBatch(Renderer.kt:844)
                                                                          at hu.lacas.newalienlwp.Renderer.access$resizeBatch(Renderer.kt:44)
                                                                          at hu.lacas.newalienlwp.Renderer$resize$1.run(Renderer.kt:828)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

The source code

    override fun resize(width: Int, height: Int) {
        camera.viewportHeight = Gdx.graphics.height.toFloat()
        camera.viewportWidth = Gdx.graphics.width.toFloat()
        mOrientation = if (camera.viewportHeight < camera.viewportWidth) LiveWallpaper.ORIENTATION_LANDSCAPE else LiveWallpaper.ORIENTATION_PORTRAIT
        camera.fieldOfView = (if (mOrientation != LiveWallpaper.ORIENTATION_LANDSCAPE) 27 else 20).toFloat()
        camera.update()

        handler.postDelayed({
            resizeBatch()
        }, 900)

    }
	
	
    private fun resizeBatch() {
        val viewportWidth = Gdx.graphics.width
        val viewportHeight = Gdx.graphics.height
        if (camera2D == null) camera2D = OrthographicCamera()
        camera2D?.setToOrtho(false, viewportWidth.toFloat(), viewportHeight.toFloat())
        camera2D?.update()
        spriteBatch!!.projectionMatrix = camera2D?.combined

        Objects.textureRegionScanlineFullScreen.setRegion(0, 0, Gdx.graphics.width, Gdx.graphics.height)
    }
	
	
```

it looks like the probleme is here:

--> spriteBatch!!.projectionMatrix = camera2D?.combined

This exception is just comes up sometimes... So not really understand what is going on. I created that handler with 900ms because when this is not there the exception is shown more.. Whats is going on? 
Libgdx not loaded the matrix yet?

#### Please select the affected platforms
- [x] Android

**Comment by Tom-Ski** [comment]
You are multithreading incorrectly. Please use the forum or irc for personal assistance.
