### ISSUE TITLE
Java 9 module : Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit

### ISSUE THREAD

**Issue by Ealrann** [libgdx/libgdx#5178]
#### Issue details
Simply transforming the basic project template (for desktop target) into a java 9 project (with module-info.java) make the project non runnable.

#### Reproduction steps/code
I just added the module-info.java for project core and desktop in eclipse:
Right click on project name => Configure => Create module-info.java
This command will also transform the classpath entries into modulepath entries (for java9 modules).

I need java9 module because I want to extensively use services.

By the way, I think you should add the module-info.java into libgdx jars to be java9 compliant (and this shouldn't break anything I suppose?).

LibGDX v1.9.8

#### Stacktrace
```java
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit
	at gdx@1.9.8/com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at gdx@1.9.8/com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
	at gdx.backend.lwjgl@1.9.8/com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
	at gdx.backend.lwjgl@1.9.8/com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:81)
	at gdx.backend.lwjgl@1.9.8/com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
	at com.mygdxgame.desktop/com.mygdx.game.desktop.DesktopLauncher.main(DesktopLauncher.java:10)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx64.so
	at gdx@1.9.8/com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:133)
	at gdx@1.9.8/com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:289)
	at gdx@1.9.8/com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:121)
	... 5 more
```

#### Affected platforms
- [?] Android
- [?] iOS (robovm)
- [?] iOS (MOE)
- [?] HTML/GWT
- [?] Windows
- [x] Linux
- [?] MacOS

**Comment by wrldwzrd89** [comment]
The default module-info.java file isn't quite enough to get things working. It'll declare it modular and list all the dependencies OK, but, as you just discovered, loading the native libraries doesn't work anymore. Since you did this in Eclipse, you can go into project settings and tell libGDX where its native libraries are. See if that gets them to load OK.

**Comment by jrb0001** [comment]
My workaround for this issue was to merge all of libGDX and its dependencies into a single jar and including a module descriptor in it as well. Then you just depend on this single modularized jar instead of all libGDX stuff. This is really ugly, but it avoids the downsides of automatic modules.

**Comment by wrldwzrd89** [comment]
Neat hack! Long term, a way to make this solution general enough for any platform libGDX supports, along with making the library itself modular, would not only solve this, but also ease compatibility with newer Java versions. Of course, Android complicates things, but there’s no reason a dual-JDK (8+11) solution could not be used to address it, as the building system is scripted anyway. LTS versions of the JDK are used because the release cycles don’t line up well.

**Comment by jrb0001** [comment]
As I mentioned in https://github.com/junkdog/artemis-odb/issues/539, there is a maven module which allows generating the module descriptor on JDK 8. No idea if there is a similar thing for gradle and/or ant and no idea which build system libGDX actually uses (there are files for ant, maven and gradle in the repo root...).

**Comment by stodge** [comment]
Do I need to download the libgdx release and configure Eclipse to point at the referenced shared library?

**Comment by crykn** [comment]
I'm closing this, since we're already in the process of changing the setup tool.
