### ISSUE TITLE
Failed to locate library: liblwjgl32.so on LWJGL3 backend on Linux 32-bit

### ISSUE THREAD

**Issue by raeleus** [libgdx/libgdx#5186]
#### Issue details
LibGDX apps built on the LWJGL3 backend do not work on Linux 32-bit. It reports that liblwjgl32.so is missing. Indeed, liblwjgl32.so is missing from the distributed Jar file.

#### Reproduction steps/code
- Create a new project.
- Convert the project to the LWJGL3 backend. See https://github.com/libgdx/libgdx/issues/3673
- Run the "Dist" Gradle task.
- Attempt to run the resulting Jar file on Linux 32 bit (ie. Linux Mint 18.3 32-bit).

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.8

#### Stacktrace
```java
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:146)
	at org.lwjgl.system.Library.loadSystem(Library.java:66)
	at org.lwjgl.system.Library.<clinit>(Library.java:49)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:60)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:60)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:79)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:70)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:605)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:614)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:38)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:88)
	at com.mygdx.game.desktop.DesktopLauncher.main(DesktopLauncher.java:10)
```

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by intrigus** [comment]
LWJGL 3 dropped Linux x86 support.

**Comment by raeleus** [comment]
Well that's a bummer. Thanks!
