### ISSUE TITLE
Creating  FrameBuffer with Depth Texture attachment on OpenGL ES 2.0 gives GdxRuntimeException.

### ISSUE THREAD

**Issue by ZumiKua** [libgdx/libgdx#5228]
#### Issue details

When creating FrameBuffer with depth texture, program will throw a GdxRuntimeException on runtime, which says "Multiple render targets not available on GLES 2.0".

but I'm not using MRT, and it seems that OpenGL ES 2.0 supports depth attachment, according to this [link](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glFramebufferTexture2D.xml)

After checking the code, I found that this code maybe the cause of this problem,
````
if (bufferBuilder.textureAttachmentSpecs.size > 1) {
	throw new GdxRuntimeException("Multiple render targets not available on GLES 2.0");
}
````
it checks textureAttachmentSpecs's size, but ignores whether they are depth texture or not.
Is this a bug of libGDX?
#### Reproduction steps/code
````
FrameBuffer.FrameBufferBuilder builder = new GLFrameBuffer.FrameBufferBuilder(WIDTH,HEIGHT);
        builder.addBasicColorTextureAttachment(Pixmap.Format.RGBA8888);
        builder.addDepthTextureAttachment(GL20.GL_DEPTH_COMPONENT, GL20.GL_FLOAT);
        mfbo = builder.build();
````

#### Version of LibGDX and/or relevant dependencies
I'm using 1.9.7, but after checking the master branch on github, I think this issue is not got fixed.

#### Stacktrace
```java
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Multiple render targets not available on GLES 2.0
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.checkValidBuilder(GLFrameBuffer.java:377)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:113)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.<init>(GLFrameBuffer.java:87)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:51)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer$FrameBufferBuilder.build(GLFrameBuffer.java:474)
	at mevk.truth.dorothy.spriteset.World.createFBO(World.java:121)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS
* I only tested this on Windows, but I think this problem exists in all platforms.

**Comment by Tom-Ski** [comment]
GLES 2.0 supports a depth renderbuffer but not a depth texture buffer.
