### ISSUE TITLE
Libgdx is not compatible with GWT 2.8.2

### ISSUE THREAD

**Issue by patton73** [libgdx/libgdx#5256]
Please ensure you have given all the following requested information in your report.

#### Issue details
Compilation gives this error:

Exception in thread "main" java.lang.NoSuchMethodError: com.google.gwt.util.regexfilter.RegexFilter: method <init>()V not found
	at com.google.gwt.util.regexfilter.WhitelistRegexFilter.<init>(WhitelistRegexFilter.java:21)
	at com.google.gwt.dev.jjs.JJSOptionsImpl.<init>(JJSOptionsImpl.java:54)
	at com.google.gwt.dev.PrecompileTaskOptionsImpl.<init>(PrecompileTaskOptionsImpl.java:39)
	at com.google.gwt.dev.CompilerOptionsImpl.<init>(CompilerOptionsImpl.java:30)
	at com.google.gwt.dev.Compiler.main(Compiler.java:108)

#### Reproduction steps/code

Just use GWT 2.8.2 and try to recompile

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Please select the affected platforms
- [X ] HTML/GWT

**Comment by MobiDevelop** [comment]
I'm working on it.

**Comment by tommyettinger** [comment]
This also affects 2.8.1, by the way, but not 2.8.0.

**Comment by niloc132** [comment]
This error happens a lot in normal GWT development as well - it means that somehow you have both GWT 2.8.0 and 2.8.1 (or 2.8.2) on the classpath at the same time, so some classes are conflicting.

Unless libgdx has a custom build of GWT internally, this is probably just a matter of fixing all dependencies - `gwt-user`, `gwt-dev` are the two main ones, but `gwt-servlet` might be required as well.

**Comment by Gustl22** [comment]
Any workarounds for this? Is it possible to [update](https://github.com/libgdx/libgdx/commit/7ed40698018bb789916ffea6ca8b2a4f64961f92) libGDX to 2.8.2?

**Comment by niloc132** [comment]
In normal GWT development, you must simply ensure that only one copy of each GWT jar is present on the classpath, and that each is exactly the same version - it is very likely the case here too, suggesting that you have some conflicting dependencies or some second copy of gwt (but in another artifact, etc). If you're using maven, try `mvn dependency:tree -Dverbose`, possibly share the result if it isn't clear right away. If using gradle, I believe the analog is something like `:dependencyInsight --dependency gwt-dev`, but I don't know gradle very well.

**Comment by TMTHY** [comment]
2 [Gustl22](/Gustl22).
After  setting gwt.gwtVersion to 2.8.2 you have to exclude old dependencies from :html project.
```
compile ("com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion") {
        exclude group: 'com.google.gwt', module: 'gwt-user'
}
compile ("com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources") {
        exclude group: 'com.google.gwt', module: 'gwt-user'
}
```
after that it MAY compile.

**Comment by Gustl22** [comment]
Thank you for your help @niloc123 @TMTHY.
I already tried your suggestions :)
But I wanted to compile it under JDK 11 which is obviously not supported yet by GWT and JDK 9 already is outdated without LTS. So I decided to downgrade on JDK 8, which works with GWT 2.8.0, too.

**Comment by niloc132** [comment]
@Gustl22 I believe you may be mistaken, GWT 2.8.2 works correctly under Java 9, 10, 11 as far as I know (I just updated to Java 11 and compiled a gwt project correctly). Two things that do not work with Java 11 right now, but neither should affect your ability to use GWT 2.8.2 under JDK 11:

 * Building GWT from sources (due to changes in javadoc classes)
 * Running Java 9-11 sources or use JRE emulation

Both of these are in the process of being updated for the GWT 2.9 release.

**Comment by Gustl22** [comment]
> Running Java 9-11 sources or use JRE emulation

Not quite sure if this is my problem at our library. I'm not familiar with GWT development, but it complains to not finding sources in `IReflectionCacheGenerated.java` although we don't use reflection as far as I know. As it worked before upgrading from 2.8.0 to 2.8.2, I'm not sure what dependency is missing here.
<details><summary>Stacktrace</summary>

```
./gradlew :vtm-web-app:farmRun --stacktrace

> Task :vtm-web-app:draftCompileGwt
/media/Data/Coding/git/mapsforge/vtm/vtm-web-app/.
assets
Copying resources from assets to build/gwt/draftOut/
/media/Data/Coding/git/mapsforge/vtm/vtm-web-app/assets
/media/Data/Coding/git/mapsforge/vtm/vtm-web-app/assets
  com.badlogic.gdx.graphics.VertexAttributes
    com.badlogic.gdx.graphics.VertexAttribute[]
      java.lang.Object
        boolean
        int
        java.lang.String
          java.lang.CharSequence
            char
          char[]
            void
          java.lang.CharSequence[]
          double
          float
          long
          java.lang.Object[]
          java.lang.StringBuffer
          byte[]
          java.lang.String[]
          int[]
          java.lang.StringBuilder
    com.badlogic.gdx.graphics.VertexAttribute
    com.badlogic.gdx.graphics.VertexAttributes.Usage
  com.badlogic.gdx.graphics.g3d.model.Animation
  com.badlogic.gdx.graphics.g3d.model.MeshPart
  com.badlogic.gdx.graphics.g3d.model.Node
  com.badlogic.gdx.graphics.g3d.model.NodeKeyframe
  com.badlogic.gdx.graphics.g3d.model.NodeAnimation
  com.badlogic.gdx.graphics.g3d.model.NodePart
  java.util.HashMap
  java.util.ListIterator
  java.util.List
  java.util.Map
  java.util.ArrayList
  com.google.gwt.user.client.rpc.core.java.lang.Integer_CustomFieldSerializer
    java.lang.Integer
      byte
      short
  com.google.gwt.user.client.rpc.core.java.lang.String_CustomFieldSerializer
  com.google.gwt.user.client.rpc.core.java.lang.Object_Array_CustomFieldSerializer
  com.google.gwt.user.client.rpc.core.java.lang.Float_CustomFieldSerializer
    java.lang.Float
  com.google.gwt.user.client.rpc.core.java.lang.Byte_CustomFieldSerializer
    java.lang.Byte
  com.google.gwt.user.client.rpc.core.java.lang.Character_CustomFieldSerializer
    java.lang.Character
  com.google.gwt.user.client.rpc.core.java.lang.Short_CustomFieldSerializer
    java.lang.Short
  com.google.gwt.user.client.rpc.core.java.lang.Double_CustomFieldSerializer
    java.lang.Double
  com.google.gwt.user.client.rpc.core.java.lang.Boolean_CustomFieldSerializer
    java.lang.Boolean
  com.google.gwt.user.client.rpc.core.java.util.HashMap_CustomFieldSerializer
  com.google.gwt.user.client.rpc.core.java.util.Map_CustomFieldSerializerBase
  com.google.gwt.user.client.rpc.core.java.util.ArrayList_CustomFieldSerializer
  com.badlogic.gdx.graphics.g3d.model.data.ModelTexture
  com.badlogic.gdx.graphics.g3d.model.data.ModelData
    short[]
    com.badlogic.gdx.graphics.g3d.model.data.ModelMesh
      float[]
      com.badlogic.gdx.graphics.g3d.model.data.ModelMeshPart[]
  com.badlogic.gdx.graphics.g3d.model.data.ModelMaterial
    com.badlogic.gdx.graphics.g3d.model.data.ModelMaterial.MaterialType
      java.lang.Enum
        java.lang.Enum[]
      com.badlogic.gdx.graphics.g3d.model.data.ModelMaterial.MaterialType[]
  com.badlogic.gdx.graphics.g3d.model.data.ModelNodePart
    int[][]
  com.badlogic.gdx.graphics.g3d.model.data.ModelAnimation
  com.badlogic.gdx.graphics.g3d.model.data.ModelNodeAnimation
  com.badlogic.gdx.graphics.g3d.model.data.ModelMeshPart
  com.badlogic.gdx.graphics.g3d.model.data.ModelNode
    com.badlogic.gdx.graphics.g3d.model.data.ModelNodePart[]
    com.badlogic.gdx.graphics.g3d.model.data.ModelNode[]
  com.badlogic.gdx.graphics.g3d.model.data.ModelNodeKeyframe
  java.lang.StringIndexOutOfBoundsException
Compiling module org.oscim.web.VtmWebApp
   [ERROR] Errors in '/media/Data/Coding/git/mapsforge/vtm/vtm-web-app/build/gwt/gen/com/badlogic/gwtref/client/IReflectionCacheGenerated.java'
      [ERROR] Line 1531: No source code is available for type javax.annotation.Nonnull; did you forget to inherit a required module?
      [ERROR] Line 1531: No source code is available for type javax.annotation.meta.When; did you forget to inherit a required module?
   Tracing compile failure path for type 'com.badlogic.gwtref.client.IReflectionCacheGenerated'
      [ERROR] Errors in '/media/Data/Coding/git/mapsforge/vtm/vtm-web-app/build/gwt/gen/com/badlogic/gwtref/client/IReflectionCacheGenerated.java'
         [ERROR] Line 1531: No source code is available for type javax.annotation.Nonnull; did you forget to inherit a required module?
         [ERROR] Line 1531: No source code is available for type javax.annotation.meta.When; did you forget to inherit a required module?
   [ERROR] Hint: Check that the type name 'com.badlogic.gwtref.client.IReflectionCacheGenerated' is really what you meant
   [ERROR] Hint: Check that your classpath includes all required source roots
   [ERROR] Errors in 'com/badlogic/gwtref/client/ReflectionCache.java'
      [ERROR] Line 24: Rebind result 'com.badlogic.gwtref.client.IReflectionCacheGenerated' could not be found

> Task :vtm-web-app:draftCompileGwt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vtm-web-app:draftCompileGwt'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':vtm-web-app:draftCompileGwt'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:119)
        at org.gradle.api.internal.tasks.execution.ResolvePreviousStateExecuter.execute(ResolvePreviousStateExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:178)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:154)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:41)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:24)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:46)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:383)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:247)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:159)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:134)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:58)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:55)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:82)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:75)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:55)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:58)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:315)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:305)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:101)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:49)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:227)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1103)
        at org.wisepersist.gradle.plugins.gwt.AbstractGwtActionTask.exec(AbstractGwtActionTask.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:273)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:258)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:145)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:49)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:33)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:43)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:29)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:134)
        at org.gradle.internal.execution.impl.steps.CacheStep.lambda$execute$3(CacheStep.java:83)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:82)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:36)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:91)
        ... 119 more


* Get more help at https://help.gradle.org

BUILD FAILED in 9s
23 actionable tasks: 1 executed, 22 up-to-date
```
</details>

**Comment by tommyettinger** [comment]
@Gustl22 I think the errors regarding missing sources for annotations are a good lead. This has shown up on GWT's issue tracker before, although for other annotations, but I suspect that adding a dependency to the GWT build.gradle (not the root build.gradle or the core one) like `compile 'com.google.code.findbugs:jsr305:3.0.2:sources'` might help. JSR305 is the request to add Nonnull and some other annotations to the main JDK, and it's stuck in external deps for now it seems. That JSR305 project may not be the right one; you may need to do a call like `gradlew html:dependencies` or `gradlew gwt:dependencies` to see what JSR305 jar is used, duplicate that dependency in your HTML or GWT project, and add `:sources` to the end of the dependency string (this is just like the other dependencies in the GWT build.gradle, where they depend on a normal jar and also a sources jar).

**Comment by Gustl22** [comment]
Finally only succeeded by using this [workaround](https://stackoverflow.com/questions/27522728/unable-to-compile-the-gwt-module-while-trying-to-use-javax-annotation-nullable), although I added mentioned 'com.google.code.findbugs:jsr305:3.0.2:sources' package. But don't want to spam the issue with unrelated content. Thx for your help.

**Comment by braandl** [comment]
Adding the [workaround](https://stackoverflow.com/questions/27522728/unable-to-compile-the-gwt-module-while-trying-to-use-javax-annotation-nullable) and including

    api ("com.google.gwt:gwt-user:2.8.2:sources")

did fix the issue for me.

**Comment by MobiDevelop** [comment]
We've now updated to GWT 2.8.2.
