### ISSUE TITLE
Libgdx project fails to compile with 'Cannot change strategy of configuration ':android:natives'' after it has been resolved.

### ISSUE THREAD

**Issue by tpatikirikorala** [libgdx/libgdx#5303]
The issue is very easy to recreate using either latest versions of IDEA or Android studio. 

**Steps**
_1. Using latest libgdx project creator (gdx-setup.jar) create android project (no other platforms)._

_2. add following to the root gradle file under build script/dependencies_

classpath 'com.google.gms:google-services:4.0.0'
Then add following to the gradle file or android module

apply plugin: 'com.google.gms.google-services'

_3. When sync and compile follwoing error is thrown._

**_Cannot change strategy of configuration ':android:natives' after it has been resolved._**

If I comment out apply plugin: 'com.google.gms.google-services' I can compile and run but this causes issues with fire base.

**How do I get around this?**

The detailed error as follows

org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':android'.
    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:66)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
    at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
    at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:667)
    at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:136)
    at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
    at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:261)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
    at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:173)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
    at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:110)
    at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:87)
    at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:84)
    at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
    at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
    at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:84)
    at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:64)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
    at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)

**Comment by itsabhiaryan** [comment]
Same issue with updated current version of **Google Services Gradle Plugin 4.0.1**

`classpath 'com.google.gms:google-services:4.0.1'`

**Comment by tpatikirikorala** [comment]
I can not even figure out who has to fix it, is it Libgdx|google|Gradle|IDEA.

**Comment by itsabhiaryan** [comment]
I tested `'com.google.gms:google-services:4.0.1'` with Android native application with different combinations 

`Gradle 3.3`  +` 'com.android.tools.build:gradle:2.3.3'` + `'com.google.gms:google-services:4.0.1'`
`Gradle 4.4`  +` 'com.android.tools.build:gradle:2.3.3'` + `'com.google.gms:google-services:4.0.1'`
`Gradle 4.4`  +` 'com.android.tools.build:gradle:3.1.3'` +`'com.google.gms:google-services:4.0.1'`

It works in all combinations so I think it's not problem of `google-service plugin` or `Gradle` .

**Comment by naveenBhaskarSingh** [comment]
Same issue is coming with 3.3.0 and 3.3.1. Working fine till 3.2.1.

**Comment by Tom-Ski** [comment]
Can you please post the full reproduction steps? How are you running? What are your relevent IDE settings?

Using Gradle wrapper 4.6, 4.0.1 google-services and 3.1.3 android gradle tools plugin, I have no problem building on command line.

**Comment by tpatikirikorala** [comment]
I installed fresh Android studio 3 and IDEA and then used code base generated by latest gdx-setup.jar.
Then just add google-services statements to root and app modules. 
yes org.gradle.configureondemand=false

**Comment by Tom-Ski** [comment]
This does not disable configure on demand in ide.On 13 Jul 2018 11:47, Tha Pa <notifications@github.com> wrote:I installed fresh Android studio 3 and IDEA and then used code base generated by latest gdx-setup.jar.
Then just add google-services statements to root and app modules.
yes org.gradle.configureondemand=false

**Comment by obigu** [comment]
@Tom-Ski is right, it works ok (at least on Idea) as long as you disable configure on demand on the IDE

Go to Settings -> Build, Execution, Deployment -> Gradle Android Compiler -> Configure on Demand

**Comment by ilyaklyukin** [comment]
resolved by placing call of
apply plugin: 'com.google.gms.google-services'
before
task copyAndroidNatives() {

**Comment by rizal-rovins** [comment]
> @Tom-Ski is right, it works ok (at least on Idea) as long as you disable configure on demand on the IDE
> 
> Go to Settings -> Build, Execution, Deployment -> Gradle Android Compiler -> Configure on Demand
> 
> UPDATE: Also make sure you apply the plugin at the BOTTOM as specified in the docs:
> 
> > Add dependencies for basic libraries required for the services you have enabled. This step requires that the apply plugin: 'com.google.gms.google-services' line be at the **bottom** of your app/build.gradle file so that no dependency collisions are introduced. You can see the result of this step by running ./gradlew :app:dependencies.

Go to Settings -> Build, Execution, Deployment -> Gradle Android Compiler -> Configure on Demand
There is no option to disable configure on demand  in my android studio 3.2.1

**Comment by ahmed7official** [comment]
> resolved by placing call of
> apply plugin: 'com.google.gms.google-services'
> before
> task copyAndroidNatives() {
This work with me

**Comment by ilyaklyukin** [comment]
After convert to AndroidX approach described above didn;t help.
Fixed with changing:

`task copyAndroidNatives() {
    file("libs/armeabi/").mkdirs()
    file("libs/armeabi-v7a/").mkdirs()
    file("libs/arm64-v8a/").mkdirs()
    file("libs/x86/").mkdirs()
    file("libs/x86_64/").mkdirs()

    configurations.getByName("natives").copy().files.each { jar ->
        def outputDir = null
        if (jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
        if (jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
        if (jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
        if (jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
        if (jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
        if (outputDir != null) {
            copy {
                from zipTree(jar)
                into outputDir
                include "*.so"
            }
        }
    }
}`

**Comment by Tonielro** [comment]
@ilyaklyukin your solution saved my day.

After convert to AndroidX approach described above didn;t help.
Fixed with changing:

`
task copyAndroidNatives() {
file("libs/armeabi/").mkdirs()
file("libs/armeabi-v7a/").mkdirs()
file("libs/arm64-v8a/").mkdirs()
file("libs/x86/").mkdirs()
file("libs/x86_64/").mkdirs()

configurations.getByName("natives").copy().files.each { jar ->
    def outputDir = null
    if (jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
    if (jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
    if (jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
    if (jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
    if (jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
    if (outputDir != null) {
        copy {
            from zipTree(jar)
            into outputDir
            include "*.so"
        }
    }
}
}`

**Comment by dunno7** [comment]
> @ilyaklyukin your solution saved my day.
> 
> After convert to AndroidX approach described above didn;t help.
> Fixed with changing:
> 
> `
> task copyAndroidNatives() {
> file("libs/armeabi/").mkdirs()
> file("libs/armeabi-v7a/").mkdirs()
> file("libs/arm64-v8a/").mkdirs()
> file("libs/x86/").mkdirs()
> file("libs/x86_64/").mkdirs()
> 
> configurations.getByName("natives").copy().files.each { jar ->
> def outputDir = null
> if (jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
> if (jar.name.endsWith("natives-armeabi.jar")) outputDir = file("libs/armeabi")
> if (jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
> if (jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
> if (jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
> if (outputDir != null) {
> copy {
> from zipTree(jar)
> into outputDir
> include "*.so"
> }
> }
> }
> }`

This is correct one! Thanks you !!!
