### ISSUE TITLE
Libgdx Scene2D TextArea ArrayIndexOutOfBoundsException when clicking on empty first line

### ISSUE THREAD

**Issue by PeanutPanda** [libgdx/libgdx#5309]
When clicking on the first line of a Textarea that is empty, the exception occurs.
This only happens when the first line is empty (for instance after entering on the first line).
Always reproducible.

1. Make sure first line is empty (not even spaces) by just pressing ENTER
2. Click on that first line
3. Crash

```java
 public TextArea textArea;

 @Override
    public void create() {
        this.textArea = new TextArea("", skin);
     
        Table root = new Table();
        Table left = new Table();
        ScrollPane leftScrollPane = new ScrollPane(inputField, skin);
        root.add(left);
        stage.addActor(root);
    }

 @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }

 @Override
    public void render() {
        Gdx.gl.glClearColor(40f / 255f, 40f / 255f, 40f / 255f, 1f);
        Gdx.gl.glBlendFunc(GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        stage.act();
        stage.draw();
   }

 @Override
    public void dispose() {
        stage.dispose();
        assetLoader.manager.dispose();
   }
```

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.8
Vis-UI 1.4.0 (VisUI is not yet used in the app, but is a part of the used Skin)

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.badlogic.gdx.scenes.scene2d.ui.TextArea.letterUnderCursor(TextArea.java:91)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.setCursorPosition(TextField.java:850)
	at com.badlogic.gdx.scenes.scene2d.ui.TextArea$TextAreaListener.setCursorPosition(TextArea.java:391)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.touchDown(TextField.java:828)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:280)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:329)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Not reproducable on master, and this code doesn't compile either.
