### ISSUE TITLE
Libgdx Scene2D TextArea ArrayIndexOutOfBoundsException when clicking on empty first line

### ISSUE THREAD

**Issue by PeanutPanda** [libgdx/libgdx#5319]
When clicking on the first line of a Textarea that is empty while the cursor is on another line, the exception occurs.
This only happens when the first line is empty AND has a linebreak (for instance after entering on the first line).
Always reproducible.

- Make sure first line is empty (not even spaces)
- Press ENTER so the cursor moves to the second line
- Click on the first line
- Crash

#### Version of LibGDX and/or relevant dependencies
Libgdx 1.9.9-SNAPSHOT

```java
import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextArea;
import com.badlogic.gdx.utils.viewport.ScreenViewport;

public class TextAreaTest extends Game {

    private Stage stage;

    @Override
    public void create() {
        Skin skin = new Skin(Gdx.files.internal("skin/uiskin.json"));
        this.stage = new Stage(new ScreenViewport());
        Gdx.input.setInputProcessor(stage);
        TextArea textArea = new TextArea("", skin);
        Table root = new Table();
        root.add(textArea).size(1000);
        stage.addActor(root);
        root.setFillParent(true);
        textArea.setDebug(true);
    }

    @Override
    public void resize(int width, int height) {
        stage.getViewport().update(width, height, true);
    }

    @Override
    public void render() {
        Gdx.gl.glClearColor(40f / 255f, 40f / 255f, 40f / 255f, 1f);
        Gdx.gl.glBlendFunc(GL20.GL_SRC_ALPHA, GL20.GL_ONE_MINUS_SRC_ALPHA);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        stage.act();
        stage.draw();

    }

    @Override
    public void dispose() {
        stage.dispose();
    }

    // DesktopLauncher
    public static void main(String[] args) {
        LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
        config.width = 1024;
        config.height = 768;
        new LwjglApplication(new TextAreaTest(), config);
    }
}
```

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.badlogic.gdx.scenes.scene2d.ui.TextArea.letterUnderCursor(TextArea.java:91)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.setCursorPosition(TextField.java:850)
	at com.badlogic.gdx.scenes.scene2d.ui.TextArea$TextAreaListener.setCursorPosition(TextArea.java:391)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField$TextFieldClickListener.touchDown(TextField.java:828)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:280)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:329)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by PeanutPanda** [comment]
Previous issue was closed due to 
 "Not reproducable on master, and this code doesn't compile either."

This should now compile. Also this always happens on every new project.

**Comment by mgsx-dev** [comment]
I reproduce it with libgdx TextAreaTest by removing all characters from first line (living a blank line), click on another line and then click on the first line.
