### ISSUE TITLE
IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.g2d.ParticleEmitter.SpawnShape.false

### ISSUE THREAD

**Issue by Airsaid** [libgdx/libgdx#5342]
#### Issue details
Use the .p file created in the wiki's particle editor (http://libgdx.badlogicgames.com/nightlies/) to report errors when running in code:

``` java
Exception in thread "LWJGL Application" java.lang.RuntimeException: Error parsing emitter: boom
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:1160)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.<init>(ParticleEmitter.java:103)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.newEmitter(ParticleEffect.java:227)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.loadEmitters(ParticleEffect.java:173)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.load(ParticleEffect.java:153)
	at com.github.airsaid.sample.ParticleSample.create(ParticleSample.java:24)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.g2d.ParticleEmitter.SpawnShape.false
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShape.valueOf(ParticleEmitter.java:1637)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShapeValue.load(ParticleEmitter.java:1622)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:1107)
	... 7 more
```

#### Reproduction steps/code
Use code:
``` java
public class ParticleSample extends Game {

    private ParticleEffect particleEffect;
    private SpriteBatch batch;

    @Override
    public void create() {
        batch = new SpriteBatch();

        particleEffect = new ParticleEffect();
        particleEffect.load(Gdx.files.internal("particle/boom.p"), Gdx.files.internal("particle"));
        particleEffect.setPosition(Gdx.graphics.getWidth() / 2, Gdx.graphics.getHeight() / 2);
    }

    @Override
    public void render() {
        super.render();
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        batch.begin();
        float deltaTime = Gdx.graphics.getDeltaTime();
        particleEffect.draw(batch, deltaTime);
        batch.end();
    }

    @Override
    public void dispose() {
        super.dispose();
        particleEffect.dispose();
        batch.dispose();
    }
}
```

#### Version of LibGDX and/or relevant dependencies
```
gdxVersion = '1.9.8'
roboVMVersion = '2.3.3'
box2DLightsVersion = '1.4'
ashleyVersion = '1.7.0'
aiVersion = '1.8.0' 
```

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.RuntimeException: Error parsing emitter: boom
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:1160)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.<init>(ParticleEmitter.java:103)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.newEmitter(ParticleEffect.java:227)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.loadEmitters(ParticleEffect.java:173)
	at com.badlogic.gdx.graphics.g2d.ParticleEffect.load(ParticleEffect.java:153)
	at com.github.airsaid.sample.ParticleSample.create(ParticleSample.java:24)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.lang.IllegalArgumentException: No enum constant com.badlogic.gdx.graphics.g2d.ParticleEmitter.SpawnShape.false
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShape.valueOf(ParticleEmitter.java:1637)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter$SpawnShapeValue.load(ParticleEmitter.java:1622)
	at com.badlogic.gdx.graphics.g2d.ParticleEmitter.load(ParticleEmitter.java:1107)
	... 7 more
```

.p File（Easy to upload and modify to .txt）：

[boom.txt](https://github.com/libgdx/libgdx/files/2279864/boom.txt)

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [x] MacOS

**Comment by NathanMBui** [comment]
You should use the same version of both ParticleEditor (nightly = 19.9-SNAPSHOT for now) and libgdx(1.9.8)

**Comment by Airsaid** [comment]
Where should I download this version?

**Comment by Airsaid** [comment]
I looked up the problem according to the source code, and found that the problem was in the code that did not parse the independent attribute.

So, my solution now is to manually remove what the editor generates each time:
```
relative: false
```

**Comment by NathanMBui** [comment]
Are you using gradle?. just change gdx version in root/build.gradle then sync your project

**Comment by Airsaid** [comment]
Currently my libGDX version is: 1.9.8.

Where should I go to download the version of the Particle Editor?

**Comment by NathanMBui** [comment]
I cant find the jar file for it. You may need to run/build it from source
[https://github.com/libgdx/libgdx/releases](url)

**Comment by Airsaid** [comment]
Ok, Thank you.

**Comment by metaphore** [comment]
It's actually a bit frustrating fact that there are no tools' distributions for the latest stable release at all. It doesn't feel like a right thing to do, keep only bleeding edge nightly version available publicly on the site. many new devs could be confused with the same problem as they may don't realize those breaking changes and compatibility issues, and they most likely won't build them from source, rather then just look for a distribution executable. I guess the same is about stable compiled jar release files, looks like they are also absent on the site. 

@badlogic what do you think?

**Comment by obigu** [comment]
I definitely agree the Tools Jars should be available for the latest stable release and not only the nighly build. The fact that libGDX hasn't had a stable release for so long makes it worse.

Best chance to get a reply is from @Tom-Ski , @badlogic is not actively mantaining the project atm.
