### ISSUE TITLE
load obj faces too more?

### ISSUE THREAD

**Issue by hillday** [libgdx/libgdx#5343]
#### Issue details
when load a .obj file catch a exception with Invalid part specified ( offset=0, count=0, max=80268 ),i debug it foud `final int numIndices = numFaces * 3 >= Short.MAX_VALUE ? 0 : numFaces * 3;`.it's mean can not load obj face more than Short.MAX_VALUE?
#### Reproduction steps/code
```java
        ModelLoader<?> loader = new ObjLoader();
        Gdx.app.log("loading","begin load...");
        model = loader.loadModel(Gdx.files.internal("data/b.obj"));
````

#### Stacktrace
```java
 com.badlogic.gdx.utils.GdxRuntimeException: Invalid part specified ( offset=0, count=0, max=80268 )
                      at com.badlogic.gdx.graphics.Mesh.extendBoundingBox(Mesh.java:637)
                      at com.badlogic.gdx.graphics.Mesh.extendBoundingBox(Mesh.java:622)
                      at com.badlogic.gdx.graphics.Mesh.calculateBoundingBox(Mesh.java:604)
                      at com.badlogic.gdx.graphics.g3d.model.MeshPart.update(MeshPart.java:124)
                      at com.badlogic.gdx.graphics.g3d.Model.convertMesh(Model.java:263)
                      at com.badlogic.gdx.graphics.g3d.Model.loadMeshes(Model.java:231)
                      at com.badlogic.gdx.graphics.g3d.Model.load(Model.java:106)
                      at com.badlogic.gdx.graphics.g3d.Model.<init>(Model.java:102)
                      at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:54)
                      at com.badlogic.gdx.assets.loaders.ModelLoader.loadModel(ModelLoader.java:69)
                      at com.mygdx.game.LoadObjTest.create(LoadObjTest.java:46)
                      at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1555)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
Please supply the obj file your trying to load.
Although you are correct, you cannot load more than Short.MAX_VALUE vertecies and I'm fairly sure faces too, this is stated in the docs and wiki.

**Comment by EtK2000** [comment]
Can you please supply the model which you're failing to load, otherwise this issue is useless.

**Comment by RUSshy** [comment]
I think this is limitation to the 3D pipeline since they use short for indices

To lift this limitation, should change Mesh to use int instead of short

But i'm not sure

ping @xoppa

**Comment by RUSshy** [comment]
Why close ?

This is valid issue, opengl supports in32 indices, there is no valid reason to stick to that limitation

**Comment by EtK2000** [comment]
Take it up with someone who has a say with this.
I would ping someone else, I don't know how often xoppa is checking issues.

**Comment by mgsx-dev** [comment]
as per #3386 i think this issue can be rejected.

**Comment by russelRajitha** [comment]
is there any solution for this? um also stuck in this for days

**Comment by RUSshy** [comment]
@mgsx-dev this is stupid reasoning, how can someone that is external to the project OP is making can make assumptions about his needs

just do like every other libs and put an enum, so people will choose what they want to use

opengl supports in32 indices


"i am an opengl game lib, but fuck opengl i don't support it, but i stick with it" this is stupid

**Comment by yuripourre** [comment]
@RUSshy

I do not think that it's stupid, it is a way to keep it efficient in most cases. Not all libgdx apps uses complex models and it is very easy to add new importers.

**Comment by RUSshy** [comment]
assuming people don't need it is stupid

want to render bigger model ? oh you run out of space for indices, you are now forced to split your mesh in two, so you waste 2x more memory

that's why other libs suport in32 indices, they are future proof, libgdx is not

**Comment by russelRajitha** [comment]
I think i found the issue. i fixed this by changing file path to absolute from blender. here what happened is files are saved in another location and i exported as `.obj` or `.g3db `or any type of libgdx supported one and moved it to my project. but it makes this error. then i created new project in assets folder using blender and set **external data to make all paths as absolute** in blender. we have to do all blender things with keeping all file in assets folder of libgdx project. then export `.obj or .g3db`. and dont forget following steps in blender.
```
Shading -> material mode -> GLSL
ViewPortShading-> texture
```

**Comment by mgsx-dev** [comment]
I tested it and there is no errors, apparently fixed in https://github.com/libgdx/libgdx/commit/d7fa8a0037ceb94f45b1a1877f74b70fb3751ed9
you can have as many vertices as you want with OBJ files since indexing is disabled for large meshes.
