### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown by IntMap

### ISSUE THREAD

**Issue by WinterAlexander** [libgdx/libgdx#5359]
#### Issue details
Seems similar to #3826. I could never reproduce this issue on my computer. My game automatically reports crashes and this was submitted by a player. It appears that in IntMap:

```
int index = key & mask;
if (keyTable[index] != key) {
// ...
```
The index was out of range for the keyTable array. This code is not fail safe? What could trigger this problem? The map wasn't used at lot, it probably crashed in the very first usage of the map (or in the very first usages). The caller does nothing weird:

```
@Override
public BiomeType getBiomeAt(float x, float y)
{
	BiomeType biome = content.get(key(x, y));

	return biome == null ? defaultBiome : biome;
}
```

where `content` is the said IntMap.

IntMap is initialized like this:

`protected final IntMap<BiomeType> content = new IntMap<>();`

#### Reproduction steps/code
I'd love to be able to reproduce the issue. I'm looking for suggestions on that and possible causes of that crash. The issue doesn't seem linked to weird usage.

#### Version of LibGDX and/or relevant dependencies
LibGDX version 1.9.8

#### Crash report
I'm sorry about the incompleteness of my crash reporter. Next version will feature java version, OS and architecture. I'm 90% sure that it was on windows 64 bits, I can confirm that later.

```java
Version: 0.3.0
Date: Mon Aug 20 17:34:42 EDT 2018
Cause: java.lang.ArrayIndexOutOfBoundsException: 1021
	at com.badlogic.gdx.utils.IntMap.get(IntMap.java:306)
	at net.jumpai.world.biome.LevelBiomeMap.getBiomeAt(LevelBiomeMap.java:48)
	at net.jumpai.world.biome.BiomeMap.getBiomeAt(BiomeMap.java:23)
	at net.jumpai.world.component.location.Localizable.getBiome(Localizable.java:37)
	at net.jumpai.client.editor.components.render.RoughBiomeTileRenderer.render(RoughBiomeTileRenderer.java:98)
	at net.jumpai.world.component.render.Renderable.render(Renderable.java:38)
	at net.jumpai.client.editor.EditorScreen.renderScene(EditorScreen.java:213)
	at net.jumpai.client.StagedSceneScreen.render(StagedSceneScreen.java:140)
	at net.jumpai.client.StagedSceneScreen.render(StagedSceneScreen.java:81)
	at net.jumpai.render.ScreenStackGame.render(ScreenStackGame.java:208)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

Loggers: 3
Logs: 
17:34:06 [INFO] Logger enabled with level DEBUG
17:34:06 [INFO] Jumpaï v0.3.0
17:34:07 [DEBUG] New AssetLoadingScreen added, first in stack
17:34:22 [INFO] Assets finished loading
17:34:22 [INFO] Playing demo id 3
17:34:24 [DEBUG] AssetLoadingScreen finished, replacing with TitleScreen
17:34:33 [DEBUG] New TransitionScreen added, previous was TitleScreen
17:34:34 [DEBUG] TransitionScreen finished, replacing with OnlineGameScreen
17:34:34 [INFO] Welcomed by server on level 235
17:34:36 [DEBUG] Leave packet sent
17:34:36 [DEBUG] OnlineGameScreen finished by replaceAll
17:34:36 [DEBUG] Replacing with TransitionScreen
17:34:37 [DEBUG] TransitionScreen finished, replacing with EditorScreen
17:34:37 [DEBUG] Leave success:true open: false
17:34:42 [ERROR] FATAL ERROR: Game has just crashed
java.lang.ArrayIndexOutOfBoundsException: 1021
	at com.badlogic.gdx.utils.IntMap.get(IntMap.java:306)
	at net.jumpai.world.biome.LevelBiomeMap.getBiomeAt(LevelBiomeMap.java:48)
	at net.jumpai.world.biome.BiomeMap.getBiomeAt(BiomeMap.java:23)
	at net.jumpai.world.component.location.Localizable.getBiome(Localizable.java:37)
	at net.jumpai.client.editor.components.render.RoughBiomeTileRenderer.render(RoughBiomeTileRenderer.java:98)
	at net.jumpai.world.component.render.Renderable.render(Renderable.java:38)
	at net.jumpai.client.editor.EditorScreen.renderScene(EditorScreen.java:213)
	at net.jumpai.client.StagedSceneScreen.render(StagedSceneScreen.java:140)
	at net.jumpai.client.StagedSceneScreen.render(StagedSceneScreen.java:81)
	at net.jumpai.render.ScreenStackGame.render(ScreenStackGame.java:208)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

---------
Account IsLogged: true
UserId: 68
Username: Nexred76
Token: 6c2b1087-a2d5-4115-a0be-2919eb51819468
Loaded assets: 366
Locale: fr
Screen stack: 2
	TitleScreen
	EditorScreen
```

For sake of completeness, here's the full code of that part using the map: https://hastebin.com/gezutuwubu.java
Reading the stack trace, the scenario is that a `EditorBiomeMap` was initialized and got passed another `LevelBiomeMap`. This means `content.putAll(other.content);` was called.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Darkyenus** [comment]
As mentioned in the issue you have linked, these hard to reproduce errors that don't make much sense usually hint at threading issues (at your side). You probably don't have enough synchronization somewhere in the code that interacted with the collection at the time of crash or *earlier*.

 libGDX collections are used often, so they are pretty robust - as are desktop JVMs, so please first check your code.

**Comment by WinterAlexander** [comment]
@Darkyenus Thanks for the pointer, will make sure to check all possible problems with multithreading.

**Comment by WinterAlexander** [comment]
Found a possible cause in my cause, will reopen if I find evidence that it doesn't come from me.
