### ISSUE TITLE
building libGDX from source fail with the `./gradlew fetchNatives` command

### ISSUE THREAD

**Issue by julienvillegas** [libgdx/libgdx#5375]
#### Issue details
building libGDX from source fail with the `./gradlew fetchNatives` command
It seems some certificate have expired or are not valid.
Running with --scan provide more details available in the stacktrace below.

I have the latest Java JDK installed: Java 8 update 181 (In the instructions it specifies that not having an updated JDK could be a source of error)

#### Reproduction steps/code

Execute the instructions as outlined here: https://libgdx.badlogicgames.com/documentation/hacking/Working%20from%20source.html#importing-into-intellij

When you run ./gradlew fetchNatives
you will get error below.

#### Version of LibGDX and/or relevant dependencies
LibGDX: Version 1.9.9-SNAPSHOT
MacOX:  10.13.6

#### Stacktrace
```java

Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.12.1/build-scan-plugin-1.12.1.pom
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.12.1/build-scan-plugin-1.12.1.jar

> Configure project :tests:gdx-tests-android 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018

> Configure project :tests:gdx-tests-ios-intel 
Using already downloaded SDK: /Users/julienvillegas/.moe/moe-sdk-1.4.0


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/julienvillegas/code/libgdx/build.gradle' line: 53

* What went wrong:
Execution failed for task ':fetch'.

The :fetch task failed.
Build file '/Users/julienvillegas/code/libgdx/build.gradle' line: 53
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    > unable to find valid certification path to requested target

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':fetch'.Open stacktrace
Caused by: org.apache.tools.ant.BuildException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetOpen stacktrace
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetOpen stacktrace
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetOpen stacktrace
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetClose stacktrace
at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:737)
at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:757)
at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:650)
at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:640)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by Tom-Ski** [comment]
Provide ./gradlew --version info

**Comment by julienvillegas** [comment]
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_72 (Oracle Corporation 25.72-b15)
OS:           Mac OS X 10.13.6 x86_64

**Comment by Tom-Ski** [comment]
`1.8.0_72` You are using a jdk version under the required verison.

**Comment by julienvillegas** [comment]
Thanks and sorry Tomski, I had foolishly updated java, not the JDK..
