### ISSUE TITLE
IndexOutOfBoundsException after scrolling ScrollPane

### ISSUE THREAD

**Issue by retrodaredevil** [libgdx/libgdx#5431]
**EDIT**: The problematic code was me removing something I added to the table the wrong way.

For whatever reason, I was using:
```java
actor.remove();
table.getCells().removeValue(actorCell, true);
table.invalidate
```
when this would have worked better:
```java
table.removeActor(actor);
```

**The issues has been fixed, closing issue.**

#### Issue details
Whenever I scroll a scroll pane then resize that scroll pane I get an IndexOutOfBoundsException. This is only after I had scrolled that scroll pane. If just the content table is resized and the scroll pane hasn't been scrolled, it works normally.
EDIT: I believe 

#### Reproduction steps/code
- Have a ScrollPane and fill its content table so you are able to scroll
- scroll on the scroll pane by dragging
- remove something from the content table so you cannot scroll anymore
- You should get an IndexOutOfBoundsException

This happens in my main render loop after things have been removed so it's not happening when I actual remove the cell from the content table or in my case, the cell in the table that's in the content table.

OR: 

```java
// look at second stacktrace for this
container.remove();
table.getCells().removeValue(containerCell, true);
table.invalidate();
```

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._
```groovy
// straight from my build.gradle in root of project:
ext {
        appName = "Track Shooter"
        gdxVersion = '1.9.8'
        roboVMVersion = '2.3.3'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
 }
```

#### Stacktrace
```java
Process: me.retrodaredevil.game.trackshooter, PID: 7891
    java.lang.IndexOutOfBoundsException: index can't be >= size: 8 >= 3
        at com.badlogic.gdx.utils.Array.get(Array.java:154)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:826)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:401)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:65)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:835)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:401)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:65)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:835)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefHeight(Table.java:408)
        at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.getPrefHeight(ScrollPane.java:647)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$4.get(Value.java:74)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:836)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:401)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:65)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:835)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:961)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:757)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.validate(WidgetGroup.java:115)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:101)
        at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:249)
        at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
        at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
        at me.retrodaredevil.game.trackshooter.util.RenderUtil.drawStage(RenderUtil.java:36)
        at me.retrodaredevil.game.trackshooter.render.Renderer.render(Renderer.java:76)
        at me.retrodaredevil.game.trackshooter.StartScreen.render(StartScreen.java:108)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at me.retrodaredevil.game.trackshooter.GameMain.render(GameMain.java:150)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:495)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

Second stacktrace: from piece of code
```java
    java.lang.IndexOutOfBoundsException: index can't be >= size: 10 >= 10
        at com.badlogic.gdx.utils.Array.get(Array.java:154)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:826)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:961)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.layout(Table.java:757)
        at me.retrodaredevil.game.trackshooter.render.selection.ContainerSingleOption.remove(ContainerSingleOption.java:76)
 ...
```
Is there a way to remove the containerCell from the table without messing up other cells?

**Comment by NathanSweet** [comment]
Note either of these would work:
```
actor.remove();
table.removeActor(actor);
```
