### ISSUE TITLE
android: Couldn't load shared library 'gdx' for target: Linux, 32-bit

### ISSUE THREAD

**Issue by sadeghpro** [libgdx/libgdx#5438]
#### Issue details
hi,
I create my first project with libgdx it's cool and work nice on desktop but when i want to run it on android give me a error.
I develop on mac and use intellij

#### Version of LibGDX and/or relevant dependencies
Gdx version: 1.9.8

#### Stacktrace
```11-02 00:43:24.320 14035-14035/ir.sadeghpro.game E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1319)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1054)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2223)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
        at android.app.ActivityThread.access$600(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:153)
        at android.app.ActivityThread.main(ActivityThread.java:5299)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33)
        at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:63)
        at java.lang.Class.newInstanceImpl(Native Method) 
        at java.lang.Class.newInstance(Class.java:1319) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1054) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2223) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358) 
        at android.app.ActivityThread.access$600(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:153) 
        at android.app.ActivityThread.main(ActivityThread.java:5299) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.UnsatisfiedLinkError: Couldn't load gdx from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ir.sadeghpro.game-1.apk"],nativeLibraryDirectories=[/data/app-lib/ir.sadeghpro.game-1, /vendor/lib, /system/lib]]]: findLibrary returned null
        at java.lang.Runtime.loadLibrary(Runtime.java:359)
        at java.lang.System.loadLibrary(System.java:514)
        at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:119)
        at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33) 
        at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:63) 
        at java.lang.Class.newInstanceImpl(Native Method) 
        at java.lang.Class.newInstance(Class.java:1319) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1054) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2223) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358) 
        at android.app.ActivityThread.access$600(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:153) 
        at android.app.ActivityThread.main(ActivityThread.java:5299) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
        at dalvik.system.NativeStart.main(Native Method) 

```

#### Please select the affected platforms
- [ * ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

**Comment by Tom-Ski** [comment]
Use the android:copyNatives Task located in the android/build.gradle file

**Comment by sadeghpro** [comment]
tnx @Tom-Ski  I use `task copyAndroidNatives {` but I get this error:
```
2:07:07 PM: Executing task 'copyAndroidNatives'...

The newly created daemon process has a different context than expected.
Java home is different.
Expecting: '/Applications/IntelliJ IDEA.app/Contents/jdk/Contents/Home' but was: '/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home'.
Please configure the JDK to match the expected one.
Open JDK Settings
2:07:10 PM: Task execution finished 'copyAndroidNatives'.
```

I use custom jdk not intellij jdk.
Is there any way to fix this jdk path beacuse I give this error when run html platform too

**Comment by sadeghpro** [comment]
tnx @Tom-Ski 
I fix my problem with setting following in `gradle.properties` in project level or in `~/.gradle/gradle.properties` (if not exist create yourself):
```org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home```

**Comment by fanqaz** [comment]
.so文件没有。需要在Terminal 中运行 gradlew  fetchNatives

这个task在libgdx下面的build.gradle里。如下：
task fetchNatives {
    doLast {
        ant.importBuild "fetch.xml"
        fetch.execute()
        copy.execute()
        
    }
}

**Comment by hoangcongtuan** [comment]
> .so文件没有。需要在Terminal 中运行 gradlew fetchNatives
> 
> 这个task在项目下面的build.gradle里。如下：
> task fetchNatives {
> doLast {
> ant.importBuild "fetch.xml"
> fetch.execute()
> copy.execute()
> 
> ```
> }
> ```
> }

how i get fetch.xml file?
