### ISSUE TITLE
JoGL + controllers : fail

### ISSUE THREAD

**Issue by alexis-puska** [libgdx/libgdx#5442]
#### Issue details
Hi all, i made a reboo of bomberman to desktop (win, unix, mac) and raspberry pi, my project is here : https://github.com/alexis-puska/MultiBomberman
I have made a subproject for raspberry pi based on JoGL backend, i have found a repository with the backend compiled with libGDX 1.9.8, when a call the method  static private void initialize () of Controllers.java , the programs crash with the stack trace attached in this issues. 

#### Reproduction steps/code
```java
public void resize(int width, int height) {
		this.viewport.update(width, height, true);
		Gdx.app.log(LOG_NAME, "RESIZE");
		try {
			Thread.sleep(500);
			Controllers.clearListeners(); // make call to initialize();
			Controllers.addListener(controllerAdapter);
		} catch (InterruptedException e) {
			Gdx.app.error("MultiBomberman", "Resize thread error");
			Thread.currentThread().interrupt();
		}
	}
```

```java
Array<Controller> controllers = Controllers.getControllers(); // make call to initialize();
```

 Why in this enum of graphic type that not list JoGL ?
```java
code inside JoGL : 
@Override
public GraphicsType getType () {
	return GraphicsType.Jogl;
}
```

code inside LibGdx
```java
public interface Graphics {
	/** Enumeration describing different types of {@link Graphics} implementations.
	 *
	 * @author mzechner */
	public enum GraphicsType {
		AndroidGL, LWJGL, WebGL, iOSGL, JGLFW, Mock, LWJGL3
	}
```

#### Version of LibGDX and/or relevant dependencies
1.9.8

#### Stacktrace
```java
Exception in thread "main-Animator#00" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught NoSuchFieldError: JoglGL on thread main-Animator#00
        at com.jogamp.opengl.util.DefaultAnimatorImpl.display(DefaultAnimatorImpl.java:68)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.Animator$MainLoop.run(Animator.java:204)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.jogamp.opengl.GLException: Caught NoSuchFieldError: JoglGL on thread main-Animator#00
        at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.DefaultAnimatorImpl.display(DefaultAnimatorImpl.java:58)
        ... 3 more
Caused by: java.lang.NoSuchFieldError: JoglGL
        at com.badlogic.gdx.backends.jogamp.JoglGraphicsBase.getType(JoglGraphicsBase.java:366)
        at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:96)
        at com.badlogic.gdx.controllers.Controllers.clearListeners(Controllers.java:67)
        at com.mygdx.main.MultiBombermanGame.resize(MultiBombermanGame.java:127)
        at com.badlogic.gdx.backends.jogamp.JoglGraphicsBase.reshape(JoglGraphicsBase.java:164)
        at jogamp.opengl.GLDrawableHelper.reshape(GLDrawableHelper.java:751)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:440)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        ... 6 more
AL lib: (WW) FreeContext: (0x668c4c30) Deleting 16 Source(s)
AL lib: (WW) FreeDevice: (0x668cfac0) Deleting 18 Buffer(s)
EGLDisplayUtil.EGLDisplays: Shutdown (open: 1)
EGLDisplayUtil: Open EGL Display Connections: 1
EGLDisplayUtil: Open[0]: 0x1: EGLDisplayRef[0x1: refCnt 2]
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by EtK2000** [comment]
https://www.badlogicgames.com/wordpress/?p=2566

JoGL has been depricated and removed.
You might be able to got back to an older version that still has it.
That being said, this issue will not be fixed AFAIK due to the deprication.
Either find a way around it, or clone the repo and locally make changes.

**Comment by alexis-puska** [comment]
What backend is used for raspberry pi now ?

**Comment by EtK2000** [comment]
I don't know that.
Ask on the forums or irc.

This issue should be closed now.

**Comment by MobiDevelop** [comment]
libgdx hasn't supported JoGL for quite a few years. There's also no official support for Raspberry Pi at this time.
