### ISSUE TITLE
Cannot change attributes of configuration ':app:qaCompile' after it has been resolved

### ISSUE THREAD

**Issue by Kolyall** [libgdx/libgdx#5449]
Please ensure you have given all the following requested information in your report.

#### Issue details
sync failed with Cannot change attributes of configuration ':android:kapt' after it has been resolved message.

#### Reproduction steps/code
Using kotlin in Android Studio 3.2.1(Build #AI-181.5540.7.32.5056338, built on October 9, 2018 JRE: 1.8.0_152-release-1136-b06 amd64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o Windows 7 6.1) with Android Gradle version 3.2.1, 

#### Version of LibGDX and/or relevant dependencies
GdxVersion = 1.9.8
Android gradle plugin = 3.2.1
KotlinVersion = 1.3.10
GradleVersion = 4.6

#### Stacktrace
```java
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:667)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:136)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:261)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:173)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
	at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:110)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:87)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:84)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:84)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:64)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:49)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot change attributes of configuration ':app:qaCompile' after it has been resolved
	at org.gradle.api.internal.attributes.ImmutableAttributeContainerWithErrorMessage.attribute(ImmutableAttributeContainerWithErrorMessage.java:51)
	at org.jetbrains.kotlin.gradle.plugin.KotlinTargetConfiguratorKt.usesPlatformOf(KotlinTargetConfigurator.kt:721)
	at org.jetbrains.kotlin.gradle.plugin.ProjectLocalConfigurationsKt.setupAsLocalTargetSpecificConfigurationIfSupported(ProjectLocalConfigurations.kt:48)
	at org.jetbrains.kotlin.gradle.plugin.AbstractKotlinTargetConfigurator$Companion.defineConfigurationsForCompilation(KotlinTargetConfigurator.kt:255)
	at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler.setUpDependencyResolution(Android25ProjectHandler.kt:118)
	at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler.setUpDependencyResolution(Android25ProjectHandler.kt:20)
	at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2$1.invoke(KotlinPlugin.kt:668)
	at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2$1.invoke(KotlinPlugin.kt:616)
	at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler$sam$org_gradle_api_Action$0.execute(Android25ProjectHandler.kt)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
	at org.jetbrains.kotlin.gradle.plugin.Android25ProjectHandler.forEachVariant(Android25ProjectHandler.kt:26)
	at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2.execute(KotlinPlugin.kt:665)
	at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2.execute(KotlinPlugin.kt:616)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy31.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)
	... 85 more


```
**MyProject/build.gradle**
```
apply from: 'dependencies.gradle'
apply plugin: 'kotlin'

buildscript {
    ext.kotlin_version = '1.3.10'
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        //region realm
        maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local' }
        //endregion
    }
    dependencies {
        //region google()
        classpath 'com.android.tools.build:gradle:3.2.1'
        //endregion
        //region jcenter()
        classpath 'com.google.gms:google-services:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.orhanobut.tracklytics:tracklytics-plugin:2.0.0'
        //endregion
        //region maven { url 'https://maven.fabric.io/public' }
        //to check fabric gradle ver
        //https://s3.amazonaws.com/fabric-artifacts/public/io/fabric/tools/gradle/maven-metadata.xml
        classpath 'io.fabric.tools:gradle:1.+'
        //endregion
        //region realm
        classpath "io.realm:realm-gradle-plugin:5.4.2"
        //endregion
    }
}

allprojects {

    repositories {
        mavenLocal()
        google()
        jcenter()
        mavenCentral()

        maven { url "https://dl.bintray.com/nickunuchek/maven" }
        maven { url "https://jitpack.io" }
    }

    ext {
        androidApplicationId = 'com.example'
        androidVersionCode = 4
        androidVersionName = "1.1.6"
    }

    configurations.all {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jre7'

        resolutionStrategy {
            // fail eagerly on version conflict (includes transitive dependencies)
            // e.g. multiple different versions of the same dependency (group and name are equal)
            failOnVersionConflict()

            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version",
                    "com.android.support:appcompat-v7:${supportLibVer}",
                    "com.android.support:design:${supportLibVer}",
                    "com.squareup.okhttp3:okhttp:${okHttpVersion}",
                    "com.android.support:support-annotations:${supportLibVer}",
                    "com.android.support:mediarouter-v7:${supportLibVer}",

                    "io.fabric.sdk.android:fabric:1.4.2",
                    "commons-logging:commons-logging:1.2",
                    "io.reactivex:rxjava:${rxJavaVersion}",
                    "com.android.support:support-core-ui:${supportLibVer}",

                    "com.android.support:support-v4:${supportLibVer}",
                    "com.google.code.gson:gson:${gsonVersion}",

                    "com.android.support:support-compat:${supportLibVer}",
                    "org.apache.httpcomponents:httpcore:4.2.5",
                    "com.android.support:multidex:1.0.3",
                    "com.google.guava:guava:23.3-jre",
                    "com.google.auto:auto-common:0.8",
                    "com.squareup:javapoet:1.9.0"
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}

compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

```
**MyProject/app/build.gradle**
```
apply plugin: 'com.android.application'
apply plugin: 'com.orhanobut.tracklytics'   // Must be added after com.android.application
apply plugin: 'io.fabric'
apply plugin: 'kotlin-android'
apply from: 'customBuildConfigFieldsConfigurator.gradle'
apply from: 'fabric.gradle'
apply from: 'https://raw.githubusercontent.com/Kolyall/MavenPublish/master/apkrename.gradle'
apply from: 'https://raw.githubusercontent.com/Kolyall/MavenPublish/master/appVersion.gradle'
apply from: '../config/quality.gradle'

def gitSha = 'git rev-parse --short HEAD '.execute([], project.rootDir).text.trim()
def buildTime = new Date().format("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
android {
    compileSdkVersion androidCompileSdkVersion
    buildToolsVersion androidBuildToolsVersion

    defaultConfig {
        multiDexEnabled true

        applicationId androidApplicationId
        minSdkVersion androidMinSdkVersion
        targetSdkVersion androidTargetSdkVersion
        versionCode appVersionCode
        versionName appVersionName

        renderscriptTargetApi androidTargetSdkVersion
        renderscriptSupportModeEnabled true

        buildConfigField "String", "GIT_SHA", "\"${gitSha}\""
        buildConfigField "String", "BUILD_TIME", "\"${buildTime}\""

        //region Disable warnings on lib: com.hannesdorfmann.fragmentargs
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [ fragmentArgsLogWarnings: 'false' ]
                includeCompileClasspath true
            }
        }
        //endregion
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        disable 'InvalidPackage'           //Some libraries have issues with this.
        disable 'OldTargetApi'
        //Lint gives this warning but SDK 20 would be Android L Beta.
        disable 'IconDensities'            //For testing purpose. This is safe to remove.
        disable 'IconMissingDensityFolder' //For testing purpose. This is safe to remove.
    }

    signingConfigs {
        release {

            def signingPropertiesFile = file('properties/signing/signing.properties')
            def keystore = "keys/gramophone-android.jks";
            def keystorePassword = "Gramophone123";
            def keyalias = "gram";
            def keypassword = "Gramophone123";
            if (signingPropertiesFile.canRead()) {
                Properties properties = new Properties()
                properties.load(new FileInputStream(signingPropertiesFile))
                keystore = String.valueOf(properties['keystore']);
                keystorePassword = String.valueOf(properties['keystore.password']);
                keyalias = String.valueOf(properties['keyalias']);
                keypassword = String.valueOf(properties['keypassword']);
            } else {
                throw new Exception("Could not read properties/signing/signing.properties!")
            }

            storeFile file(keystore)
            storePassword keystorePassword
            keyAlias keyalias
            keyPassword keypassword
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            debuggable false
            signingConfig signingConfigs.release
            //region ---Adding properties/payment/release.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('release','properties/payment/release.properties')
            //endregion
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            proguardFiles fileTree(include: ['*.pro'], dir: '../modules/proguard').asList().toArray()
        }
        stage {
            versionNameSuffix "-stage"
            signingConfig signingConfigs.release
            debuggable true
            minifyEnabled true
            //region ---Adding properties/payment/release.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('stage','properties/payment/release.properties')
            //endregion
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            proguardFiles fileTree(include: ['*.pro'], dir: '../modules/proguard').asList().toArray()
        }
        debug {
            versionNameSuffix '-debug'
            signingConfig signingConfigs.release
            debuggable true
            minifyEnabled false
            ext.alwaysUpdateBuildId = false
            //region ---Adding properties/payment/debug.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('debug','properties/payment/debug.properties')
            //endregion
        }
        local {
            versionNameSuffix '-local'
            signingConfig signingConfigs.release
            debuggable true
            minifyEnabled false
            ext.alwaysUpdateBuildId = false
            //region ---Adding properties/payment/debug.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('local','properties/payment/debug.properties')
            //endregion
        }
        qa {
            versionNameSuffix '-qa'
            signingConfig signingConfigs.release
            debuggable true
            minifyEnabled false
            ext.alwaysUpdateBuildId = false
            //region ---Adding properties/payment/debug.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('qa','properties/payment/debug.properties')
            //endregion
        }
        develop {
            versionNameSuffix '-develop'
            applicationIdSuffix ".develop"
            signingConfig signingConfigs.release
            debuggable true
            minifyEnabled false
            ext.alwaysUpdateBuildId = false
            //region ---Adding properties/payment/debug.properties KEYs to BuildConfig---
            customBuildConfig.addAllFieldsFrom('develop','properties/payment/debug.properties')
            //endregion
        }
    }

    dexOptions {
        maxProcessCount 2
        javaMaxHeapSize "16g"
    }

    packagingOptions {
        exclude 'LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/rxjava.properties'
    }

    sourceSets {
        release {
            java.srcDirs('src/release/java')
        }
        stage {
            java.srcDirs('src/release/java')
        }
        debug {
            java.srcDirs('src/develop/java')
        }
        local {
            java.srcDirs('src/develop/java')
        }
        qa {
            java.srcDirs('src/develop/java')
        }
        develop {
            java.srcDirs('src/develop/java')
        }
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}"

    implementation "com.android.support:support-compat:${supportLibVer}"
    implementation "com.android.support:appcompat-v7:${supportLibVer}"
    implementation "com.android.support:support-v4:${supportLibVer}"
    implementation("com.android.support:gridlayout-v7:${supportLibVer}") {
        exclude group: "com.android.support"
    }
    implementation "com.android.support:cardview-v7:${supportLibVer}"
    implementation "com.android.support:recyclerview-v7:${supportLibVer}"
    implementation("com.android.support:preference-v14:${supportLibVer}") {
        exclude group: "com.android.support"
    }
    implementation "com.android.support:support-vector-drawable:${supportLibVer}"
    implementation "com.android.support:animated-vector-drawable:${supportLibVer}"
    implementation "com.android.support:mediarouter-v7:${supportLibVer}"
    implementation "com.android.support:leanback-v17:${supportLibVer}"
    implementation "com.android.support:design:${supportLibVer}"
    implementation "com.android.support:percent:${supportLibVer}"

//    implementation "com.google.android.gms:play-services-cast-framework:${googleLibVer}"

    implementation("com.google.android.exoplayer:exoplayer:2.7.3") {
        exclude group: "com.android.support"
    }

    // picasso
    implementation "com.squareup.picasso:picasso:${picassoVersion}"

    // dagger
    implementation("com.google.dagger:dagger-android-support:${daggerVersion}") {
        exclude group: "com.android.support"
    }
    annotationProcessor "com.google.dagger:dagger-compiler:${daggerVersion}"
    annotationProcessor "com.google.dagger:dagger-android-processor:${daggerVersion}"
    implementation "javax.annotation:jsr250-api:${javaxAnnotationVersion}"
    implementation "javax.inject:javax.inject:${javaxInjectVersion}"
//    provided "org.glassfish:javax.annotation:10.0-b28"

    // jake ftw
    annotationProcessor "com.jakewharton:butterknife-compiler:${butterKnifeVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // FragmentWithArgs
    implementation "com.hannesdorfmann.fragmentargs:annotation:${fragmentargsVersion}"
    annotationProcessor "com.hannesdorfmann.fragmentargs:processor:${fragmentargsVersion}"

    implementation "org.parceler:parceler-api:${parcelerVersion}"
    annotationProcessor "org.parceler:parceler:${parcelerVersion}"
    implementation "com.hannesdorfmann.fragmentargs:bundler-parceler:${parcelerbundlerVersion}"

    implementation "com.android.support:multidex:${multidexVersion}"

    implementation("com.crashlytics.sdk.android:crashlytics:2.9.1@aar") {
        transitive = true;
    }

    implementation "org.greenrobot:eventbus:3.0.0"
    //font
    implementation("uk.co.chrisjenx:calligraphy:2.3.0") {
        exclude group: "com.android.support"
    }
    implementation("com.github.florent37:expectanim:1.0.6") {
        exclude group: "com.android.support"
    }
    implementation "com.romandanylyk:pageindicatorview:0.2.0@aar"
    implementation "com.flaviofaria:kenburnsview:1.0.7"
    implementation("com.github.florent37:arclayout:1.0.2") {
        exclude group: "com.android.support"
    }

    implementation("com.jakewharton.rxbinding:rxbinding:1.0.1") {
        exclude group: "io.reactivex"
        exclude group: "com.android.support"
    }
    implementation("com.jakewharton.rxbinding:rxbinding-support-v4:1.0.1") {
        exclude group: "io.reactivex"
        exclude group: "com.android.support"
    }
    implementation "com.wang.avi:library:2.1.3"
    implementation("com.borax12.materialdaterangepicker:library:1.9") {
        exclude group: "com.android.support"
    }
//    implementation "by.unick:glow-decorator:1.0"
    //Location
    implementation "com.tbruyelle.rxpermissions:rxpermissions:0.9.4@aar"
    implementation "pl.charmas.android:android-reactive-location:0.10@aar"
    implementation "com.google.android.gms:play-services-maps:${googleMapsLibVer}"
    implementation "com.google.android.gms:play-services-location:${googleLocationLibVer}"
    //you can use newer GMS version if you need
//    implementation "com.google.android.gms:play-services-places:${googleLibVer}"
    implementation("com.google.firebase:firebase-core:${firebaseCoreVersion}") {
        exclude group: "com.android.support"
    }

    implementation("commons-validator:commons-validator:1.6") {
        exclude module: "commons-collections"
    }
    implementation "com.balysv:material-ripple:1.0.2"
    implementation "com.googlecode.libphonenumber:libphonenumber:8.5.2"
    implementation("ru.egslava:MaskedEditText:1.0.5") {
        exclude group: "com.android.support"
    }
    implementation("com.futuremind.recyclerfastscroll:fastscroll:0.2.5") {
        exclude group: "com.android.support"
    }

    implementation "rouchuan.viewpagerlayoutmanager:viewpagerlayoutmanager:2.0.19"
    implementation("com.r0adkll:slidableactivity:2.0.6") {
        exclude group: "com.android.support"
    }

    implementation("com.nightonke:jellytogglebutton:1.0.2") {
        exclude group: "com.android.support"
    }

    implementation "com.daimajia.swipelayout:library:1.2.0@aar"

    implementation("com.airbnb.android:paris:1.0.0") {
        exclude group: "com.android.support"
    }
    // If you are using Paris annotations
    implementation "com.airbnb.android:paris-annotations:1.0.0"
    annotationProcessor "com.airbnb.android:paris-processor:1.0.0"

    implementation("com.getkeepsafe.taptargetview:taptargetview:1.12.0") {
        exclude group: "com.android.support"
    }

    //region maven { url "https://jitpack.io" }
    // intent builder
    annotationProcessor "com.github.marcinmoskala.activitystarter:activitystarter-compiler:${activitystarterVersion}"

    //region maven { url "https://dl.bintray.com/nickunuchek/maven" }
    implementation "com.github.kolyall:rx-assist:${rxAssistVersion}"
    implementation("com.github.kolyall:glowdecorator:${glowdecoratorVersion}") {
        exclude group: "com.android.support"
    }
    implementation("com.github.kolyall:vector-morph:${vectormorphVersion}") {
        exclude group: "com.android.support"
    }
    implementation("com.github.kolyall:progressbutton:${progressbuttonVersion}") {
        exclude group: "com.android.support"
    }
    //endregion

    //region maven mavelCustom
    implementation ("com.github.kolyall:mvpr:${mvprVersion}") {
        exclude group: "com.github.kolyall", module: "rx-android-utils"
        exclude group: "com.squareup.picasso", module: "picasso"
    }
    implementation "com.github.kolyall:ucrop:${ucropVersion}"
    implementation("com.github.kolyall:ahbottomnavigation:${ahbottomnavigationVersion}") {
        exclude group: "com.android.support"
    }
    implementation "com.github.kolyall:FlycoTabLayout_Lib:${flycoTabLayoutVersion}"
    implementation "com.github.kolyall:expandabletext:1.0.9"
    //endregion

    implementation project(":library_colors")
    implementation project(":library_job")
    implementation(project(":module_data")) {
        exclude group: "com.github.kolyall", module: "utils"
    }
    implementation project(":library_icons")
}

task findConventions << {
    println project.getConvention()
}

apply plugin: 'com.google.gms.google-services'

```

#### Please select the affected platforms
- [V] Android
- [  ] iOS (robovm)
- [  ] iOS (MOE)
- [  ] HTML/GWT
- [  ] Windows
- [  ] Linux
- [  ] MacOS

**Comment by Tom-Ski** [comment]
You have provided small snippets of heavily modified gradle scripts that have no reference to anything libgdx related. This is a Gradle/android config issue, not libGDX. If you can provide a runnable sample that reproduces your problem using stock LibGDX config, we can reopen.
