### ISSUE TITLE
Tooltip manager crash in run() method

### ISSUE THREAD

**Issue by bryanbrunt** [libgdx/libgdx#5453]
Please ensure you have given all the following requested information in your report.

#### Issue details

I have button with a tooltip that closes a stage and opens another stage. The button will occasionally crash the application. It appears that TooltipManager is attempting to access a stage that no longer exists.

The issue is only intermittently reproducible as it depends on the timing of the tooltip instantiation. Probably critically, the closing of the stage is tied to a fadeout action.

#### Reproduction steps/code

This is the code that changes the screen.

        this.addAction(Actions.sequence(Actions.fadeOut(0.2f), Actions.run(new Runnable() {
            @Override
            public void run() {
                GrandStrategy.get().changeScreen(GrandStrategy.GAMESELECTION);
            }
        })));

#### Version of LibGDX and/or relevant dependencies

Version 1.9.8.

#### Stacktrace
```java

The manager crashes when accessing the stage, which in this code inside of the Tooltip run method is null:

public class TooltipManager {

		public void run () {
			if (showTooltip == null) return;

			Stage stage = showTooltip.targetActor.getStage();

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.ui.TooltipManager$2.run(TooltipManager.java:69)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:259)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:210)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by bryanbrunt** [comment]
This is fixed 1.9.9-Snapshot.
