### ISSUE TITLE
ProgressBar null pointer issue

### ISSUE THREAD

**Issue by trizet86** [libgdx/libgdx#5454]
#### Issue details
I use ProgressBar as a super class for my class HealthBar.
And I get a null pointer exception when I create this.
This happened only if vertical orientation used.
My HealthBar constructor is:
```java
public HealthBar(int width, int height, boolean vertical, Color color, Color backColor) {
        super(0f, 1f, 0.01f, vertical, new ProgressBarStyle()); <-------- EXCEPTION HERE
        getStyle().background = getColoredDrawable(width, height, backColor);
        getStyle().knob = getColoredDrawable(0, height, color);
        getStyle().knobBefore = getColoredDrawable(width, height, color);

        setWidth(width);
        setHeight(height);

        setAnimateDuration(0.0f);
        setValue(1f);

        setAnimateDuration(0.25f);
    }
```

Exception happened in ProgressBar.java constructor when called this methods:
```java
public float getPrefWidth () {
	if (vertical) {
		final Drawable knob = getKnobDrawable();
		final Drawable bg = (disabled && style.disabledBackground != null) ? style.disabledBackground : style.background;
                ----- EXCEPTION ON NEXT LINE BECAUSE bg IS NULL -----
		return Math.max(knob == null ? 0 : knob.getMinWidth(), bg.getMinWidth());
	} else
		return 140;
}

public float getPrefHeight () {
	if (vertical)
		return 140;
	else {
		final Drawable knob = getKnobDrawable();
		final Drawable bg = (disabled && style.disabledBackground != null) ? style.disabledBackground : style.background;
                ----- BUT HERE bg CHECKED FOR NULL -----
		return Math.max(knob == null ? 0 : knob.getMinHeight(), bg == null ? 0 : bg.getMinHeight()); 
	}
}
```
I check for null must be implemented into getPrefWidth also.

#### Reproduction steps/code
If style background is null.

#### Version of LibGDX and/or relevant dependencies
1.9.9

#### Stacktrace
```java
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.ui.ProgressBar.getPrefWidth(ProgressBar.java:307)
	at com.badlogic.gdx.scenes.scene2d.ui.ProgressBar.<init>(ProgressBar.java:83)
	at com.nbdev.startexgame.GameObjects.HealthBar.<init>(HealthBar.java:30)
	at com.nbdev.startexgame.ItemSlot.<init>(ItemSlot.java:35)
	at com.nbdev.startexgame.Screens.GameScreen.show(GameScreen.java:51)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.nbdev.startexgame.Screens.MenuScreen$1.buttonUp(MenuScreen.java:33)
	at com.nbdev.startexgame.Buttons.Button.touchUp(Button.java:25)
	at com.nbdev.startexgame.Screens.MenuScreen.touchUp(MenuScreen.java:84)
	at com.nbdev.startexgame.BaseScreen.touchUp(BaseScreen.java:91)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by AugustasMacys** [comment]
I have the same problem. Any ideas why?

**Comment by trizet86** [comment]
As I see it was fixed. But I don't test after...
In my project I found another solution.


Среда, 13 февраля 2019, 19:16 +03:00 от Augustas Macys <notifications@github.com>:
>I have the same problem. Any ideas why?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Have nice day! Nathan.
https://vk.com/vjtwin
