### ISSUE TITLE
Implementation tags in build.gradle file causes issues in desktop:dist

### ISSUE THREAD

**Issue by HeinousGames** [libgdx/libgdx#5491]
#### Issue details
desktop:dist exports a jar that has no class defined for ApplicationListener when not using "compile" in the build.gradle file.

#### Reproduction steps/code
- Create a new project from the gdx-setup.jar tool.
- Change "compile" tags to "implementation" tags inside the build.gradle file.
- Attempt desktop:dist from command line.

A jar will be exported but will not run. This happens on a project that is only made with the desktop module. If attempting to make a project with the Android module, changing the tags from implementation to compile is not enough, you must also ensure the android:build:gradle plugin is 3.1.3. **I am alarmed by this as Android Studio says "compile" will be obsolete at the end of 2018.**

#### Version of LibGDX and/or relevant dependencies
LibGDX v1.9.8 & 1.9.9
Android Studio v3.1.4
Mac OS Mojave v10.14.2

#### Stacktrace when attempting to run the jar via command line
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [Not sure but assuming] Windows
- [Not sure but assuming] Linux
- [X] MacOS

**Comment by intrigus** [comment]
Please provide a `diff` of the changes you did.

**Comment by 0megaD** [comment]
> The only changes I made was to change the compile tags to implementation tags. I changed them to implementation because Android Studio says compile will be obsolete at the end of the year. Do I need to upload a build.gradle file of those changes to provide a diff?

Do you get the same issue changing `compile`  to `api`? `api` allows chaining dependencies, `implementation` does not. Both `api` and `implementation` fulfill the requirement for the deprecation warning.

**Comment by Laurent1967** [comment]
I may confirm (on Android Studio with gradle 4.6) that replacing compile EITHER by implementation or api causes desktop:dist to include only the Desktop.launcher.class in the jar. There is no other class included at all. On the other hand, desktop:run works fine.
Reverting to compile (with the deprecation message) makes desktop:dist to include all necessary project classes and dependancies. Ressources are not concerned and rightly included in each configuration (compile, implementation, api)

**Comment by Laurent1967** [comment]
I found the fix.

in desktop:dist task, replace 
`from files(sourceSets.main.output.classesDir)
  from {configurations.compile.collect {zipTree(it)}}`

by :

`from files(sourceSets.main.output.classesDirs)  // update for Gradle 5
  from {configurations.compileClasspath.collect { it.isDirectory() ? it : zipTree(it) }} `

Then, some external libraries must be compiled with 'api' instead of 'implementation' 
It is then wise to start by replacing all "compile" with "api". Thus replace also each occurence of :
`apply plugin: "java"`
by 
`apply plugin: "java-library"`

**Comment by XantjiProductions** [comment]
I did exactly the same steps and still get the same stacktrace 
`"C:\Program Files\Android\Android Studio\jre\bin\java.exe" -Dfile.encoding=windows-1252 -jar D:\Anwendungen\Workspace\Project2019\desktop\build\libs\desktop-1.0.jar
java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1`

It runs by using the run task, but there ist no class inside the jar except the DesktopLuncher.
Is there any more to specify in the Project Structure?
My desktop module depends on :core with the scope implementation.

I'am using Gradle 5.1 all and Android Plugin 3.3.0

Gradle Sync runs without complaints but my AndroidStudio says about my Desktop Gradle
`dist.dependsOn classes
task afterEclipseImport(description: "Post processing after project generation", group: "IDE") {
    doLast {
        def classpath = new XmlParser().parse(file(".classpath"))
        new Node(classpath, "classpathentry", [kind: 'src', path: 'assets'])
        def writer = new FileWriter(file(".classpath"))
        def printer = new XmlNodePrinter(new PrintWriter(writer))
        printer.setPreserveWhitespace(true)
        printer.print(classpath)
    }
}`
Result of new Node() is ignored.

Any suggestions how I can get a complete JAR?
