### ISSUE TITLE
Libgdx fails to load natives on Windows if username contains non-ascii characters

### ISSUE THREAD

**Issue by d6e** [libgdx/libgdx#5524]
#### Issue details
On Windows, Libgdx seems to fail to load dynamic libraries when users have non-ascii characters in their usernames. I looked into it and found the root cause. It appears`System.load()` does not accept non-ascii characters in the path. It appears to be a known issue: https://bugs.openjdk.java.net/browse/JDK-8195129

Looking into the code. I think the issue with Java can be worked around, in `SharedLibraryLoader.java`, if the path is checked for non-ascii characters before being fed into `System.load()`. If the path does contain non-ascii characters, one of the fallback paths can be used such as the relative path `.temp`. This should be fine if the game is installed in `C:\Program Files` since that path is used by Windows and shouldn't ever contain non-ascii characters. 

#### Reproduction steps/code
I put together the minimal amount of steps to reproduce the issue since reproducing the issue with libgdx as it is in the wild requires creating a new system user. I figured this example would be easier for demonstrating the issue.

1. Make a directory with a non-ascii unicode character in it such as `test大`. 
2. Put a dll in it like `gdx64.dll`.
3. Create the following `Test.java` program and run it:
```
import java.io.File;

public class Test {
    public static void main(String[] args) {
        System.load(new File("test大/gdx64.dll").getAbsolutePath());
    }
}
```
It should crash with an error like:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: C:\longabsolutepath\test大\gdx64.dll
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at Test.main(Test.java:14)
```

#### Version of LibGDX and/or relevant dependencies
At least libgdx 1.9.5 and up.

#### Stacktrace
```java
LwjglApplication: Couldn't initialize audio, disabling audio
java.lang.UnsatisfiedLinkError: C:\Users\???????\AppData\Local\Temp\libgdx???????\dc0f0009\lwjgl64.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.lwjgl.Sys$1.run(Sys.java:70)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:87)
        at org.lwjgl.Sys.<clinit>(Sys.java:117)
        at org.lwjgl.openal.AL.<clinit>(AL.java:59)
        at com.badlogic.gdx.backends.lwjgl.audio.OpenALAudio.<init>(OpenALAudio.java:72)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:88)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:69)
        at com.megacrit.cardcrawl.desktop.DesktopLauncher.main(DesktopLauncher.java:53)
Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:558)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
The problem is that the absolute path used here is writable, but still not usable by `System.load()` since it contains non-ascii characters in the user's username.

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by code-disaster** [comment]
> I think the issue with Java can be worked around, in SharedLibraryLoader.java, if the path is checked for non-ascii characters before being fed into System.load()

Yeah, but SharedLibraryLoader isn't even used in your example, or your stacktrace. I don't see a workaround yet which doesn't involve modifying library dependencies (lwjgl2/openal in this case, but the same issue happens with lwjgl3).

**Comment by NathanSweet** [comment]
An alternative could be to try other locations if `loadLibrary` fails.

**Comment by tomcashman** [comment]
Fallback location could be Java temp directory - not ideal but it'll work.

**Comment by NathanSweet** [comment]
Sure, many locations can be tried. Currently we find a temp folder, trying multiple until one is found, then try to load the lib once. This should change so that finding the temp folder AND loading the lib is tried for each temp folder location. A temp folder may contains characters that cause loading to file, as described above, but may also not have execute permissions or something else could go wrong.

**Comment by Frosty-J** [comment]
Does `System.setProperty("java.io.tmpdir", System.getenv("ProgramData"))` instead of leaving it as `%TEMP%` work as a solution? It still includes the Windows username in subfolders (e.g. `libgdxJames`, `lwjgl_James`) so I have a degree of scepticism.

https://github.com/libgdx/gdx-liftoff/commit/cb49a0f2ca102bc73e77662e0847b3f0b7655a44

**Comment by tommyettinger** [comment]
Liftoff's solution was tested with the fictional username `Kıng` (using the dotless i from Turkish, which is known to cause issues with case in sorting also). It hasn't been tested with spaces in the username, but I know someone who used her `Firstname Lastname` (all ASCII chars) as her username, and that caused issues with TeaVM even though LWJGL3 worked fine. I can test again if there's a need.

It might be nice (once we can settle on a solution) to have StartupHelper added to libGDX and run in Lwjgl3ApplicationConfiguration's constructor. I'm not sure if there's a better place to put it; it should really only run once (maybe a static initializer block in that configuration class?).

**Comment by WinterAlexander** [comment]
> Does `System.setProperty("java.io.tmpdir", System.getenv("ProgramData"))` instead of leaving it as `%TEMP%` work as a solution? It still includes the Windows username in subfolders (e.g. `libgdxJames`, `lwjgl_James`) so I have a degree of scepticism.
> 
> [libgdx/gdx-liftoff@cb49a0f](https://github.com/libgdx/gdx-liftoff/commit/cb49a0f2ca102bc73e77662e0847b3f0b7655a44)

I agree with your skepticism. However the following solution avoids using the name entirely:

```
String prevTmpDir = System.getProperty("java.io.tmpdir");
String prevUser = System.getProperty("user.name");
System.setProperty("java.io.tmpdir", System.getenv("ProgramData"));
System.setProperty("user.name", "YourGameName" + YourGameVersion.CURRENT + "_gdx" + com.badlogic.gdx.Version.VERSION);
LwjglNativesLoader.load();
System.setProperty("java.io.tmpdir", prevTmpDir);
System.setProperty("user.name", prevUser);
```

**Comment by tommyettinger** [comment]
To avoid depending on defining a game version and using libGDX' Version class, one could also define user.name as either the .hashCode() of the existing user.name (as a base-10 string, maybe positive or negative), or the Base64 encoding of the existing name, assuming the encoding doesn't use any chars that are problems on Windows. This way we could ensure that (for the hashCode() at least) all chars used are in the set `[0123456789-]`, which should be fine for filenames.

I hadn't thought of loading Lwjgl natives right away, and setting the properties back afterward. That's a really good idea! I'll try that out today.
