### ISSUE TITLE
How can I enable dead code stripping in moe?

### ISSUE THREAD

**Issue by AyoCrazy** [libgdx/libgdx#5533]
#### Issue details
When I enable "dead code stripping" in xcode, I get a "No implementation found for void com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init" error. My requirement is to embed a unity project in the libgdx project, but the unity project must have "dead code stripping" enabled to work. What should I do?
#### Reproduction steps/code
Enable "dead code stripping" in xcode

#### Version of LibGDX and/or relevant dependencies
libgdx 1.9.9
moe-sdk 1.4.0
#### Stacktrace
```java
2019-01-23 19:49:17.420737+0800 libgdxUnity[947:975436] *** Terminating app due to uncaught exception 'java.lang.UnsatisfiedLinkError', reason: 'java.lang.UnsatisfiedLinkError: No implementation found for void com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init() (tried Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_init and Java_com_badlogic_gdx_backends_iosrobovm_IOSGLES20_init__)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.init(Native Method)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES20.<init>(IOSGLES20.java:28)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.init(IOSGraphics.java:125)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.init(IOSGraphics.java:195)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.createGraphics(IOSApplication.java:193)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.init(IOSApplication.java:176)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication.didFinishLaunching(IOSApplication.java:134)
	at com.badlogic.gdx.backends.iosmoe.IOSApplication$Delegate.applicationDidFinishLaunchingWithOptions(IOSApplication.java:75)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at com.test.libgdx.unity.IOSMoeLauncher.main(IOSMoeLauncher.java:27)
```

#### Please select the affected platforms
- [x] iOS (MOE)

**Comment by MrStahlfelge** [comment]
Closed. ios-moe support is removed from libgdx.
