### ISSUE TITLE
Able to run game from Android Studio but running Jar file NoClassDefFoundError

### ISSUE THREAD

**Issue by AAbhishek1234** [libgdx/libgdx#5553]
HI Guys ,
My libgdx project which i have created for Desktop runs perfectly fine if i Run it from Android Studio , But when i create a jar file by command /gradlew desktop:dist and run the jar file . it gived me following error : 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

, I opened the jar file and checked , It only contains my DesktopLauncher class file and assets folder.

**Comment by mgsx-dev** [comment]
might be same issue as #5491

**Comment by AAbhishek1234** [comment]
Apparently changing implementation to compile in gradle fixes this . closing
