### ISSUE TITLE
Improper ProGuard configuration causing ios-moe crash

### ISSUE THREAD

**Issue by caillette** [libgdx/libgdx#5560]
Current version of libGDX Project Setup (as of  2019-01-15) generates a ProGuard configuration which causes useful classes to be omitted by the build. As a consequence, an iOS application can not load skin resources.

This is the exact version of libGDX I'm using to generate the setup:

```
$ git rev-parse HEAD
18477473e7a552b8e4abb95fe855998e7bf84548
```

Xcode was kind enough to show this stack trace in the log:

```
com.badlogic.gdx.utils.SerializationException: Error reading file: skin/dark-hdpi/Holo-dark-hdpi.json
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:104)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:81)
	at io.github.uborkaszoftver.scrollbardemo.ScrollbarDemo.create(ScrollbarDemo.java:25)
	at com.badlogic.gdx.backends.iosmoe.IOSGraphics.glkViewDrawInRect(IOSGraphics.java:241)
	at com.badlogic.gdx.backends.iosmoe.IOSGLKView.drawRect(IOSGLKView.java:81)
	at apple.uikit.c.UIKit.UIApplicationMain(Native Method)
	at io.github.uborkaszoftver.scrollbardemo.IOSMoeLauncher.main(IOSMoeLauncher.java:24)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: skin/dark-hdpi/Holo-dark-hdpi.json
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:715)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:102)
	... 6 more
Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: titleFont (com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle)
Serialization trace:
{}."com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle".default.titleFont
	at com.badlogic.gdx.utils.Json.readFields(Json.java:811)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readFields(Skin.java:462)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:958)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:436)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:883)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:485)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:474)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:468)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:917)
	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:436)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:713)
	... 7 more
```

This is an extract of ``ios-moe/build/moe/main/proguard/ProGuard.log`` :

```
com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle:
    public com.badlogic.gdx.scenes.scene2d.utils.Drawable background
    public com.badlogic.gdx.graphics.g2d.BitmapFont titleFont
    343:354:public Window$WindowStyle(com.badlogic.gdx.graphics.g2d.BitmapFont,com.badlogic.gdx.graphics.Color,com.badlogic.gdx.scenes.scene2d.utils.Drawable)
    343:360:public Window$WindowStyle(com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle)
```

I dezipped `ios-moe/build/moe/main/proguard/output.jar`, which contains `com/badlogic/gdx/scenes/scene2d/ui/Window$WindowStyle.class`. I decompiled it:

```
$ javap ios-moe/build/moe/main/proguard/output-jar/com/badlogic/gdx/scenes/scene2d/ui/Window\$WindowStyle.class
Compiled from "Window.java"
public class com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle {
  public com.badlogic.gdx.graphics.Color titleFontColor;
  public com.badlogic.gdx.scenes.scene2d.utils.Drawable stageBackground;
  public com.badlogic.gdx.scenes.scene2d.ui.Window$WindowStyle();
}
```

So the field is clearly missing.

As a workaround, I moved the `proguard.append.cfg` generated (if the file does not exist) at project root to `ios-moe` directory. Then the application started as expected, and loaded the skin.

**Comment by MrStahlfelge** [comment]
Closed. ios-moe support is removed from libgdx.
