### ISSUE TITLE
A JNI error has occurred while packaging to Desktop

### ISSUE THREAD

**Issue by hanxuechen** [libgdx/libgdx#5569]
Please ensure you have given all the following requested information in your report.

#### Issue details
it 's ok when running the CMD and "./gradlew desktop:dist",
but when i run "java -jar desktop.jar", it then came out 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

as the screenshot mentioned
![inked2019-02-21_001658_li](https://user-images.githubusercontent.com/31240078/53106933-0307de00-356f-11e9-8674-d6a7c121199f.jpg)

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_

#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ Y] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
probably duplicate of #5553 and #5491

**Comment by hanxuechen** [comment]
Thanks alot, i figured it out by @Laurent1967 post
