### ISSUE TITLE
Is this a gradle issue?

### ISSUE THREAD

**Issue by elieobeid7** [libgdx/libgdx#5604]
Starting a new project, I got this error

```
Generating app in /home/elie/Desktop/PokerGame
Executing '/home/elie/Desktop/PokerGame/gradlew clean --no-daemon'
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/elie/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.jaDone!
va:To import in Eclipse: File -> Import -> Gradle -> Gradle Project
1To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...
07)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

I wounder, is this related to https://github.com/libgdx/libgdx/issues/4698 or a totally different issue?

**Comment by Darkyenus** [comment]
Do you have two gradle applications running at the same time? Try restarting your computer. In any case, it does not look like a libGDX issue.

**Comment by elieobeid7** [comment]
My bad I was using an old Libgdx version.
