### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.badlogic.gdx.utils.o$c.c()' on a null object reference

### ISSUE THREAD

**Issue by lizzy115115** [libgdx/libgdx#5662]
user libgdx create actor to play flash, has crash in some android phone

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.badlogic.gdx.utils.o$c.c()' on a null object reference
 at com.badlogic.gdx.utils.o.e(ObjectMap.java:649)
 at com.badlogic.gdx.graphics.glutils.o.g(ShaderProgram.java:781)
 at com.badlogic.gdx.backends.android.k.t(AndroidGraphics.java:579)
 at com.badlogic.gdx.backends.android.k.onSurfaceCreated(AndroidGraphics.java:334)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)

how to avoid this crash

the code location is shaders is null result in
ShaderProgram.java:781
public static String getManagedStatus () {
		StringBuilder builder = new StringBuilder();
		int i = 0;
		builder.append("Managed shaders/app: { ");
		for (Application app : shaders.keys()) {
			builder.append(shaders.get(app).size);
			builder.append(" ");
		}
		builder.append("}");
		return builder.toString();
	}

user gdx version：1.9.8
implementation "com.badlogicgames.gdx:gdx:1.9.8"
implementation "com.badlogicgames.gdx:gdx-backend-android:1.9.8"
implementation "com.esotericsoftware.spine:spine-libgdx:3.5.51.1"

#### Please select the affected platforms
 -[] Android

**Comment by intrigus** [comment]
Please provide a stacktrace without proguard.

**Comment by NathanSweet** [comment]
Will reopen if more info is provided.

**Comment by lizzy115115** [comment]
on a null object reference
 at com.badlogic.gdx.utils.ObjectMap.keys(ObjectMap.java:649)
 at com.badlogic.gdx.graphics.glutils.ShaderProgram.getManagedStatus(ShaderProgram.java:781)
 at com.badlogic.gdx.backends.android.AndroidGraphics.logManagedCachesStatus(AndroidGraphics.java:579)
 at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:334)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)

**Comment by lizzy115115** [comment]
> Will reopen if more info is provided.

on a null object reference
 at com.badlogic.gdx.utils.ObjectMap.keys(ObjectMap.java:649)
 at com.badlogic.gdx.graphics.glutils.ShaderProgram.getManagedStatus(ShaderProgram.java:781)
 at com.badlogic.gdx.backends.android.AndroidGraphics.logManagedCachesStatus(AndroidGraphics.java:579)
 at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceCreated(AndroidGraphics.java:334)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)

**Comment by NathanSweet** [comment]
The latest ObjectMap.java:649 can't throw NPE:
https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/ObjectMap.java#L649
I'm guessing the version you are using is this, but this line 649 can't throw NPE either:
https://github.com/libgdx/libgdx/blob/0b46a2e78b3e6815b9eead9f3c1b27bc87b47b56/gdx/src/com/badlogic/gdx/utils/ObjectMap.java#L649
I can't tell what is going on. `shaders.keys()` is called, then where is the NPE happening?

**Comment by Tom-Ski** [comment]
https://github.com/libgdx/libgdx/blob/gdx-parent-1.9.8/gdx/src/com/badlogic/gdx/utils/ObjectMap.java#L649
Since this is using 1.9.8. I guess some rare multithreaded cases is the only thing that can cause this? Keys2 would be null, which should be impossible otherwise.

**Comment by lizzy115115** [comment]
> The latest ObjectMap.java:649 can't throw NPE:
> https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/ObjectMap.java#L649
> I'm guessing the version you are using is this, but this line 649 can't throw NPE either:
> https://github.com/libgdx/libgdx/blob/0b46a2e78b3e6815b9eead9f3c1b27bc87b47b56/gdx/src/com/badlogic/gdx/utils/ObjectMap.java#L649
> 
> 
> I can't tell what is going on. `shaders.keys()` is called, then where is the NPE happening?

I  using 1.9.8 

mplementation "com.badlogicgames.gdx:gdx:1.9.8"
implementation "com.badlogicgames.gdx:gdx-backend-android:1.9.8"
implementation "com.esotericsoftware.spine:spine-libgdx:3.5.51.1"
