### ISSUE TITLE
LibGDX 1.9.10 TmxMapLoader not compatible with .tmx files generated by Tiled 1.2.4 (latest version)

### ISSUE THREAD

**Issue by emilfilipdev** [libgdx/libgdx#5764]
#### Issue details
When loading a tmx tilemap generated by Tiled 1.2.4, libGDX does not take into account the new format for tmx files (which use CSV data). When loading a tilemap, the method **getTileIds** of the class **BaseTmxMapLoader** calls "data.getText()", which causes a null pointer exception. This is because in Tiled 1.2.4, the CSV data is now stored within <chunk> tags inside the <data> tag of the .tmx file. Hence, the "text" attribute of "data" is null, as the text is stored in "chunk" instead.

#### Reproduction steps/code
The code which generates the error is simple:

FileHandle tmxFileHandle = Gdx.files.absolute("C:\\projectroot\\assets\\levels\\room1.tmx");
AssetDescriptor<TiledMap> descriptor = new AssetDescriptor<>(tmxFileHandle, TiledMap.class);
assetManager.setLoader(TiledMap.class, new TmxMapLoader(new AbsoluteFileHandleResolver()));
assetManager.load(descriptor);

The problem lies in the **BaseTmxMapLoader** class at line 499. This is an extract of the method **getTileIds**, which is what caused the problem:

public static int[] getTileIds(Element element, int width, int height) {
        Element data = element.getChildByName("data");
        String encoding = data.getAttribute("encoding", (String)null);
        if (encoding == null) {
            throw new GdxRuntimeException("Unsupported encoding (XML) for TMX Layer Data");
        } else {
            int[] ids = new int[width * height];
            if (encoding.equals("csv")) {
                String[] array = **data.getText().split(",");**

                for(int i = 0; i < array.length; ++i) {
                    ids[i] = (int)Long.parseLong(array[i].trim());
                }
            } else {
...

This LibGDX class is trying to retrieve the data text straight from the data XML tag, which cannot be done as the text is actually stored in chunk tags within the data tag. The following is an example of the new tmx format in Tiled 1.2.4:

<map version="1.2" tiledversion="1.2.4" orientation="orthogonal" renderorder="right-down" width="20" height="22" tilewidth="64" tileheight="64" infinite="1" nextlayerid="17" nextobjectid="2">
 <tileset firstgid="1" source="tileset1.tsx"/>
 <tileset firstgid="11" source="tileset2.tsx"/>
<layer id="14" name="env" width="20" height="22" offsetx="0" offsety="128">
  <data encoding="csv">
   <chunk x="-16" y="16" width="16" height="16">
0,0,0,0,0,0,0,0,0,9,8,8,8,8,8,8,
0,0,0,0,0,0,0,0,0,3,4,4,4,4,4,4,
0,0,0,0,0,0,0,9,7,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,2,0,0,2,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,2,0,0,2,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,3,5,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,9,8,8,8,8,8,8,
0,0,0,0,0,0,0,0,0,3,4,4,4,4,4,4,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
</chunk>
   <chunk x="0" y="16" width="16" height="16">
8,8,8,8,8,8,7,0,0,0,0,0,0,0,0,0,
4,4,4,4,4,4,5,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,9,7,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,2,0,0,2,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,2,0,0,2,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,10,6,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,3,5,0,0,0,0,0,0,0,
8,8,8,8,8,8,7,0,0,0,0,0,0,0,0,0,
4,4,4,4,4,4,5,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
</chunk>
  </data>
 </layer>
</map>

Note that the CSV text is between <chunk> tags.

#### Version of LibGDX and/or relevant dependencies
LibGDX 1.9.10
Tiled 1.2.4

#### Stacktrace
'''
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load asset: C:/projectroot/assets/levels/room1.tmx
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:636)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:411)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:437)
	at ocr.emilfilip3061.core.io.AssetLoader$1.accept(AssetLoader.java:103)
	at ocr.emilfilip3061.core.io.AssetLoader$1.accept(AssetLoader.java:86)
	at ocr.emilfilip3061.core.io.AssetLoader$1.accept(AssetLoader.java:86)
	at ocr.emilfilip3061.core.io.AssetLoader$1.accept(AssetLoader.java:79)
	at ocr.emilfilip3061.core.io.AssetLoader.beginLoading(AssetLoader.java:113)
	at ocr.emilfilip3061.core.mvc.MainListener.create(MainListener.java:51)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:429)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:377)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at ocr.emilfilip3061.desktop.DesktopLauncher.main(DesktopLauncher.java:32)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load asset: C:/projectroot/assets/levels/room1.tmx
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:139)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:561)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:409)
	... 12 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NullPointerException
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:137)
	... 15 more
Caused by: java.lang.NullPointerException
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.getTileIds(BaseTmxMapLoader.java:478)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTileLayer(BaseTmxMapLoader.java:213)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadLayer(BaseTmxMapLoader.java:172)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTiledMap(BaseTmxMapLoader.java:162)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadAsync(TmxMapLoader.java:88)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.loadAsync(TmxMapLoader.java:36)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:74)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
'''

#### Affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
**- [X] Windows**
- [ ] Linux
- [ ] MacOS

**Comment by MobiDevelop** [comment]
The tmx file spec indicates the chunk element is only applicable when creating "infinite" maps. Is that no longer true?

**Comment by emilfilipdev** [comment]
No, the chunk tags are still only applicable to infinite maps. The issue is that LibGDX does not support them. As a result I had to change all my tmx maps to non-infinite.

**Comment by mgsx-dev** [comment]
all features after TMX map format version 0.18 are not supported by libgdx which include infinite map, templates, and so on. Maybe we could document it in the wiki?

for reference: https://doc.mapeditor.org/en/stable/reference/tmx-changelog

**Comment by emilfilipdev** [comment]
Is support for these features planned in a later libgdx update?

**Comment by vito-Z80** [comment]
2 дня пытался понять ошибку. :(
Ответов нет.

**Comment by nklbdev** [comment]
I just made a [pull request](https://github.com/libgdx/libgdx/pull/6025) that solves this problem. Let's see if it will be accepted.
