### ISSUE TITLE
Load TextureAtlas from zip archive

### ISSUE THREAD

**Issue by JuKu** [libgdx/libgdx#5830]
Hi there, is it possible to load assets from a (external) zip archive?

#### Issue details
Hi there, is it possible to load assets from a (external) zip archive?

#### Reproduction steps/code
I have already tried this and it works for most assets (like Textures and so on), but not for TextureAtlas:
```java
package com.jukusoft.engine2d.view.assets.zip;

import com.badlogic.gdx.Files;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.GdxRuntimeException;
import com.jukusoft.engine2d.core.utils.StringUtils;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Objects;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * file handle for files inside a (zip) archive
 *
 * see also: https://gist.github.com/MobiDevelop/5514357
 */
public class ArchiveFileHandle extends FileHandle {

    final ZipFile archive;
    final ZipEntry archiveEntry;

    public ArchiveFileHandle (ZipFile archive, File file) {
        super(new File(file.getAbsolutePath().replace("\\", "/")), Files.FileType.Classpath);//Classpath, External

        Objects.requireNonNull(archive);
        Objects.requireNonNull(file);

        this.archive = archive;
        archiveEntry = this.archive.getEntry(file.getPath().replace("\\", "/"));
    }

    public ArchiveFileHandle (ZipFile archive, String fileName) {
        super(fileName.replace('\\', '/'), Files.FileType.Classpath);//Classpath, External

        Objects.requireNonNull(archive);
        StringUtils.checkNotNullAndNotEmpty(fileName, "fileName");

        this.archive = archive;
        this.archiveEntry = archive.getEntry(fileName.replace('\\', '/'));

        if (this.archiveEntry == null) {
            throw new IllegalStateException("file does not exists in zip archive: " + fileName);
        }
    }

    @Override
    public FileHandle child (String name) {
        name = name.replace('\\', '/');
        if (file.getPath().length() == 0) return new ArchiveFileHandle(archive, new File(name));
        return new ArchiveFileHandle(archive, new File(file, name));
    }

    @Override
    public FileHandle sibling (String name) {
        name = name.replace('\\', '/');
        if (file.getPath().length() == 0) throw new GdxRuntimeException("Cannot get the sibling of the root.");
        return new ArchiveFileHandle(archive, new File(file.getParent(), name));
    }

    @Override
    public FileHandle parent () {
        File parent = file.getParentFile();
        if (parent == null) {
            if (type == Files.FileType.Absolute)
                parent = new File("/");
            else
                parent = new File("");
        }
        return new ArchiveFileHandle(archive, parent);
    }

    @Override
    public InputStream read () {
        try {
            return archive.getInputStream(archiveEntry);
        } catch (IOException e) {
            throw new GdxRuntimeException("File not found: " + file + " (Archive)");
        }
    }

    @Override
    public boolean exists() {
        return archiveEntry != null;
    }

    @Override
    public long length () {
        return archiveEntry.getSize();
    }

    @Override
    public long lastModified () {
        return archiveEntry.getTime();
    }

}
```

```java
package com.jukusoft.engine2d.view.assets.zip;

import com.badlogic.gdx.assets.loaders.FileHandleResolver;
import com.badlogic.gdx.files.FileHandle;

import java.util.Objects;
import java.util.zip.ZipFile;

//see also: https://gist.github.com/MobiDevelop/5514357
public class ZipFileHandleResolver implements FileHandleResolver {

    private final ZipFile zipFile;

    public ZipFileHandleResolver(ZipFile zipFile) {
        Objects.requireNonNull(zipFile);
        this.zipFile = zipFile;
    }

    @Override
    public FileHandle resolve(String fileName) {
        return new ArchiveFileHandle(zipFile, fileName);
    }

}

```

```java
package com.jukusoft.engine2d.view.assets;

import com.badlogic.gdx.assets.AssetManager;
import com.badlogic.gdx.assets.loaders.TextureAtlasLoader;
import com.badlogic.gdx.assets.loaders.TextureLoader;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.maps.tiled.TmxMapLoader;
import com.jukusoft.engine2d.view.assets.zip.ZipFileHandleResolver;

import java.util.Objects;
import java.util.zip.ZipFile;

public class ZipAssetManagerFactory {

    private ZipAssetManagerFactory() {
        //
    }

    /**
     * create a new asset manager instance which loads assets from a specific zip archive
     *
     * Important! You have to cleanup later with assetManager.dispose()!
     *
     * @return
     */
    public static AssetManager create(ZipFile zipFile) {
        //see also: https://gist.github.com/MobiDevelop/5514357

        Objects.requireNonNull(zipFile);

        if (zipFile.size() == 0) {
            throw new IllegalStateException("zip file is empty");
        }

        ZipFileHandleResolver resolver = new ZipFileHandleResolver(zipFile);
        AssetManager assetManager = new AssetManager(resolver);

        assetManager.setLoader(TextureAtlas.class, new TextureAtlasLoader(resolver));
        assetManager.setLoader(TiledMap.class, new TmxMapLoader(resolver));

        //see also: https://github.com/libgdx/libgdx/wiki/Managing-your-assets
        //assetManager.setLoader(TiledMap.class, new TmxMapLoader(resolver));
        //assetManager.setLoader(Texture.class, new TextureLoader(resolver));

        return assetManager;
    }

}
```

But it does not works.

#### Version of LibGDX and/or relevant dependencies
libGDX version: 1.9.10
Java version: 12

#### Stacktrace
```java
com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: C:/Users/Justin/IdeaProjects/open-island-2/loadscreen/AnimationLoadingScreen5.png
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:636)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:411)
	at com.badlogic.gdx.assets.AssetManager.finishLoadingAsset(AssetManager.java:468)
	at de.openislandgame.view.screen.LoadScreen.onResume(LoadScreen.java:90)
	at com.jukusoft.engine2d.view.screens.impl.DefaultScreenManager.push(DefaultScreenManager.java:118)
	at com.jukusoft.engine2d.view.screens.impl.DefaultScreenManager.leaveAllAndEnter(DefaultScreenManager.java:141)
	at de.openislandgame.view.subsystem.ScreenSubSystemFactory.create(ScreenSubSystemFactory.java:27)
	at de.openislandgame.base.GameFactory$1.lambda$addSubSystems$1(GameFactory.java:52)
	at com.jukusoft.engine2d.applayer.init.impl.SubSystemCreatorInitializer.init(SubSystemCreatorInitializer.java:22)
	at com.jukusoft.engine2d.applayer.init.InitializerProcessor.process(InitializerProcessor.java:45)
	at com.jukusoft.engine2d.applayer.BaseApp.render(BaseApp.java:107)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.jukusoft.engine2d.desktop.DesktopLauncher.start(DesktopLauncher.java:79)
	at com.jukusoft.engine2d.desktop.DesktopLauncher.main(DesktopLauncher.java:30)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: C:/Users/Justin/IdeaProjects/open-island-2/loadscreen/AnimationLoadingScreen5.png
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:121)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:561)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:409)
	... 14 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: C:/Users/Justin/IdeaProjects/open-island-2/loadscreen/AnimationLoadingScreen5.png
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:119)
	... 17 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: C:/Users/Justin/IdeaProjects/open-island-2/loadscreen/AnimationLoadingScreen5.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:144)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:62)
	at com.badlogic.gdx.assets.loaders.TextureLoader.loadAsync(TextureLoader.java:35)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:70)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NullPointerException: entry
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:364)
	at com.jukusoft.engine2d.view.assets.zip.ArchiveFileHandle.read(ArchiveFileHandle.java:78)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:228)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:141)
	... 10 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by intrigus** [comment]
This does not seem to be a libgdx issue.
The exception is caused by your own code.
You may have a look at the forum, irc or Discord to discuss your problem.

**Comment by JuKu** [comment]
@intrigus Thank you for your answer!
I have already found the solution.

If someone has the same problem, here is the solution:
https://github.com/JuKu/libgdx-2d-engine/tree/12e6c83a92eccad1b1e2e4fc362173ea498788fc/game-view/src/main/java/com/jukusoft/engine2d/view/assets
