### ISSUE TITLE
ArrayIndexOutOfBoundsException at AndroidMultiTouchHandler

### ISSUE THREAD

**Issue by oshetima** [libgdx/libgdx#5870]
#### Issue details
From time to time I see this crash reported on my live wallpaper apps. It is impossible for me to reproduce.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Stacktrace
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=20; index=20
       at com.badlogic.gdx.backends.android.AndroidMultiTouchHandler.onTouch(AndroidMultiTouchHandler.java:90)
       at com.badlogic.gdx.backends.android.AndroidInput.onTouch(AndroidInput.java:460)
       at com.badlogic.gdx.backends.android.AndroidLiveWallpaperService$AndroidWallpaperEngine.onTouchEvent(AndroidLiveWallpaperService.java:521)
       at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1404)
       at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)nTC-I0EOPv-wWck3RUbSCS8HgSGqFCI8roz
```
#### Please select the affected platforms
- [X] Android

It looks like the problem resides in [this line](https://github.com/libgdx/libgdx/blob/0d5021844c4f8e555f5ccb570ba3a07488c25dff/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidMultiTouchHandler.java#L90) where it seems that the input.realId.length is bigger than input.pressure.length while they must be equal (but I can be wrong). Thanks for your support.

**Comment by noblemaster** [comment]
Thanks for the report. The bug is here:
https://github.com/libgdx/libgdx/blob/0d5021844c4f8e555f5ccb570ba3a07488c25dff/backends/gdx-backend-android/src/com/badlogic/gdx/backends/android/AndroidInput.java#L864-L870

When the arrays get resized, resizing the pressure array is missing!

**Comment by noblemaster** [comment]
Fixed: https://github.com/libgdx/libgdx/commit/91ad1320b78cdb48a17d7f3f2889a5f2795ccc37

Sorry, the imports got re-ordered.
