### ISSUE TITLE
I can't run my application 

### ISSUE THREAD

**Issue by Andyshome** [libgdx/libgdx#5882]
Please ensure you have given all the following requested information in your report.

#### Issue details
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.dylib' for target: Mac OS X, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
	at com.badlogic.gdx.backends.lwjgl.LwjglNativesLoader.load(LwjglNativesLoader.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:79)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:67)
	at pacman.DesktopLauncher.main(DesktopLauncher.java:18)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: dlopen(/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: code signature in (/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: dlopen(/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib, 1): no suitable image found.  Did find:

	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:311)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:115)
	... 5 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: dlopen(/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib, 1): no suitable image found.  Did find:
	/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: code signature in (/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib: dlopen(/private/var/folders/jb/rqnljx6n2k14tlk15jl2xqnh0000gn/T/libgdxmingshi/801e903a/libgdx64.dylib, 1): no suitable image found.  Did find:

	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:317)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:286)
	... 6 more

Execution failed for task ':DesktopLauncher.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/adoptopenjdk-12.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue.  This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://github.com/libgdx/libgdx/wiki/Getting-help)_
I just simply can't compile this project
#### Version of LibGDX and/or relevant dependencies
_Please provide the version(s) affected._

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] MacOS

**Comment by mgsx-dev** [comment]
@Andyshome did you tried to reproduce with an other JRE (adoptopenjdk 8 for instance), there might be some issues with java 12 (not sure).

**Comment by MobiDevelop** [comment]
Seems related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1211

**Comment by Andyshome** [comment]
Well, thanks @MobiDevelop , I found the solution, I change my JDK from 12.0.2 to 12.0.1 the problem got fixed! 
JDK 12.0.1 can get from this website https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html.
If any macOS Catalina user got the same problem, can try this way, it works for me!
