### ISSUE TITLE
AssetManager ArrayIndexOutOfBoundsException on finishLoading

### ISSUE THREAD

**Issue by oshetima** [libgdx/libgdx#5939]
#### Issue details
From time to time I see this crash reported on my live wallpaper apps. It is impossible for me to reproduce.

#### Version of LibGDX and/or relevant dependencies
1.9.10

#### Stacktrace
```java
Fatal Exception: com.badlogic.gdx.utils.i: java.lang.ArrayIndexOutOfBoundsException: src.length=28 srcPos=0 dst.length=49 dstPos=0 length=29
       at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:638)
       at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:412)
       at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:439)
       at com.myapp.getSprite(LwLauncher.java:244)
       at com.myapp.setQuantities(LwLauncher.java:137)
       at com.myapp.run(LwLauncher.java:284)
       at com.myapp.render(LwLauncher.java:262)
       at com.badlogic.gdx.backends.android.AndroidGraphicsLiveWallpaper.onDrawFrame(AndroidGraphicsLiveWallpaper.java:217)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)

Caused by java.lang.ArrayIndexOutOfBoundsException: src.length=28 srcPos=0 dst.length=49 dstPos=0 length=29
       at java.lang.System.arraycopy(System.java)
       at com.badlogic.gdx.utils.Array.resize(Array.java:410)
       at com.badlogic.gdx.utils.Array.add(Array.java:101)
       at com.badlogic.gdx.graphics.Texture.addManagedTexture(Texture.java:233)
       at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:148)
       at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
       at com.badlogic.gdx.assets.loaders.TextureLoader.loadSync(TextureLoader.java:77)
       at com.badlogic.gdx.assets.loaders.TextureLoader.loadSync(TextureLoader.java:35)
       at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:125)
       at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
       at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:563)
       at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:410)
       at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:439)
       at com.myapp.getSprite(LwLauncher.java:244)
       at com.myapp.setQuantities(LwLauncher.java:137)
       at com.myapp.run(LwLauncher.java:284)
       at com.myapp.render(LwLauncher.java:262)
       at com.badlogic.gdx.backends.android.AndroidGraphicsLiveWallpaper.onDrawFrame(AndroidGraphicsLiveWallpaper.java:217)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
```

It looks like the problem resides in [this](https://github.com/libgdx/libgdx/blob/247c5d52b6bc90a3f66a66f6dcc39ae1a36ae390/gdx/src/com/badlogic/gdx/utils/Array.java#L410) line where for the System.arraycopy to work as it should, the result of the function Math.min(size, newItems.length)  must be <= items.length (in my case it looks like "size" is 29 while items.length is 28, thus giving the ArrayIndexOutOfBoundsException) - But I can be wrong. This happens rarely and I don't know why. 
Thanks for your support.

#### Please select the affected platforms
- [x ] Android

**Comment by NathanSweet** [comment]
It looks like Texture `managedTextures` is accessed OR modified by multiple threads. It should only ever be accessed and modified by the OpenGL thread (the "sync" part of loading an asset). You could add checks that make sure everywhere Texture `managedTextures` is referenced Thread.currentThread() is in the same as the thread that eg called `create` on your app listener.

**Comment by oshetima** [comment]
Thanks for your suggestion. Probably you are right. 
My situation is that I'm showing a small window of the live wallpaper and under it, I put a button that starts the system full-screen live wallpaper preview. I think that if the user presses the button fast enough, the small preview and the full-screen preview will start almost at the same time thus accessing  `managedTextures` by multiple threads. I think I just have to wait for the small preview to finish loading and then make the button clickable. 
Thank you so much NathanSweet. You really helped me.

**Comment by NathanSweet** [comment]
Cheers! Likely you just need to use Gdx.app.postRunnable to ensure your code is run on the libgdx OpenGL thread (but I've never done wallpaper stuff, so maybe things aren't initialized yet).

**Comment by oshetima** [comment]
I'm already using Gdx.app.postRunnable in many situations, but a re-check never hurt. Thanks again
