### ISSUE TITLE
Not able to run gdx-setup.jar

### ISSUE THREAD

**Issue by sh3ll** [libgdx/libgdx#5964]
#### Issue details
I am not able to run gdx-setup.jar as GUI and CMD. Added Stack for both GUI and CMD.

#### Reproduction steps/code
Trying to run GUI:
java -jar gdx-setup.jar

Trying to run CMD (with correct AndroidSDK):
java -jar D:\ADT\LibGDX\gdx-setup.jar --dir D:\ADT\TEST --name TestGame --package com.badlogic.testgame --mainClass TestGame --sdkLocation C:\Users\sh3ll\AppData\Local\Android\Sdk --excludeModules ios;html --extensions box2d

#### Version of LibGDX and/or relevant dependencies
Current gdx-setup.jar from https://libgdx.badlogicgames.com/nightlies/dist/gdx-setup.jar

#### Stacktrace
GUI:
java.lang.IllegalArgumentException: InputStream cannot be null
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:117)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.initData(Unknown Sour
ce)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.uiLayout(Unknown Sour
ce)
        at com.badlogic.gdx.setup.ExternalExtensionsDialog.<init>(Unknown Source
)
        at com.badlogic.gdx.setup.GdxSetupUI$Form.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$UI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.main(Unknown Source)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.setup.GdxSetupUI$Form.uiLayout(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$Form.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI$UI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetupUI.<init>(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.main(Unknown Source)
Caused by: java.lang.IllegalArgumentException: input == null!
        at javax.imageio.ImageIO.read(ImageIO.java:1348)
        at com.badlogic.gdx.setup.GdxSetupUI$SetupCheckBox.getCheckboxImage(Unkn
own Source)
        at com.badlogic.gdx.setup.GdxSetupUI$SetupCheckBox.<clinit>(Unknown Sour
ce)
        ... 5 more

CMD:
Extension box2d found
Exception in thread "main" java.lang.RuntimeException: Couldn't read resource 'gitignore'
        at com.badlogic.gdx.setup.GdxSetup.readResource(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.copyFile(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.copyAndReplace(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.build(Unknown Source)
        at com.badlogic.gdx.setup.GdxSetup.main(Unknown Source)

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [ ] MacOS

**Comment by SimonIT** [comment]
Duplicate to #5963

**Comment by obigu** [comment]
Fix https://github.com/libgdx/libgdx/pull/5966
