### ISSUE TITLE
Issue in DragAndDrop class

### ISSUE THREAD

**Issue by kdenzel** [libgdx/libgdx#6020]
I can confirm this issue. I am working with the Book "Mastering LibGDX" by  [Patrick Hoey](https://github.com/patrickhoey/BludBourne). With Version 1.9.8 and before there isn't any issue with the DragAndDrop class, but when i switch to Version 1.9.10 i get the Nullpointer exception too.
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.drag(DragAndDrop.java:110)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchDragged(DragListener.java:61)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:62)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDragged(Stage.java:315)
	at com.badlogic.gdx.InputMultiplexer.touchDragged(InputMultiplexer.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:363)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

_Originally posted by @kdenzel in https://github.com/libgdx/libgdx/issues/5675#issuecomment-619383598_

**Comment by kdenzel** [comment]
https://stackoverflow.com/questions/61211370/libgdx-drag-and-drop-crashes-when-starting-drag

**Comment by NathanSweet** [comment]
Please don't create new issues when there is an existing issue.
