### ISSUE TITLE
Still some problems with Android GL20 strict mode violations

### ISSUE THREAD

**Issue by melodicore** [libgdx/libgdx#6030]
Hi!

I'm working on an Android app that uses scene2d. Everything is working fine on desktop and my relatively new Android 10 -equipped phone, but when uploading an app bundle to the Google Play Console, I'm getting some crashes in their testing, as well as unsupported library usage related to java.nio.Buffer. This is related to #5485 however I am using the latest version of libgdx, 1.9.10.

Steps to reproduce:

1. Initialize a scene2d Stage.
2. Run on some Android phone (funnily enough the only ones that are crashing are Android 7, according to Google's testing).
3. Crash?

`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/nio/Buffer;->_elementSizeShift:I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at android.opengl.GLES20.glGetShaderiv(Native Method)
	at com.badlogic.gdx.backends.android.AndroidGL20.glGetShaderiv(AndroidGL20.java:362)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.loadShader(ShaderProgram.java:214)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.compileShaders(ShaderProgram.java:188)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.<init>(ShaderProgram.java:171)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:162)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
	at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:100)
	at me.datafox.foxxoland.FoxxoLand.create(FoxxoLand.java:40)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:310)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)`

**Comment by intrigus** [comment]
I'd guess that the code in GLES20.glGetShaderiv is the problem.
That means that googles code is violating strict mode on older android versions.

Is strict mode mandatory for apps?

**Comment by melodicore** [comment]
Strict Mode isn't strictly mandatory, but this strict mode violation means that some Android phones don't have the libraries for java.nio.Buffer. I'm also flabbergasted at the fact that the code runs without any problems on as early Android versions as 4.3, the only ones that crashed in Google's testing were Android 7 or 7.1.

If this is a problem with Android's GLES20 implementation, I should probably look for answers from Google's side.

**Comment by intrigus** [comment]
As I said, I'd assume that google maybe forgot to whitelist these apis for their own use?
The *relevant* GLES20 source code hasn't been changed for like 5 years.

**Comment by obigu** [comment]
Is that a Google Play prelaunch report? Those crash reports are very unreliable and throw a lot of false positives. I haven't seen those crash reports on any live app which use Scene 2D (with high number of daily users). I wouldn't worry unless you get them on a live app.

**Comment by melodicore** [comment]
After further investigation, the crashes are unrelated. As @obigu said, it's most likely a false positive in the testing, as even adding extensive logging to my application, I couldn't link it into anything related to my code or libgdx itself. Closing the issue.
