### ISSUE TITLE
Fat jar cannot resolve relative paths in assets

### ISSUE THREAD

**Issue by jacek-bulatek** [libgdx/libgdx#6125]
#### Issue details
I have skin.json in ```assets/skins```, which refers to font by relative path ```(../fonts/font.fnt)```. Everything works fine, when I build and run app in my IDE, but I am trying to create CI for the project and invoke:
```
gradlew wrapper
gradlew build
gradlew desktop:dist
```
created this way fat jar shows this error:
```
Caused by: com.badlogic.gdx.utils.SerializationExeption: Font file not found: ../fonts/font.fnt
```
I load skins using:
```
Utility.java:
[...]
public static TextureAtlas myAtlas = new TextureAtlas("skins/mySkin.atlas");
public static Skin mySkin = new Skin(Gdx.files.internal("skins/mySkin.json"), myAtlas);
[...]
```
mySkin.json:
```
[...]
com.badlogic.gdx.graphics.g2d.BitmapFont: {
		myFont: {
			file: ../fonts/font.fnt
		}
	}
[...]
```
Assets directory structure:
```
assets __ __skins__ __mySkin.json
         |         |
         |         |__mySkin.atlas
         |
         |__fonts__ __font.fnt
                   |
                   |__...
```

#### Reproduction steps/code
I guess as described above

#### Version of LibGDX and/or relevant dependencies
newest

#### Stacktrace
```
C:\xxx>java -jar desktop-1.0.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/C:/xxx/desktop-1.0.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ExceptionInInitializerError
        at com.xxx.screens.myScreen.<init>(xxx.java:26)
        at com.xxx.create(xxx.java:60)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: skins/mySkin.json
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:98)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.<init>(Skin.java:83)
        at com.xxx.Utility.<clinit>(Utility.java:29)
        ... 4 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: skins/mySkin.json
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:702)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin.load(Skin.java:96)
        ... 6 more
Caused by: com.badlogic.gdx.utils.SerializationException: Font file not found: ../fonts/myFont.fnt
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$3.read(Skin.java:472)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$3.read(Skin.java:463)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:892)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:428)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:860)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.readNamedObjects(Skin.java:449)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:438)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$2.read(Skin.java:434)
        at com.badlogic.gdx.utils.Json.readValue(Json.java:892)
        at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:428)
        at com.badlogic.gdx.utils.Json.fromJson(Json.java:700)
        ... 7 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS (robovm)
- [ ] iOS (MOE)
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
Font file not found: ../fonts/**myFont**.fnt :-)
It looks like mySkin need myFont.fnt, not font.fnt... maybe double check your skin file?

**Comment by jacek-bulatek** [comment]
Yea I might get it wrong when I was hiding my secrets ;) however my actual names are clean (obviously, since it works when ran through IDE)

**Comment by NathanSweet** [comment]
`file: ../fonts/font.fnt` why are you using a relative path in your skin JSON? An internal FileHandler is used and the `..` will prevent it from finding the file in the classpath.

**Comment by NathanSweet** [comment]
`file: ../fonts/font.fnt` why are you using a relative path in your skin JSON? An internal FileHandler is used and the `..` will prevent it from finding the file in the classpath.

**Comment by jacek-bulatek** [comment]
To be honest, skin creation tool made it for me. Nevertheless fact, that it works when ran in IDE made me think, that it shouldn't matter.

**Comment by jacek-bulatek** [comment]
Ok I changed it in mySkin.json and issue is still there, so I guess fat jar includes all assets as well? In this case I think I understand what causes the problem. Thanks!

**Comment by NathanSweet** [comment]
When running in an IDE the file is found relative to the working directory. See `Files.FileType.Internal`.
