### ISSUE TITLE
Label IndexOutOfBoundsException

### ISSUE THREAD

**Issue by taluks** [libgdx/libgdx#6128]
#### Issue details
If wrap set to true, works with any fonts
#### Reproduction steps/code
```java
public class LabelTest extends ApplicationAdapter {
	public static void main(String[] args) {
		LwjglApplicationConfiguration config = new LwjglApplicationConfiguration();
		new LwjglFrame(new LabelTest(), config);
	}
	private Stage stage;
	@Override
	public void create() {

		LabelStyle labelStyle = new LabelStyle(new BitmapFont(Gdx.files.internal("fonts/arial_14.fnt")), Color.WHITE);
		Label label = new Label(
				"Цитадель - сердце фракции. Потеряв над ней контроль, вы теряете контроль над всеми своими зданиями и перестаете развиваться. Для освобождения планеты фракция предоставляет резервные войска.\r\n"
						+ "Защиту каждой фракции обеспечивают двенадцать врат. Захватив все врата, вы открываете путь на родную планету врага.",
				labelStyle);
		label.setWrap(true);

		stage = new Stage();
		stage.addActor(label);
	}
	@Override
	public void render() {
		Gdx.gl.glClearColor(0f, 0f, 0f, 1f);
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		stage.draw();
		super.render();
	}
}
```
#### Version of LibGDX and/or relevant dependencies
1.9.12-SNAPSHOT

#### Stacktrace
```java
java.lang.IndexOutOfBoundsException: index can't be >= size: 189 >= 189
	at com.badlogic.gdx.utils.Array.get(Array.java:155)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:190)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:82)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.computePrefSize(Label.java:161)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.scaleAndComputePrefSize(Label.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.getPrefHeight(Label.java:253)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:175)
	at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:229)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
	at com.ktest.LabelTest.render(LabelTest.java:44)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:271)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

#### Please select the affected platforms
- [x] Android
- [x] iOS (robovm)
- [x] iOS (MOE)
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by MarcinSc** [comment]
Maybe problem with the "\r" character? (try removing it)

**Comment by taluks** [comment]
yes, problem in "\r"
