### ISSUE TITLE
No x-height character found in font

### ISSUE THREAD

**Issue by vsb** [libgdx/libgdx#6202]
#### Issue details
![Capture](https://user-images.githubusercontent.com/776195/95020757-4311cb00-0697-11eb-8bf5-9f998d7c0cf3.PNG)

2020-10-04 23:07:44.187 20619-20809/huu.phong.pikamon W/System.err: com.badlogic.gdx.utils.k: No x-height character found in font
2020-10-04 23:07:44.187 20619-20809/huu.phong.pikamon W/System.err:     at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:331)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at huu.phong.pikamon.tools.Fonts.createFont(Fonts.java:79)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at huu.phong.pikamon.tools.Fonts.init(Fonts.java:89)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at huu.phong.pikamon.game.Pikamon.create(Pikamon.java:106)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at com.badlogic.gdx.backends.android.k.onSurfaceChanged(AndroidGraphics.java:278)
2020-10-04 23:07:44.188 20619-20809/huu.phong.pikamon W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
2020-10-04 23:07:44.189 20619-20809/huu.phong.pikamon W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

#### Reproduction steps/code
    protected BitmapFont createFont(String file) {
        FreeTypeFontGenerator generator = new FreeTypeFontGenerator(Gdx.files.absolute(file));
        FreeTypeFontParameter parameter = new FreeTypeFontParameter();
        parameter.characters = Properties.EMPTY_CHARACTERS;
        parameter.size = 32;
        parameter.minFilter = Texture.TextureFilter.Linear;
        parameter.magFilter = Texture.TextureFilter.Linear;
        parameter.hinting = FreeTypeFontGenerator.Hinting.AutoSlight;
        parameter.gamma = 0.9f;
        parameter.renderCount = 1;
        parameter.spaceX = -1;
        parameter.incremental = true;
        return generator.generateFont(parameter);
    }

#### Version of LibGDX and/or relevant dependencies
gdxVersion = '1.9.11'

#### Please select the affected platforms
- [x] Android
- [x] [Windows]

#### Link to the font
https://vsbcloud.nyc3.digitaloceanspaces.com/fonts/NotoSansLao-Regular.ttf

**Comment by Darkyenus** [comment]
`parameter.characters = Properties.EMPTY_CHARACTERS;` is the problem - you have to specify which characters you want to be included in your generated font, otherwise it will be empty and you will get this error. Or is there any particular reason why you want to generate an empty font?

**Comment by vsb** [comment]
`parameter.characters = Properties.EMPTY_CHARACTERS;` has no problem. It still throw exception if the string is NOT empty too.

I want to pre-cache the font for later use, I do not want to generate the Glyph since it take some memory and slow game start. The Glyph is only generated once Label need it since I use a fly option `parameter.incremental = true;`

I have a LeaderBoard of game with multilanguage for player name so before create a Label I will choose a font in the list that can display that text then add it to the Label

**Comment by tommyettinger** [comment]
Well, the font you attached doesn't have any ASCII letters, so for libGDX's font code (or almost any font code) to adequately guess at the size of a glyph is virtually impossible. This shows what chars are present in the first 256 codepoints:
![Screenshot of ANSI section of NotoSansLao](https://i.imgur.com/oJCVaSt.png)

Since you're using incremental mode, you can use a font that supports a lot of characters (like other versions of Noto Sans), and only the used characters should be rendered. Rendering from multiple fonts in real-time should only be done if they're all in the same atlas, but for a high-score screen FPS doesn't matter much. If you needed to render multilingual labels in-game, like a player's name above their character's head, then having many fonts could be a performance issue, and one large font would do better if the text was all drawn in one pass.

**Comment by NathanSweet** [comment]
As tommyettinger pointed out, your font doesn't have the glyphs BitmapFontData looks for by default to determine x height (and cap height). To remedy this you can call `generateFont(parameter, data)` instead of `generateFont(parameter)`. Pass in a `new FreeTypeBitmapFontData()` which you have configured to set the `xChars` and `capChars` fields to have an appropriate glyph that is actually in the font. Those glyphs won't be rendered to the backing texture, they are only used to determine metrics.
