### ISSUE TITLE
extension 'GL_OES_EGL_image_external' is not supported on IOS

### ISSUE THREAD

**Issue by vaaneeunbnd** [libgdx/libgdx#6311]
Hello, 

I am trying to render a video texture using Opengl in RoboVM. However, I am getting the error - 'extension 'GL_OES_EGL_image_external' is not supported for my fragment shader function. 

String fragmentShaderCode =
            "#extension GL_OES_EGL_image_external : require\n" +
                    "uniform samplerExternalOES u_sampler0;" +
                    "varying highp vec2 v_texCoord0;" +
                    "void main()                 \n" +
                    "{                           \n" +
                    "  vec4 c = texture2D(u_sampler0, v_texCoord0); \n" +
                    "  gl_FragColor = c; \n" +
                    "}";

To reproduce this issue, 
Try to render a video texture for the above fragment shader function in RoboVM Libgdx.

LibGDX Version: '1.9.12'
roboVMVersion = '2.3.11'

#### Stacktrace
```Fragment shader:
ERROR: 0:1: '' :  extension 'GL_OES_EGL_image_external' is not supported
ERROR: 0:2: 'u_sampler0' : syntax error: syntax error

	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:305)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:294)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:526)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:517)
	at com.badlogic.gdx.graphics.glutils.ImmediateModeRenderer20.flush(ImmediateModeRenderer20.java:151)
	at com.badlogic.gdx.graphics.glutils.ImmediateModeRenderer20.end(ImmediateModeRenderer20.java:163)
        at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java:369)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java:241)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(IOSGraphics.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:446)
```

#### Affected platforms
- [ ^] iOS

Thanks :)

**Comment by mgsx-dev** [comment]
You always need to check if an extension is supported before using it. Does the target platform supports it?

**Comment by mgsx-dev** [comment]
Feel fre to reopen if you really think it's a libGDX issue.
