### ISSUE TITLE
Hiero crashes on startup on Windows

### ISSUE THREAD

**Issue by obigu** [libgdx/libgdx#6359]
Hiero crashes on startup with the following stacktrace on Windows (both running from IDE and a jar):

```
com.badlogic.gdx.utils.GdxRuntimeException: No x-height character found in font
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:331)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
	at com.badlogic.gdx.tools.hiero.unicodefont.UnicodeFont.setRenderType(UnicodeFont.java:647)
	at com.badlogic.gdx.tools.hiero.Hiero.updateFont(Hiero.java:315)
	at com.badlogic.gdx.tools.hiero.Hiero$1FontUpdateListener.actionPerformed(Hiero.java:456)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.badlogic.gdx.tools.hiero.Hiero$17.actionPerformed(Hiero.java:681)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at com.badlogic.gdx.tools.hiero.Hiero$Renderer.create(Hiero.java:1419)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas.create(LwjglCanvas.java:216)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$1.addNotify(LwjglCanvas.java:106)
	at java.awt.Container.addImpl(Container.java:1124)
	at java.awt.Container.add(Container.java:419)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:183)
	at com.badlogic.gdx.tools.hiero.Hiero$21.run(Hiero.java:1598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGenTextures(GL11.java:1403)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glGenTexture(LwjglGL20.java:348)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page$1.<init>(PixmapPacker.java:504)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page.updateTexture(PixmapPacker.java:504)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker.updatePageTextures(PixmapPacker.java:410)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker.updateTextureRegions(PixmapPacker.java:402)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateData(FreeTypeFontGenerator.java:464)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:161)
	at com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator.generateFont(FreeTypeFontGenerator.java:152)
	at com.badlogic.gdx.tools.hiero.unicodefont.UnicodeFont.setRenderType(UnicodeFont.java:647)
	at com.badlogic.gdx.tools.hiero.Hiero.updateFont(Hiero.java:315)
	at com.badlogic.gdx.tools.hiero.Hiero$3.valueChanged(Hiero.java:440)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1802)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1816)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2216)
	at javax.swing.JList.setSelectedValue(JList.java:2366)
	at com.badlogic.gdx.tools.hiero.Hiero.<init>(Hiero.java:190)
	at com.badlogic.gdx.tools.hiero.Hiero$21.run(Hiero.java:1598)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I've tested an old Hiero.jar I had locally and it doesn't crash so I guess it's realted to a recent change.

This seems to be related https://github.com/libgdx/libgdx/issues/6202

**Comment by tommyettinger** [comment]
I can reproduce if the last font I had selected lacked the 'x' character. I have a PR ready for this, it's not too hard of a fix.

**Comment by tommyettinger** [comment]
Ah, I see your case has both a GdxRuntimeException (which I catch in my PR) and a RuntimeException relating in some way to OpenGL... which I do not catch, nor understand... Hm, and judging by the RuntimeException, it isn't something that catching would help with. I can reproduce the first GdxRuntimeException by selecting a font without the 'x' character, but I haven't yet encountered the second one.

**Comment by NathanSweet** [comment]
Not clear what the runtime exception is about. Hiero runs on the GL thread, OpenGL should be there. Maybe the `x` problem nukes OpenGL, causing the second exception.

**Comment by obigu** [comment]
I reopen the issue because https://github.com/libgdx/libgdx/issues/6359, even if probably necessary, doesn't fix the problem.

I've updated main post with the new Stacktrace.

**Comment by obigu** [comment]
I've debugged a bit the issue. 

On initialization,  Hiero loads all available fonts on a combo list and sets index to the first one. In my case the first one is `Abster` font (https://unblast.com/abster-free-font/). I'm not sure what does the font lack, it does dispaly the `x` character properly when using it on other apps.

After initialization, when the following line is executed:

`gamePanel.add(rendererCanvas.getCanvas());` triggers the FontUpdateListener:

```
public void actionPerformed (ActionEvent evt) {
	updateFont();
}
```

Then the crash occurs. By commenting `updateFont()` the crash doesn't occur.

**Comment by tommyettinger** [comment]
I'm not sure what's going on with the font combo list on my PC, but I installed Abster (and had a font with an even earlier name, A Starry) and it doesn't show up in the list at all. Neither does A Starry, though that one can be loaded by the file selector. It's pretty hard to debug this. A Starry has the 'x' character, and via file selector it works. Abster does not have 'x', and with the just-merged PR, selecting it with the file selector gets reset to Arial and posts a message. I'm wondering if that unblast.com site changed how they distributed Abster at some point (TTF to OTF?), and that changed how Hiero is able to see the font. I'm on Windows 10 Pro.

**Comment by obigu** [comment]
@tommyettinger Can you try uninstalling "A Starry" see what happens on startup?

**Comment by tommyettinger** [comment]
Sure thing. Sorry, just got your message a week later... It has never shown Abster in the font list, and it still doesn't. The first font selected is Agency FB: ![Hiero screenshot](https://i.imgur.com/umhfvG4.png). Also, it never showed A Starry in the font list. I uninstalled A Starry and left Abster installed, but the first font is then the one after those in alphabetical order.

**Comment by obigu** [comment]
Ok, thanks, do you know of a font I can download that lacks x-height? I will try to edit it to rename it so that it's the first to load alphabetically see if I get the same error.

**Comment by tommyettinger** [comment]
There's the thing, I don't know what makes Hiero decide to display a font in the dropdown box. I suspect it has something to do with being a font family (maybe that means it supports bold and italic or oblique?), but it could be some other criterion. I'll check what I have installed for any other fonts that may be missing 'x'. I'm guessing there are some language-support fonts for non-Latin scripts that don't have any Latin letters.

**Comment by tommyettinger** [comment]
I found EmojiOne Color as a pre-installed font on Windows (CC-BY licensed), and it lacks the 'x' character. I just can't seem to edit its name and have the edited copy show up as installed in the dropdown... I think I can send another PR, with extra checks. Only Freetype has issues when 'x' is missing, so the idea is to switch to the Java rendering if Freetype would crash.
