### ISSUE TITLE
Android clipboard throws exception on some devices

### ISSUE THREAD

**Issue by lucas-kakele** [libgdx/libgdx#6371]
#### Issue details
Some Android devices throw an exception when calling `Gdx.app.getClipboard().setContents`.

#### Reproduction steps/code
This is not reproducible in all devices. We are also not getting exceptions in our Google Play Console. We know this is happening because we have a  `UncaughtExceptionHandler` that logs to our servers. The app doesn't seem to crash as well (the exception is swallowed?).

The `Build.MODEL` and `Build.VERSION.SDK_INT` logged for the exceptions we collected are:

SM-G530M v19
SM-G530H v19
(I will add more to this list if we see new devices)

#### Version of LibGDX and/or relevant dependencies
1.9.12

#### Stacktrace
```java
Exception: java.lang.RuntimeException: 

Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.widget.Toast$TN.<init>(Toast.java:372)
at android.widget.Toast.<init>(Toast.java:105)
at android.widget.Toast.makeText(Toast.java:264)
at android.widget.Toast.makeText(Toast.java:313)
at android.content.ClipboardManager.setPrimaryClip(ClipboardManager.java:143)
at com.badlogic.gdx.backends.android.AndroidClipboard.setContents(SourceFile:2)
...
at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener$1.tap(SourceFile:2)
at com.badlogic.gdx.input.GestureDetector.touchUp(SourceFile:17)
at com.badlogic.gdx.scenes.scene2d.utils.ActorGestureListener.handle(SourceFile:11)
at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(SourceFile:21)
at com.badlogic.gdx.InputMultiplexer.touchUp(SourceFile:3)
at com.badlogic.gdx.InputMultiplexer.touchUp(SourceFile:3)
at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(SourceFile:29)
at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(SourceFile:38)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

#### Please select the affected platforms
- [X] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] MacOS

Let me know if you need more info. Thanks!

**Comment by MobiDevelop** [comment]
Seems Samsung was (on v19) unsafely showing a Toast message from the ClipboardManager by assuming that setPrimaryClip will always be called on the main thread. I suppose we could force this to the main thread - though it doesn't seem to be a widespread issue.
