### ISSUE TITLE
TextField/TextArea crash with .markupEnabled=true on input of [square]bracket[] pairs

### ISSUE THREAD

**Issue by Grisgram** [libgdx/libgdx#6387]
Hello again,

libGdx 1.9.13
I encountered a second bug in those two controls:

If you use a font with `.getData().markupEnabled = true;` and the user types square brackets, the cursorposition may get out of sync and when the user enters an empty square bracket pair [ ] (which is interpreted as "reset color" in markupEnabled), both controls crash as soon as the closing bracket is typed.

[18.381 DesktopLauncher] Exception caught in main game loop with graphics at 1285x776.
java.lang.IndexOutOfBoundsException: index can't be >= size: 19 >= 18
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.drawCursor(TextField.java:391)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:358)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:97)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:543)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:117)
	at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:253)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)

cheers, Gris
(Haerion on discord... gonna change my github username...)

**Comment by crykn** [comment]
Hey @Grisgram this is a known issue, see https://github.com/libgdx/libgdx/issues/4576#issuecomment-359413117. A PR is still welcome.
