### ISSUE TITLE
Creating a FrameBuffer object results in an org.lwjgl.opengl.OpenGLException after upgrading to libgdx 1.9.14

### ISSUE THREAD

**Issue by JohannStolz** [libgdx/libgdx#6419]
#### Issue details
After updating the libgdx version from 1.9.13 to 1.9.14, the program began to crash at the stage of creating a FrameBuffer object like
`fboA = new FrameBuffer(Pixmap.Format.RGBA8888, (int) BaseGame.WIDTH, (int) BaseGame.HEIGHT, false);` 
with org.lwjgl.opengl.OpenGLException: Cannot use offsets when Pixel Unpack Buffer Object is disabled

#### Reproduction steps/code
Create in a project with libdx version lower than 1.9.14 (tested on versions 1.9.12 and 1.9.13), a FrameBuffer object using the 
`public FrameBuffer (Pixmap.Format format, int width, int height, boolean hasDepth)`, start a program,
make sure that initialization of the  FrameBuffer object occurs without exceptions, change the libdx version in the project to 1.9.14,  start a programm, get an exception.  

#### Version of LibGDX and/or relevant dependencies
1.9.14
#### Stacktrace
```
        org.lwjgl.opengl.OpenGLException: Cannot use offsets when Pixel Unpack Buffer Object is disabled
	at org.lwjgl.opengl.GLChecks.ensureUnpackPBOenabled(GLChecks.java:125)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:2899)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glTexImage2D(LwjglGL20.java:598)
	at com.badlogic.gdx.graphics.glutils.GLOnlyTextureData.consumeCustomData(GLOnlyTextureData.java:78)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:270)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:257)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:159)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:147)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:81)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:42)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:174)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:75)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:57)
	at com.johannstolz.childremote.screen.stage.MyStage.<init>(MyStage.java:57)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] MacOS

**Comment by mgsx-dev** [comment]
It was a regression in 1.9.14, It's fixed in 1.9.15-SNAPSHOT. Sorry about that.
