### ISSUE TITLE
Some GlyphLayout random crashes

### ISSUE THREAD

**Issue by fgnm** [libgdx/libgdx#6588]
#### Issue details
Sometimes I got these crashes in `GlyphLayout` class. Unfortunately I cannot find a way to exactly reproduce the crash as they happens random. If I put Label rendering into a `try catch` block, I can see that the crash happens just for one random frame without any particular reason I can explain.

#### Version of LibGDX and/or relevant dependencies
Currently testing `1.10.0` and latest `1.10.1`, but I've got these in past (not sure from which version appears). Currently I've noticed them in LWJGL3 and Android, but I guess they will happens on other platforms too.

#### Stacktrace
This crash happens more often
```java
    java.lang.NullPointerException: Attempt to read from field 'int com.badlogic.gdx.graphics.g2d.BitmapFont$Glyph.width' on a null object reference
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.getGlyphWidth(GlyphLayout.java:442)
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.calculateAndSetWidths(GlyphLayout.java:301)
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:278)
        at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:77)
        at com.badlogic.gdx.scenes.scene2d.ui.Label.computePrefSize(Label.java:164)
        at com.badlogic.gdx.scenes.scene2d.ui.Label.scaleAndComputePrefSize(Label.java:148)
        at com.badlogic.gdx.scenes.scene2d.ui.Label.getPrefWidth(Label.java:245)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:87)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:827)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:432)
        at com.badlogic.gdx.scenes.scene2d.ui.Value$3.get(Value.java:87)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.computeSize(Table.java:827)
        at com.badlogic.gdx.scenes.scene2d.ui.Table.getPrefWidth(Table.java:432)
        at com.badlogic.gdx.scenes.scene2d.ui.Window.getPrefWidth(Window.java:328)
        at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.pack(WidgetGroup.java:151)
```

This one is less frequent but also random
```Java
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=4 srcPos=0 dst.length=8 dstPos=0 length=5
       at java.lang.System.arraycopy(System.java)
       at com.badlogic.gdx.utils.Array.resize(Array.java:420)
       at com.badlogic.gdx.utils.Array.add(Array.java:101)
       at com.badlogic.gdx.utils.Pool.free(Pool.java:63)
       at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:285)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.layout(Label.java:223)
       at com.badlogic.gdx.scenes.scene2d.ui.Widget.validate(Widget.java:88)
       at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:230)
       at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
       at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
       at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
```

#### Please select the affected platforms
- [x] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [x] Linux
- [x] MacOS

**Comment by piotr-j** [comment]
There doesnt seem to be a `1.10.1` yet, just SNAPSHOT. `getGlyphWidth` is new and there are few recent commits mentioning fixed crashes. Reverting to release version might be a good idea.

**Comment by tommyettinger** [comment]
Have you encountered the crash on all four of the checked platforms, or just some? Android might have device-specific bugs, and I'm aware of some rare bugs when running on older Intel Atom processors (I'm guessing those were on Linux, since they were reported on a server as well as on some consumer PCs).

**Comment by fgnm** [comment]
I personally got them on Android, Windows, Linux and macOS.. I'm thinking that this could be a duplicate issue of #6330, in android and desktop I use respectively `runOnUiThread` and `Executors` to perform some operations in the platform specific code.. By checking all thread execution and using `Gdx.app.postRunnable` when necessary, looks like that no more crashes happens at least on android.. I've to do more checks

**Comment by NathanSweet** [comment]
GlyphLayout is not thread safe, it is likely access from a thread other than the libgdx game thread.

**Comment by fgnm** [comment]
Closing because by fixing thread managements crashes looks like doesn't appear anymore on each platforms, thanks all!
