### ISSUE TITLE
I18NBundle: ChoiceFormat throws exception for number formats with decimals

### ISSUE THREAD

**Issue by TCreutzenberg** [libgdx/libgdx#6616]
#### Issue details
The I18NBundle throws an exception for choice + number format with decimals.

`{0,choice,0#zero|0<{0,number,integer}}` works fine.
`{0,choice,0#zero|0<{0,number,#.##}}` throws an exception stating `Choice Pattern incorrect: 0#zero|0<{0,number,#.##}` which seems wrong according to the code examples below.

This issue can be seen as a bug or a feature request.

#### Reproduction steps/code

I use I18NBundle#format(String key, Object... args)

Keys with args:
`{0,number,integer}` with `1000` = `1,000`
`{0,number,#.##}` with `1000` = `1000`
`{0,number,#.##}` with `1234.56` = `1,234.56`

`{0,choice,0#zero|0<{0,number,integer}}` with `0` = `zero`
`{0,choice,0#zero|0<{0,number,integer}}` with `1000` = `1,000`
`{0,choice,0#zero|0<{0,number,#.##}}` with any number throws:
```
Exception in thread "main" java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#zero|0<{0,number,#.##}
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1544)
	at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:492)
	at com.badlogic.gdx.utils.TextFormatter.format(TextFormatter.java:61)
	at com.badlogic.gdx.utils.I18NBundle.format(I18NBundle.java:451)
	...
Caused by: java.lang.IllegalArgumentException: Each interval must contain a number before a format
	at java.base/java.text.ChoiceFormat.applyPattern(ChoiceFormat.java:206)
	at java.base/java.text.ChoiceFormat.<init>(ChoiceFormat.java:321)
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1541)
	... 21 more
```

#### Version of libGDX and/or relevant dependencies
1.10.1-SNAPSHOT

#### Stacktrace
See above

#### Please select the affected platforms
Tested on Windows 10 but this should be platform-independent code and should affect all platforms

**Comment by NathanSweet** [comment]
PR is welcome! I've never used the i18n stuff myself.
