### ISSUE TITLE
3D Particle Effect Editor don`t load Texture Atlas

### ISSUE THREAD

**Issue by Slexxxx** [libgdx/libgdx#6660]
#### Issue details
3D Particle Effect Editor doesn`t load Texture Atlas

#### Reproduction steps/code
Exception in thread "AWT-EventQueue-0" com.badlogic.gdx.utils.GdxRuntimeException: Asset not loaded: F:/xxx.atlas
	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:158)
	at com.badlogic.gdx.assets.AssetManager.get(AssetManager.java:135)
	at com.badlogic.gdx.tools.flame.FlameMain.load(FlameMain.java:1001)
	at com.badlogic.gdx.tools.flame.TextureLoaderPanel$2.actionPerformed(TextureLoaderPanel.java:56)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

#### Version of libGDX and/or relevant dependencies
1.10.1-SNAPSHOT

#### Please select the affected platforms
WIN10

**Comment by Dgzt** [comment]
I've tried to reproduce this issue with particle:

https://user-images.githubusercontent.com/1684274/200127105-6d0b49bc-a638-40d6-b0c5-181b5b124ec3.mp4

and without particle:

https://user-images.githubusercontent.com/1684274/200127117-4cc1a776-42e7-4e96-b069-4d9a80cabd07.mp4

As you see, it worked for me. Do you remember what you did when you got this issue?

Test atlas:

[test_atlas.zip](https://github.com/libgdx/libgdx/files/9944130/test_atlas.zip)
