### ISSUE TITLE
LWJGL3 doesn't raise fatal exception

### ISSUE THREAD

**Issue by fgnm** [libgdx/libgdx#6780]
#### Issue details
With latest commit 7f5017aaac47cead603a24df2882a06e680ce266 the `Lwjgl3Application` is not able to rise fatal exceptions. When for example an NPE happens the app closes silently without rise exception.

Ref to https://github.com/libgdx/libgdx/commit/7f5017aaac47cead603a24df2882a06e680ce266#r64441191

#### Reproduction steps/code
Create a `Lwjgl3Application` and make an NPE, the app will close without errors/stacktrace.

#### Version of libGDX and/or relevant dependencies
latest libGDX head 7f5017aaac47cead603a24df2882a06e680ce266

#### Stacktrace
Well.. None :p

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] macOS

**Comment by badlogic** [comment]
I've tried to reproduce this on macOS, adding `throw new GdxRuntimeException()` in the `Lwjgl3TestStarter.create()` method. But I get the expected exception:

```
Exception in thread "main" java.lang.RuntimeException
	at com.badlogic.gdx.tests.lwjgl3.Lwjgl3TestStarter$TestChooser.create(Lwjgl3TestStarter.java:92)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:190)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:164)
	at com.badlogic.gdx.tests.lwjgl3.Lwjgl3TestStarter.main(Lwjgl3TestStarter.java:83)
```

Please provide an `ApplicationListener` implementation that shows the issue.

**Comment by fgnm** [comment]
Can't try if macOS has different behavior, but in Ubuntu (20.04) even with an empty project I cannot get exception.
```Java
public class Main {
    public static void main(String[] args) {
        new Lwjgl3Application(new TestApp(), new Lwjgl3ApplicationConfiguration());
    }

    private static class TestApp implements ApplicationListener {

        @Override
        public void create() {
            throw new RuntimeException("test");
        }

        @Override
        public void resize(int width, int height) {

        }

        @Override
        public void render() {

        }

        @Override
        public void pause() {

        }

        @Override
        public void resume() {

        }

        @Override
        public void dispose() {

        }
    }
}
```

It's easy to confirm the issue because I can override `cleanup` method in this way and finally I can get correctly the stacktrace:
```Java
public class Main {
    public static void main(String[] args) {
        new Lwjgl3Application(new TestApp(), new Lwjgl3ApplicationConfiguration()) {
            @Override
            protected void cleanup() {
                //Don't call super method
                //super.cleanup();
            }
        };
    }

    private static class TestApp implements ApplicationListener {

        @Override
        public void create() {
            throw new RuntimeException("test");
        }

        @Override
        public void resize(int width, int height) {

        }

        @Override
        public void render() {

        }

        @Override
        public void pause() {

        }

        @Override
        public void resume() {

        }

        @Override
        public void dispose() {

        }
    }
}
```

*Stacktrace*
```
Exception in thread "main" java.lang.RuntimeException: test
	at games.rednblack.editor.Main$TestApp.create(Main.java:69)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:190)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:164)
	at games.rednblack.editor.Main$1.<init>(Main.java:57)
	at games.rednblack.editor.Main.main(Main.java:57)
```

I'm not using `gdx-lwjgl3-angle` nor `gdx-lwjgl3-glfw-awt-macos`

**Comment by badlogic** [comment]
Confirmed it, reverted the change. Thanks!
