### ISSUE TITLE
Running error:Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit

### ISSUE THREAD

**Issue by chebyshevvv** [libgdx/libgdx#6813]
I diden't use the setup tool but created project by myself in jetbrain ideal.i just wrote the codes blow.
public class DesktopLauncher {
    public static void main(String[] args) {
        Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
        config.setTitle("demo");
        config.setWindowedMode(480,320);
        new Lwjgl3Application(new MyDemoGame(),config);
    }
}
Then I ran it but an error happens.
the stack trace : 
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3NativesLoader.load(Lwjgl3NativesLoader.java:28)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:80)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:91)
	at com.chebyshev.gamedemo.DesktopLauncher.main(DesktopLauncher.java:17)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: gdx64.dll
	at com.badlogic.gdx.utils.SharedLibraryLoader.readFile(SharedLibraryLoader.java:134)
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:290)
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:122)
	... 5 more

lib version : 1.10
platform : Windows11 64 bit

**Comment by tommyettinger** [comment]
You're missing vital dependencies, most likely the platform jar or jars. The setup tools exist for a reason; it is hard to set up a project from scratch, and tools like gdx-setup and gdx-liftoff have already done the hard work for you. You can either use an existing project as a template or make a project with a setup tool; either one will show what dependencies are needed to get this project operational.

This is a bug tracker and this is not a report of any kind of bug in libGDX, so I'll close. Requests for help with your own code belong in places like [the Discord server](https://libgdx.com/community/discord/) .

**Comment by chebyshevvv** [comment]
> You're missing vital dependencies, most likely the platform jar or jars. The setup tools exist for a reason; it is hard to set up a project from scratch, and tools like gdx-setup and gdx-liftoff have already done the hard work for you. You can either use an existing project as a template or make a project with a setup tool; either one will show what dependencies are needed to get this project operational.
> 
> This is a bug tracker and this is not a report of any kind of bug in libGDX, so I'll close. Requests for help with your own code belong in places like [the Discord server](https://libgdx.com/community/discord/) .

The same error happens when I run the project that the setup tool generated.

**Comment by chebyshevvv** [comment]
sorry it was my fault . To avoid this error when I use Maven just need to  import dependence like this :
<dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-platform</artifactId>
            <version>1.10.0</version>
            <classifier>natives-desktop</classifier>
</dependency>
Hope this is help for people encountering same problem.

**Comment by Cucuzacu** [comment]
NO WAY DUDE!!! THANKS A LOT!!! IT WORKED!
