### ISSUE TITLE
`Lwjgl3ApplicationConfiguration#enableGLDebugOutput` doesn't work with `GLEmulation.ANGLE_GLES20`

### ISSUE THREAD

**Issue by fgnm** [libgdx/libgdx#6861]
#### Issue details
As title, it is not possible to enable the GL debug if `ANGLE_GLES20` is enabled.

#### Reproduction steps/code
```Java
Lwjgl3ApplicationConfiguration config = new Lwjgl3ApplicationConfiguration();
config.enableGLDebugOutput(true, System.out);
config.setOpenGLEmulation(Lwjgl3ApplicationConfiguration.GLEmulation.ANGLE_GLES20, 3, 2);
new Lwjgl3Application(new App(), config);
```

#### Version of libGDX and/or relevant dependencies
libGDX 1.10.1-SNAPSHOT

#### Stacktrace
```java
java.lang.IllegalStateException: No GLCapabilities instance set for the current thread. Possible solutions:
	a) Call GL.createCapabilities() after making a context current in the current thread.
	b) Call GL.setCapabilities() if a GLCapabilities instance already exists for the current context.
	at org.lwjgl.opengl.GL.checkCapabilities(GL.java:234)
	at org.lwjgl.opengl.GL.getCapabilities(GL.java:229)
	at org.lwjgl.opengl.GLUtil.setupDebugMessageCallback(GLUtil.java:41)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:586)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [X] Linux
- [X] macOS

**Comment by jootnet** [comment]
the fact, Lwjgl3ApplicationConfiguration.GLEmulation.GL30 also crash for me. In mac os

**Comment by crykn** [comment]
Hey @jootnet, your problem is most certainly not related to the one reported in this issue. Instead, it's likely caused by the fact that macOS only supports the OpenGL 3.2 core profile for OpenGL 3, see #5960.
