### ISSUE TITLE
gdx-backend-lwjgl3 references natives that cannot be found or do not exist, causes build to fail

### ISSUE THREAD

**Issue by WasabiThumb** [libgdx/libgdx#6878]
#### Issue details
In a new project created with the provided tool and imported with IntelliJ IDEA, with a project SDK of 18 and running on Linux, trying to run or build the project fails as gradle cannot locate "natives-linux-arm64" for lwjgl-glfw, lwjgl-openal, lwjgl-opengl, lwjgl-stb and lwjgl.

#### Version of libGDX and/or relevant dependencies
```
        gdxVersion = '1.11.0'
        roboVMVersion = '2.3.16'
        box2DLightsVersion = '1.5'
        ashleyVersion = '1.7.4'
        aiVersion = '1.8.2'
        gdxControllersVersion = '2.2.1'
```

#### Stacktrace
**Without fix**:
```
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not find lwjgl-glfw-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl-glfw:3.3.1).
Searched in the following locations:
    file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-linux-arm64.jar
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:388)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:137)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
	<truncated>
```
[See full paste here](https://pastebin.com/w056AQk0)

**With "fix"**:
Runs fine, however:
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [X] Linux
- [ ] macOS

**The "fix"**:
This is not at all ideal, and essentially just excludes lwjgl, lwjgl-glfw etc. from gdx-backend-lwjgl3 and replaces it with all the same stuff except excluding the natives that cause trouble. I've commented out the windows and mac natives, because for some reason they cannot be found on my Linux machine similarly to the Linux ARM64 natives that originally caused this problem (which are also commented out). This is a problem because it will produce a binary that's not actually cross-platform, however it at least **runs** and I can continue development. The list of natives is based on the [pom.xml file for gdx-backend-lwjgl3](https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-backend-lwjgl3/1.11.0/gdx-backend-lwjgl3-1.11.0.pom).
```gradle
project(":desktop") {
    apply plugin: "java-library"


    dependencies {
        implementation project(":core")
        api("com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion") {
            // this is required because gdx-backend-lwjgl3 tries to link in non-existent ARM64 natives
            exclude group: 'org.lwjgl', module: 'lwjgl-glfw'
            exclude group: 'org.lwjgl', module: 'lwjgl-openal'
            exclude group: 'org.lwjgl', module: 'lwjgl-opengl'
            exclude group: 'org.lwjgl', module: 'lwjgl-stb'
            exclude group: 'org.lwjgl', module: 'lwjgl'
        }
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        api "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"

        // re-add the dependencies manually, no natives
        api "org.lwjgl:lwjgl-glfw:3.3.1"
        api "org.lwjgl:lwjgl-openal:3.3.1"
        api "org.lwjgl:lwjgl-opengl:3.3.1"
        api "org.lwjgl:lwjgl-stb:3.3.1"
        api "org.lwjgl:lwjgl:3.3.1"

        // selectively re-add the natives
        // Linux //
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-linux"
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-linux-arm32"
        // api "org.lwjgl:lwjgl-glfw:3.3.1:natives-linux-arm64"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-linux"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-linux-arm32"
        // api "org.lwjgl:lwjgl-openal:3.3.1:natives-linux-arm64"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-linux"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-linux-arm32"
        // api "org.lwjgl:lwjgl-opengl:3.3.1:natives-linux-arm64"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-linux"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-linux-arm32"
        // api "org.lwjgl:lwjgl-stb:3.3.1:natives-linux-arm64"
        api "org.lwjgl:lwjgl:3.3.1:natives-linux"
        api "org.lwjgl:lwjgl:3.3.1:natives-linux-arm32"
        // api "org.lwjgl:lwjgl:3.3.1:natives-linux-arm64"

        // MacOS //
        /*
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-macos"
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-macos-arm64"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-macos"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-macos-arm64"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-macos"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-macos-arm64"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-macos"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-macos-arm64"
        api "org.lwjgl:lwjgl:3.3.1:natives-macos"
        api "org.lwjgl:lwjgl:3.3.1:natives-macos-arm64"
         */

        // Windows //
        /*
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-windows"
        api "org.lwjgl:lwjgl-glfw:3.3.1:natives-windows-x86"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-windows"
        api "org.lwjgl:lwjgl-openal:3.3.1:natives-windows-x86"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-windows"
        api "org.lwjgl:lwjgl-opengl:3.3.1:natives-windows-x86"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-windows"
        api "org.lwjgl:lwjgl-stb:3.3.1:natives-windows-x86"
        api "org.lwjgl:lwjgl:3.3.1:natives-windows"
        api "org.lwjgl:lwjgl:3.3.1:natives-windows-x86"
         */
    }
}
```

Compare to this version given by the project creation tool, which "causes" the error described:
```gradle
    dependencies {
        implementation project(":core")
        api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        api "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
    }
```

**Comment by Tom-Ski** [comment]
https://repo1.maven.org/maven2/org/lwjgl/lwjgl-glfw/3.3.1/
this dependency does exist, your log is showing that its only looking in maven local and then failing to find it. 
Can you show your repositories configuration?

**Comment by tommyettinger** [comment]
This happens to me a lot; I usually just remove `mavenLocal()` from my Gradle `repositories` and it works as soon as I sync again. Gradle is not the most reliable software...

**Comment by WasabiThumb** [comment]
> https://repo1.maven.org/maven2/org/lwjgl/lwjgl-glfw/3.3.1/ this dependency does exist, your log is showing that its only looking in maven local and then failing to find it. Can you show your repositories configuration?

I did realize that and thought it was strange, but dismissed it since I haven't touched my repositories :^|
```gradle
    repositories {
        mavenLocal()
        mavenCentral()
        google()
        gradlePluginPortal()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
        maven { url "https://jitpack.io" }
    }
```

**Comment by WasabiThumb** [comment]
> This happens to me a lot; I usually just remove `mavenLocal()` from my Gradle `repositories` and it works as soon as I sync again. Gradle is not the most reliable software...

This worked! How strange that Gradle doesn't even bother to look elsewhere if it cant find your dependency in the local repository, but only sometimes. I still don't really consider this a fix but someone else can close the issue if they feel like this is a gradle-related hangup and not a problem with gdx-backend-lwjgl3.

**Comment by Tom-Ski** [comment]
These dependencies are added using classifier notation, you are just seeing the "expanded" version that shows you it raw.

This is probably not Gradle, but Gradle plugin for IDEA that is not resolving this properly. Running from command line, gradle is probably quite happy.

**Comment by WasabiThumb** [comment]
The only thing that is being changed here is the build.gradle, it's clearly an issue with Gradle as it's Gradle's sole responsibility to resolve those dependencies afaik

**Comment by Tom-Ski** [comment]
No its not, IDEA plugin is integrating Gradle into the IDE tooling system. Its in the stacktrace you posted.
`	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:388)`
This is the gradle integration plugin from jetbrains trying to import, and falling short.

Run your project from command line outside of IDEA, if it truly is a Gradle problem, you will get the same failure, but with a different stacktrace because obviously IDEA plugins do not exist there. A simple `./gradlew desktop:run` from terminal/shell will determine where that problem actually is.

**Comment by WasabiThumb** [comment]
> if it truly is a Gradle problem, you will get the same failure, but with a different stacktrace because obviously IDEA plugins do not exist there.

```
> Task :desktop:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:compileJava'.
> Could not resolve all files for configuration ':desktop:compileClasspath'.
   > Could not find lwjgl-glfw-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl-glfw:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-linux-arm64.jar
   > Could not find lwjgl-glfw-3.3.1-natives-macos.jar (org.lwjgl:lwjgl-glfw:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos.jar
   > Could not find lwjgl-glfw-3.3.1-natives-macos-arm64.jar (org.lwjgl:lwjgl-glfw:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-macos-arm64.jar
   > Could not find lwjgl-glfw-3.3.1-natives-windows.jar (org.lwjgl:lwjgl-glfw:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
   > Could not find lwjgl-glfw-3.3.1-natives-windows-x86.jar (org.lwjgl:lwjgl-glfw:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows-x86.jar
   > Could not find lwjgl-openal-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl-openal:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-linux-arm64.jar
   > Could not find lwjgl-openal-3.3.1-natives-macos.jar (org.lwjgl:lwjgl-openal:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos.jar
   > Could not find lwjgl-openal-3.3.1-natives-macos-arm64.jar (org.lwjgl:lwjgl-openal:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-macos-arm64.jar
   > Could not find lwjgl-openal-3.3.1-natives-windows.jar (org.lwjgl:lwjgl-openal:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
   > Could not find lwjgl-openal-3.3.1-natives-windows-x86.jar (org.lwjgl:lwjgl-openal:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows-x86.jar
   > Could not find lwjgl-opengl-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl-opengl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-linux-arm64.jar
   > Could not find lwjgl-opengl-3.3.1-natives-macos.jar (org.lwjgl:lwjgl-opengl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos.jar
   > Could not find lwjgl-opengl-3.3.1-natives-macos-arm64.jar (org.lwjgl:lwjgl-opengl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-macos-arm64.jar
   > Could not find lwjgl-opengl-3.3.1-natives-windows.jar (org.lwjgl:lwjgl-opengl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
   > Could not find lwjgl-opengl-3.3.1-natives-windows-x86.jar (org.lwjgl:lwjgl-opengl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows-x86.jar
   > Could not find lwjgl-stb-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl-stb:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-linux-arm64.jar
   > Could not find lwjgl-stb-3.3.1-natives-macos.jar (org.lwjgl:lwjgl-stb:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos.jar
   > Could not find lwjgl-stb-3.3.1-natives-macos-arm64.jar (org.lwjgl:lwjgl-stb:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-macos-arm64.jar
   > Could not find lwjgl-stb-3.3.1-natives-windows.jar (org.lwjgl:lwjgl-stb:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
   > Could not find lwjgl-stb-3.3.1-natives-windows-x86.jar (org.lwjgl:lwjgl-stb:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows-x86.jar
   > Could not find lwjgl-3.3.1-natives-linux-arm64.jar (org.lwjgl:lwjgl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-linux-arm64.jar
   > Could not find lwjgl-3.3.1-natives-macos.jar (org.lwjgl:lwjgl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos.jar
   > Could not find lwjgl-3.3.1-natives-macos-arm64.jar (org.lwjgl:lwjgl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-macos-arm64.jar
   > Could not find lwjgl-3.3.1-natives-windows.jar (org.lwjgl:lwjgl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar
   > Could not find lwjgl-3.3.1-natives-windows-x86.jar (org.lwjgl:lwjgl:3.3.1).
     Searched in the following locations:
         file:/home/wasabi/.m2/repository/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows-x86.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

The IDEA plugin is clearly just wrapping gradle functionality and passing along the exceptions, e.g. `throw new ExternalSystemException(gradleException)` just like I thought.

**Comment by WasabiThumb** [comment]
Here it is with the --stacktrace option, for your viewing pleasure.
`./gradlew desktop:run --stacktrace &> log.txt`
[log.txt](https://github.com/libgdx/libgdx/files/8767190/log.txt)

**Comment by Tom-Ski** [comment]
Good to isolate it to Gradle. 

Are you running on arm32? did you manually build lwjgl natives on your system? Do you have any lwjgl maven artifacts in your maven local repo? Because that should be the only reason mavenLocal would be populated with only those natives.  Your idea makes sense as a possible cause, and maybe a limitation of dependency resolution, but these should all be treated as separate artifacts during dependency resolution, so one should not have my impact on another. But would need to look at the source for more details.

Worth noting that that this is not a new issue, been happening in Gradle for 9+years, changing the order of the repositories should also 'fix' it. I have seen many threads address this, and the other repos have also been known to cause this exact failure, jcenter and google in combination with plugins. 


For us, we should just remove it, since only people that gain anything from it are people building from source, in which case they can add it. But its still an interesting problem to see where exactly this is being.

**Comment by WasabiThumb** [comment]
Q: Are you running on arm32?
A: amd64

Q: Did you manually build lwjgl natives on your system?
A: Never built lwjgl natives manually, never installed any lwjgl natives to maven local

Q: Do you have any lwjgl maven artifacts in your maven local repo?
A: I'm guessing so, because it's managing to find linux and linux-arm32 natives just fine. Here's a directory listing for `~/.m2/repository/org/lwjgl/lwjgl/3.3.1`.
```
_remote.repositories                      lwjgl-3.3.1-natives-linux.jar       lwjgl-3.3.1.jar.sha1
lwjgl-3.3.1-natives-linux-arm32.jar       lwjgl-3.3.1-natives-linux.jar.sha1  lwjgl-3.3.1.pom
lwjgl-3.3.1-natives-linux-arm32.jar.sha1  lwjgl-3.3.1.jar                     lwjgl-3.3.1.pom.sha1
```
I also did some digging around and found `~/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.3` which has a couple of the missing natives. Note, not all of them, namely linux-arm64. Really puzzling.
```
_remote.repositories                         lwjgl-platform-2.9.3-natives-windows.jar
lwjgl-platform-2.9.3-natives-linux.jar       lwjgl-platform-2.9.3-natives-windows.jar.sha1
lwjgl-platform-2.9.3-natives-linux.jar.sha1  lwjgl-platform-2.9.3.pom
lwjgl-platform-2.9.3-natives-osx.jar         lwjgl-platform-2.9.3.pom.sha1
lwjgl-platform-2.9.3-natives-osx.jar.sha1
```

> changing the order of the repositories should also 'fix' it

Moving mavenLocal() to the end of the list does actually 'fix' it. God I love Gradle.

**Comment by Tom-Ski** [comment]
Yeah, so thats it. MavenLocal is searched first, finds a result so chooses that repository for that module. All other repositories are ignored, and then it fails because the other artifacts are not in mavenLocal.

This part apparently isn't a bug, this behaviour is as described in their docs. So if we can accept that, then the _real_ bug, is how come there is a partial result of artifacts in mavenLocal.

**Comment by Tom-Ski** [comment]
Oh, @WasabiThumb have you used pure maven with this same version? Like a project managed by maven bringing in deps of 3.3.1?

If you did, and had
```xml
<dependency>
  <groupId>org.lwjgl</groupId>
  <artifactId>lwjgl</artifactId>
  <version>3.3.1</version>
  <classifier>natives-linux</classifier>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>org.lwjgl</groupId>
  <artifactId>lwjgl</artifactId>
  <version>3.3.1</version>
  <classifier>natives-linux-arm32</classifier>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>org.lwjgl</groupId>
  <artifactId>lwjgl</artifactId>
  <version>3.3.1</version>
  <classifier>natives-linux-arm64</classifier>
  <scope>compile</scope>
</dependency>
```
only, then it all makes sense.

**Comment by Samyssmile** [comment]
For me to remove 

` mavenLocal()`

fixed the issue

**Comment by crykn** [comment]
Since this isn't a bug within libGDX, but rather a (usage) problem with Gradle, I'm closing this for now.
