### ISSUE TITLE
SpriteBatch + opengl 3.2 throw exception on macos with m1 chip

### ISSUE THREAD

**Issue by kunterbunt2** [libgdx/libgdx#6897]
Please ensure you have given all the following requested information in your report.

#### Issue details
to simplify the debugging I created a simple test using the project creator wizard.
https://github.com/kunterbunt2/libgdx4m1
if run with setOpenGLEmulation(GLEmulation.GL30, 3, 2), it will throw an exception on a mac mini with m1 chip.
exception at https://github.com/kunterbunt2/libgdx4m1/blob/main/SpriteBatchTestException.txt

xception in thread "main" java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error
Fragment shader:
ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:7: 'varying' : syntax error: syntax error

	at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:164)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:127)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:81)
	at com.mygdx.game.Libgdx4M1.create(Libgdx4M1.java:14)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.mygdx.game.full.screen.SpriteBatchTest.main(SpriteBatchTest.java:21)

#### Reproduction steps/code
import project at https://github.com/kunterbunt2/libgdx4m1 as gradle project into Eclipse with jre 1.8.
execute desktop/src/com/mygdx/game/full/screen)/SpriteBatchTest.java
you will see exception

#### Version of libGDX and/or relevant dependencies

libgdx 1.11.0 + gdx-lwjgl3-glfw-awt-macos

Stacktrace
https://github.com/kunterbunt2/libgdx4m1/blob/main/SpriteBatchTestException.txt

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by crykn** [comment]
See #5960.

**Comment by kunterbunt2** [comment]
Wow, that was fast. Will try it tomorrow. Strange that I did not find that ticket. Sorry!

**Comment by kunterbunt2** [comment]
@crykn it looks as if the latest version of your gdx library (that is compatible with libgdx 1.11), is not available as an artifact. 0.3.1 is available, but not 0.3.2. Strange is that the core library is available.
I cannot actually search at https://oss.sonatype.org/content/repositories/snapshots, I have to use maven for that.

**Comment by tommyettinger** [comment]
You should probably use JitPack to get Guacamole, if that's what you're referring to. https://jitpack.io/#crykn/guacamole/v0.3.2

**Comment by kunterbunt2** [comment]
I use jitpack and can get the core library, but not the gtx library. I switched to previous version until the 0.3.2 is deployed to jitpack.

**Comment by crykn** [comment]
The Jitpack [build log](https://jitpack.io/com/github/crykn/guacamole/0.3.2/build.log) says it's there, but I remember having some trouble with the same artifact missing in the past as well. Alternatively, you could just copy the necessary classes. 

Btw opinions on and reviews of #5960 are very welcome!

**Comment by kunterbunt2** [comment]
I will check when I am back at my computer. Thanks.

**Comment by kunterbunt2** [comment]
Concerning the pull request. I am new to git and need to study if I can include this in my version to test it, or if this is just a theoretical discussion of the calling convention. 
interestingly, I use both default shaders,  it also added my own pre code to shaders. So, I am interested in the topic , as I am just now trying to get my game working on Mac.
