### ISSUE TITLE
Support Tiled "object" type MapProperty 

### ISSUE THREAD

**Issue by Faust90** [libgdx/libgdx#6901]
gdxVersion = '1.11.0'

Since Tiled 1.4 a Tiled Object can have custom properties of type "object", which can be used to reference another object inside that map.

It would be nice to have support of such feature in LibGDX Tiled libraries.

### STACKTRACE
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Wrong type given for property triggeredBy, given : object, supported : string, bool, int, float, color
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.castProperty(BaseTmxMapLoader.java:446)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadProperties(BaseTmxMapLoader.java:425)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:409)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObject(BaseTmxMapLoader.java:313)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadObjectGroup(BaseTmxMapLoader.java:250)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadLayer(BaseTmxMapLoader.java:174)
	at com.badlogic.gdx.maps.tiled.BaseTmxMapLoader.loadTiledMap(BaseTmxMapLoader.java:161)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:81)
	at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:59)
	at com.faust.lhitgame.game.rooms.impl.FixedRoom.loadTiledMap(FixedRoom.java:52)

**Comment by spencerflem** [comment]
just ran into this as well

**Comment by JohnLavender474** [comment]
Hey, I'd like to take a try at this issue. Could someone assign me to it?

**Comment by JohnLavender474** [comment]
Could you provide an example of how you're trying to use this? Are you wanting to access just the properties of another object?

**Comment by Faust90** [comment]
> Could you provide an example of how you're trying to use this? Are you wanting to access just the properties of another object? One immediate concern is that it's possible to have infinite recursion (depending on what you're wanting to return) if two objects are pointing at each other, i.e. object 1 has a property pointing to object 2, and object 2 also has a prop pointing to object 1.

In my Tiled maps I have "Actors" objects which can be activated by "Trigger" object on a particular game event. Having the Trigger object reference inside the Actor object would be great. As for now, I am using the Tiled object id as a reference, but a full fledged "object" field support would be great.

**Comment by JohnLavender474** [comment]
Hey, so I made a PR for this issue. In my solution, when you have an "object" property, the value ends up being the MapProperties of the tiled object being pointed to. Is this what you were looking for? https://github.com/libgdx/libgdx/pull/7229
