### ISSUE TITLE
com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android

### ISSUE THREAD

**Issue by ainide2990** [libgdx/libgdx#6956]
Please ensure you have given all the following requested information in your report.

#### Issue details
Alway error runtime the gdx-tests-android project, android studio logcat display error info is “Couldn't load shared library 'gdx' for target: Android”

#### Reproduction steps/code
_Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue. This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://libgdx.com/wiki/articles/getting-help)_

#### Version of libGDX and/or relevant dependencies
implementation project(":tests:gdx-tests")
implementation project(":backends:gdx-backend-android")

#### Stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.badlogic.gdx.tests.android/com.badlogic.gdx.tests.android.GdxTestActivity}: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

#### Please select the affected platforms
-Android

**Comment by Frosty-J** [comment]
Have you run the `fetchNatives` Gradle task, or whatever it's called? I forget what there is - IDE should help.

**Comment by obigu** [comment]
As @Frosty-J suggests make sure to follow https://libgdx.com/dev/from-source/. If you still find issues feel free to reopen it with details about your environment, OS and IDE versions and reproduction steps.
