### ISSUE TITLE
IndexOutOfBoundsException with OpenALAudio and AudioDevice

### ISSUE THREAD

**Issue by chrislo27** [libgdx/libgdx#6977]
#### Issue details
A concurrent modification can cause an `IndexOutOfBoundsException` when iterating through the `idleSources` `IntArray` in `OpenALLwjgl3Audio`. While accessing the audio API isn't typically done in multiple threads (usually just called on the rendering thread), when using `AudioDevice` it effectively becomes mandatory due to `AudioDevice#writeSamples` blocking.

My suspicion that it is a concurrency issue stems from the fact that I use `AudioDevice` with the [Beads](https://github.com/orsjb/beads) audio library to produce realtime sample data. This is done in a separate thread because the `AudioDevice#writeSamples` method blocks until it is complete.

In `OpenALLwjgl3Audio#stopSourcesWithBuffer`, the `IntArray` of `idleSources` is iterated through. https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java#L221-L231

However, `idleSources` is only ever mutated in `obtainSource` (an item is removed, L181) or `freeSource` (source added, L205). https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java#L172-L206

In `freeSource`, it is only ever removed if the source `isMusic`, which is only called with `isMusic` = true in `OpenALMusic` and `OpenALAudioDevice#writeSamples(byte[], int, int)`. In the latter's method, `obtainSource` is possibly called. https://github.com/libgdx/libgdx/blob/b86c20cf1a354f5345fd1e8612dcd46c9b46a972/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALAudioDevice.java#L84-L89

In the for loop when iterating through `idleSources` in `OpenALLwjgl3Audio`, the only way for it to throw an `IndexOutOfBoundsException` would be for `n`, being the `idleSources.size` to be larger than what it eventually is in later iterations. Therefore, I believe this can be triggered due to concurrent mutations (specifically removals) of `idleSources` when using `AudioDevice`, since usage of that API warrants multithreading. (See first snippet.) Additionally, there are other instances of iterating through `idleSources` in `OpenALLwjgl3Audio`, it isn't just in `stopSourcesWithBuffer()`.

#### Reproduction steps/code
I don't think this issue is easily reproducible due to my suspicion that it is a concurrency issue, but I have a (LWJGL3 backend) example that could theoretically trigger it. There's a separate thread that feeds `AudioDevice#writeSamples` with a 440 Hz sine tone as a demonstration, and a separate ticking `Sound` that is repeatedly being played and stopped midway through.

```java
import com.badlogic.gdx.ApplicationAdapter;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.AudioDevice;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.math.MathUtils;

public class Barebones extends ApplicationAdapter {
	
	private Sound ticSound;
	private AudioDevice audioDevice;
	private Thread audioDevThread;
	private float sfxCountdown = 0f;
	
	public void create () {
		ticSound = Gdx.audio.newSound(Gdx.files.internal("data/tic_long.ogg"));
		
		audioDevice = Gdx.audio.newAudioDevice(44100, false);
		audioDevThread = new Thread(() -> {
			float[] samples = new float[10000];
			
			// Generates a simple sine tone at 440 Hz
			float period = 44100 / 440f;
			for (int i = 0; i < samples.length / 2; i++) {
				float value = (float) Math.sin(2 * MathUtils.PI * i / period);
				value *= 0.075f;
				samples[i * 2] = value;
				samples[i * 2 + 1] = value;
			}
			
			// Constantly write to the audio device. This could underfill it and cause it to lose its source
			while (true) {
				audioDevice.writeSamples(samples, 0, samples.length);
			}
		});
		audioDevThread.setDaemon(true);
		audioDevThread.start();
	}

	public void render () {
		Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
		
		if (sfxCountdown <= 0f) {
			sfxCountdown = 1f;
			ticSound.stop();
			ticSound.play(0.75f);
		} else {
			sfxCountdown -= Gdx.graphics.getDeltaTime() / 0.2f;
		}
	}

	@Override
	public void dispose() {
		super.dispose();
		ticSound.dispose();
		audioDevThread.interrupt();
		audioDevice.dispose();
	}

	public static void main (String[] args) throws Exception {
		new Lwjgl3Application(new Barebones());
	}
}
```

#### Version of libGDX and/or relevant dependencies
libGDX 1.11.0 on commit b86c20cf1a354f5345fd1e8612dcd46c9b46a972, which was the most recent commit at the time of testing and writing. Using the LWJGL3 backend. No other dependencies.

#### Stacktrace
This stacktrace was given to me by one of my users. I was not able to reproduce it but I have detailed my own findings above.
```java
java.lang.IndexOutOfBoundsException: index can't be >= size: 98 >= 98
	at com.badlogic.gdx.utils.IntArray.get(IntArray.java:131)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.stopSourcesWithBuffer(OpenALLwjgl3Audio.java:224)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALSound.stop(OpenALSound.java:98)
        ... triggered by a call in my game to com.badlogic.gdx.audio.Sound#stop()
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by crykn** [comment]
Since no class in libGDX is thread-safe until specified otherwise, I figured this was best categorized as a feature request/enhancement. But you're right, considering the fact that calling the blocking `AudioDevice#writeSamples` on another thread is probably a very common use case, marking this as a bug makes sense as well!

**Comment by mgsx-dev** [comment]
i agree, AudioDevice should be better documented: which method should be called in rendering thread and which are fine (or intended) to be called in another thread.

**Comment by chrislo27** [comment]
> The best solution imho is to move that late init code (source creation) to the constructor, i think it was a copy paste from Music implementation.

I am a bit hesitant about this solution because it's likely that someone who uses AudioDevice in another thread probably also created it in another thread, which could lead to the same problem. (I do that with my interface with Beads and gdx's AudioDevice.) However, I understand that every libGDX class is not thread-safe unless specified, so it's perfectly acceptable to specify that a new AudioDevice should only be created in the main rendering thread.

I suppose that ensuring thread-safe concurrent access to `idleSources` in OpenALLwjgl3Audio would be enough due to its mutability, but I'm not sure on the performance overhead for that.

Thanks for the swift responses so far!
