### ISSUE TITLE
Can't create HexagonTiledMapRenderer with empty TiledMap

### ISSUE THREAD

**Issue by AverageBeerEnjoyer** [libgdx/libgdx#7024]
#### Issue details
I can't create HexagonTiledMapRenderer with empty TiledMap

#### Reproduction steps/code
`private final HexagonalTiledMapRenderer renderer=new HexagonalTiledMapRenderer(new TiledMap());`

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
```java
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
        at com.badlogic.gdx.utils.Array.get(Array.java:155)
        at com.badlogic.gdx.maps.MapLayers.get(MapLayers.java:31)
        at com.badlogic.gdx.maps.tiled.renderers.HexagonalTiledMapRenderer.init(HexagonalTiledMapRenderer.java:89)
        at com.badlogic.gdx.maps.tiled.renderers.HexagonalTiledMapRenderer.<init>(HexagonalTiledMapRenderer.java:43)
        at controllers.MapToRendererTransformator.<init>(MapToRendererTransformator.java:23)
        at com.mygdx.game.view.ConstructorMap.<init>(ConstructorMap.java:47)
        at com.mygdx.game.view.CreateMenuScreen$1.changed(CreateMenuScreen.java:45)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)

```

#### Please select the affected platforms
- [x] Android
- [x] iOS
- [x] HTML/GWT
- [x] Windows
- [x] Linux
- [x] macOS

**Comment by BoBIsHere86** [comment]
This issue has bee fixed with the merging of #7700.

Please close.
