### ISSUE TITLE
Can not run the .jar generated in MacOS Apple M1

### ISSUE THREAD

**Issue by sebaber** [libgdx/libgdx#7051]
I created the .jar for Desktop distribution with task: `./gradlew desktop:dist`. But when i executed it, it comes with this error:

```
% java -jar desktop-1.0.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:84)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
	at com.mobilecostudios.kaiontale.desktop.DesktopLauncher.main(DesktopLauncher.java:28)
Caused by: java.lang.UnsupportedOperationException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/jni/JNINativeInterface.GetJavaVM(Lorg/lwjgl/PointerBuffer;)I @8: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/lwjgl/PointerBuffer' }
    stack: { 'org/lwjgl/PointerBuffer', integer }
  Bytecode:
    0000000: b200 0499 0008 2a04 b800 432a b800 44b8
    0000010: 0045 ac                                
  Stackmap Table:
    same_frame(@11)

	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:130)
	... 5 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/jni/JNINativeInterface.GetJavaVM(Lorg/lwjgl/PointerBuffer;)I @8: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/lwjgl/PointerBuffer' }
    stack: { 'org/lwjgl/PointerBuffer', integer }
  Bytecode:
    0000000: b200 0499 0008 2a04 b800 432a b800 44b8
    0000010: 0045 ac                                
  Stackmap Table:
    same_frame(@11)

	at org.lwjgl.system.MemoryUtil.getMarkOffset(MemoryUtil.java:3018)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:115)
	... 5 more
silmano@Sebastians-MacBook-Air libs % java -jar desktop-1.0.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:84)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration.getDisplayMode(Lwjgl3ApplicationConfiguration.java:219)
	at com.mobilecostudios.kaiontale.desktop.DesktopLauncher.main(DesktopLauncher.java:28)
Caused by: java.lang.UnsupportedOperationException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/jni/JNINativeInterface.GetJavaVM(Lorg/lwjgl/PointerBuffer;)I @8: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/lwjgl/PointerBuffer' }
    stack: { 'org/lwjgl/PointerBuffer', integer }
  Bytecode:
    0000000: b200 0499 0008 2a04 b800 432a b800 44b8
    0000010: 0045 ac                                
  Stackmap Table:
    same_frame(@11)

	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:130)
	... 5 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/jni/JNINativeInterface.GetJavaVM(Lorg/lwjgl/PointerBuffer;)I @8: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @8
    flags: { }
    locals: { 'org/lwjgl/PointerBuffer' }
    stack: { 'org/lwjgl/PointerBuffer', integer }
  Bytecode:
    0000000: b200 0499 0008 2a04 b800 432a b800 44b8
    0000010: 0045 ac                                
  Stackmap Table:
    same_frame(@11)

	at org.lwjgl.system.MemoryUtil.getMarkOffset(MemoryUtil.java:3018)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:115)
	... 5 more
```
Anyone knows what could be?

I try with a MacOS Apple M1 and also in a PC with windows and same issue. I try to use a JDK 8 and didn't work also.

- gdxVersion = '1.11.0'
- JDK 15.0.2
- MacBook Air Apple M1
- desktop dependencies:
  - api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
  - api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
  - api "com.badlogicgames.gdx:gdx-lwjgl3-glfw-awt-macos:$gdxVersion"
  - implementation "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
  - implementation "com.badlogicgames.gdx:gdx-tools:$gdxVersion"
  - implementation "com.badlogicgames.gdx-controllers:gdx-controllers-desktop:$gdxControllersVersion"}

- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [X] Windows
- [ ] Linux
- [X] macOS

**Comment by sebaber** [comment]
tysm for the response! that was the solution i can run without problems with that! i have another problem with the obfuscation right now but i will do another issue if necessary! TYSM!
