### ISSUE TITLE
Problem with native file loading.

### ISSUE THREAD

**Issue by itsPrime3** [libgdx/libgdx#7062]
**Issue details(Over-detailed)**
I was working on a game(still on it) for android (without a IDE)(My own setup) . I was using libgdx 1.9.0 or something like that . and there was no problem . 
But the problem occured when I upgraded to **1.11.0.** 
what was the problem ?

It was nothing (JOKING) . i can built it fine , problem was when I Launch it . it just kicks me out . WTh! tried to find why(maybe problem with my codes) . couldn't find why !
after some changes and testing found that it was something to do with library . at first i thought maybe problem with the native files . I change back - forth versions but at the end it was gdx.jar that had something missing .

I don't know why but **1.11.0** doesn't have ```com.badlogic.gdx.utils.SharedLibraryLoader``` class (1.10.0 has it)

I don't why you guys removed it but for android this class is essential . Maybe you guys found some other way around but forgot to implement it for android (backend(```AndroidApplication``` class)).

#### Reproduction steps/code
Just added ```com.badlogic.gdx.utils.SharedLibraryLoader``` class from **1.10.0** _to_ **1.11.0** and works for me.

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
```java
//Please provide the stacktrace if applicable 
```time: 1673555830933
msg: java.lang.ClassNotFoundException: com.badlogic.gdx.utils.SharedLibraryLoader
stacktrace: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/badlogic/gdx/utils/SharedLibraryLoader;
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:30)
	at com.badlogic.gdx.backends.android.AndroidApplication.init(AndroidApplication.java:115)
	at com.badlogic.gdx.backends.android.AndroidApplication.initialize(AndroidApplication.java:81)
	at com.dark.bounceup.MainActivity.onCreate(MainActivity.java:16)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Activity.performCreate(Activity.java:7978)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1314)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.utils.SharedLibraryLoader
	... 19 more
```

#### Please select the affected platforms
- [ ] Android

**Comment by tommyettinger** [comment]
OK. I'll try to refrain from ranting, but we use dependency management with Gradle for good reasons. In 1.10.0, there was some awkwardly placed SharedLibraryLoader code (it might have been duplicated?), and to save on distributable size and keep code where it logically belonged, that file was moved to the [gdx-jnigen](https://github.com/libgdx/gdx-jnigen) project. You can see the code that relies on this in one of the build.gradle files, https://github.com/libgdx/libgdx/blob/1.11.0/gdx/build.gradle#L43 . 1.11.0 is the first stable release to get SharedLibraryLoader from gdx-jnigen-loader, which is why you're noticing it in this version update, and it seems like you aren't depending on gdx-jnigen-loader, so without that or your solution (copying in an older SharedLibraryLoader), the code wouldn't be able to work correctly. I'd recommend using the gdx-jnigen-loader JAR that 1.11.0 depends on (you can download the JAR from Maven Central directly, https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-jnigen-loader/2.3.1/ , or build from source, https://github.com/libgdx/gdx-jnigen ), but the SharedLibraryLoader code could be the same in 1.10.0 and you might see no difference.

So there we are. This isn't a bug, you were just missing a dependency. Closing.

**Comment by itsPrime3** [comment]
I think you guys should mention some more info in wiki.
thank you for your help.
