### ISSUE TITLE
Crash in native code if Pixmap dimensions are ~2^15 (32768)

### ISSUE THREAD

**Issue by 0xKZ** [libgdx/libgdx#7097]
#### Issue details

I use an OpenGL query to determine the maximum texture dimensions for packing at atlas at runtime, and I ran into this issue that was annoying to debug. 

If this limitation is meant to exist, that's fine, but the Java code should test for it and throw some kind of useful exception. 

#### Reproduction steps/code

Here is a short Kotlin test I wrote that reproduces:

```kotlin
val crashesJvm = 32768
// val throwsCapacityErrorFromUnderflow = 32767
val p = Pixmap(crashesJvm, crashesJvm, Pixmap.Format.RGBA8888)
p.setColor(Color(0f, 0f, 0f, 0f))
p.fill()
```

Note that for a different error, you can use `32767`, this overflows something and it tries to create a negative buffer. At least if I do that I get a stack trace.

#### Version of libGDX and/or relevant dependencies
v 1.11.0

#### Stacktrace
For the crash case (`32768`): This is probably not that useful, but the heap dump for me pointed here:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 3547  com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.clear(JI)V (0 bytes) @ 0x000001fcc1024374 [0x000001fcc1024320+0x0000000000000054]
J 3524 c1 com.badlogic.gdx.graphics.Pixmap.<init>(IILcom/badlogic/gdx/graphics/Pixmap$Format;)V (53 bytes) @ 0x000001fcba052a14 [0x000001fcba052720+0x00000000000002f4]
j  com.badlogic.gdx.graphics.g2d.PixmapPacker$Page.<init>(Lcom/badlogic/gdx/graphics/g2d/PixmapPacker;)V+43
...
```

For the overflow case (`32767`):
```
Exception in thread "HeadlessApplication" java.lang.IllegalArgumentException: capacity < 0: (-262140 < 0)
	at java.base/java.nio.Buffer.createCapacityException(Buffer.java:278)
	at java.base/java.nio.Buffer.<init>(Buffer.java:241)
	at java.base/java.nio.ByteBuffer.<init>(ByteBuffer.java:286)
	at java.base/java.nio.ByteBuffer.<init>(ByteBuffer.java:294)
	at java.base/java.nio.MappedByteBuffer.<init>(MappedByteBuffer.java:110)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:170)
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.newPixmap(Native Method)
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:136)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... (my test code)
```

#### Please select the affected platforms

I only tested this on Windows.

- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
This error probably depends on the format of the Pixmap. If you have 2^15 by 2^15 pixels, each using RGBA8888 format, that uses 2^32 bytes in a ByteBuffer. Using just slightly less for width and height, or using RGB888 format, gives you something between 2^31 and 2^32, which is a negative number in Java (since it has signed ints). I think a 1-byte format like Luminance could actually work with 2^15 by 2^15 pixels.

I'm not sure this even needs to be documented -- you can't create an array that large (the limit is just slightly less than 2^31), just as a limit of the JVM.

**Comment by 0xKZ** [comment]
> 

To a user, it is not obvious that the system internally will try to fully address every pixel using a signed integer, that doesn't really make sense to me (as it would overflow, like in this case).

IMO, an exception on the JVM side is a perfectly reasonable response here. I don't think we should have users of the framework scratching their head at these hard to debug heap dump crashes.

**Comment by tommyettinger** [comment]
32768 is fine for width OR height, just not both width AND height. If width is 32768 and height is much smaller, like 256, then that should need a much smaller buffer, and shouldn't have issues. It's probably possible to check that the capacity a Pixmap will need is within limits, and throw an Exception with info instead of crashing, we just need to be sure what those limits are.

**Comment by 0xKZ** [comment]
> 32768 is fine for width OR height, just not both width AND height. If width is 32768 and height is much smaller, like 256, then that should need a much smaller buffer, and shouldn't have issues. It's probably possible to check that the capacity a Pixmap will need is within limits, and throw an Exception with info instead of crashing, we just need to be sure what those limits are.

Yeah, I meant as more of a one-time check on Pixmap creation where you just multiply out the number of bytes into a long and make sure you can hold 'em in an int.
