### ISSUE TITLE
UIUtils error when use graalvm builld native image

### ISSUE THREAD

**Issue by authorZhao** [libgdx/libgdx#7111]
#### Issue details

i use graalvm build native image in win10,

error code

```
public final class UIUtils {
	public UIUtils () {
		System.out.println("myUIUtils");
	}

	static public boolean isAndroid = System.getProperty("java.runtime.name","").contains("Android");
	static public boolean isMac = !isAndroid && System.getProperty("os.name","").contains("Mac");
	static public boolean isWindows = !isAndroid && System.getProperty("os.name","").contains("Windows");
	static public boolean isLinux = !isAndroid && System.getProperty("os.name","").contains("Linux");
	static public boolean isIos = !isAndroid && (!(isWindows || isLinux || isMac));
}
```

#### Reproduction steps/code

when i use TextField 

- click Mouse
- input word
- error and stop

#### Version of libGDX and/or relevant dependencies

1.11.0

#### Stacktrace

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.git.cube.move.Test3DCube.main(Test3DCube.java:31)
Caused by: java.lang.NullPointerException
        at com.badlogic.gdx.scenes.scene2d.utils.UIUtils.<clinit>(UIUtils.java:12)
        ... 1 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
I can confirm, and it looks like your fix of adding default values for getProperty works. A commit to spotvox is linked above, it has the temporary code I'm using to check a fix for UIUtils. I hadn't tried with the two-argument getProperty() in the linked commit, but it should be similar with that, and when I did try it later, it works just fine.

The code I like best, that I've tested most recently and works, is:

```java
    static private final String osName = System.getProperty("os.name", "");
    static private final String jrName = System.getProperty("java.runtime.name", "");
    static public boolean isAndroid = jrName.contains("Android");
    static public boolean isMac = !isAndroid && osName.contains("Mac");
    static public boolean isWindows = !isAndroid && osName.contains("Windows");
    static public boolean isLinux = !isAndroid && osName.contains("Linux")
            || osName.contains("FreeBSD");
    static public boolean isIos = !isAndroid && (!(isWindows || isLinux || isMac));
```

The non-null default values for properties make all the difference.

**Comment by authorZhao** [comment]
Thanks for listening，I hope to use the fix version earlier
