### ISSUE TITLE
Can we coordinate efforts to support Graal Native Image?

### ISSUE THREAD

**Issue by tommyettinger** [libgdx/libgdx#7113]
#### Issue details
Graal Native Image allows building an entire game, including what would normally be a bundled JRE, into one executable. This also offers some resistance to decompilation, since assets are stored in the executable rather than in the flimsy protection of a JAR. Various people have worked with Native Image before, and I'm not sure if anyone has a 100% optimal way to use it yet. In the PR https://github.com/libgdx/libgdx/pull/7112 , @Berstanio and I discussed some of this, and I feel like an issue for this partly-missing support is a more appropriate venue to invite further discussion.

Some existing work has been done by anyicomplex (who doesn't seem active on GitHub anymore) at https://github.com/anyicomplex?tab=repositories , Berstanio at https://github.com/Berstanio/gdx-graalhelper , and at least a few other people I remember hearing about. I've gotten native image working with the headless backend (see https://github.com/tommyettinger/noisegen/blob/main/graalvm-env/build_native.bat , which is nasty and uses machine-specific paths ), but not LWJGL3, which is a goal for me. The shared libraries are a problem for LWJGL3 and native images, and getting them to load correctly from inside a platform jar is tricky. If anyone has examples that work, particularly with the current libGDX stable release (1.11.0), that would be greatly appreciated.

Apparently, native images can be built for iOS, but I know nothing about iOS, so I'd find any explanation of how it works there useful.

#### Reproduction steps/code
Building a JAR into a native image is done after the JAR is built, but currently some Graal dependencies seem to be required in the native binary. I would absolutely love to be wrong about this, and I really hope there's a way to keep the large Graal dependency out of an .exe or the like. The configuration to get native images built is pretty arcane, and it would be helpful to have some good documentation here. At least when using anyicomplex' version of gdx-svmhelper, figuring out what versions of Graal and libGDX were compatible with that library was very challenging.

#### Version of libGDX and/or relevant dependencies
1.11.0 and onward.

#### Stacktrace
Not relevant.

#### Please select the affected platforms
- [ ] Android
- [ ? ] iOS
- [ ] HTML/GWT
- [ x ] Windows
- [ x ] Linux
- [ x ] macOS

**Comment by Berstanio** [comment]
> Apparently, native images can be built for iOS, but I know nothing about iOS, so I'd find any explanation of how it works there useful.

On iOS it does a normal native-image execution, with the main difference that it exits after a relocatable object file has been created. This object file than gets linked together with the main app. Besides that, it is just native-image.
On iOS we also don't need to worry about libraries, because they are currently statically linked and even if not, they would be extracted to frameworks in any case.

> but currently some Graal dependencies seem to be required in the native binary. I would absolutely love to be wrong about this, and I really hope there's a way to keep the large Graal dependency out of an .exe or the like.

They don't end up in the final executable. The dependencies are needed to be able to produce code, that will run at image build time, for custom configuration (e.g. here: https://github.com/Berstanio/gdx-graalhelper/blob/06d0a663981cb5eb72bf61617697dbcbcea9e3f0/src/main/java/com/anyicomplex/gdx/svm/ReflectionRegistrationFeature.java#L162-L166)
The classes won't end up in the final image. No jar would also contain the graal dependencies, since they are provided by native-image, so they are only compileOnly dependencies.

> At least when using anyicomplex' version of gdx-svmhelper, figuring out what versions of Graal and libGDX were compatible with that library was very challenging.

That is true, this is why I would be in favor to integrate it into libGDX, so that the native-image configuration gets distributed with the jars and get picked up automatically.

**Comment by tommyettinger** [comment]
The last part sounds really good, I just have no idea what might be needed. It looks like gdx-graalhelper would need to be updated to the most recent libGDX version or incorporated in some way into libGDX itself. There's also the critical need for LWJGL3 to work with Graal, since most (actually all) of the games I know of that want to resist decompilation are on desktop and have no options other than getting Graal native image to work, or using an old version of Excelsior JET (if they can somehow get one).

**Comment by Berstanio** [comment]
I picked up some work on native-imaga again, so here are a few notes:
> The shared libraries are a problem for LWJGL3 and native images, and getting them to load correctly from inside a platform jar is tricky

I don't know why I thought that, we can just extract the shared librarys from the native-image as we do with the jars.

I got a native image build so far, loading librarys *seems* to work. Problematic is atm https://github.com/LWJGL/lwjgl3/blob/4f9767cd5eb87c0e682ec5107b3601bc409d93a9/modules/lwjgl/core/src/main/java/org/lwjgl/system/ThreadLocalUtil.java#L157 , cause it leads to a segfault.

**Comment by tommyettinger** [comment]
Nice work! Does this need a library dependency, or does it just need Gradle config, or is it as simple as running the Graal tools with the right arguments?

**Comment by Berstanio** [comment]
At the moment it needs a modified lwjgl openGL native to run. https://github.com/LWJGL/lwjgl3/issues/875
The rest is only configuration which can be applied in different ways, either with a dependency or manually by the user.

**Comment by Berstanio** [comment]
With just a few lines of code, I was able to get rid of the need of a lwjgl3 fork: https://github.com/Berstanio/gdx-graalhelper/commit/4867e9e45eeb62103642246ce4e6532e5d287e43
Now it's only a dependency/configuration thing.

**Comment by tommyettinger** [comment]
Awesome! I'll try to take a look soon. It might be good to take a quick break from the TextraTypist library debugging I've been doing, and see what I can get running on Graal!

**Comment by Berstanio** [comment]
Okay, I haven't documented anything yet, so just the rough overview:
- You need lwjgl3-3.3.2
- You need to build the gdx-graalhelper branch from source, the "dev" branch
- You should use graalvm 22.3.1 Java 11
- As extra native-image parameters you need to pass "`--no-fallback --report-unsupported-elements-at-runtime`"
- Depending on your platform you also need to add "`-H:IncludeResources=".*dylib.*`" or "`-H:IncludeResources=".*so.*`"
- However I would recommend for testing purpose to just pass `-H:IncludeResources=".*.*` to just include everything
- If something doesn't work because of reflection, you can add the "@CollectForReflection" annotation to the class and everything inside will be registered for reflection (java 11 is required)
- If something libGDX internal fails for reflection, than it should probably be added to the gdx-graalhelper lib

If anything else, feel free to hit me up on discord.

**Comment by Berstanio** [comment]
Okay, a few updates:
I completly revamped the whole reflection registration.  Now it should be way more presice thus reducing resulting imaga size. It should be also way better at automatically registering reflection needs for Pooling and JSON serialization.
bullets JNI registration is still kinda garbage, but SWIG is also a complicated code generator. We will probably need some kind of script to effectivly dump out all needed JNI access. However, that is low prio.
The limitation for Java 11 was lifted, this was mainly done with the fact in mind, that next graal release won't ship java 11 anymore. However, now we rely on some internal API, which isn't great.
Related graal issue: https://github.com/oracle/graal/issues/4925
All native-image parameters should be now passed automatically. Only the "-H:IncludeResources=" should be left needed.
At some point I would like to have at least the native inclusion automatically, but we are blocked by https://github.com/oracle/graal/issues/4767
We are also waiting for https://github.com/oracle/graal/issues/6391 to be fixed. It is also under investigation, whether the struct is Thread local, the same way it is in the jvms. If it is not it wouldn't be a big deal atm., therefor this is rather low prio.

@CollectForReflection was renamed to @CollectForGDXJsonSerialization

At this point, I would prepare the library to be pr'ed for integration into the main libGDX repo. This is useful, since it enables user to build native-images easily without extra dependencys. This is also side effect free, since the configuration will only be read by graal.

Thats all from me for the moment I think!

**Comment by tommyettinger** [comment]
Just following up on this; I've been using Berstanio's Graal helper for a while now [in one repo](https://github.com/yellowstonegames/DetritusScion), and even though there are [a few small issues I encountered](https://github.com/Berstanio/gdx-graalhelper/issues/5), it's mostly been solid. The file sizes of zipped .exe files are so much smaller than the bundled JREs with games produced by jpackage... Using Graal 17 produces zipped .exe files under 20MB in size, as long as the assets aren't huge.

I think we can definitely start pushing for wider adoption soon. Maybe that should start with a wiki article?

**Comment by ThanosFisherman** [comment]
@tommyettinger I tried your [sample](https://github.com/yellowstonegames/DetritusScion) on my linux machine. I created a Jar file via the "jar" task and then I was able to create a native binary. However when I try to run that binary I get the following error

```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl.system.Library.loadSystem(Library.java:174)
	at org.lwjgl.system.Library.loadSystem(Library.java:64)
	at org.lwjgl.system.Library.<clinit>(Library.java:52)
	at com.github.yellowstonegames.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:20)
```
Any idea what I'm missing? Is there maybe more to do in order to compile for linux?

**Comment by Berstanio** [comment]
> @tommyettinger I tried your [sample](https://github.com/yellowstonegames/DetritusScion) on my linux machine. I created a Jar file via the "jar" task and then I was able to create a native binary. However when I try to run that binary I get the following error
> 
> ```
> [LWJGL] Failed to load a library. Possible solutions:
> 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
> 	b) Add the JAR that contains the shared library to the classpath.
> [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
> [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
> Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
> 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
> 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
> 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
> 	at com.github.yellowstonegames.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:20)
> ```
> 
> Any idea what I'm missing? Is there maybe more to do in order to compile for linux?

The repo doesn't include linux build steps, as it seems.

https://github.com/yellowstonegames/DetritusScion/blob/main/graal-native/build_native.bat

You need to adjust this for linux accordingly, in case you haven't done that.

**Comment by ThanosFisherman** [comment]
> You need to adjust this for linux accordingly, in case you haven't done that.

Thanks for pointing me to the right direction. I created a bash script and compiled the executable using the flags as in the .bat script. It runs fine now although I noticed different behaviors across different GraalVM versions but they all do compile and generate a perfectly runnable executable for linux :)

Another observation is that the executable file size is 50MB which is quite big as opposed to the fat jar which is around ~18MB

**Comment by Berstanio** [comment]
Great to hear that it works!

> Another observation is that the executable file size is 50MB which is quite big as opposed to the fat jar which is around ~18MB

That is very much expected. For a better comparison you would need to compare JRE + fat jar vs executable, since your executable contains also runtime classes.
Another example is, the size of your executable will vary very much based on the amount of reflection you use, since it needs to generate more code to support this. A jar is totally unaffected by that.

**Comment by tommyettinger** [comment]
The .bat files in DetritusScion are, as you found, just commands that run directly in cmd.exe or a shell. They don't use any Batch-specific features other than maybe using a backslash to continue a line. I often just copy the line it runs into my cmd.exe session, rather than editing the .bat when I want to make a small change. They would probably function as a Linux executable with a shebang, but I don't know if that would let them still work as a Batch file.

As for the size of the executable: try compressing it, I have gotten excellent results! JAR files are already compressed using DEFLATE (the same algorithm as a .zip), but Graal Native Image executables are not by default compressed. They also tend to have a lot of repetitive or duplicate data inside them, it seems, because zipping a Graal Native Image .exe tends to shrink it to about 1/3 the original size, while it will barely make any change to the size of a .zip or .jar file.

**Comment by ThanosFisherman** [comment]
> As for the size of the executable: try compressing it, I have gotten excellent results! 

I don't suppose you mean that I simply wrap the binary into a .zip file?
Otherwise I'm not sure how to do that. Does GraalVM support compression? I'll check it out tho thanks.

I've been trying to streamline this process with other 2D sample games as well but the steps are not always the same. Plus I had a hard time making it work when there's already an Android module in the way. I'll do some more digging and maybe come up with a tutorial at some point.

**Comment by tommyettinger** [comment]
> I don't suppose you mean that I simply wrap the binary into a .zip file?

Actually, that's exactly what I mean! The size of (the .exe) matters less than the size of (everything needed to run the game), so when measuring the bandwidth used by a server to distribute your game, you're probably measuring the size of zipped files (or some other form of compression) rather than uncompressed ones.

When you compare the sizes of a) a JAR without a JVM, b) that JAR without a JVM, zipped, c) that JAR packed into a native binary and zipped, Windows x64, and d) that JAR packed with jpackageimage and zipped:

![Comparison of File Sizes](https://github.com/libgdx/libgdx/assets/160684/aeef453c-5762-42f0-a604-8bbc6afe55e1)

The Graal Native Image zip is less than half the size of the jpackageimage zip, and less than 1MB larger than the JAR zipped (and the JAR wouldn't be runnable to any users without a JVM, plus no Java 8+ JVMs I know of fit in under 1MB).

The jpackageimage zip includes everything in `lwjgl3/build/distributions`, while the Graal Native zip includes the .exe and 5 small .dll files (I don't know if they're always required). The zipped JAR is just a .jar file inside a zip archive, which for most users isn't enough to run the game. I haven't compared with Packr yet.
