### ISSUE TITLE
GdxRuntimeException: Couldn't create window

### ISSUE THREAD

**Issue by isHarryh** [libgdx/libgdx#7139]
### Issue details

When one of my app's users tried to initialize the Lwjgl app, he got a `GdxRuntimeException: Couldn't create window`. However, when launched in other computers, it works very well.

It may be a rare problem of some particular computers. Could you tell me how to continue my investigation into this problem?

### Reproduction steps/code
It is not reproducable, since this exception has only occurred in my user's computer. Btw, my app project is [ArkPets](https://github.com/isHarryh/Ark-Pets).

### Version of libGDX
- libGDX 1.11.0

### Stacktrace
```java
// OS: Windows 10 (amd64), with Java 20.0.1

com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:462)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:448)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:162)
	at cn.harryh.arkpets.EmbeddedLauncher.main(EmbeddedLauncher.java:70)
```

Here the exception threw:  
https://github.com/libgdx/libgdx/blob/1.11.0/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/Lwjgl3Application.java#L527

#### Affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by crykn** [comment]
You could try to see whether GLFW has anything useful to say about the error, either via `GLFW#glfwGetError(...)` or by setting an error callback (`GLFW#glfwSetErrorCallback(...)`). The possible error codes can be found [here](https://www.glfw.org/docs/3.3/group__window.html#ga3555a418df92ad53f917597fe2f64aeb).

**Comment by isHarryh** [comment]
I let my user outputting the GLFW error, read:
```
(Code 65542) WGL: The driver does not appear to support OpenGL
```
My user's graphic card is `AMD Radeon(TM) Graphics` with the driver version `27.20.21030.8001`.

**Comment by crykn** [comment]
The driver seems to be over one and a half years old, so maybe updating does fix the issue. Anyways, this is a third-party issue, so there is nothing really we can do about it.

**Comment by Engilynx** [comment]
i was able to get it to happen from just opening Destination Sol, the error link i got is:
 com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:472)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:415)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:401)
at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:113)
at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:138)
