### ISSUE TITLE
LongMap can run into an endless loop

### ISSUE THREAD

**Issue by SomeTroglodyte** [libgdx/libgdx#7141]
#### Issue details
I've just stopped a nonresponsive, pegging-one-core-at-100% Gdx app running under the debugger. It is endlessly looping in [`LongMap.locateKey`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/LongMap.java#L130), called from `OpenALLwjgl3Audio.obtainSource` line 179. The keyTable has 64 entries, the key parameter is _not_ contained therein, no entry is 0, mask is 63 - it's obvious that there's no escape.

#### Reproduction steps/code
Difficult. I was rapidly buying stuff in Unciv via keyboard, each plays a coin sound, maybe 3 (identical) Sound.play calls per second.

#### Version of libGDX and/or relevant dependencies
1.11.0

#### Stacktrace
<details><summary>Forced via `(new Exception()).printStackTrace();`</summary>

```java
java.lang.Exception
	at com.badlogic.gdx.utils.LongMap.locateKey(LongMap.java:134)
	at com.badlogic.gdx.utils.LongMap.remove(LongMap.java:208)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.obtainSource(OpenALLwjgl3Audio.java:179)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALSound.play(OpenALSound.java:62)
	at com.unciv.ui.audio.SoundPlayer.play(SoundPlayer.kt:173)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable.purchaseConstruction(CityConstructionsTable.kt:629)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable.access$purchaseConstruction(CityConstructionsTable.kt:67)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable$askToBuyConstruction$2.invoke(CityConstructionsTable.kt:597)
	at com.unciv.ui.screens.cityscreen.CityConstructionsTable$askToBuyConstruction$2.invoke(CityConstructionsTable.kt:597)
	at com.unciv.ui.popups.Popup$addOKButton$cell$1.invoke(Popup.kt:234)
	at com.unciv.ui.popups.Popup$addOKButton$cell$1.invoke(Popup.kt:231)
	at com.unciv.ui.popups.Popup$addButton$1.invoke(Popup.kt:182)
	at com.unciv.ui.popups.Popup$addButton$1.invoke(Popup.kt:182)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:194)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$onActivation$1.invoke(Scene2dExtensions.kt:192)
	at com.unciv.ui.components.extensions.ActorAttachments.activate(Scene2dExtensions.kt:140)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt.activate(Scene2dExtensions.kt:183)
	at com.unciv.ui.components.extensions.ActorKeyShortcutDispatcher$add$3.invoke(Scene2dExtensions.kt:107)
	at com.unciv.ui.components.extensions.ActorKeyShortcutDispatcher$add$3.invoke(Scene2dExtensions.kt:107)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$installShortcutDispatcher$1.activate(Scene2dExtensions.kt:265)
	at com.unciv.ui.components.extensions.Scene2dExtensionsKt$installShortcutDispatcher$1.keyDown(Scene2dExtensions.kt:231)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:53)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:418)
	at com.unciv.ui.screens.basescreen.UncivStage.access$keyDown$s80204510(UncivStage.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage$keyDown$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.screens.basescreen.UncivStage$keyDown$1.invoke(UncivStage.kt:87)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.screens.basescreen.UncivStage.keyDown(UncivStage.kt:87)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:58)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:378)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:80)
```
</details>

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [x] Linux
- [ ] macOS

#### Comment
I don't expect this is enough to derive an idea for a fix, but I thought I'd let you know anyway. That LongMap seems out of some kind of sync (the size field is 48, though I have no idea whether that is supposed to match the keyTable's size or not), and the sourceToSoundId/soundIdToSource maps of OpenALLwjgl3Audio are pretty obviously out of sync. Chances are our concurrency approach is simply calling Sound.play on the wrong thread, though the interface's JavaDoc says nothing about thread safety requirements.

**Comment by mgsx-dev** [comment]
as per wiki : https://libgdx.com/wiki/app/threading#which-libgdx-classes-are-thread-safe

> No class in libGDX is thread-safe unless explicitly marked as thread-safe in the class documentation!

**Comment by mgsx-dev** [comment]
The fact that it freeze in GLThread doesn't mean it's not thread related (sorry for the double negative). If another thread interact with the map, then it could crash or freeze in any other thread.

> Chances are our concurrency approach is simply calling Sound.play on the wrong thread

Considering the symptoms, it sounds like it.

Feel free to reopen if you have more information. There is nothing we can do until then. Hope you understand.

**Comment by tommyettinger** [comment]
It's always more likely when threading is in use that it's the culprit, but... It is very strange that this could happen at all, even with concurrent access. `OpenALLwjgl3Audio` only calls `get()`, `put()`, and `remove()` from `LongMap`. `remove()` makes certain that if it removes a key from the `keyTable`, then it assigns `0` to its position in the table, marking it as empty. In your case, it sounds like the `keyTable` had 64 entries, all of which were non-zero, but the `size` was only 48. With the load factor used in `OpenALLwjgl3Audio`, 48 is just below the maximum `LongMap` can hold before resizing to the next PoT size (128); it might be the actual maximum. The load factor should (almost) always be less than 1.0f, and the default load factor of 0.8f ensures there is always some empty space if things are functioning correctly. What I'm thinking is that some kind of concurrent access to the audio set the size to a correctly-increased size, kept running, another thread set the size to an incorrectly-reduced size, and the `LongMap` went happily along thinking its `size` was actually 48 even though it was completely full of items. That could have prevented `resize()` from getting called when the 64th non-zero key was added, and since `LongMap` never has that happen in a single-threaded scenario unless there's some reflective access happening, `locateKey()` enters a scenario that it is not meant to ever face. I'm fairly sure that because `OpenALLwjgl3Audio` only calls the absolute most-commonly-called methods, it isn't hitting some rare buggy case that has never happened before now. This definitely seems like sounds being played on other threads are the root of the problem; they could be played at any point in the program's execution, as long as multiple sounds played in close enough succession.

**Comment by tommyettinger** [comment]
I'm not sure if this is the right code, but this section seems like it's asking for trouble...  https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/audio/SoundPlayer.kt#L162-L163

There's also the maybe-maybe-possible chance that this could be related to some `Throwable` being caught after some variable had changed, but before a method like `remove()` or `put()` could complete. This doesn't seem too likely to me; `Exception`s are mostly thrown at the start of methods in `LongMap` after detecting invalid conditions.
