### ISSUE TITLE
Can't run ParticleEditor in libgdx project tools extension

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#7183]
#### Issue details
I want to run ParticleEditor in my libgdx project, so I add gdx-tools dependency in desktop gradle file. When I located the ParticleEditor.java file then right-click and select “Run ParticleEditor.main()”, it opens java application but then crashed with this log.

#### Reproduction steps/code
1. Add gdx-tools dependency in project(desktop) gradle section.
2. Sync gradle file and located ParticleEditor in External Libraries.
3. right-click and select "Run ParticleEditor.main()", click continue run when prompt.

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.12.0'
api "com.badlogicgames.gdx:gdx-tools:$gdxVersion"

#### Stacktrace
```java
[LwjglApplication] Couldn't initialize audio, disabling audio
java.lang.NoSuchMethodError: org.lwjgl.openal.AL.create()V
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALLwjglAudio.<init>(OpenALLwjglAudio.java:72)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createAudio(LwjglApplication.java:282)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:90)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:75)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.createCanvas(ParticleEditor.java:133)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.initializeComponents(ParticleEditor.java:236)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.<init>(ParticleEditor.java:95)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor$6.run(ParticleEditor.java:677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl.DefaultLwjglInput.<init>(DefaultLwjglInput.java:63)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.createInput(LwjglApplication.java:288)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:97)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.<init>(LwjglApplication.java:75)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.createCanvas(ParticleEditor.java:133)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.initializeComponents(ParticleEditor.java:236)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor.<init>(ParticleEditor.java:95)
	at com.badlogic.gdx.tools.particleeditor.ParticleEditor$6.run(ParticleEditor.java:677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.SecurityException: sealing violation: package org.lwjgl is sealed
	at java.net.URLClassLoader.getAndVerifyPackage(URLClassLoader.java:399)
	at java.net.URLClassLoader.definePackageInternal(URLClassLoader.java:419)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.lwjgl.input.Keyboard.<clinit>(Keyboard.java:265)
	... 22 more
```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
This error, `java.lang.SecurityException: sealing violation: package org.lwjgl is sealed`, comes from the LWJGL3 library trying to use the `org.lwjgl` package when LWJGL2 has already used it, or vice versa. This message only happens on relatively recent JVM versions, but there's likely other errors that would happen whenever LWJGL3 and LWJGL2 are both in use, and the particle editor needs LWJGL2. Currently, gdx-setup only makes LWJGL3 modules, when you select the Desktop platform. On the other hand, [gdx-liftoff](https://github.com/tommyettinger/gdx-liftoff) allows creating both an LWJGL3 and an LWJGL2 module in the same project, and if the gdx-tools dependency is only present in the LWJGL2 module, the rest of the game will be fine. If you only need the particle editor separately from your main game code, my suggestion is to create just a separate LWJGL2 project with gdx-liftoff (it's called "Desktop (Legacy)"), probably checking the gdx-tools box on the Extensions tab, and to run that like how you've already tried. Since LWJGL3 won't be around to overlap with the necessary LWJGL2, it should run just fine then. You're on a Mac, it looks like, which could cause other issues with gdx-tools, but I'm not as familiar with the Mac-specific issues.

**Comment by Frosty-J** [comment]
Additionally, some other tools such as Hiero may have the same issue. I use the standalone versions of these tools - for the particle editor, that would be https://libgdx-nightlies.s3.amazonaws.com/libgdx-runnables/runnable-2D-particles.jar

**Comment by wangdong20** [comment]
> Additionally, some other tools such as Hiero may have the same issue. I use the standalone versions of these tools - for the particle editor, that would be https://libgdx-nightlies.s3.amazonaws.com/libgdx-runnables/runnable-2D-particles.jar
> 
> Note that they all can have issues on ARM (including Apple Silicon) processors and JRE versions newer than 8. Hiero I've heard issues with working correctly on macOS at all (no fonts). Your mileage may vary.

The runnable-2D-particles.jar you provided can't open pfx file and editor properties and emitter properties are empty in UI. I can't see the default emitter neither.

**Comment by crykn** [comment]
This should be fixed by using the new standalone version over at https://github.com/libgdx/gdx-particle-editor (#7285).
