### ISSUE TITLE
ld: framework not found gdx-freetype

### ISSUE THREAD

**Issue by wangdong20** [libgdx/libgdx#7201]
#### Issue details
I just update gdxVersion to '1.12.0', when I try to build iOS via robovm it failed.

#### Reproduction steps/code
1. set gdxVersion to 1.12.0
2. build iOS via robovm

#### Version of libGDX and/or relevant dependencies
gdxVersion = '1.12.0'
roboVMVersion = '2.3.18'

#### Stacktrace
```java
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, -o, /Users/David/AndroidStudioProjects/Battleship/ios/robovm-build/tmp/iOS/ios/arm64/IOSLauncher, -Wl,-filelist,/Users/David/AndroidStudioProjects/Battleship/ios/robovm-build/tmp/iOS/ios/arm64/objects0, -L, /Users/David/.robovm-sdks/robovm-2.3.18/lib/vm/ios/arm64, -ObjC, -exported_symbols_list, /Users/David/AndroidStudioProjects/Battleship/ios/robovm-build/tmp/iOS/ios/arm64/exported_symbols, -Wl,-no_implicit_dylibs, -Wl,-dead_strip, -F/Users/David/.robovm/cache/ios/arm64/release/Users/David/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-freetype-platform/1.12.0/7dc40f1944fb12594f4bf07d60d857ef031a168c/gdx-freetype-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/David/.robovm/cache/ios/arm64/release/Users/David/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-box2d-platform/1.12.0/556f60eb6e9bd082cb0f84c60c2c6b2fcf877d79/gdx-box2d-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/David/.robovm/cache/ios/arm64/release/Users/David/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.0/e7eb1777f7c465f6ef8cb1dad7dfc405184f17aa/gdx-platform-1.12.0-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/David/AndroidStudioProjects/Battleship/ios/arm_libs, -L/usr/lib/swift, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphoneos, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos, -fPIC, --target=arm64-apple-ios12.0, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk, -lrobovm-bc, -force_load, /Users/David/.robovm-sdks/robovm-2.3.18/lib/vm/ios/arm64/librobovm-rt.a, -lrobovm-debug, -lrobovm-core, -lgc, -lpthread, -ldl, -lm, -lz, -liconv, -lsqlite3, -framework, Foundation, -framework, FirebaseCore, -framework, FirebaseCoreInternal, -framework, GoogleUtilities, -framework, FBLPromises, -framework, OpenGLES, -framework, FirebaseDatabase, -framework, leveldb-library, -framework, FirebaseAppCheck, -framework, GoogleMobileAds, -framework, GoogleAppMeasurement, -framework, nanopb, -framework, JavaScriptCore, -framework, gdx-freetype, -framework, FirebaseAuth, -framework, GTMSessionFetcher, -framework, gdx-box2d, -framework, UserMessagingPlatform, -framework, gdx, -framework, ObjectAL, -framework, UIKit, -framework, QuartzCore, -framework, CoreGraphics, -framework, OpenAL, -framework, AudioToolbox, -framework, AVFoundation, -framework, GameController, -framework, UnityAdapter, -framework, UnityAds, -framework, AppLovinAdapter, -framework, AppLovinSDK, -framework, MetaAdapter, -framework, FBAudienceNetwork, -lz, -framework, MobileCoreServices, -Xlinker, -rpath, -Xlinker, /usr/lib/swift, -Xlinker, -rpath, -Xlinker, @executable_path/Frameworks, -Xlinker, -rpath, -Xlinker, @loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:404)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:271)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:333)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:264)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:518)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:955)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:277)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)
```

#### Please select the affected platforms
- [ ] Android
- [x] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by wangdong20** [comment]
> Can you try upgrading your robovm version to the latest one?

Do you mean 1.12.1-SNAPSHOT?

**Comment by Berstanio** [comment]
No, the robovm version. You mentioned that you use `roboVMVersion = '2.3.18'`, but the latest is 2.3.19 I think
