### ISSUE TITLE
Arm64-v8a native binary throws ExceptionInInitializerError

### ISSUE THREAD

**Issue by CallofVoid** [libgdx/libgdx#7204]
#### Issue details
 using arm64-v8a libgdx.so file in libs causes crash in blank android project 

#### Reproduction steps/code
including libs/arm64-v8a/libgdx.so  
native platform downloaded from maven repository causes crash even in blank project
removing arm64-v8a doesn't cause crash

tried on Samsung Galaxy A30s with arm64 

#### Version of libGDX and/or relevant dependencies
libgdx 1.9.0

#### Stacktrace
```java
08-05 21:52:15.221 9157 9157 D     AndroidRuntime                               Shutting down VM
08-05 21:52:15.227 9157 9157 E     AndroidRuntime                               FATAL EXCEPTION: main
08-05 21:52:15.227 9157 9157 E     AndroidRuntime                               Process: com.purplevoidgames.operationfoxtrap, PID: 9157
08-05 21:52:15.227 9157 9157 E     AndroidRuntime                               java.lang.ExceptionInInitializerError
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at java.lang.Class.newInstance(Native Method)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.Instrumentation.newActivity(Instrumentation.java:1219)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3053)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.os.Handler.dispatchMessage(Handler.java:106)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.os.Looper.loop(Looper.java:216)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at android.app.ActivityThread.main(ActivityThread.java:7285)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at java.lang.reflect.Method.invoke(Native Method)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:118)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:62)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               ... 15 more
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.purplevoidgames.operationfoxtrap-mQBj7V0zYLR3IwhdpGwxLw==/lib/arm64/libgdx.so" has bad ELF magic
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at java.lang.System.loadLibrary(System.java:1669)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:113)
08-05 21:15:06.296 32183 32183 E   AndroidRuntime                               ... 17 more
```

#### Please select the affected platforms
- [ ●] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
Version 1.9.0 was released on Jan 24, 2016 . Android moves fast, and using 7-year-old releases is not a good way to ensure you can target current Android devices. I'd try to update, though there have been 17 releases since then, so definitely check [the changelog](https://github.com/libgdx/libgdx/blob/master/CHANGES).

**Comment by Frosty-J** [comment]
Yeah, try 1.12.1-SNAPSHOT if you can (or 1.11.0, or 1.12.0 with androidx workaround). I don't have an ARMv8 device to test on but most people will have v8 now, as all new devices (even the cheap ones) have been v8 for some years now.

**Comment by CallofVoid** [comment]
1.11.0 doesn't work for me due to change in the native library initialization 
even if I use `GDXNativesLoader.load()` at the start of AndroidLauncher onCreate method, app crashes at the startup

**Comment by CallofVoid** [comment]
btw what is that androidx workaround you're talking about?

**Comment by CallofVoid** [comment]
checked changelogs and seems like 1.9.1 has a fix for arm64 binaries, will check

**Comment by Frosty-J** [comment]
> btw what is that androidx workaround you're talking about?

1.12.0 requires `android.useAndroidX=true` in `gradle.properties`. Other versions, including 1.12.1-SNAPSHOT, don't.

**Comment by CallofVoid** [comment]
yep 1.10 worked very well

**Comment by CallofVoid** [comment]
I guess this issue should be closed
