### ISSUE TITLE
DecalBatch rare crash when sorting tons of close decals

### ISSUE THREAD

**Issue by tylerhasman** [libgdx/libgdx#7214]
Please ensure you have given all the following requested information in your report.

#### Issue details
The current implementation of the Comparator<Decal> in the CameraGroupStrategy class causes a crash when floating-point errors happen.

The issue is in the following code snippet:

```java
this.cameraSorter = new Comparator<Decal>() {
    @Override
    public int compare (Decal o1, Decal o2) {
        float dist1 = CameraGroupStrategy.this.camera.position.dst(o1.position);
        float dist2 = CameraGroupStrategy.this.camera.position.dst(o2.position);
        return (int)Math.signum(dist2 - dist1);
    }
};
```

The casting to an integer after calling Math.signum on the difference can lead to inconsistencies in the comparison.

A solution to this is to simply use ```Float.compare``` instead like so:

```java
this.cameraSorter = new Comparator<Decal>() {
    @Override
    public int compare(Decal o1, Decal o2) {
        float dist1 = CameraGroupStrategy.this.camera.position.dst(o1.position);
        float dist2 = CameraGroupStrategy.this.camera.position.dst(o2.position);

        return Float.compare(dist2, dist1);
    }
};

```

Changing this prevents the crash from occuring.

#### Reproduction steps/code
Spawn tons of particles very close together such that a floating-point error is likely to occur.

#### Version of libGDX and/or relevant dependencies
1.12.0

#### Stacktrace
```java
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at com.badlogic.gdx.utils.TimSort.mergeHi(TimSort.java:791)
	at com.badlogic.gdx.utils.TimSort.mergeAt(TimSort.java:449)
	at com.badlogic.gdx.utils.TimSort.mergeForceCollapse(TimSort.java:396)
	at com.badlogic.gdx.utils.TimSort.doSort(TimSort.java:138)
	at com.badlogic.gdx.utils.Sort.sort(Sort.java:59)
	at com.badlogic.gdx.utils.Array.sort(Array.java:433)
	at com.badlogic.gdx.graphics.g3d.decals.CameraGroupStrategy.beforeGroup(CameraGroupStrategy.java:137)
	at com.badlogic.gdx.graphics.g3d.decals.DecalBatch.render(DecalBatch.java:143)
	at com.badlogic.gdx.graphics.g3d.decals.DecalBatch.flush(DecalBatch.java:135)
	at rpg.client.graphics.ParticleSystem.renderDecals(ParticleSystem.java:96)
	at rpg.client.RpgClient.render(RpgClient.java:892)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at rpg.client.desktop.DesktopLauncher.main(DesktopLauncher.java:59)
```

#### Please select the affected platforms
- [X] Android
- [X] iOS
- [X] HTML/GWT
- [X] Windows
- [X] Linux
- [x] macOS

**Comment by tommyettinger** [comment]
The only thing Float.compare() does differently, as far as I can tell, is handle the case when one or both of its inputs are NaN. What could be the issue here has to do with comparison with NaN in general, which is... a mess. With the signum appoach, if either distance is NaN, then the difference between the distances is NaN, signum(NaN) is also NaN, and (int)NaN is 0, signifying everything is considered equivalent to a NaN distance. That would break the contract for sure. If you have NaN positions, switching to Float.compare() will fix their positions in a sort, arguably, but will not fix the other issues inherent in having NaN in with your other values.

I think you should try to catch the IllegalArgumentException and get a complete log of all Camera and Decal positions when this happens. Ideally, you'd also have the data of which Decals were being compared when the crash happens. If nothing anywhere is NaN, then the issue could be in how dst() is calculated -- it returns NaN if the squared distance is somehow less than 0, though I don't know how that could happen given that the squared distance should always be >= 0 .

**Comment by tylerhasman** [comment]
I'll debug it and take a look at what exactly is going on.

**Comment by tylerhasman** [comment]
This is definitely caused by a problem in my code. Decal's were having their position set to NaN. I'm going to close this issue but it may be a good idea to support decals having a NaN position. Rendering something with an inifinite or NaN position doesn't usually crash things, they just don't appear. It may be a good idea for DecalBatch to also be consistent with this. Cheers!
