### ISSUE TITLE
RoboVM launchIphoneSimulator compile error

### ISSUE THREAD

**Issue by recaifurkan** [libgdx/libgdx#7269]
#### Issue details
I can't run launchIphoneSimulator my libgdx project

#### Version of libGDX and/or relevant dependencies
1.12.1 and 1.20.0 robovm version 2.3.20 and 2.3.19 both of them tested

#### Stacktrace
[INFO] 03:48:20.154 Using SDK boot classpath
[INFO] 03:48:20.671 Cleaning output dir /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator
[INFO] 03:48:20.910 Compiling classes using 4 threads
[INFO] 03:48:35.101 Compiled 0 classes in 14.19 seconds
[INFO] 03:48:35.105 Linking 6459 classes (ios x86_64-simulator release)
[INFO] 03:48:35.314 88011 methods out of 88695 included in the executable
[INFO] 03:48:37.940 Building ios binary /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/IOSLauncher
[INFO] 03:48:37.959 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/IOSLauncher -Wl,-filelist,/Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/objects0 -L /Users/recaifurkan/.robovm-sdks/robovm-2.3.20/lib/vm/ios/x86_64-simulator -ObjC -exported_symbols_list /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-bullet-platform/1.12.1/53e65ff6cc6948023053255b637d8807c9581e9f/gdx-bullet-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-bullet-platform/1.12.1/53e65ff6cc6948023053255b637d8807c9581e9f/gdx-bullet-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx-bullet.xcframework/ios-arm64_x86_64-simulator 
[INFO] 03:48:37.959     -L/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator -fPIC --target=x86_64-apple-ios11.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/Entitlements-Simulated.plist -lrobovm-bc -force_load /Users/recaifurkan/.robovm-sdks/robovm-2.3.20/lib/vm/ios/x86_64-simulator/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework gdx -framework ObjectAL -framework AVFoundation -framework gdx-bullet -framework OpenGLES -framework UIKit -framework QuartzCore -framework CoreGraphics -framework OpenAL -framework AudioToolbox -framework AVFoundation -framework GameController -lz -framework MobileCoreServices -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
[WARNING] 03:48:38.021 ld: warning: ignoring duplicate libraries: '-lz'
[ERROR] 03:48:40.622 0  0x10ce43f43  __assert_rtn + 64
[ERROR] 03:48:40.622 1  0x10cdebd4b  void dispatchForEach<mach_o::CompactUnwind::Diff24Fixup const, ld::LayoutExecutable::writeCompactUnwind(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long, ld::SectionLayout const&) const::$_26>(std::__1::span<mach_o::CompactUnwind::Diff24Fixup const, 18446744073709551615ul>, unsigned long, ld::LayoutExecutable::writeCompactUnwind(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long, ld::SectionLayout const&) const::$_26)::'lambda'(unsigned long)::operator()(unsigned long) const + 347
[ERROR] 03:48:40.622 2  0x7ff810269066  _dispatch_client_callout2 + 8
[ERROR] 03:48:40.622 3  0x7ff81027c18f  _dispatch_apply_invoke_and_wait + 213
[ERROR] 03:48:40.622 4  0x7ff81027b692  _dispatch_apply_with_attr_f + 1207
[ERROR] 03:48:40.622 5  0x7ff81027b847  dispatch_apply + 45
[ERROR] 03:48:40.622 6  0x10cdec116  ld::LayoutExecutable::writeContentWithoutLinkEdit(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long) + 950
[ERROR] 03:48:40.622 7  0x10cdf39fa  ld::LayoutExecutable::writeToFile(char const*) + 21546
[ERROR] 03:48:40.622 8  0x10cd92f9f  main + 12831
[ERROR] 03:48:40.622 ld: Assertion failed: (false && "compact unwind compressed function offset doesn't fit in 24 bits"), function operator(), file Layout.cpp, line 5758.
[ERROR] 03:48:40.736 clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app
org.apache.commons.exec.ExecuteException: Command '[/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, -o, /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/IOSLauncher, -Wl,-filelist,/Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/objects0, -L, /Users/recaifurkan/.robovm-sdks/robovm-2.3.20/lib/vm/ios/x86_64-simulator, -ObjC, -exported_symbols_list, /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/exported_symbols, -Wl,-no_implicit_dylibs, -Wl,-dead_strip, -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx.xcframework/ios-arm64_x86_64-simulator, -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.12.1/d2eeda8914d8a29b53f37f3c5e2256d67037fe77/gdx-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/ObjectAL.xcframework/ios-arm64_x86_64-simulator, -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-bullet-platform/1.12.1/53e65ff6cc6948023053255b637d8807c9581e9f/gdx-bullet-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs, -F/Users/recaifurkan/.robovm/cache/ios/x86_64-simulator/release/Users/recaifurkan/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-bullet-platform/1.12.1/53e65ff6cc6948023053255b637d8807c9581e9f/gdx-bullet-platform-1.12.1-natives-ios.jar.extracted/META-INF/robovm/ios/libs/gdx-bullet.xcframework/ios-arm64_x86_64-simulator, -L/usr/lib/swift, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/iphonesimulator, -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphonesimulator, -fPIC, --target=x86_64-apple-ios11.0-simulator, -isysroot, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk, -Xlinker, -sectcreate, -Xlinker, __TEXT, -Xlinker, __entitlements, -Xlinker, /Users/recaifurkan/Desktop/basketball_libgdx_port/ios/robovm-build/tmp/ios-simulator/ios/x86_64-simulator/Entitlements-Simulated.plist, -lrobovm-bc, -force_load, /Users/recaifurkan/.robovm-sdks/robovm-2.3.20/lib/vm/ios/x86_64-simulator/librobovm-rt.a, -lrobovm-debug, -lrobovm-core, -lgc, -lpthread, -ldl, -lm, -lz, -liconv, -lsqlite3, -framework, Foundation, -framework, gdx, -framework, ObjectAL, -framework, AVFoundation, -framework, gdx-bullet, -framework, OpenGLES, -framework, UIKit, -framework, QuartzCore, -framework, CoreGraphics, -framework, OpenAL, -framework, AudioToolbox, -framework, AVFoundation, -framework, GameController, -lz, -framework, MobileCoreServices, -Xlinker, -rpath, -Xlinker, /usr/lib/swift, -Xlinker, -rpath, -Xlinker, @executable_path/Frameworks, -Xlinker, -rpath, -Xlinker, @loader_path/Frameworks]' failed  (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:472)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:275)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:333)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:268)
	at org.robovm.compiler.Linker.link(Linker.java:449)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:520)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:957)
	at org.robovm.idea.compilation.RoboVmCompileTask$3.doCompile(RoboVmCompileTask.java:277)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:69)

- [ *] iOS

**Comment by recaifurkan** [comment]
The problem was related to xcode15. When I downgraded xcode to 14.3.1, the problem was solved.
