### ISSUE TITLE
 Could not find lwjgl-glfw-3.3.3-natives-linux.jar in windows 10 

### ISSUE THREAD

**Issue by whiletrue111** [libgdx/libgdx#7292]
P 
#### Issue details
 generate project and importing to android studio 

#### Version of libGDX and/or relevant dependencies
 letest libGDX 
libGDX project generator 1.12.1

#### Stacktrace
```java
The client will now receive all logging from the daemon (pid: 34484). The daemon log file: C:\Users\xxx\.gradle\daemon\7.5.1\daemon-34484.out.log
Starting 3rd build in daemon [uptime: 4 mins 18.199 secs, performance: 100%]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 8 worker leases.
Now considering [C:\dev\my\java\libgdx\test2] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file 'C:\dev\my\java\libgdx\test2\settings.gradle'.
Projects loaded. Root project using build file 'C:\dev\my\java\libgdx\test2\build.gradle'.
Included projects: [root project 'test2', project ':android', project ':core', project ':desktop']

> Configure project :
Evaluating root project 'test2' using build file 'C:\dev\my\java\libgdx\test2\build.gradle'.

> Configure project :android
Evaluating project ':android' using build file 'C:\dev\my\java\libgdx\test2\android\build.gradle'.
Parsed shrinker version: 3.3.83

> Configure project :core
Evaluating project ':core' using build file 'C:\dev\my\java\libgdx\test2\core\build.gradle'.

> Configure project :desktop
Evaluating project ':desktop' using build file 'C:\dev\my\java\libgdx\test2\desktop\build.gradle'.
All projects evaluated.
Task name matched 'prepareKotlinBuildScriptModel'
Selected primary task 'prepareKotlinBuildScriptModel' from project :
Tasks to be executed: [task ':prepareKotlinBuildScriptModel']
Tasks that were excluded: []
Resolve mutations for :prepareKotlinBuildScriptModel (Thread[Execution worker,5,main]) started.
:prepareKotlinBuildScriptModel (Thread[included builds,5,main]) started.
Resolve mutations for :prepareKotlinBuildScriptModel (Thread[Execution worker,5,main]) completed. Took 0.0 secs.

> Task :prepareKotlinBuildScriptModel UP-TO-DATE
Skipping task ':prepareKotlinBuildScriptModel' as it has no actions.
:prepareKotlinBuildScriptModel (Thread[included builds,5,main]) completed. Took 0.004 secs.
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://oss.sonatype.org/content/repositories/snapshots/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://jitpack.io/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Resource missing. [HTTP GET: https://oss.sonatype.org/content/repositories/snapshots/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Resource missing. [HTTP GET: https://jitpack.io/com/github/MrStahlfelge/gdx-websockets/common/1.1.0/common-1.1.0.pom]
Could not resolve: com.github.MrStahlfelge.gdx-websockets:core:1.1.0
Could not resolve: com.github.MrStahlfelge.gdx-websockets:common:1.1.0
Transforming android.jar with MockableJarTransform
Transforming FakeDependency.jar with D8BackportedMethodsGenerator
Transforming android.jar with MockableJarTransform
Transforming FakeDependency.jar with D8BackportedMethodsGenerator
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with AarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with AarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with AarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with IdentityTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with ExtractAarTransform
Transforming gdx-backend-android-1.12.1.aar (com.badlogicgames.gdx:gdx-backend-android:1.12.1) with AarTransform

FAILURE: Build failed with an exception.

* What went wrong:
Could not find lwjgl-glfw-3.3.3-natives-linux.jar (org.lwjgl:lwjgl-glfw:3.3.3).
Searched in the following locations:
    file:/C:/Users/xxx/.m2/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux.jar

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Could not find lwjgl-glfw-3.3.3-natives-linux.jar (org.lwjgl:lwjgl-glfw:3.3.3).
Searched in the following locations:
    file:/C:/Users/xxx/.m2/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux.jar
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:412)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:138)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:64)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.runAction(AbstractClientProvidedBuildActionRunner.java:131)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:104)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner$ActionAdapter.fromBuildModel(AbstractClientProvidedBuildActionRunner.java:84)
	at org.gradle.internal.buildtree.DefaultBuildTreeModelCreator.fromBuildModel(DefaultBuildTreeModelCreator.java:57)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$fromBuildModel$1(DefaultBuildTreeLifecycleController.java:82)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$runBuild$4(DefaultBuildTreeLifecycleController.java:106)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$5(StateTransitionController.java:166)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:247)
	at org.gradle.internal.model.StateTransitionController.lambda$transition$6(StateTransitionController.java:166)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.transition(StateTransitionController.java:166)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.runBuild(DefaultBuildTreeLifecycleController.java:103)
	at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.fromBuildModel(DefaultBuildTreeLifecycleController.java:74)
	at org.gradle.tooling.internal.provider.runner.AbstractClientProvidedBuildActionRunner.runClientAction(AbstractClientProvidedBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:53)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:49)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:65)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:136)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:122)
	at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
	at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
	at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:65)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.lambda$execute$0(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.launcher.exec.RunAsWorkerThreadBuildActionExecutor.execute(RunAsWorkerThreadBuildActionExecutor.java:36)
	at org.gradle.tooling.internal.provider.continuous.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:110)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
	at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:100)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter$ActionImpl.apply(BuildSessionLifecycleBuildActionExecuter.java:88)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:40)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find lwjgl-glfw-3.3.3-natives-linux.jar (org.lwjgl:lwjgl-glfw:3.3.3).
Searched in the following locations:
    file:/C:/Users/xxx/.m2/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-linux.jar
	at org.gradle.internal.resolve.result.DefaultBuildableArtifactResolveResult.notFound(DefaultBuildableArtifactResolveResult.java:28)
	at org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver$RemoteRepositoryAccess.resolveArtifact(ExternalResourceResolver.java:510)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess.resolveArtifact(CachingModuleComponentRepository.java:439)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.LocalModuleComponentRepository$LocalAccess.resolveArtifact(LocalModuleComponentRepository.java:91)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.lambda$resolveArtifact$12(ErrorHandlingModuleComponentRepository.java:171)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.tryResolveAndMaybeBlacklist(ErrorHandlingModuleComponentRepository.java:227)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.performOperationWithRetries(ErrorHandlingModuleComponentRepository.java:193)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess.resolveArtifact(ErrorHandlingModuleComponentRepository.java:169)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainArtifactResolver.resolveArtifact(RepositoryChainArtifactResolver.java:78)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ArtifactResolverChain.resolveArtifact(ComponentResolversChain.java:129)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ErrorHandlingArtifactResolver.resolveArtifact(ErrorHandlingArtifactResolver.java:46)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:290)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.DefaultArtifactSet$LazyArtifactSupplier.calculateValue(DefaultArtifactSet.java:261)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.lambda$attachValue$0(CalculatedValueContainer.java:218)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.internal.model.CalculatedValueContainer$CalculationState.attachValue(CalculatedValueContainer.java:213)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:186)
	at org.gradle.internal.model.CalculatedValueContainer.finalizeIfNotAlready(CalculatedValueContainer.java:177)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ArtifactBackedResolvedVariant$DownloadArtifactFile.run(ArtifactBackedResolvedVariant.java:192)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:238)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:266)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:247)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:237)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
	at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:221)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:237)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:223)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:191)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)



* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Watched directory hierarchies: []

```

#### Please select the affected platforms
- [ ] Android
- [ ] iOS
- [ ] HTML/GWT
- [ X] Windows
- [ ] Linux
- [ ] macOS

**Comment by crykn** [comment]
This isn't really an issue with libGDX, but a problem with Gradle, so our Discord would have been a better place to ask this. It is most likely caused by your `mavenLocal()` repository containing broken artifacts. Removing it should fix this.

Also see #6878.

**Comment by Bobybyk** [comment]
There appears to be a problem in the way lwjgl-ovr dependencies are indexed for Linux with Gradle.

I fixed it by adding a condition

```kts
if (lwjglNatives == "natives-linux") runtimeOnly("org.lwjgl", "lwjgl-ovr", classifier = "sources") else runtimeOnly("org.lwjgl", "lwjgl-ovr", classifier = lwjglNatives)
```

This is probably not a very good solution to solve this problem, but it works for me...

**Comment by tommyettinger** [comment]
@Bobybyk This issue doesn't have anything to do with OVR, and not only that, but your solution seems to only work by avoiding downloading requisite binaries for Linux... If you're fine ignoring Linux as a target, that is not a problem for about 98% of players of commercial games, so it isn't much of a revenue loss, I guess. I'd suggest posting your issue in [the LWJGL3 repo](https://github.com/LWJGL/lwjgl3) if there isn't one already.

**Comment by Bobybyk** [comment]
Oups, sorry, i didn't answer to the right topic (too many tabs open...). Btw, i don't ignore linux as a target, it's only that for lwjgl-ovr there are no files *-natives-linux.jar as in other packages, it is *-sources.jar here.
