### ISSUE TITLE
Unable to launch gdx Liftoff on macOs

### ISSUE THREAD

**Issue by duy1502** [libgdx/libgdx#7431]
Please ensure you have given all the following requested information in your report.

#### Issue details
[LWJGL] GLFW_FORMAT_UNAVAILABLE error
	Description : NSGL: Failed to find a suitable pixel format
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
		gdx.liftoff.Main.main(Main.java:198)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:530)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
	at gdx.liftoff.Main.main(Main.java:198)

i have installed jdk 21 on macOs device

**Comment by tommyettinger** [comment]
I'm guessing you're running in a VM (or a Hackintosh setup), and not actually running on Apple hardware, since some quick googling finds only results containing `NSGL: Failed to find a suitable pixel format` when someone is using a VM. I would suggest either running Liftoff on whatever host is running the virtualization, or downloading and editing one of the pre-generated templates: https://github.com/libgdx/gdx-liftoff-demo (Java) or https://github.com/libgdx/gdx-liftoff-demo-kotlin (Kotlin).
