### ISSUE TITLE
[iOS] Creating a TextureArray throws UnsatisfiedLinkError

### ISSUE THREAD

**Issue by hujasonx** [libgdx/libgdx#7434]
Please ensure you have given all the following requested information in your report.

#### Issue details
Calling new TextureArray() throws the following error on iOS:
```
java.lang.UnsatisfiedLinkError: com.badlogic.gdx.backends.iosrobovm.IOSGLES30.glTexImage3DJNI(IIIIIIIIILjava/nio/Buffer;)V
```

#### Reproduction steps/code
Using a template generated with gdx-liftoff
```
public class Core extends ApplicationAdapter {
    private TextureArray textureArray;

    @Override
    public void create() {
        textureArray = new TextureArray(true, new FileHandle[] {
            Gdx.files.internal("texture/array/0_blank.png"),
            Gdx.files.internal("texture/array/1_noise.png")
        });
    }

    @Override
    public void render() {
    }

    @Override
    public void dispose() {
    }
}
```

IOSLauncher.java:
```
configuration.useGL30 = true;
```

#### Version of libGDX and/or relevant dependencies
robovmVersion=2.3.20
gdxVersion=1.12.1

Both of these backends:
com.badlogicgames.gdx:gdx-backend-robovm
com.badlogicgames.gdx:gdx-backend-robovm-metalangle

#### Stacktrace
```
java.lang.UnsatisfiedLinkError: com.badlogic.gdx.backends.iosrobovm.IOSGLES30.glTexImage3DJNI(IIIIIIIIILjava/nio/Buffer;)V
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES30.glTexImage3DJNI(Native Method)
	at com.badlogic.gdx.backends.iosrobovm.IOSGLES30.glTexImage3D(IOSGLES30.java:32)
	at com.badlogic.gdx.graphics.TextureArray.load(TextureArray.java:78)
	at com.badlogic.gdx.graphics.TextureArray.<init>(TextureArray.java:59)
	at com.badlogic.gdx.graphics.TextureArray.<init>(TextureArray.java:49)
	at com.badlogic.gdx.graphics.TextureArray.<init>(TextureArray.java:45)
```

#### Please select the affected platforms
- [ ] Android
- [*] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

#### Notes
I really hope there is something wrong on my end, and that Libgdx fully supports opengl es 3 on iOS. However, if not, I would love if there was a resource that explains which opengl es3 features are not supported on iOS, now that useGL30 is not marked deprecated.

**Comment by tommyettinger** [comment]
Indeed, the ANGLE-related backends seem to be nearly undocumented, which is part of why I have never used some of them. This issue, https://github.com/libgdx/libgdx.github.io/issues/218 , is related. What I can say with some certainty is that ANGLE only supports GL20 emulation -- if the original library supports GL30 at all, we haven't yet updated to a version that can use GL30. I could be wrong! Maybe GL30 is available through some other method. I don't think it is.

**Comment by Frosty-J** [comment]
That issue is about the LWJGL3 ANGLE extension. This seems unrelated since the plain RoboVM backend is affected.

**Comment by tommyettinger** [comment]
Could this be related to the Java 8/Java 9 change to java.nio.Buffer ? I don't know what RoboVM usually uses, just that it is limited to language level 8 at most.

**Comment by Berstanio** [comment]
Do you have a dependency on the ios natives in your build.gradle files? Do the natives have also the version `1.12.1`?
Could you post the output of the following, if possible:
`./gradlew :ios:dependencies` or replace "ios" with however your iOS module is named.

**Comment by hujasonx** [comment]
Thank you all folks, these resources have been very useful! I have indeed noticed some angle-backend-only issues too in my experience, so having those bugs to look at is very helpful.

As per the natives, I have been importing them using 
```
implementation "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion" (or with metalangle)
implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
```
with my gradle.properties including
``` 
gdxVersion=1.12.1
```


Running the command ./gradlew :ios:dependencies gave me:

```
> Task :ios:dependencies

------------------------------------------------------------
Project ':ios'
------------------------------------------------------------

annotationProcessor - Annotation processors and their dependencies for source set 'main'.
No dependencies

api - API dependencies for the 'main' feature. (n)
No dependencies

apiElements - API elements for the 'main' feature. (n)
No dependencies

compileClasspath - Compile classpath for source set 'main'.
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.12.1
|    +--- com.badlogicgames.gdx:gdx:1.12.1
|    |    \--- com.badlogicgames.gdx:gdx-jnigen-loader:2.3.1
|    +--- com.mobidevelop.robovm:robovm-rt:2.3.20
|    +--- com.mobidevelop.robovm:robovm-objc:2.3.20
|    \--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20
|         \--- com.mobidevelop.robovm:robovm-objc:2.3.20
+--- com.badlogicgames.gdx:gdx-platform:1.12.1
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20 (*)
+--- com.mobidevelop.robovm:robovm-rt:2.3.20
\--- project :core
     \--- com.badlogicgames.gdx:gdx:1.12.1 (*)

compileOnly - Compile-only dependencies for the 'main' feature. (n)
No dependencies

compileOnlyApi - Compile-only API dependencies for the 'main' feature. (n)
No dependencies

default - Configuration for default artifacts. (n)
No dependencies

implementation - Implementation dependencies for the 'main' feature. (n)
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.12.1 (n)
+--- com.badlogicgames.gdx:gdx-platform:1.12.1 (n)
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20 (n)
+--- com.mobidevelop.robovm:robovm-rt:2.3.20 (n)
\--- project core (n)

mainSourceElements - List of source directories contained in the Main SourceSet. (n)
No dependencies

runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.12.1
|    +--- com.badlogicgames.gdx:gdx:1.12.1
|    |    \--- com.badlogicgames.gdx:gdx-jnigen-loader:2.3.1
|    +--- com.mobidevelop.robovm:robovm-rt:2.3.20
|    +--- com.mobidevelop.robovm:robovm-objc:2.3.20
|    \--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20
|         \--- com.mobidevelop.robovm:robovm-objc:2.3.20
+--- com.badlogicgames.gdx:gdx-platform:1.12.1
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20 (*)
+--- com.mobidevelop.robovm:robovm-rt:2.3.20
\--- project :core
     \--- com.badlogicgames.gdx:gdx:1.12.1 (*)

runtimeElements - Runtime elements for the 'main' feature. (n)
No dependencies

runtimeOnly - Runtime-only dependencies for the 'main' feature. (n)
No dependencies

testAnnotationProcessor - Annotation processors and their dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.12.1
|    +--- com.badlogicgames.gdx:gdx:1.12.1
|    |    \--- com.badlogicgames.gdx:gdx-jnigen-loader:2.3.1
|    +--- com.mobidevelop.robovm:robovm-rt:2.3.20
|    +--- com.mobidevelop.robovm:robovm-objc:2.3.20
|    \--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20
|         \--- com.mobidevelop.robovm:robovm-objc:2.3.20
+--- com.badlogicgames.gdx:gdx-platform:1.12.1
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20 (*)
+--- com.mobidevelop.robovm:robovm-rt:2.3.20
\--- project :core
     \--- com.badlogicgames.gdx:gdx:1.12.1 (*)

testCompileOnly - Compile only dependencies for source set 'test'. (n)
No dependencies

testImplementation - Implementation only dependencies for source set 'test'. (n)
No dependencies

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.12.1
|    +--- com.badlogicgames.gdx:gdx:1.12.1
|    |    \--- com.badlogicgames.gdx:gdx-jnigen-loader:2.3.1
|    +--- com.mobidevelop.robovm:robovm-rt:2.3.20
|    +--- com.mobidevelop.robovm:robovm-objc:2.3.20
|    \--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20
|         \--- com.mobidevelop.robovm:robovm-objc:2.3.20
+--- com.badlogicgames.gdx:gdx-platform:1.12.1
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.3.20 (*)
+--- com.mobidevelop.robovm:robovm-rt:2.3.20
\--- project :core
     \--- com.badlogicgames.gdx:gdx:1.12.1 (*)

testRuntimeOnly - Runtime only dependencies for source set 'test'. (n)
No dependencies

(*) - Indicates repeated occurrences of a transitive dependency subtree. Gradle expands transitive dependency subtrees only once per project; repeat occurrences only display the root of the subtree, followed by this annotation.

(n) - A dependency or dependency configuration that cannot be resolved.
```

**Comment by Berstanio** [comment]
Thank you for the info!
For whoever is curius, the issue is that the header file defines the function name as this:
https://github.com/libgdx/libgdx/blob/d2edf6139bddca83b235c2ebdf497f163162a498/gdx/jni/iosgl/iosgl30.h#L55
but the implementation as:
https://github.com/libgdx/libgdx/blob/d2edf6139bddca83b235c2ebdf497f163162a498/gdx/jni/iosgl/iosgl30.cpp#L159
Because of this, the function is not exported as a C function, so the name gets mangled -> jni can't resolve it.

I'm not sure tho, what the "correct" signature of this is.
