### ISSUE TITLE
com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android

### ISSUE THREAD

**Issue by Born-alone** [libgdx/libgdx#7441]
Issue details
Alway error runtime the gdx-tests-android project, android studio logcat display error info is “Couldn't load shared library 'gdx' for target: Android”

 Reproduction steps/code
Even if you think your issue is trivial to reproduce, please supply a [SSCCE](http://sscce.org/) that demonstrates your issue. This saves time on our end, and makes it much more likely that your issue will be fixed.
You can find barebones templates [here](https://libgdx.com/wiki/articles/getting-help)

Version of libGDX and/or relevant dependencies
version 1.21.1

Stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.badlogic.gdx.tests.android/com.badlogic.gdx.tests.android.GdxTestActivity}: com.badlogic.gdx.utils.SharedLibraryLoadRuntimeException: Couldn't load shared library 'gdx' for target: Android
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4788)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:5006)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:123)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3082)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:117)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9975)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

Please select the affected platforms
 Android

**Comment by Frosty-J** [comment]
You need to run the `fetchNatives` Gradle task first. Unlike in actual libGDX projects, the shared libraries don't get downloaded automatically.
