### ISSUE TITLE
No implementation found for java.nio.ByteBuffer com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.load

### ISSUE THREAD

**Issue by Ousyoung** [libgdx/libgdx#7450]
#### Issue details
No implementation found for java.nio.ByteBuffer com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.load

Is it because the gdx version does not match?
Do I need to import other so files manually?

#### Reproduction steps/code
```kotlin
TextureRegion(Texture(AssertFileHandle(context,"btn_summon.png")))

class AssertFileHandle(
    private val context: Context, private val fileName: String
) : FileHandle(fileName, Files.FileType.Internal) {
    
    override fun read(): InputStream {
        try {
            return context.assets.open(fileName)
        } catch (e: IOException) {
            throw RuntimeException(e)
        }
    }
}
```

#### Version of libGDX and/or relevant dependencies
implementation "com.badlogicgames.gdx:gdx:1.12.1"

#### Stacktrace
```kotlin
java.lang.UnsatisfiedLinkError: No implementation found for java.nio.ByteBuffer com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.load(long[], byte[], int, int) (tried Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_load and Java_com_badlogic_gdx_graphics_g2d_Gdx2DPixmap_load___3J_3BII)
                                                                                      	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.load(Native Method)
                                                                                      	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:84)
                                                                                      	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:188)
                                                                                      	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:101)
                                                                                      	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:122)
                                                                                      	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:114)
```

#### Please select the affected platforms
- [√] Android
- [ ] iOS
- [ ] HTML/GWT
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by tommyettinger** [comment]
I don't see any ApplicationListener type, so if that's your entire code, you aren't in the libGDX lifecycle. You should try to follow one of the first-step tutorials, such as https://libgdx.com/wiki/start/project-generation . The project setup tool (gdx-liftoff) manages the dependencies on things like the libGDX native libraries, where that mentioned Gdx2DPixmap method is implemented. The lifecycle ensures those libraries are loaded before you use them.

If you do have a class that extends Game or ApplicationAdapter, or implements ApplicationListener, then you should show that. The issue could also be in your Gradle dependencies. Following the tutorial should avoid these issues.

**Comment by badlogic** [comment]
[You are using spine-android](https://github.com/EsotericSoftware/spine-runtimes/issues/2617), which only depends on gdx core. spine-android does not support developing libGDX applications. Your code triggers loading of libGDX shared libraries which are not part of your Android project' dependencies, nor does your code trigger setup loading of the shared libraries.

If you want to do libGDX things, you will need to create a libGDX app and use spine-libgdx. If you want to do Android stuff with Spine, use spine-android and don't touch any libGDX APIs.
