### ISSUE TITLE
Exception stating Graphics Card does not support OpenGL when it does (Radeon HD4850)

### ISSUE THREAD

**Issue by jasonf20** [libgdx/libgdx#997]
When trying to run the Desktop project created by the UI, I encounter the following error:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:213)
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:175)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:131)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
    at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
    at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
    at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:244)
    at org.lwjgl.opengl.Display.createWindow(Display.java:306)
    at org.lwjgl.opengl.Display.create(Display.java:848)
    at org.lwjgl.opengl.Display.create(Display.java:757)
    at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:210)
    ... 3 more
```

I am using a Graphics card fully capable of OpenGL es 1.5 and above (AMD HD 4850). It's a bit old but should be fully compatible. 

I have the latest drivers installed from AMD's website.

Perhaps there is an issue with the graphics capability detection?

**Comment by chieubkhn** [comment]
@MobiDevelop Thanks you!
